function spec = prepToolbox()
%PREPTOOLBOX  The PREP pipeline, described for TransTools.EnsureToolbox.
%
%   PINNED TO TAG v0.56.0 (August 2021), the current release, whose
%   prepPipeline.m is identical to the repository's master branch. The
%   archive is EEG-Clean-Tools, which holds PREP in its PrepPipeline folder;
%   PREP's own EEGLAB plugin puts that folder and all its subfolders on the
%   path, so this does the same (Subfolders).
%
%   The probe is getPrepDefaults, not prepPipeline: it lives in a subfolder,
%   so finding it means the helpers PREP calls are on the path too, not
%   just its entry point.
%
%   See also PREP, TRANSTOOLS.ENSURETOOLBOX.
    spec = struct( ...
        'Name',       'the PREP pipeline', ...
        'Feature',    'PREP', ...
        'Probe',      'getPrepDefaults', ...
        'ProbeFile',  'prepPipeline.m', ...
        'Folder',     'PrepPipeline', ...
        'Url',        'https://github.com/VisLab/EEG-Clean-Tools/archive/refs/tags/v0.56.0.zip', ...
        'Version',    '0.56.0', ...
        'About',      ['PREP is free, open-source (GPL) software by Bigdely-Shamlo, Mullen, ' ...
                       'Kothe, Su and Robbins (2015) for the standardised early stages of EEG ' ...
                       'preprocessing: line noise, bad channels and a robust average reference.'], ...
        'Subfolders', true);
end
