classdef ManualTest < matlab.unittest.TestCase
%MANUALTEST  The manual keeps up with the transformations and its pictures.
%
%   The manual (manual/, Quarto) is the documentation, and the Help button
%   shows it, so a transformation without a section there is one a user
%   cannot look up. The reference chapters give each one a heading with the
%   id sec-tr-<folder name, in lower case>, which is what this looks for.
%
%   Its pictures are regenerated by captureManualImages from the list in
%   manualShots. A picture the manual shows must exist, and one the capture
%   takes must be shown somewhere, or the list and the text have drifted:
%   a shot renamed in one place and not the other leaves the manual showing
%   a stale picture that no capture will ever refresh.
%
%   Run with: runtests('tests/ManualTest.m').
%
%   See also CAPTUREMANUALIMAGES, MANUALSHOTS.

    properties (Constant)
        % Pictures the manual shows that are not made by the capture tool:
        % a rendered report, which the capture cannot make without writing
        % into a real workspace (see manualShots).
        NotCaptured = {'statistics-report'}
    end

    methods (TestClassSetup)
        function addCaptureToPath(testCase)
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(testCase.root(), 'src', 'help', 'capture')));
        end
    end

    methods (Test)
        function everyTransformationHasASection(testCase)
            text = testCase.manualText();
            folders = dir(fullfile(testCase.root(), 'src', 'Transformations'));
            folders = folders([folders.isdir] & ~startsWith({folders.name}, {'.', '+'}));
            testCase.assertNotEmpty(folders);
            for k = 1:numel(folders)
                name = folders(k).name;
                if ~isfile(fullfile(folders(k).folder, name, [name '.json']))
                    continue;   % not a transformation
                end
                testCase.verifyTrue(contains(text, ['{#sec-tr-' lower(name) '}']), ...
                    sprintf(['%s has no section in the manual (a heading with ' ...
                    '{#sec-tr-%s} in manual/chapters).'], name, lower(name)));
            end
        end

        function everyPictureTheManualShowsExists(testCase)
            images = testCase.picturesShown();
            testCase.assertNotEmpty(images);
            for k = 1:numel(images)
                testCase.verifyTrue(isfile(fullfile(testCase.root(), 'manual', images{k})), ...
                    sprintf('The manual shows %s, which is not in manual/images.', images{k}));
            end
        end

        function everyCapturedPictureIsShown(testCase)
            [~, shots] = manualShots(testCase.root());
            shown = testCase.shownNames();
            missing = setdiff({shots.name}, shown);
            testCase.verifyEmpty(missing, sprintf(['manualShots takes pictures the ' ...
                'manual does not show: %s'], strjoin(missing, ', ')));
        end

        function everyPictureInTheFolderIsShown(testCase)
        %EVERYPICTUREINTHEFOLDERISSHOWN  A picture nothing shows is either
        %   left over from a renamed shot or a figure the text forgot.
            files = dir(fullfile(testCase.root(), 'manual', 'images', '*.*'));
            files = files(~[files.isdir]);
            [~, names] = arrayfun(@(f) fileparts(f.name), files, 'UniformOutput', false);
            unused = setdiff(names, testCase.shownNames());
            testCase.verifyEmpty(unused, sprintf(['manual/images holds pictures the ' ...
                'manual does not show: %s'], strjoin(unused, ', ')));
        end

        function theTextHasNoDashesForPunctuation(testCase)
        %THETEXTHASNODASHESFORPUNCTUATION  The house style uses no em dash,
        %   and " -- ", which the manual's renderer turns into a dash, is
        %   the same thing typed differently.
            files = [dir(fullfile(testCase.root(), 'manual', '*.qmd')); ...
                dir(fullfile(testCase.root(), 'manual', 'chapters', '*.qmd')); ...
                dir(fullfile(testCase.root(), 'README.MD'))];
            for k = 1:numel(files)
                text = fileread(fullfile(files(k).folder, files(k).name), 'Encoding', 'UTF-8');
                testCase.verifyFalse(contains(text, char(8212)), ...
                    sprintf('%s has an em dash.', files(k).name));
                testCase.verifyFalse(contains(text, ' -- '), ...
                    sprintf('%s has " -- ", which renders as a dash.', files(k).name));
            end
        end

        function everyShownPictureIsCaptured(testCase)
            [~, shots] = manualShots(testCase.root());
            stray = setdiff(testCase.shownNames(), [{shots.name}, testCase.NotCaptured]);
            testCase.verifyEmpty(stray, sprintf(['The manual shows pictures no capture ' ...
                'makes, so nothing will refresh them: %s'], strjoin(stray, ', ')));
        end
    end

    methods (Access = private)
        function folder = root(~)
            folder = fileparts(fileparts(mfilename('fullpath')));
        end

        function text = manualText(testCase)
            files = [dir(fullfile(testCase.root(), 'manual', '*.qmd')); ...
                dir(fullfile(testCase.root(), 'manual', 'chapters', '*.qmd'))];
            read = @(f) fileread(fullfile(f.folder, f.name), 'Encoding', 'UTF-8');
            text = strjoin(arrayfun(read, files, 'UniformOutput', false), newline);
        end

        function images = picturesShown(testCase)
        %PICTURESSHOWN  Every images/<file> the manual's text refers to.
            images = unique(regexp(testCase.manualText(), ...
                'images/[\w.-]+\.(?:png|jpg|jpeg|svg)', 'match'));
        end

        function names = shownNames(testCase)
            [~, names] = cellfun(@fileparts, testCase.picturesShown(), 'UniformOutput', false);
            names = unique(names);
        end
    end
end
