function html = aboutPageHtml(info, logoPath)
%ABOUTPAGEHTML  The About box's markup, as one self-contained HTML string.
%   HTML = aboutPageHtml(INFO, LOGOPATH) renders INFO (an alakazamVersion
%   struct) into the page Alakazam.onAbout loads into its uihtml, with the
%   image at LOGOPATH embedded as a base64 data URI.
%
%   Self-contained, like every other uihtml page in this app (see
%   AlakazamRibbon's own comment on the same point): the image is embedded
%   and the styling is inline, so nothing has to resolve a relative path
%   once the component has loaded the string.
%
%   A separate function rather than a local one inside onAbout so the exact
%   markup that ships can be generated and inspected without constructing
%   an Alakazam app -- the page is the part with something to get wrong,
%   and onAbout around it is four lines of window plumbing.
%
%   LOGOPATH may be missing or unreadable, in which case the image is
%   simply omitted: an About box that refuses to open because its
%   decoration is absent would be a worse failure than one without a
%   picture.
%
%   See also ALAKAZAMVERSION, ALAKAZAM/ONABOUT.
    logoUri = logoDataUri(logoPath);
    if isempty(logoUri)
        logoTag = '';
    else
        logoTag = sprintf('<img id="logo" src="%s" alt="%s">', logoUri, info.Name);
    end

    % target="_blank" so a click does not navigate this small dialog away
    % from itself: unlike a browser it has no way back.
    link = @(url, text) sprintf( ...
        '<a href="%s" target="_blank" rel="noopener noreferrer">%s</a>', url, text);

    html = sprintf([ ...
        '<!doctype html><html><head><meta charset="utf-8"><style>\n' ...
        'html,body{margin:0;padding:0;height:100%%;' ...
        'font-family:-apple-system,Segoe UI,Arial,sans-serif;color:#222;background:#fff;}\n' ...
        '#wrap{box-sizing:border-box;height:100%%;overflow-y:auto;padding:22px 26px;}\n' ...
        '#head{display:flex;align-items:center;gap:18px;}\n' ...
        '#logo{width:96px;height:96px;object-fit:contain;flex:none;}\n' ...
        'h1{margin:0;font-size:26px;color:#2e5c8a;}\n' ...
        '#version{margin:2px 0 0;font-size:13px;color:#555;}\n' ...
        '#tagline{margin:14px 0 0;font-size:13px;line-height:1.5;color:#333;}\n' ...
        'hr{border:none;border-top:1px solid #ddd;margin:16px 0;}\n' ...
        'table{border-collapse:collapse;font-size:12.5px;width:100%%;}\n' ...
        'th{text-align:left;color:#555;font-weight:600;padding:3px 12px 3px 0;' ...
        'white-space:nowrap;vertical-align:top;width:1%%;}\n' ...
        'td{padding:3px 0;vertical-align:top;}\n' ...
        'a{color:#4a7fc9;}\n' ...
        '</style></head><body><div id="wrap">\n' ...
        '<div id="head">%s<div><h1>%s</h1><p id="version">%s</p></div></div>\n' ...
        '<p id="tagline">%s</p>\n' ...
        '<hr>\n' ...
        '<table>\n' ...
        '<tr><th>Author</th><td>%s &lt;%s&gt;</td></tr>\n' ...
        '<tr><th>Repository</th><td>%s</td></tr>\n' ...
        '<tr><th>Releases</th><td>%s</td></tr>\n' ...
        '<tr><th>Report a problem</th><td>%s</td></tr>\n' ...
        '<tr><th>Licence</th><td>%s</td></tr>\n' ...
        '</table>\n' ...
        '</div></body></html>'], ...
        logoTag, info.Name, info.Version, info.Tagline, ...
        info.Author, info.Email, ...
        link(info.Repository, info.Repository), ...
        link(info.Releases, 'Downloads and release notes'), ...
        link(info.Issues, 'Open an issue on GitHub'), ...
        info.License);
end

% ======================================================================= %
function uri = logoDataUri(logoPath)
%LOGODATAURI  The artwork as a base64 data URI, or '' when it is missing.
%   The MIME type is taken from the extension, so swapping the mark for a
%   PNG or a WebP later needs no change here. It is an SVG today
%   (src/Icons/Alakazam.svg), which matters twice over: one file serves
%   both the 24px ribbon button and the 96px decoration here without
%   resampling, and it stays readable by MATLAB's own uiimage should this
%   dialog ever be rebuilt from native components.
    uri = '';
    if isempty(logoPath) || exist(logoPath, 'file') ~= 2
        return;
    end
    [~, ~, ext] = fileparts(logoPath);
    subtype = lower(erase(ext, '.'));
    if isempty(subtype)
        return;
    end
    if strcmp(subtype, 'jpg')
        subtype = 'jpeg';
    end
    if strcmp(subtype, 'svg')
        subtype = 'svg+xml';
    end
    fid = fopen(logoPath, 'r');
    if fid < 0
        return;
    end
    closeFile = onCleanup(@() fclose(fid));
    bytes = fread(fid, inf, '*uint8')';
    uri = ['data:image/' subtype ';base64,' char(matlab.net.base64encode(bytes))];
end
