function html = aboutPageHtml(info, logoPath)
%ABOUTPAGEHTML  The About box's markup, as one self-contained HTML string.
%   HTML = aboutPageHtml(INFO, LOGOPATH) renders INFO (an alakazamVersion
%   struct) into the page Alakazam.onAbout loads into its uihtml, with the
%   image at LOGOPATH embedded as a base64 data URI.
%
%   Self-contained, like every other uihtml page in this app (see
%   AlakazamRibbon's own comment on the same point): the image is embedded
%   and the styling is inline, so nothing has to resolve a relative path
%   once the component has loaded the string.
%
%   A separate function rather than a local one inside onAbout so the exact
%   markup that ships can be generated and inspected without constructing
%   an Alakazam app -- the page is the part with something to get wrong,
%   and onAbout around it is four lines of window plumbing.
%
%   LOGOPATH may be missing or unreadable, in which case the image is
%   simply omitted: an About box that refuses to open because its
%   decoration is absent would be a worse failure than one without a
%   picture.
%
%   See also ALAKAZAMVERSION, ALAKAZAM/ONABOUT.
    logoUri = logoDataUri(logoPath);
    if isempty(logoUri)
        logoTag = '';
    else
        logoTag = sprintf('<img id="logo" src="%s" alt="%s">', logoUri, info.Name);
    end

    % A LINK IN A uihtml GOES NOWHERE ON ITS OWN. The component embeds a
    % browser with no window of its own to open into, so target="_blank"
    % (what this used to carry) does nothing at all when clicked: no new
    % tab, no navigation, no error. The href is kept so the address still
    % shows on hover and the markup stays sensible, but the click is handed
    % to MATLAB over the same sendEventToMATLAB bridge the ribbon and the
    % workspace tree already use, and Alakazam.onAbout opens it in the real
    % browser from there.
    link = @(url, text) sprintf( ...
        '<a href="%s" class="ext" data-url="%s">%s</a>', url, url, text);

    html = sprintf([ ...
        '<!doctype html><html><head><meta charset="utf-8"><style>\n' ...
        'html,body{margin:0;padding:0;height:100%%;' ...
        'font-family:-apple-system,Segoe UI,Arial,sans-serif;color:#222;background:#fff;}\n' ...
        '#wrap{box-sizing:border-box;height:100%%;overflow-y:auto;padding:22px 26px;}\n' ...
        '#head{display:flex;align-items:center;gap:18px;}\n' ...
        '#logo{width:96px;height:96px;object-fit:contain;flex:none;}\n' ...
        'h1{margin:0;font-size:26px;color:#2e5c8a;}\n' ...
        '#version{margin:2px 0 0;font-size:13px;color:#555;}\n' ...
        '#version .src{color:#888;}\n' ...
        '#tagline{margin:14px 0 0;font-size:13px;line-height:1.5;color:#333;}\n' ...
        'hr{border:none;border-top:1px solid #ddd;margin:16px 0;}\n' ...
        'table{border-collapse:collapse;font-size:12.5px;width:100%%;}\n' ...
        'th{text-align:left;color:#555;font-weight:600;padding:3px 12px 3px 0;' ...
        'white-space:nowrap;vertical-align:top;width:1%%;}\n' ...
        'td{padding:3px 0;vertical-align:top;}\n' ...
        'a{color:#4a7fc9;}\n' ...
        'h2{margin:20px 0 6px;font-size:14px;color:#2e5c8a;}\n' ...
        'h3{margin:14px 0 4px;font-size:11px;letter-spacing:.06em;' ...
        'text-transform:uppercase;color:#777;font-weight:600;}\n' ...
        '.dep{margin:0 0 9px;font-size:12.5px;line-height:1.45;}\n' ...
        '.dep .n{font-weight:600;}\n' ...
        '.dep .meta{color:#666;}\n' ...
        '.dep .note{display:block;color:#444;}\n' ...
        '.lic{color:#8a4b2e;}\n' ...
        '#credit{margin:16px 0 0;font-size:12px;color:#555;line-height:1.5;}\n' ...
        '</style></head><body><div id="wrap">\n' ...
        '<div id="head">%s<div><h1>%s</h1><p id="version">%s</p></div></div>\n' ...
        '<p id="tagline">%s</p>\n' ...
        '<hr>\n' ...
        '<table>\n' ...
        '<tr><th>Author</th><td>%s &lt;%s&gt;</td></tr>\n' ...
        '<tr><th>Repository</th><td>%s</td></tr>\n' ...
        '<tr><th>Releases</th><td>%s</td></tr>\n' ...
        '<tr><th>Report a problem</th><td>%s</td></tr>\n' ...
        '<tr><th>Licence</th><td>%s</td></tr>\n' ...
        '</table>\n' ...
        '<hr>\n' ...
        '%s' ...
        '</div>\n' ...
        ... % The bridge. setup() is uihtml''s own entry point, the same one
        ... % AlakazamRibbon.html and the workspace tree use. One delegated
        ... % listener rather than one per link, so the dependency list can
        ... % grow without touching this.
        '<script>\n' ...
        'let alzAbout;\n' ...
        'function setup(htmlComponent) {\n' ...
        '  alzAbout = htmlComponent;\n' ...
        '  document.addEventListener("click", function (e) {\n' ...
        '    const a = e.target.closest("a.ext");\n' ...
        '    if (!a) { return; }\n' ...
        '    e.preventDefault();\n' ...
        '    if (alzAbout) { alzAbout.sendEventToMATLAB("openUrl", a.dataset.url); }\n' ...
        '  });\n' ...
        '}\n' ...
        '</script>\n' ...
        '</body></html>'], ...
        logoTag, info.Name, versionText(info), info.Tagline, ...
        info.Author, info.Email, ...
        link(info.Repository, info.Repository), ...
        link(info.Releases, 'Downloads and release notes'), ...
        link(info.Issues, 'Open an issue on GitHub'), ...
        info.License, ...
        dependencySection(link));
end

% ======================================================================= %
function text = versionText(info)
%VERSIONTEXT  The version, and where it was read from.
%   alakazamVersion works the version out from the packaged VERSION stamp,
%   from `git describe`, or from its own constant, and says which. Showing
%   that here costs a parenthetical and answers the question a maintainer
%   asks first about any reported version: is this a release, or somebody's
%   working copy with uncommitted changes in it.
    text = escapeHtml(info.Version);
    if isfield(info, 'VersionSource') && ~isempty(info.VersionSource)
        text = sprintf('%s <span class="src">(%s)</span>', ...
            text, escapeHtml(info.VersionSource));
    end
end

% ======================================================================= %
function html = dependencySection(link)
%DEPENDENCYSECTION  The third-party work Alakazam runs on, grouped by what
%   it is for. Built from alakazamDependencies rather than written out
%   here, so the About box and dependencies.md cannot drift apart silently.
%
%   Each entry names its licence. That is partly credit and partly
%   practical: GEDAI is PolyForm Noncommercial, which restricts what a
%   reader may do with their own work, and an About box is where somebody
%   looks for exactly that.
    deps = alakazamDependencies();
    if isempty(deps)
        html = '';
        return;
    end

    parts = {sprintf('<h2>Built on</h2>\n')};
    parts{end + 1} = ['<p id="credit">Alakazam is a thin layer over the toolkits below. ' ...
        'The analysis is theirs; the workflow around it is what this application adds.</p>' newline];

    categories = unique({deps.category}, 'stable');
    for c = 1:numel(categories)
        parts{end + 1} = sprintf('<h3>%s</h3>\n', escapeHtml(categories{c})); %#ok<AGROW>
        mine = deps(strcmp({deps.category}, categories{c}));
        for i = 1:numel(mine)
            d = mine(i);
            parts{end + 1} = sprintf( ...
                ['<p class="dep"><span class="n">%s</span> ' ...
                 '<span class="meta">%s &middot; <span class="lic">%s</span></span> &middot; %s' ...
                 '<span class="note">%s</span></p>\n'], ...
                escapeHtml(d.name), escapeHtml(d.version), escapeHtml(d.licence), ...
                link(d.url, 'source'), escapeHtml(d.note)); %#ok<AGROW>
        end
    end
    html = strjoin(parts, '');
end

function text = escapeHtml(text)
%ESCAPEHTML  These strings are authored in alakazamDependencies rather than
%   entered by anyone, so this is tidiness rather than safety -- but a
%   licence name with an ampersand in it should still render as one.
    text = char(string(text));
    text = strrep(text, '&', '&amp;');
    text = strrep(text, '<', '&lt;');
    text = strrep(text, '>', '&gt;');
end

% ======================================================================= %
function uri = logoDataUri(logoPath)
%LOGODATAURI  The artwork as a base64 data URI, or '' when it is missing.
%   The MIME type is taken from the extension, so swapping the mark for a
%   PNG or a WebP later needs no change here. It is an SVG today
%   (src/Icons/Alakazam.svg), which matters twice over: one file serves
%   both the 24px ribbon button and the 96px decoration here without
%   resampling, and it stays readable by MATLAB's own uiimage should this
%   dialog ever be rebuilt from native components.
    uri = '';
    if isempty(logoPath) || exist(logoPath, 'file') ~= 2
        return;
    end
    [~, ~, ext] = fileparts(logoPath);
    subtype = lower(erase(ext, '.'));
    if isempty(subtype)
        return;
    end
    if strcmp(subtype, 'jpg')
        subtype = 'jpeg';
    end
    if strcmp(subtype, 'svg')
        subtype = 'svg+xml';
    end
    fid = fopen(logoPath, 'r');
    if fid < 0
        return;
    end
    closeFile = onCleanup(@() fclose(fid));
    bytes = fread(fid, inf, '*uint8')';
    uri = ['data:image/' subtype ';base64,' char(matlab.net.base64encode(bytes))];
end
