function deps = alakazamDependencies()
%ALAKAZAMDEPENDENCIES  The third-party work Alakazam runs on.
%
%   Returns a struct array (.name, .version, .licence, .url, .note,
%   .category) of every external toolkit, bundled component and data asset
%   the running application depends on. Rendered in the About box (see
%   aboutPageHtml), where it belongs for two reasons: credit, and the fact
%   that at least one of these carries a licence an analyst genuinely needs
%   to know about before using it in commercial work.
%
%   ONE LIST, TWO READERS. dependencies.md is the maintainer's account of
%   where each toolkit is installed from and why it is pinned; this is the
%   user-facing version of the same facts. They can drift, and
%   AboutDependenciesTest checks the names here still appear there, so a
%   toolkit added to one is noticed when it is missing from the other.
%
%   Not listed: MATLAB itself and its toolboxes (a requirement rather than
%   a dependency, and already stated in the README), and the build-time
%   tooling in src/webtree and src/help, whose code does not run in the
%   application. yy-tree IS listed, because unlike those its JavaScript is
%   bundled into WorkSpaceTree.html and runs in every session.
%
%   See also ABOUTPAGEHTML, ALAKAZAMVERSION, ALAKAZAM/ONABOUT.
    deps = struct('name', {}, 'version', {}, 'licence', {}, 'url', {}, ...
        'note', {}, 'category', {});

    % ---- analysis toolkits ------------------------------------------- %
    deps(end + 1) = entry('EEGLAB', 'current', 'GNU GPL v2+', ...
        'https://sccn.ucsd.edu/eeglab/', ...
        'The EEG data structure, readers and signal-processing core Alakazam is built on.', ...
        'Analysis toolkits');

    deps(end + 1) = entry('bva-io', 'current', 'GNU GPL v2+', ...
        'https://github.com/arnodelorme/bva-io', ...
        'EEGLAB plugin: reads BrainVision .vhdr/.eeg/.vmrk recordings.', ...
        'Analysis toolkits');

    deps(end + 1) = entry('ICLabel', 'current', 'BSD 2-Clause', ...
        'https://github.com/sccn/ICLabel', ...
        'EEGLAB plugin: classifies independent components, used by AutoEyeICA.', ...
        'Analysis toolkits');

    deps(end + 1) = entry('FastICA', '2.5', 'GNU GPL v2+', ...
        'https://research.ics.aalto.fi/ica/fastica/', ...
        ['Independent component analysis. Used by AutoEyeICA when present; ' ...
         'pop_runica''s own default algorithm is the fallback.'], ...
        'Analysis toolkits');

    % The one entry whose licence changes what a reader may do with their
    % own results, so it is stated in full rather than abbreviated.
    deps(end + 1) = entry('GEDAI', '1.7', 'PolyForm Noncommercial 1.0.0', ...
        'https://github.com/neurotuning/GEDAI-master', ...
        ['Generalised eigendecomposition artefact correction, used by AutoGEDAI. ' ...
         'Free for personal and non-commercial research only: commercial use needs ' ...
         'a separate licence from its authors. Downloaded on first use, with consent.'], ...
        'Analysis toolkits');

    deps(end + 1) = entry('FieldTrip', '20260812 (pinned)', 'GNU GPL v2/v3', ...
        'https://www.fieldtriptoolbox.org/', ...
        ['Cluster-based permutation statistics, and the head and source models behind ' ...
         'Brain3D''s source-estimate view. Downloaded on first use, with consent.'], ...
        'Analysis toolkits');

    % ---- bundled components ------------------------------------------ %
    deps(end + 1) = entry('yy-tree', 'bundled', 'MIT', ...
        'https://github.com/davidfig/tree', ...
        'The drag-and-drop tree behind the data browser, built into WorkSpaceTree.html.', ...
        'Bundled components');

    % ---- data assets -------------------------------------------------- %
    deps(end + 1) = entry('BrainMesh_ICBM152', 'fetched 2026-08-18', 'GNU GPL v3', ...
        'https://github.com/mingruixia/BrainNet-Viewer', ...
        ['The 3D cortical surface Brain3D projects scalp topographies onto, from ' ...
         'BrainNet Viewer (Xia, Wang & He, 2013).'], ...
        'Data assets');

    % ---- reporting ---------------------------------------------------- %
    % Needed only to RENDER a report; the analysis itself runs without them,
    % and renderQuartoReport says so plainly when they are absent.
    deps(end + 1) = entry('Quarto', 'any recent', 'MIT', ...
        'https://quarto.org', ...
        'Renders the generated .qmd statistical reports to HTML.', ...
        'Reporting');

    deps(end + 1) = entry('R', 'any recent', 'GNU GPL v2+', ...
        'https://www.r-project.org', ...
        ['Runs the statistics inside those reports, via tidyverse, rstatix, ggpubr, gt, ' ...
         'lme4, lmerTest, emmeans, effectsize, performance and BayesFactor. ' ...
         'Each report installs whichever of these are missing on its first render.'], ...
        'Reporting');
end

% ----------------------------------------------------------------------- %
function e = entry(name, version, licence, url, note, category)
    e = struct('name', name, 'version', version, 'licence', licence, ...
        'url', url, 'note', note, 'category', category);
end
