function refs = alakazamReferences()
%ALAKAZAMREFERENCES  The papers behind what Alakazam does, to cite with it.
%   REFS = alakazamReferences() returns a struct array, one element per
%   paper, with .authors, .year, .title, .source (journal, volume, pages),
%   .doi (bare, without https://doi.org/) and .usedFor (which part of
%   Alakazam rests on it).
%
%   WHY THIS EXISTS BESIDE ALAKAZAMDEPENDENCIES. That list credits the code
%   Alakazam runs on; this one names the papers a user should cite when they
%   report an analysis done with it. They are not the same set: RESS is a
%   method Alakazam implements itself, from Cohen & Gulbinaite's article, and
%   has no toolkit to credit, while the Dimigen & Ehinger (2021) paper is
%   where the practice Deconvolve follows on eye-movement data is set out.
%
%   Every DOI here was checked against Crossref when it was added, and
%   AboutDependenciesTest holds each one to appearing in README.MD's
%   References too, so the About box and the README cannot name different
%   papers without a test saying so.
%
%   See also ALAKAZAMDEPENDENCIES, ABOUTPAGEHTML.
    refs = struct('authors', {}, 'year', {}, 'title', {}, 'source', {}, 'doi', {}, 'usedFor', {});

    refs(end + 1) = ref('Delorme, A., & Makeig, S.', 2004, ...
        ['EEGLAB: an open source toolbox for analysis of single-trial EEG dynamics ' ...
         'including independent component analysis'], ...
        'Journal of Neuroscience Methods, 134(1), 9-21', '10.1016/j.jneumeth.2003.10.009', ...
        'The data structure and toolbox everything else is built on.');

    refs(end + 1) = ref('Pion-Tonachini, L., Kreutz-Delgado, K., & Makeig, S.', 2019, ...
        'ICLabel: An automated electroencephalographic independent component classifier, dataset, and website', ...
        'NeuroImage, 198, 181-197', '10.1016/j.neuroimage.2019.05.026', ...
        'AutoEyeICA''s classification of eye components.');

    refs(end + 1) = ref('Oostenveld, R., Fries, P., Maris, E., & Schoffelen, J.-M.', 2011, ...
        ['FieldTrip: Open source software for advanced analysis of MEG, EEG, and invasive ' ...
         'electrophysiological data'], ...
        'Computational Intelligence and Neuroscience, 2011, 156869', '10.1155/2011/156869', ...
        'The cluster statistics and the source-estimate view.');

    refs(end + 1) = ref('Maris, E., & Oostenveld, R.', 2007, ...
        'Nonparametric statistical testing of EEG- and MEG-data', ...
        'Journal of Neuroscience Methods, 164(1), 177-190', '10.1016/j.jneumeth.2007.03.024', ...
        'Cluster-based permutation testing.');

    refs(end + 1) = ref('Cohen, M. X., & Gulbinaite, R.', 2017, ...
        ['Rhythmic entrainment source separation: Optimizing analyses of neural responses ' ...
         'to rhythmic sensory stimulation'], ...
        'NeuroImage, 147, 43-56', '10.1016/j.neuroimage.2016.11.036', ...
        'RESS, which Alakazam implements from this article.');

    refs(end + 1) = ref('Ehinger, B. V., & Dimigen, O.', 2019, ...
        ['Unfold: An integrated toolbox for overlap correction, non-linear modeling, and ' ...
         'regression-based EEG analysis'], ...
        'PeerJ, 7, e7838', '10.7717/peerj.7838', ...
        'The Unfold toolbox, which Deconvolve runs.');

    refs(end + 1) = ref('Dimigen, O., & Ehinger, B. V.', 2021, ...
        'Regression-based analysis of combined EEG and eye-tracking data: Theory and applications', ...
        'Journal of Vision, 21(1), 3', '10.1167/jov.21.1.3', ...
        'Deconvolution of fixation-related potentials.');

    refs(end + 1) = ref('Dimigen, O., Sommer, W., Hohlfeld, A., Jacobs, A. M., & Kliegl, R.', 2011, ...
        'Coregistration of eye movements and EEG in natural reading: Analyses and review', ...
        'Journal of Experimental Psychology: General, 140(4), 552-572', '10.1037/a0023885', ...
        'EYE-EEG, which EyeTracking uses to join an eye-tracking recording onto the EEG.');
end

function r = ref(authors, year, title, source, doi, usedFor)
    r = struct('authors', authors, 'year', year, 'title', title, 'source', source, ...
        'doi', doi, 'usedFor', usedFor);
end
