function block = betweenSection(windowLabel, measureType, binLabel)
%BETWEENSECTION  Exactly one ordinary bin, but a between-subjects group is
%   assigned (see WorkSpace.editSubjects/distinctGroups) -- so, unlike
%   descriptiveSection's own single-bin, no-comparison-possible case,
%   there IS a comparison here: independent-samples across groups.
%   n_distinct(d$group) is checked PER CHANNEL at R runtime, not decided
%   once in MATLAB (unlike ordinaryLabels/comboBins), since it can
%   legitimately vary channel to channel once NA values are dropped -- a
%   Welch two-sample *t*-test (2 groups, or a Mann-Whitney U when the data
%   depart from normality), or a Welch one-way ANOVA + Games-Howell
%   post-hoc (3+ groups), mirroring pairedSection/lmmSection's own split
%   for the WITHIN-subjects case one bin count up.
    lines = [{ ...
        '## __WINDOW_MD__ -- __MEASURETYPE_MD__ (Between Subjects)' ...
        '' ...
        'Single condition ("__BIN1_MD__"), compared BETWEEN the between-subjects groups.' ...
        '' ...
        '```{r}' ...
        '#| label: __CHUNKLABEL__' ...
        '#| results: asis' ...
        'grp <- dat %>% filter(measure_type == "__MEASURETYPE_R__", window == "__WINDOW_R__", bin == "__BIN1_R__") %>% droplevels()' ...
        '__BLOCKMATCHDIAGNOSTIC__' ...
        '' ...
        }, ReportSections.channelLoop('open'), { ...
        '  d <- grp %>% filter(channel == ch, !is.na(value)) %>% droplevels()' ...
        '  n_groups <- n_distinct(d$group)' ...
        '  if (n_groups < 2 || nrow(d) < 2) {' ...
        '    cat(sprintf("\n\n### %s\n\n*Skipped: fewer than two groups have a usable value for this channel.*\n\n", ch))' ...
        '    next' ...
        '  }' ...
        '  tag <- str_replace_all(paste("__WINDOW_R__", "__MEASURETYPE_R__", ch, sep = "_"), "[^A-Za-z0-9]+", "_")' ...
        '' ...
        '  cat(sprintf("\n\n### %s\n\n", ch))' ...
        '  descr <- d %>% group_by(group) %>% summarise(M = mean(value), SD = sd(value), n = n(), .groups = "drop")' ...
        '  cat(as_raw_html(apa_gt(descr, "Descriptive Statistics")))' ...
        '' ...
        '  if (n_groups == 2) {' ...
        '    # Not narrated -- used only to choose which test below to report.' ...
        '    shap <- tryCatch(shapiro.test(d$value), error = function(e) NULL)' ...
        '    use_parametric <- is.null(shap) || shap$p.value >= .05' ...
        '' ...
        '    if (use_parametric) {' ...
        '      tt <- t.test(value ~ group, data = d)' ...
        '      eff <- d %>% rstatix::cohens_d(value ~ group, ci = TRUE, ci.type = "bca", nboot = 200)' ...
        '      res <- tibble(Test = "Welch two-sample t-test", Statistic = unname(tt$statistic), df = apa_num(unname(tt$parameter), 1),' ...
        '                    p = apa_p(tt$p.value), Effect = "Cohen''s d", Estimate = eff$effsize,' ...
        '                    CI_low = eff$conf.low, CI_high = eff$conf.high)' ...
        '      p_grp <- tt$p.value; caption_txt <- "__CAPTION_WELCH_T__"' ...
        '      omnibus <- bind_rows(omnibus, tibble(group = tag, window = "__WINDOW_R__", measure = "__MEASURETYPE_R__", channel = ch, contrast = NA_character_, role = "primary", design = "indep_t", test = "welch_t_test", p = p_grp,' ...
        '                                            estimate = eff$effsize, conf.low = eff$conf.low, conf.high = eff$conf.high))' ...
        '    } else {' ...
        '      wt <- wilcox.test(value ~ group, data = d, conf.int = TRUE)' ...
        '      eff <- d %>% rstatix::wilcox_effsize(value ~ group, ci = TRUE)' ...
        '      res <- tibble(Test = "Mann-Whitney U", Statistic = unname(wt$statistic), df = "--",' ...
        '                    p = apa_p(wt$p.value), Effect = "Rank-biserial r", Estimate = eff$effsize,' ...
        '                    CI_low = eff$conf.low, CI_high = eff$conf.high)' ...
        '      p_grp <- wt$p.value; caption_txt <- "__CAPTION_MANN_WHITNEY__"' ...
        '      omnibus <- bind_rows(omnibus, tibble(group = tag, window = "__WINDOW_R__", measure = "__MEASURETYPE_R__", channel = ch, contrast = NA_character_, role = "primary", design = "indep_t", test = "mann_whitney_u", p = p_grp,' ...
        '                                            estimate = eff$effsize, conf.low = eff$conf.low, conf.high = eff$conf.high))' ...
        '    }' ...
        '    cat(as_raw_html(blank_missing(apa_gt(res, "Test Result"))))' ...
        '    cat(sprintf("\n*%s*\n\n", caption_txt))' ...
        '  } else {' ...
        '    # Welch''s one-way ANOVA, not the classic (Fisher) one -- it does not' ...
        '    # assume equal variances across groups, which is routinely violated' ...
        '    # and rarely checked; matches the 2-group branch above already using' ...
        '    # Welch''s t-test rather than Student''s for the same reason (Delacre' ...
        '    # et al., 2019). Games-Howell is its matching post-hoc, for the same' ...
        '    # reason Tukey (which assumes equal variances/group sizes) is not used.' ...
        '    aov <- tryCatch(welch_anova_test(data = d, formula = value ~ group), error = function(e) NULL)' ...
        '    p_grp <- NA_real_' ...
        '    if (!is.null(aov)) {' ...
        '      p_grp <- aov$p[1]' ...
        '      cat(as_raw_html(apa_gt(as.data.frame(aov), "Welch One-Way ANOVA")))' ...
        '      cat(sprintf("\n*%s*\n\n", "__CAPTION_WELCH_ANOVA__"))' ...
        '    }' ...
        '' ...
        '    pw <- d %>% games_howell_test(value ~ group)' ...
        '    cat(as_raw_html(apa_gt(pw, "Pairwise Comparisons (Games-Howell)")))' ...
        '    cat(sprintf("\n*%s*\n\n", "__CAPTION_GAMES_HOWELL__"))' ...
        '' ...
        '    omnibus <- bind_rows(omnibus, tibble(group = tag, window = "__WINDOW_R__", measure = "__MEASURETYPE_R__", channel = ch, contrast = NA_character_, role = "primary", design = "welch_anova", test = "omnibus", p = p_grp,' ...
        '                                          estimate = NA_real_, conf.low = NA_real_, conf.high = NA_real_))' ...
        '  }' ...
        '' ...
        '  common_layers <- list(' ...
        '    geom_jitter(width = 0.06, alpha = 0.6),' ...
        '    stat_summary(fun = mean, geom = "point", size = 3),' ...
        '    stat_summary(fun.data = mean_se, geom = "errorbar", width = 0.1),' ...
        '    labs(x = "Group", y = "__YLABEL__"),' ...
        '    scale_colour_brewer(palette = "Set2"),' ...
        '    scale_fill_brewer(palette = "Set2"),' ...
        '    alz_theme(),' ...
        '    theme(legend.position = "none")' ...
        '  )' ...
        '  p <- ggplot(d, aes(group, value, colour = group, fill = group)) + violin_layers() + common_layers' ...
        '  print(p)' ...
        }, ReportSections.channelLoop('close'), { ...
        '```' ...
        }];
    text = strjoin(lines, newline);
    text = strrep(text, '__CHUNKLABEL__', ReportSections.chunkLabel('between', windowLabel, measureType));
    text = strrep(text, '__YLABEL__', ReportSections.yAxisLabel(measureType));
    text = strrep(text, '__BLOCKMATCHDIAGNOSTIC__', ReportSections.blockMatchDiagnosticText());
    text = strrep(text, '__CAPTION_WELCH_T__', ReportSections.rLit(ReportSections.testCaption('welch_t')));
    text = strrep(text, '__CAPTION_MANN_WHITNEY__', ReportSections.rLit(ReportSections.testCaption('mann_whitney')));
    text = strrep(text, '__CAPTION_WELCH_ANOVA__', ReportSections.rLit(ReportSections.testCaption('welch_anova')));
    text = strrep(text, '__CAPTION_GAMES_HOWELL__', ReportSections.rLit(ReportSections.testCaption('games_howell')));
    block = ReportSections.fillCommonTokens(text, windowLabel, measureType, binLabel, '');
end
