function lines = betweenGroupsLines(includeBetweenGroups)
%BETWEENGROUPSLINES  The actually-new comparison comboSectionGrouped adds:
%   an independent-samples test of the combo score BETWEEN groups --
%   spliced in when INCLUDEBETWEENGROUPS, {} (no-op) otherwise. Mirrors
%   betweenSection's own 2-group-t-test/3+-group-one-way-ANOVA split
%   (including its own normality gating for the 2-group case), just on a
%   combination bin's already-differenced score instead of an ordinary
%   bin's raw one.
    if ~includeBetweenGroups
        lines = {};
        return;
    end
    welchTCaption = ReportSections.rLit(ReportSections.testCaption('welch_t'));
    mannWhitneyCaption = ReportSections.rLit(ReportSections.testCaption('mann_whitney'));
    welchAnovaCaption = ReportSections.rLit(ReportSections.testCaption('welch_anova'));
    gamesHowellCaption = ReportSections.rLit(ReportSections.testCaption('games_howell'));
    lines = { ...
        '' ...
        '  n_groups <- n_distinct(d$group)' ...
        '  if (n_groups < 2) {' ...
        '    cat("\n*Only one group has a usable value for this channel; the between-group comparison could not be run.*\n\n")' ...
        '  } else if (n_groups == 2) {' ...
        '    # Not narrated -- used only to choose which test below to report.' ...
        '    shap <- tryCatch(shapiro.test(d$value), error = function(e) NULL)' ...
        '    use_parametric <- is.null(shap) || shap$p.value >= .05' ...
        '' ...
        '    if (use_parametric) {' ...
        '      tt <- t.test(value ~ group, data = d)' ...
        '      eff <- d %>% rstatix::cohens_d(value ~ group, ci = TRUE, ci.type = "bca", nboot = 200)' ...
        '      res <- tibble(Test = "Welch two-sample t-test", Statistic = unname(tt$statistic), df = apa_num(unname(tt$parameter), 1),' ...
        '                    p = apa_p(tt$p.value), Effect = "Cohen''s d", Estimate = eff$effsize,' ...
        '                    CI_low = eff$conf.low, CI_high = eff$conf.high)' ...
        '      p_grp <- tt$p.value' ...
        ['      caption_txt <- "' welchTCaption '"'] ...
        '      omnibus <- bind_rows(omnibus, tibble(group = tag, window = "__WINDOW_R__", measure = "__MEASURETYPE_R__", channel = ch, contrast = "__COMBOLABEL_R__", role = "secondary", design = "between_group_combo", test = "welch_t_test", p = p_grp,' ...
        '                                            estimate = eff$effsize, conf.low = eff$conf.low, conf.high = eff$conf.high))' ...
        '    } else {' ...
        '      wt <- wilcox.test(value ~ group, data = d, conf.int = TRUE)' ...
        '      eff <- d %>% rstatix::wilcox_effsize(value ~ group, ci = TRUE)' ...
        '      res <- tibble(Test = "Mann-Whitney U", Statistic = unname(wt$statistic), df = "--",' ...
        '                    p = apa_p(wt$p.value), Effect = "Rank-biserial r", Estimate = eff$effsize,' ...
        '                    CI_low = eff$conf.low, CI_high = eff$conf.high)' ...
        '      p_grp <- wt$p.value' ...
        ['      caption_txt <- "' mannWhitneyCaption '"'] ...
        '      omnibus <- bind_rows(omnibus, tibble(group = tag, window = "__WINDOW_R__", measure = "__MEASURETYPE_R__", channel = ch, contrast = "__COMBOLABEL_R__", role = "secondary", design = "between_group_combo", test = "mann_whitney_u", p = p_grp,' ...
        '                                            estimate = eff$effsize, conf.low = eff$conf.low, conf.high = eff$conf.high))' ...
        '    }' ...
        '    cat(as_raw_html(blank_missing(apa_gt(res, "Test Result (Between Groups)"))))' ...
        '    cat(sprintf("\n*%s*\n\n", caption_txt))' ...
        '  } else {' ...
        '    # Welch ANOVA + Games-Howell, not classic ANOVA + Tukey -- see' ...
        '    # betweenSection''s own comment on this same choice.' ...
        '    aov <- tryCatch(welch_anova_test(data = d, formula = value ~ group), error = function(e) NULL)' ...
        '    p_grp <- NA_real_' ...
        '    if (!is.null(aov)) {' ...
        '      p_grp <- aov$p[1]' ...
        '      cat(as_raw_html(apa_gt(as.data.frame(aov), "Welch One-Way ANOVA")))' ...
        ['      cat(sprintf("\n*%s*\n\n", "' welchAnovaCaption '"))'] ...
        '    }' ...
        '' ...
        '    pw <- d %>% games_howell_test(value ~ group)' ...
        '    cat(as_raw_html(apa_gt(pw, "Pairwise Comparisons (Games-Howell)")))' ...
        ['    cat(sprintf("\n*%s*\n\n", "' gamesHowellCaption '"))'] ...
        '' ...
        '    omnibus <- bind_rows(omnibus, tibble(group = tag, window = "__WINDOW_R__", measure = "__MEASURETYPE_R__", channel = ch, contrast = "__COMBOLABEL_R__", role = "secondary", design = "between_group_combo", test = "welch_anova", p = p_grp,' ...
        '                                          estimate = NA_real_, conf.low = NA_real_, conf.high = NA_real_))' ...
        '  }'};
end
