function block = circularSection(windowLabel, measureType, binLabels)
%CIRCULARSECTION  Ordinary bins whose measure type is CIRCULAR (see
%   isCircularType): circular descriptive statistics, and no linear test.
%
%   WHY THIS EXISTS. A Spectral export's 'phase' and 'phaselag' are angles
%   that wrap at +/-pi, and every ordinary-bin route in this report is
%   linear: pairedSection runs a t-test, lmmSection fits lmerTest::lmer,
%   descriptiveSection summarises with mean() and sd(). None of those mean
%   anything on a circle. The arithmetic mean of 179 and -179 degrees is
%   0, which is the point exactly opposite where the data actually sit,
%   and an sd computed the same way is larger the more tightly the angles
%   cluster around the wrap.
%
%   The combination-bin branch already refused these types a linear test
%   (comboSectionDescriptiveOnly), so before this existed one report could
%   state in one section that a linear test of 'phase' was invalid and in
%   the next section report exactly such a test on the same measure.
%
%   WHAT IT REPORTS INSTEAD, and why not simply nothing. The two standard
%   first-order circular statistics need no package beyond base R:
%
%     mean angle       atan2(mean(sin(t)), mean(cos(t)))
%     resultant length R = sqrt(mean(sin(t))^2 + mean(cos(t))^2), in [0,1]
%
%   R is the concentration: 1 means every subject had the same angle, 0
%   means they are spread evenly around the circle and the mean angle is
%   meaningless. Reporting the mean angle without R would be the circular
%   equivalent of a mean without an SD, so the two always appear together.
%
%   AND AN INTERVAL ON THE MEAN ANGLE, by bootstrap over subjects. A mean
%   direction with no interval invites exactly the over-reading R is there
%   to prevent, and R alone does not answer "how well is this direction
%   pinned down", because the same R at n = 5 and n = 40 supports very
%   different claims. Bootstrapping needs no distributional assumption and
%   no package, and it degrades honestly: when the angles are near uniform
%   the interval widens towards the whole circle, which says "there is no
%   direction here" more plainly than any statistic.
%
%   The resamples are taken on the DEVIATION from the observed mean,
%   wrapped into (-pi, pi], rather than on the angles themselves. Taking
%   percentiles of raw angles puts the discontinuity inside the data
%   whenever the mean sits near the wrap, and produces an interval running
%   the wrong way round the circle. The seed is fixed so that re-rendering
%   the same export twice gives the same interval.
%
%   NO TEST IS OFFERED. A Rayleigh or Watson-Williams test would be the
%   right instrument, and both are genuinely useful, but they belong in a
%   deliberate decision about which circular test this pipeline endorses
%   rather than in the fix for a routing defect. The interval covers most
%   of what a reader needs from one: an interval spanning the circle is
%   the uninformative case, stated directly rather than as a p-value.
%
%   CLUSTERED ACROSS CHANNELS -- see pairedSection's own header comment.
%   The "close to uniform" / "too few observations" caveat is a Note
%   column in the one combined table now, rather than a sentence repeated
%   per bin per channel that mostly restated the row beside it. No plot:
%   deliberately not added (a circular quantity is poorly served by a
%   linear axis, and a polar plot was considered and rejected).
%
%   See also ISCIRCULARTYPE, DESCRIPTIVEONLYREASON, DESCRIPTIVESECTION.
    binLabels = cellstr(string(binLabels));

    lines = { ...
        '## __WINDOW_MD__ -- __MEASURETYPE_MD__' ...
        '' ...
        ['Conditions: __BINLIST_MD__. ' ...
         'This is a circular quantity (an angle that wraps at +/-pi radians), so the linear ' ...
         'comparisons used elsewhere in this report are not valid for it: the arithmetic mean ' ...
         'of two angles on either side of the wrap falls opposite the direction of the data. ' ...
         'Circular descriptive statistics are reported instead, and no test is run.'] ...
        '' ...
        '```{r}' ...
        '#| label: __CHUNKLABEL__' ...
        '#| results: asis' ...
        'grp <- dat %>% filter(measure_type == "__MEASURETYPE_R__", window == "__WINDOW_R__") %>% droplevels()' ...
        '__BLOCKMATCHDIAGNOSTIC__' ...
        '' ...
        'circ_list <- list()' ...
        'for (ch in unique(grp$channel)) {' ...
        '  tryCatch({' ...
        '  d <- grp %>% filter(channel == ch, !is.na(value)) %>% droplevels()' ...
        '  if (nrow(d) < 1) {' ...
        '    circ_list[[ch]] <- tibble(channel = ch, Note = "Skipped: no usable observations.")' ...
        '    next' ...
        '  }' ...
        '' ...
        '  # First-order circular statistics, in base R. mean_angle is the' ...
        '  # direction of the resultant vector; R_bar is its length, which is 1' ...
        '  # when every subject agrees and 0 when they are spread evenly, in' ...
        '  # which case the mean angle carries no information at all.' ...
        '  circ <- d %>% group_by(bin) %>% summarise(' ...
        '    mean_angle_rad = atan2(mean(sin(value)), mean(cos(value))),' ...
        '    R_bar = sqrt(mean(sin(value))^2 + mean(cos(value))^2),' ...
        '    n = n(), .groups = "drop") %>%' ...
        '    mutate(mean_angle_deg = mean_angle_rad * 180 / pi)' ...
        '' ...
        '  # Percentile bootstrap over subjects, on the deviation from the' ...
        '  # observed mean rather than on the angles themselves: percentiles of' ...
        '  # raw angles put the wrap inside the data whenever the mean sits near' ...
        '  # it, and return an interval running the wrong way round the circle.' ...
        '  set.seed(20260101)' ...
        '  circ_ci <- function(theta, B = 2000, level = 0.95) {' ...
        '    n <- length(theta)' ...
        '    if (n < 3) return(c(NA_real_, NA_real_, NA_real_))' ...
        '    mu <- atan2(mean(sin(theta)), mean(cos(theta)))' ...
        '    draws <- vapply(seq_len(B), function(i) {' ...
        '      s <- theta[sample.int(n, n, replace = TRUE)]' ...
        '      atan2(mean(sin(s)), mean(cos(s)))' ...
        '    }, numeric(1))' ...
        '    dev <- atan2(sin(draws - mu), cos(draws - mu))' ...
        '    q <- unname(quantile(dev, c((1 - level) / 2, 1 - (1 - level) / 2)))' ...
        '    c((mu + q) * 180 / pi, diff(q) * 180 / pi)' ...
        '  }' ...
        '  ci <- d %>% group_by(bin) %>% group_modify(~ {' ...
        '    v <- circ_ci(.x$value)' ...
        '    tibble(ci_lo_deg = v[1], ci_hi_deg = v[2], ci_width_deg = v[3])' ...
        '  }) %>% ungroup()' ...
        '  circ <- left_join(circ, ci, by = "bin")' ...
        '' ...
        '  # A width in degrees beside a mean angle is easy to skim past and is' ...
        '  # the one number that decides whether the mean angle should be' ...
        '  # quoted at all -- said explicitly as a Note rather than left for' ...
        '  # the reader to derive from ci_width_deg themselves.' ...
        '  circ <- circ %>% mutate(Note = case_when(' ...
        '    is.na(ci_width_deg) ~ "Too few observations for an interval on the mean angle.",' ...
        '    ci_width_deg > 180 ~ "Close to uniform: the mean direction should not be quoted.",' ...
        '    TRUE ~ NA_character_' ...
        '  ))' ...
        '  circ_list[[ch]] <- circ %>% mutate(channel = ch, .before = 1)' ...
        '  }, error = function(e) {' ...
        '    circ_list[[ch]] <<- tibble(channel = ch, Note = sprintf("Could not be analysed: %s", conditionMessage(e)))' ...
        '  })' ...
        '}' ...
        '' ...
        'circ_all <- bind_rows(circ_list)' ...
        'if (nrow(circ_all) > 0) {' ...
        '  cat(as_raw_html(blank_missing(apa_gt(circ_all, "Circular Descriptive Statistics by Channel"))))' ...
        ['  cat(sprintf("\n*%s*\n\n", "' ReportSections.rLit(ReportSections.testCaption('circular_bootstrap_ci')) '"))'] ...
        '}' ...
        '```' ...
        ''};

    block = strjoin(lines, newline);
    % Empty bin slots: this section names every ordinary bin in one list
    % (__BINLIST__) rather than filling the one/two named slots the paired
    % and single-bin sections use, so BIN1/BIN2 are passed through empty,
    % which fillToken documents as a no-op.
    block = ReportSections.fillCommonTokens(block, windowLabel, measureType, '', '');
    block = ReportSections.fillToken(block, 'BINLIST', strjoin(binLabels, ', '));
    block = strrep(block, '__BLOCKMATCHDIAGNOSTIC__', ReportSections.blockMatchDiagnosticText());
    block = strrep(block, '__CHUNKLABEL__', ...
        ReportSections.chunkLabel('circ', windowLabel, measureType));
end
