function block = coherenceSection(namedChannels)
%COHERENCESECTION  The time-resolved coherence to the reference: the trace
%   that justifies a steady-state window, the reference's own spectrum, and the
%   time x frequency map.
%
%   WHAT THIS ADDS THAT NOTHING ELSE SHOWED. The scalar coherence a tagging
%   analysis tests is one number per subject, condition and channel, taken
%   over a steady-state window the user chose. Nothing in the report
%   showed where that window came from, or whether the tagged response was
%   present outside it, because the CoherenceMap result could be looked at
%   in the application and nowhere else.
%
%   THE TRACE IS THE MORE USEFUL OF THE TWO, and it is drawn first. Rise,
%   plateau and fall are visible on it directly, so a window that starts
%   inside the fade-in or ends after the response has gone is obvious
%   rather than a thing to be taken on trust. It covers every channel,
%   since it costs almost nothing to write (see exportCoherenceCSVs).
%
%   THE CHANCE LINE. Magnitude-squared coherence of N independent trials is
%   1/N by chance alone, so a coherence of 0.07 means nothing at 14 trials
%   and a great deal at 200. The dashed line marks 1/N for the median trial
%   count of each condition, and the table beside it gives the counts, so
%   conditions with different numbers of trials are not compared blind.
%
%   THE REFERENCE SPECTRUM. The trace is taken at the strongest frequency of
%   the reference INSIDE the analysed band. That is the tag only if the tag
%   is inside the band, which nothing in the trace can show: a 30 Hz SSVEP
%   condition analysed over 52 to 68 Hz is reported at 60 Hz, a 1% residual
%   of the photodiode. The reference's full spectrum is what shows it, and the
%   section says so, per condition, when the reference peaks outside the band.
%
%   THE MAP ANSWERS THE OTHER QUESTION: whether the response sits at the
%   tagged frequency alone or smears across neighbours, which is what
%   separates a tag from broadband noise that happens to peak nearby. It is
%   written for a few channels only, and the section says which and why:
%   the whole plane for every channel is about 37 MB a subject.
%
%   THE HIGHLIGHTED CHANNELS ARE CHOSEN PER CONDITION. Chosen across all the
%   conditions at once, the strongest one decides for the rest: on real RIFT
%   data the 60 Hz peak fell from 0.290 to 0.213, with nothing changed in that
%   condition, when a 30 Hz SSVEP condition came into the analysed band and
%   took over the four channels. Oz, which is fixed in advance, is reported
%   beside them as the statistic the RIFT paper gives.
%
%   A GRAND AVERAGE IS NOT A RECORDING. It is the mean of recordings already
%   in the export, so it is left out of the counts, the trace and the map.
%
%   NAMEDCHANNELS (optional, a cellstr) are the electrodes the Spectral
%   Measure rows name. When the export holds nothing else, both figures show
%   just those, in colour and without a grey field behind them, and the prose
%   says they were named by the user, not picked for their response. The
%   decision is made in R from the channels the files actually contain, so an
%   export in which some dataset fell back to its whole montage (see
%   exportCoherenceCSVs) is described as what it is.
%
%   NO TEST IS RUN HERE, deliberately. The inference in a tagging design is
%   on the scalar coherence, which the sections above already handle. A
%   test over the time x frequency plane needs a cluster-based permutation
%   over that plane, which is a different mechanism from anything in this
%   report, and offering an uncorrected one per cell would be worse than
%   offering none. The baseline and peak in the table are descriptions of the
%   figure, and the channels behind them were chosen for their response.
%
%   Guidance from Arora et al. (2026, Imaging Neuroscience) and Minarik et al.
%   (2023, NeuroImage) shaped the reference panel, the chance line and the
%   frequency warning.
%
%   See also EXPORTCOHERENCECSVS, SPECTRUMSECTION, COHERENCEMAP.
    if nargin < 1 || isempty(namedChannels)
        namedChannels = {};
    end
    namedChannels = cellstr(string(namedChannels));
    namedR = 'character(0)';
    if ~isempty(namedChannels)
        quoted = cellfun(@(c) ['"' ReportSections.rLit(c) '"'], namedChannels, 'UniformOutput', false);
        namedR = ['c(' strjoin(quoted, ', ') ')'];
    end
    namedLine = ['coh_named <- ' namedR];

    lines = ReportDoc.lines({ ...
        '## Coherence over time' ...
        '' ...
        ['Coherence between each channel and the reference at the tagged frequency, ' ...
         'against time. The tagged frequency is the reference channel''s own strongest ' ...
         'frequency inside the analysed band in each condition (typically a photodiode, ' ...
         'which measures the physical flicker directly), not an average over the EEG ' ...
         'channels'' coherence to it, which can peak on noise rather than the tag when ' ...
         'the response is weak. The dashed line is the coherence expected by chance, ' ...
         '1/N for N trials.'] ...
        ReportDoc.template('coherence-open.qmd') ...
        namedLine ...
        ReportDoc.template('coherence-trace.qmd') ...
        ['Read the window an analysis measures over against this figure. A window ' ...
         'that begins inside the rise, or ends after the response has decayed, ' ...
         'includes samples in which the tag was not being tracked, which lowers the ' ...
         'measured coherence for reasons that have nothing to do with the condition.'] ...
        '' ...
        '## Reference spectrum' ...
        '' ...
        ['The reference channel''s own amplitude spectrum in each condition, averaged ' ...
         'over recordings. A photodiode measures the flicker directly, so this is ' ...
         'what was actually displayed. The shaded band is the range the coherence ' ...
         'covers and the dotted line is the reference''s strongest frequency at 5 Hz ' ...
         'or above. A flicker shows one sharp peak at the tag, plus smaller peaks at ' ...
         'odd multiples of it if it was a square wave; a peak outside the band is ' ...
         'invisible to the coherence.'] ...
        ReportDoc.template('coherence-reference.qmd') ...
        ['The full plane (time against frequency) for a few channels. Written for a ' ...
         'few channels rather than all of them: the whole plane for a 64-channel ' ...
         'montage is around 37 MB per recording, and a tagging figure shows a handful ' ...
         'of channels in any case. Which channels are shown is stated under the figure.'] ...
        ReportDoc.template('coherence-trace-tail.qmd') ...
        namedLine ...
        ReportDoc.template('coherence-map.qmd') ...
        ['A tagged response should be confined to its own frequency row. Coherence ' ...
         'spread across neighbouring frequencies indicates broadband activity rather ' ...
         'than tracking of the flicker, and coherence present before the stimulus ' ...
         'indicates a reference channel picking up something other than the display.'] ...
        '' ''});

    block = strjoin(lines, newline);
end
