function block = coherenceSection(namedChannels)
%COHERENCESECTION  The time-resolved coherence to the reference: the trace
%   that justifies a steady-state window, the reference's own spectrum, and the
%   time x frequency map.
%
%   WHAT THIS ADDS THAT NOTHING ELSE SHOWED. The scalar coherence a tagging
%   analysis tests is one number per subject, condition and channel, taken
%   over a steady-state window the analyst chose. Nothing in the report
%   showed where that window came from, or whether the tagged response was
%   present outside it, because the CoherenceMap result could be looked at
%   in the application and nowhere else.
%
%   THE TRACE IS THE MORE USEFUL OF THE TWO, and it is drawn first. Rise,
%   plateau and fall are visible on it directly, so a window that starts
%   inside the fade-in or ends after the response has gone is obvious
%   rather than a thing to be taken on trust. It covers every channel,
%   since it costs almost nothing to write (see exportCoherenceCSVs).
%
%   THE CHANCE LINE. Magnitude-squared coherence of N independent trials is
%   1/N by chance alone, so a coherence of 0.07 means nothing at 14 trials
%   and a great deal at 200. The dashed line marks 1/N for the median trial
%   count of each condition, and the table beside it gives the counts, so
%   conditions with different numbers of trials are not compared blind.
%
%   THE REFERENCE SPECTRUM. The trace is taken at the strongest frequency of
%   the reference INSIDE the analysed band. That is the tag only if the tag
%   is inside the band, which nothing in the trace can show: a 30 Hz SSVEP
%   condition analysed over 52 to 68 Hz is reported at 60 Hz, a 1% residual
%   of the photodiode. The reference's full spectrum is what shows it, and the
%   section says so, per condition, when the reference peaks outside the band.
%
%   THE MAP ANSWERS THE OTHER QUESTION: whether the response sits at the
%   tagged frequency alone or smears across neighbours, which is what
%   separates a tag from broadband noise that happens to peak nearby. It is
%   written for a few channels only, and the section says which and why:
%   the whole plane for every channel is about 37 MB a subject.
%
%   THE HIGHLIGHTED CHANNELS ARE CHOSEN PER CONDITION. Chosen across all the
%   conditions at once, the strongest one decides for the rest: on real RIFT
%   data the 60 Hz peak fell from 0.290 to 0.213, with nothing changed in that
%   condition, when a 30 Hz SSVEP condition came into the analysed band and
%   took over the four channels. Oz, which is fixed in advance, is reported
%   beside them as the statistic the RIFT paper gives.
%
%   A GRAND AVERAGE IS NOT A RECORDING. It is the mean of recordings already
%   in the export, so it is left out of the counts, the trace and the map.
%
%   NAMEDCHANNELS (optional, a cellstr) are the electrodes the Spectral
%   Measure rows name. When the export holds nothing else, both figures show
%   just those, in colour and without a grey field behind them, and the prose
%   says they were named by the analyst, not picked for their response. The
%   decision is made in R from the channels the files actually contain, so an
%   export in which some dataset fell back to its whole montage (see
%   exportCoherenceCSVs) is described as what it is.
%
%   NO TEST IS RUN HERE, deliberately. The inference in a tagging design is
%   on the scalar coherence, which the sections above already handle. A
%   test over the time x frequency plane needs a cluster-based permutation
%   over that plane, which is a different mechanism from anything in this
%   report, and offering an uncorrected one per cell would be worse than
%   offering none. The baseline and peak in the table are descriptions of the
%   figure, and the channels behind them were chosen for their response.
%
%   Guidance from Arora et al. (2026, Imaging Neuroscience) and Minarik et al.
%   (2023, NeuroImage) shaped the reference panel, the chance line and the
%   frequency warning.
%
%   See also EXPORTCOHERENCECSVS, SPECTRUMSECTION, COHERENCEMAP.
    if nargin < 1 || isempty(namedChannels)
        namedChannels = {};
    end
    namedChannels = cellstr(string(namedChannels));
    namedR = 'character(0)';
    if ~isempty(namedChannels)
        quoted = cellfun(@(c) ['"' ReportSections.rLit(c) '"'], namedChannels, 'UniformOutput', false);
        namedR = ['c(' strjoin(quoted, ', ') ')'];
    end
    namedLine = ['coh_named <- ' namedR];

    lines = { ...
        '## Coherence over time' ...
        '' ...
        ['Coherence between each channel and the reference at the tagged frequency, ' ...
         'against time. The tagged frequency is the reference channel''s own strongest ' ...
         'frequency inside the analysed band in each condition (typically a photodiode, ' ...
         'which measures the physical flicker directly), not an average over the EEG ' ...
         'channels'' coherence to it, which can peak on noise rather than the tag when ' ...
         'the response is weak. The dashed line is the coherence expected by chance, ' ...
         '1/N for N trials.'] ...
        '' ...
        '```{r}' ...
        '#| label: coherence-trace' ...
        '#| results: asis' ...
        '#| fig-height: 4' ...
        '# The electrodes the Spectral Measure rows name, empty when there are none.' ...
        namedLine ...
        '# A grand average is the mean of the recordings already in the export, so' ...
        '# counting it as one more recording would inflate the count and add nothing.' ...
        'drop_grand_average <- function(df) {' ...
        '  if (is.null(df) || !"dataset_type" %in% names(df)) return(df)' ...
        '  dplyr::filter(df, dataset_type != "grand_average")' ...
        '}' ...
        'if (exists("cohtrace") && !is.null(cohtrace)) cohtrace <- drop_grand_average(cohtrace)' ...
        'if (exists("cohref") && !is.null(cohref)) cohref <- drop_grand_average(cohref)' ...
        'if (!exists("cohtrace") || is.null(cohtrace) || nrow(cohtrace) == 0) {' ...
        '  cat("\n*No coherence export accompanied this file, so the time course cannot be shown.*\n\n")' ...
        '} else {' ...
        '  # One tag per recording and condition, then the value most recordings' ...
        '  # agree on. Recordings that found a different tag are left out of the' ...
        '  # trace rather than averaged into it: coherence at a different frequency' ...
        '  # is not the same measurement.' ...
        '  tags <- cohtrace %>% distinct(bin, dataset, tag_hz) %>%' ...
        '    count(bin, tag_hz) %>%' ...
        '    group_by(bin) %>% arrange(desc(n), tag_hz, .by_group = TRUE) %>%' ...
        '    summarise(f = first(tag_hz), n_agree = first(n), n_total = sum(n), .groups = "drop")' ...
        '  used <- cohtrace %>%' ...
        '    inner_join(dplyr::select(tags, bin, f), by = "bin") %>%' ...
        '    filter(abs(tag_hz - f) < 1e-6)' ...
        '' ...
        '  # Averaged over subjects per channel, bin and time. Individual' ...
        '  # subjects are not drawn: with more than a handful the panel becomes' ...
        '  # unreadable, and the question here is the shape of the response, not' ...
        '  # how one person differed.' ...
        '  tr <- used %>%' ...
        '    group_by(bin, channel, time_ms) %>%' ...
        '    summarise(coherence = mean(coherence, na.rm = TRUE),' ...
        '              n = n_distinct(dataset), .groups = "drop")' ...
        '' ...
        '  # Trials behind each condition, when the export says. Older exports do not.' ...
        '  counts <- NULL' ...
        '  if ("n_trials" %in% names(used) && any(!is.na(used$n_trials))) {' ...
        '    counts <- used %>% distinct(bin, dataset, n_trials) %>%' ...
        '      group_by(bin) %>%' ...
        '      summarise(n_min = suppressWarnings(min(n_trials, na.rm = TRUE)),' ...
        '                n_med = suppressWarnings(median(n_trials, na.rm = TRUE)),' ...
        '                n_max = suppressWarnings(max(n_trials, na.rm = TRUE)), .groups = "drop") %>%' ...
        '      mutate(chance = ifelse(is.finite(n_med) & n_med > 0, 1 / n_med, NA_real_))' ...
        '  }' ...
        '' ...
        '  # The export holds only the named channels when every channel in it is one' ...
        '  # of them. A dataset that had none of them is written whole, and then this' ...
        '  # is FALSE and the figure is described as the general one.' ...
        '  named_only <- length(coh_named) > 0 &&' ...
        '    all(tolower(unique(tr$channel)) %in% tolower(coh_named))' ...
        '' ...
        '  # The strongest channels in EACH condition are drawn over the rest rather' ...
        '  # than instead of them: the faint lines are what show that the response is' ...
        '  # where it should be and absent where it should not. Chosen per condition:' ...
        '  # chosen across all of them at once, the strongest condition decides for the' ...
        '  # rest, and the set changes whenever a condition is added or dropped. When' ...
        '  # the analyst named the channels, all of those are drawn and none is a field.' ...
        '  n_best <- if (named_only) n_distinct(tr$channel) else 4' ...
        '  best <- tr %>% group_by(bin, channel) %>%' ...
        '    summarise(peak = suppressWarnings(max(coherence, na.rm = TRUE)), .groups = "drop") %>%' ...
        '    group_by(bin) %>% slice_max(peak, n = n_best, with_ties = FALSE) %>% ungroup() %>%' ...
        '    dplyr::select(bin, channel)' ...
        '' ...
        '  p <- ggplot(tr, aes(time_ms, coherence, group = channel))' ...
        '  if (!named_only) p <- p + geom_line(colour = "grey80", linewidth = 0.3)' ...
        '  p <- p +' ...
        '    geom_line(data = inner_join(tr, best, by = c("bin", "channel")),' ...
        '              aes(colour = channel), linewidth = 0.8) +' ...
        '    facet_wrap(~ bin) +' ...
        '    labs(x = "Time (ms)", y = "Coherence to reference", colour = "channel") +' ...
        '    alz_theme()' ...
        '  if (!is.null(counts) && any(!is.na(counts$chance))) {' ...
        '    p <- p + geom_hline(data = filter(counts, !is.na(chance)),' ...
        '                        aes(yintercept = chance), linetype = "dashed", colour = "grey30")' ...
        '  }' ...
        '  print(p)' ...
        '' ...
        '  # Where the reference itself peaked, when the export carries its spectrum.' ...
        '  # A condition whose reference peaks outside the analysed band has no tag' ...
        '  # in the band: what is found there is only the strongest of the rest.' ...
        '  ref_peak <- NULL' ...
        '  if (exists("cohref") && !is.null(cohref) && nrow(cohref) > 0) {' ...
        '    ref_peak <- cohref %>% filter(is.finite(peak_hz)) %>%' ...
        '      distinct(bin, dataset, peak_hz, band_lo_hz, band_hi_hz) %>%' ...
        '      group_by(bin) %>%' ...
        '      summarise(ref_hz = median(peak_hz), lo = min(band_lo_hz), hi = max(band_hi_hz), .groups = "drop") %>%' ...
        '      mutate(outside = ref_hz < lo - 0.5 | ref_hz > hi + 0.5)' ...
        '  }' ...
        '  eff <- tags %>% mutate(f_eff = f)' ...
        '  if (!is.null(ref_peak) && nrow(ref_peak) > 0) {' ...
        '    eff <- tags %>% left_join(ref_peak, by = "bin") %>%' ...
        '      mutate(f_eff = if_else(coalesce(outside, FALSE), ref_hz, f))' ...
        '  }' ...
        '' ...
        '  tag_label <- sprintf("%s at %.2f Hz", eff$bin, eff$f)' ...
        '  if ("outside" %in% names(eff)) {' ...
        '    flagged <- coalesce(eff$outside, FALSE)' ...
        '    tag_label[flagged] <- sprintf("%s at %.2f Hz (the strongest inside the band; the reference peaks at %.2f Hz)",' ...
        '                                  eff$bin[flagged], eff$f[flagged], eff$ref_hz[flagged])' ...
        '  }' ...
        '  cat(sprintf("\n\nTagged frequency per condition: %s.\n\n", paste(tag_label, collapse = "; ")))' ...
        '  disagree <- filter(tags, n_agree < n_total)' ...
        '  if (nrow(disagree) > 0) {' ...
        '    cat(sprintf("Recordings did not all find the same tag for %s; only the majority value is drawn and the others are left out of the trace.\n\n",' ...
        '        paste(sprintf("%s (%d of %d agreed)", disagree$bin, disagree$n_agree, disagree$n_total), collapse = "; ")))' ...
        '  }' ...
        '  if ("outside" %in% names(eff) && any(coalesce(eff$outside, FALSE))) {' ...
        '    out <- filter(eff, coalesce(outside, FALSE))' ...
        '    cat(sprintf("**Outside the analysed band:** %s. For these conditions the tag is not in the band, so the coherence drawn is not at the tag. Run CoherenceMap again over a band that contains the reference''s own peak to see the response.\n\n",' ...
        '        paste(sprintf("%s (the reference peaks at %.2f Hz, the band covers %.2f to %.2f Hz)", out$bin, out$ref_hz, out$lo, out$hi), collapse = "; ")))' ...
        '  }' ...
        '  if (nrow(eff) > 1 && diff(range(eff$f_eff)) > 1.5) {' ...
        '    cat(sprintf("**Conditions were tagged at different frequencies (%s Hz).** Response amplitude falls as the tagging frequency rises (Minarik et al., 2023), so a difference in coherence between these conditions can reflect frequency rather than condition. Compare conditions tagged at the same frequency, or counterbalance frequency across conditions (Arora et al., 2026).\n\n",' ...
        '        paste(sprintf("%.1f", sort(unique(round(eff$f_eff, 1)))), collapse = ", ")))' ...
        '  }' ...
        '' ...
        '  # Descriptives for the channels drawn in colour in each condition. They were' ...
        '  # chosen for their response, so these describe the figure and are not a test.' ...
        '  win <- tr %>% inner_join(best, by = c("bin", "channel")) %>%' ...
        '    group_by(bin, time_ms) %>%' ...
        '    summarise(coherence = mean(coherence, na.rm = TRUE), .groups = "drop") %>%' ...
        '    mutate(coherence = ifelse(is.nan(coherence), NA_real_, coherence))' ...
        '  base <- win %>% filter(time_ms < 0) %>% group_by(bin) %>%' ...
        '    summarise(baseline = mean(coherence, na.rm = TRUE), .groups = "drop") %>%' ...
        '    mutate(baseline = ifelse(is.nan(baseline), NA_real_, baseline))' ...
        '  top <- win %>% filter(!is.na(coherence)) %>% group_by(bin) %>%' ...
        '    slice_max(coherence, n = 1, with_ties = FALSE) %>% ungroup() %>%' ...
        '    dplyr::select(bin, peak = coherence, peak_ms = time_ms)' ...
        '  # Oz is fixed in advance, not chosen by the response, and is the channel' ...
        '  # Dimigen et al. (2025) report: its mean over the epoch in each recording,' ...
        '  # then the mean and standard deviation across recordings.' ...
        '  oz <- NULL' ...
        '  if ("Oz" %in% used$channel) {' ...
        '    oz <- used %>% filter(channel == "Oz") %>%' ...
        '      group_by(bin, dataset) %>%' ...
        '      summarise(m = mean(coherence, na.rm = TRUE), .groups = "drop") %>%' ...
        '      group_by(bin) %>%' ...
        '      summarise(oz_mean = mean(m, na.rm = TRUE), oz_sd = sd(m, na.rm = TRUE), .groups = "drop") %>%' ...
        '      mutate(oz_text = ifelse(is.finite(oz_mean),' ...
        '                              ifelse(is.finite(oz_sd), sprintf("%.3f (%.3f)", oz_mean, oz_sd),' ...
        '                                     sprintf("%.3f", oz_mean)), ""))' ...
        '  }' ...
        '  summ <- eff %>%' ...
        '    left_join(base, by = "bin") %>% left_join(top, by = "bin")' ...
        '  summ$oz_text <- ""' ...
        '  if (!is.null(oz)) summ <- summ %>% dplyr::select(-oz_text) %>% left_join(dplyr::select(oz, bin, oz_text), by = "bin")' ...
        '  if (!is.null(counts)) summ <- left_join(summ, counts, by = "bin")' ...
        '  if (is.null(counts)) summ <- mutate(summ, n_min = NA_real_, n_max = NA_real_, chance = NA_real_)' ...
        '  if (!"ref_hz" %in% names(summ)) summ$ref_hz <- NA_real_' ...
        '  tab <- summ %>% transmute(' ...
        '    Condition = bin,' ...
        '    `Tag (Hz)` = sprintf("%.2f", f),' ...
        '    `Reference peak (Hz)` = ifelse(is.na(ref_hz), "", sprintf("%.2f", ref_hz)),' ...
        '    Recordings = n_total,' ...
        '    `Trials each` = ifelse(is.finite(n_min),' ...
        '                           ifelse(n_min == n_max, sprintf("%.0f", n_min),' ...
        '                                  sprintf("%.0f to %.0f", n_min, n_max)), ""),' ...
        '    `Chance (1/N)` = chance,' ...
        '    `Oz mean (SD)` = coalesce(oz_text, ""),' ...
        '    `Before 0 ms` = baseline,' ...
        '    Peak = peak,' ...
        '    `Peak at (ms)` = round(peak_ms))' ...
        '  if (all(tab$`Reference peak (Hz)` == "")) tab$`Reference peak (Hz)` <- NULL' ...
        '  if (all(tab$`Oz mean (SD)` == "")) tab$`Oz mean (SD)` <- NULL' ...
        '  # Epochs that start at 0 ms hold nothing before the stimulus, so the baseline' ...
        '  # column could only ever be empty. Say so instead of printing a blank.' ...
        '  no_baseline <- all(is.na(tab$`Before 0 ms`))' ...
        '  if (no_baseline) tab$`Before 0 ms` <- NULL' ...
        '  cat(as_raw_html(blank_missing(apa_gt(tab, "Coherence at the Tagged Frequency"))))' ...
        '  if (named_only) {' ...
        '    cat(sprintf("\n\nAveraged over %d recording(s). Only the channels named in the Spectral Measure rows are drawn (%s), and Peak describes their mean. They were chosen in advance, not for their response.\n\n",' ...
        '        max(tr$n, na.rm = TRUE), paste(sort(unique(tr$channel)), collapse = ", ")))' ...
        '  } else {' ...
        '    cat(sprintf("\n\nAveraged over %d recording(s). The grey lines are the remaining channels. In each condition the four in colour are those that responded most, and Peak describes them.\n\n",' ...
        '        max(tr$n, na.rm = TRUE)))' ...
        '  }' ...
        '  if (!is.null(oz)) {' ...
        '    cat(sprintf("Oz was fixed in advance as the classic channel for a foveal steady-state response, so its mean over the epoch (with the standard deviation across recordings) is not chosen by the response%s. It is the statistic Dimigen et al. (2025) report.\n\n",' ...
        '        if (named_only) "" else ", unlike the channels in colour"))' ...
        '  }' ...
        '  if (no_baseline) {' ...
        '    cat("These epochs contain no time before 0 ms, so there is no baseline period to compare the response with. Arora et al. (2026) recommend a baseline in which nothing is tagged, so that the response can be judged against it; if the recording holds such a period, epoching from before the stimulus would provide one.\n\n")' ...
        '  }' ...
        '}' ...
        '```' ...
        '' ...
        ['Read the window an analysis measures over against this figure. A window ' ...
         'that begins inside the rise, or ends after the response has decayed, ' ...
         'includes samples in which the tag was not being tracked, which lowers the ' ...
         'measured coherence for reasons that have nothing to do with the condition.'] ...
        '' ...
        '## Reference spectrum' ...
        '' ...
        ['The reference channel''s own amplitude spectrum in each condition, averaged ' ...
         'over recordings. A photodiode measures the flicker directly, so this is ' ...
         'what was actually displayed. The shaded band is the range the coherence ' ...
         'covers and the dotted line is the reference''s strongest frequency at 5 Hz ' ...
         'or above. A flicker shows one sharp peak at the tag, plus smaller peaks at ' ...
         'odd multiples of it if it was a square wave; a peak outside the band is ' ...
         'invisible to the coherence.'] ...
        '' ...
        '```{r}' ...
        '#| label: coherence-reference' ...
        '#| results: asis' ...
        '#| fig-height: 4' ...
        'drop_grand_average <- function(df) {' ...
        '  if (is.null(df) || !"dataset_type" %in% names(df)) return(df)' ...
        '  dplyr::filter(df, dataset_type != "grand_average")' ...
        '}' ...
        'if (exists("cohref") && !is.null(cohref)) cohref <- drop_grand_average(cohref)' ...
        'if (!exists("cohref") || is.null(cohref) || nrow(cohref) == 0) {' ...
        '  cat("\n*The reference channel''s own spectrum was not stored with these results, which were computed before it was kept, so where the flicker actually was cannot be shown. Run CoherenceMap again to add it.*\n\n")' ...
        '} else {' ...
        '  rs <- cohref %>% filter(is.finite(amplitude), amplitude > 0) %>%' ...
        '    group_by(bin, frequency_hz) %>%' ...
        '    summarise(amplitude = mean(amplitude), .groups = "drop")' ...
        '  bands <- cohref %>% distinct(bin, band_lo_hz, band_hi_hz) %>%' ...
        '    group_by(bin) %>%' ...
        '    summarise(lo = min(band_lo_hz), hi = max(band_hi_hz), .groups = "drop")' ...
        '  marks <- cohref %>% filter(is.finite(peak_hz)) %>%' ...
        '    distinct(bin, dataset, peak_hz) %>%' ...
        '    group_by(bin) %>% summarise(peak = median(peak_hz), .groups = "drop")' ...
        '' ...
        '  p <- ggplot(rs, aes(frequency_hz, amplitude)) +' ...
        '    # ymin and ymax sit outside aes(): inside it they would pass through the' ...
        '    # log scale, log10(-Inf) is NaN, and the rectangle would silently vanish.' ...
        '    geom_rect(data = bands, aes(xmin = lo, xmax = hi), ymin = -Inf, ymax = Inf,' ...
        '              inherit.aes = FALSE, fill = alz_blue, alpha = 0.2) +' ...
        '    geom_line(linewidth = 0.4) +' ...
        '    geom_vline(data = marks, aes(xintercept = peak), linetype = "dotted", colour = alz_red) +' ...
        '    scale_y_log10(labels = scales::label_number(drop0trailing = TRUE)) +' ...
        '    facet_wrap(~ bin) +' ...
        '    labs(x = "Frequency (Hz)", y = "Reference amplitude") +' ...
        '    alz_theme()' ...
        '  print(p)' ...
        '  cat(sprintf("\n\nStrongest reference frequency per condition: %s.\n\n",' ...
        '      paste(sprintf("%s at %.2f Hz", marks$bin, marks$peak), collapse = "; ")))' ...
        '}' ...
        '```' ...
        '' ...
        '## Coherence over time and frequency' ...
        '' ...
        ['The full plane (time against frequency) for a few channels. Written for a ' ...
         'few channels rather than all of them: the whole plane for a 64-channel ' ...
         'montage is around 37 MB per recording, and a tagging figure shows a handful ' ...
         'of channels in any case. Which channels are shown is stated under the figure.'] ...
        '' ...
        '```{r}' ...
        '#| label: coherence-map' ...
        '#| results: asis' ...
        '#| fig-height: 6' ...
        namedLine ...
        'drop_grand_average <- function(df) {' ...
        '  if (is.null(df) || !"dataset_type" %in% names(df)) return(df)' ...
        '  dplyr::filter(df, dataset_type != "grand_average")' ...
        '}' ...
        'if (exists("cohmap") && !is.null(cohmap)) cohmap <- drop_grand_average(cohmap)' ...
        'if (!exists("cohmap") || is.null(cohmap) || nrow(cohmap) == 0) {' ...
        '  cat("\n*No coherence map accompanied this file.*\n\n")' ...
        '} else {' ...
        '  mp <- cohmap %>%' ...
        '    group_by(bin, channel, time_ms, frequency_hz) %>%' ...
        '    summarise(coherence = mean(coherence, na.rm = TRUE), .groups = "drop")' ...
        '' ...
        '  p <- ggplot(mp, aes(time_ms, frequency_hz, fill = coherence)) +' ...
        '    geom_raster(interpolate = TRUE) +' ...
        '    facet_grid(channel ~ bin) +' ...
        '    scale_fill_viridis_c(option = "magma", name = "coherence") +' ...
        '    labs(x = "Time (ms)", y = "Frequency (Hz)") +' ...
        '    alz_theme_map()' ...
        '  print(p)' ...
        '' ...
        '  shown <- paste(sort(unique(mp$channel)), collapse = ", ")' ...
        '  if (length(coh_named) > 0 && all(tolower(unique(mp$channel)) %in% tolower(coh_named))) {' ...
        '    cat(sprintf("\n\nChannels shown: %s, the channels named in the Spectral Measure rows.\n\n", shown))' ...
        '  } else {' ...
        '    cat(sprintf("\n\nChannels shown: %s, the ones with the strongest response in each condition. Choosing them after seeing the data is a display decision, which is safe here because nothing in this section is tested. A test on these channels would not be safe: choose channels blind to the conditions being compared, for instance from a tagging baseline or pooled over all conditions (Arora et al., 2026).\n\n", shown))' ...
        '  }' ...
        '}' ...
        '```' ...
        '' ...
        ['A tagged response should be confined to its own frequency row. Coherence ' ...
         'spread across neighbouring frequencies indicates broadband activity rather ' ...
         'than tracking of the flicker, and coherence present before the stimulus ' ...
         'indicates a reference channel picking up something other than the display.'] ...
        '' ''};

    block = strjoin(lines, newline);
end
