function block = comboSection(windowLabel, measureType, comboLabel, recipeText)
%COMBOSECTION  One combination (difference) bin. For most measure types: a
%   one-sample t-test (and Wilcoxon) against zero -- run entirely
%   separately from the omnibus test above, never as one more level
%   within it (see this file's own header comment for why that would be
%   statistically invalid). For a LATENCY or CIRCULAR measure type (see
%   isDescriptiveOnlyType): descriptive statistics only, no test.
    if ReportSections.isDescriptiveOnlyType(measureType)
        block = ReportSections.comboSectionDescriptiveOnly(windowLabel, measureType, comboLabel, recipeText);
        return;
    end
    lines = [{ ...
        '## __WINDOW_MD__ -- __MEASURETYPE_MD__: __COMBOLABEL_MD__' ...
        '' ...
        'Difference/combination bin "__COMBOLABEL_MD__" (__RECIPE_MD__). Tested against zero, not folded' ...
        'into any omnibus test over the ordinary bins above, since its own scores are a linear' ...
        'combination of the other bins'' scores, not an independent condition.' ...
        '' ...
        '```{r}' ...
        '#| label: __CHUNKLABEL__' ...
        '#| results: asis' ...
        'grp <- dat %>% filter(measure_type == "__MEASURETYPE_R__", window == "__WINDOW_R__", bin == "__COMBOLABEL_R__") %>% droplevels()' ...
        '__BLOCKMATCHDIAGNOSTIC__' ...
        '' ...
        }, ReportSections.channelLoop('open'), { ...
        '  d <- grp %>% filter(channel == ch, !is.na(value)) %>% droplevels()' ...
        '  if (n_distinct(d$dataset) < 2) {' ...
        '    cat(sprintf("\n\n### %s\n\n*Skipped: only %d subject(s) have a non-missing value for this combination bin (at least 2 are needed).*\n\n",' ...
        '                ch, n_distinct(d$dataset)))' ...
        '    next' ...
        '  }' ...
        '  tag <- str_replace_all(paste("__WINDOW_R__", "__MEASURETYPE_R__", "__COMBOLABEL_R__", ch, sep = "_"), "[^A-Za-z0-9]+", "_")' ...
        '' ...
        '  # Base R''s shapiro.test(), not rstatix''s shapiro_test(): the latter''s' ...
        '  # tidied $p column is only reliable for its GROUPED (data %>%' ...
        '  # group_by() %>% shapiro_test()) form -- called on a bare vector it can' ...
        '  # come back without a $p column at all. Base shapiro.test() has a' ...
        '  # stable list return ($statistic, $p.value); tryCatch handles the' ...
        '  # genuine edge cases it errors on outright (n < 3, zero variance)' ...
        '  # rather than relying on any particular empty-result shape.' ...
        '  shap <- tryCatch(shapiro.test(d$value), error = function(e) NULL)' ...
        '  tt <- t.test(d$value, mu = 0)' ...
        '  dz <- tryCatch(d %>% rstatix::cohens_d(value ~ 1, mu = 0, ci = TRUE, ci.type = "bca", nboot = 200),' ...
        '                 error = function(e) tibble(effsize = NA_real_, magnitude = NA_character_, conf.low = NA_real_, conf.high = NA_real_))' ...
        '  wt <- wilcox.test(d$value, mu = 0)' ...
        '  bf <- tryCatch(as.vector(BayesFactor::ttestBF(x = d$value, mu = 0)), error = function(e) NA_real_)' ...
        '' ...
        '  cat(sprintf("\n\n### %s\n\n", ch))' ...
        '  descr <- d %>% summarise(M = mean(value), SD = sd(value), n = n())' ...
        '  cat(as_raw_html(apa_gt(descr, "Descriptive Statistics")))' ...
        '' ...
        '  if (is.null(shap)) {' ...
        '    cat(sprintf("\nNormality of %s could not be assessed (fewer than 3 usable observations, or no variability among them).\n\n",' ...
        '                "__COMBOLABEL_MDR__"))' ...
        '  } else {' ...
        '    normal_txt <- if (shap$p.value >= .05) "did not depart from normality" else "departed from normality (consider the Wilcoxon test below)"' ...
        '    cat(sprintf("\nA Shapiro-Wilk test indicated %s %s, *W* = %s, *p* %s.\n\n", "__COMBOLABEL_MDR__",' ...
        '                normal_txt, apa_num(unname(shap$statistic)), apa_p(shap$p.value)))' ...
        '  }' ...
        '' ...
        '  # Direction and magnitude before the verdict, as in pairedSection: a' ...
        '  # difference bin that is reliably NEGATIVE is a different finding from' ...
        '  # one that is reliably positive, and "differed significantly" says' ...
        '  # neither.' ...
        '  direction <- if (tt$estimate >= 0) "above" else "below"' ...
        '  verdict <- if (tt$p.value < .05) "statistically significant at the .05 level"' ...
        '             else "not statistically significant at the .05 level"' ...
        '  cat(sprintf("\nAcross %d people, %s averaged %s %s zero, 95%% CI [%s, %s]; a one-sample\n",' ...
        '              sum(!is.na(d$value)), "__COMBOLABEL_MDR__", apa_num(abs(tt$estimate)),' ...
        '              direction, apa_num(tt$conf.int[1]), apa_num(tt$conf.int[2])))' ...
        '  cat(sprintf("*t*-test found that %s, *t*(%d) = %s, *p* %s,\n",' ...
        '              verdict, round(tt$parameter), apa_num(tt$statistic), apa_p(tt$p.value)))' ...
        '  cat(sprintf("*M* = %s, Cohen''s *d* = %s, 95%% CI [%s, %s]. A Wilcoxon signed-rank test, run as a\n",' ...
        '              apa_num(mean(d$value)), apa_num(dz$effsize), apa_num(dz$conf.low), apa_num(dz$conf.high)))' ...
        '  cat(sprintf("robustness check alongside it, gave *V* = %s, *p* %s; a Bayesian one-sample *t*-test\n",' ...
        '              apa_num(wt$statistic), apa_p(wt$p.value)))' ...
        '  cat(sprintf("gave BF~10~ = %s.\n\n", apa_bf(bf)))' ...
        '' ...
        '  omnibus <- bind_rows(omnibus, tibble(group = tag, window = "__WINDOW_R__", measure = "__MEASURETYPE_R__", channel = ch, contrast = "__COMBOLABEL_R__", role = "secondary", design = "one_sample_vs_0", test = "one_sample_t_test", p = tt$p.value,' ...
        '                                        estimate = dz$effsize, conf.low = dz$conf.low, conf.high = dz$conf.high))' ...
        '' ...
        '  common_layers <- list(' ...
        '    geom_jitter(width = 0.05, colour = "grey40", alpha = 0.6),' ...
        '    geom_hline(yintercept = 0, linetype = "dashed", colour = "grey50"),' ...
        '    stat_summary(fun = mean, geom = "point", size = 3, colour = "#4a7fc9"),' ...
        '    stat_summary(fun.data = mean_se, geom = "errorbar", width = 0.1, colour = "#4a7fc9"),' ...
        '    labs(x = NULL, y = "__YLABEL__"),' ...
        '    scale_x_continuous(breaks = NULL),' ...
        '    alz_theme()' ...
        '  )' ...
        '  p <- ggplot(d, aes(x = 1, y = value, group = 1)) + violin_layers("#4a7fc9") + common_layers' ...
        '  print(p)' ...
        '' ...
        '  # A combination bin IS a difference, so its own values are the' ...
        '  # contrast and the panel needs no subtraction: what is bootstrapped' ...
        '  # here is exactly the quantity the one-sample test above tested.' ...
        '  ep <- estimation_panel(d$value, "__BIN1_R__ (__YLABEL__)")' ...
        '  if (!is.null(ep)) print(ep)' ...
        }, ReportSections.channelLoop('close'), { ...
        '```' ...
        }];
    text = strjoin(lines, newline);
    text = ReportSections.fillToken(text, 'COMBOLABEL', comboLabel);
    text = ReportSections.fillToken(text, 'RECIPE', recipeText);
    text = strrep(text, '__CHUNKLABEL__', ReportSections.chunkLabel('combo', windowLabel, measureType, comboLabel));
    text = strrep(text, '__YLABEL__', ReportSections.yAxisLabel(measureType));
    text = strrep(text, '__BLOCKMATCHDIAGNOSTIC__', ReportSections.blockMatchDiagnosticText());
    block = ReportSections.fillCommonTokens(text, windowLabel, measureType, '', '');
end

