function block = comboSectionGrouped(windowLabel, measureType, comboLabel, recipeText, includeVsZero, includeBetweenGroups)
%COMBOSECTIONGROUPED  One combination (difference) bin, WITH a between-
%   subjects group assigned -- the grouped counterpart of comboSection/
%   comboSectionDescriptiveOnly, answering "does patients_group vs.
%   controls_group have a different DIFFERENCE (e.g. priming effect,
%   repetition effect) score", not just "is there a difference at all".
%
%   INCLUDEVSZERO (false for a latency/circular MEASURETYPE, see
%   isDescriptiveOnlyType) controls whether a one-sample-vs-zero test
%   still runs, now once PER GROUP rather than once for the whole sample
%   -- "does this effect exist at all" becomes a per-group question once
%   groups exist, same statistical-validity reasoning as the ungrouped
%   comboSection, just repeated per group.
%
%   INCLUDEBETWEENGROUPS (false only for a CIRCULAR MEASURETYPE, see
%   isCircularType) controls the actually-new comparison this function
%   adds: an independent-samples test of the combo score BETWEEN groups
%   (Welch *t*-test for 2 groups, Welch ANOVA + Games-Howell for 3+) -- valid
%   for a latency combo bin even though the "vs zero" test above is not
%   (a latency has no natural zero to test AGAINST, but is still an
%   ordinary linear quantity groups can be compared on), invalid only for
%   a circular quantity (phase/phaselag), for which no linear comparison
%   at all -- one-sample or between-groups -- is valid.
%
%   CLUSTERED ACROSS CHANNELS -- see pairedSection's own header comment.
%   vsZeroLines/betweenGroupsLines append into the accumulator lists
%   declared here rather than printing per channel, and this function
%   prints each combined table once, after the channel loop.
%
%   A CIRCULAR measure is summarised per group by its mean angle and resultant
%   length, with no plot, as circularSection does for the ordinary bins. It
%   used to get a linear mean, SD and violin, under a sentence saying linear
%   statistics are not valid for it.
    circular = ReportSections.isCircularType(measureType);
    if circular
        descrLines = { ...
            '  descr_list[[ch]] <- d %>% group_by(group) %>% summarise(' ...
            '    mean_angle_deg = atan2(mean(sin(value)), mean(cos(value))) * 180 / pi,' ...
            '    R_bar = sqrt(mean(sin(value))^2 + mean(cos(value))^2), n = n(), .groups = "drop") %>%' ...
            '    mutate(channel = ch, .before = 1)'};
        descrTitle = 'Circular Descriptive Statistics by Channel';
    else
        descrLines = { ...
            '  descr_list[[ch]] <- d %>% group_by(group) %>% summarise(M = mean(value), SD = sd(value), n = n(), .groups = "drop") %>%' ...
            '    mutate(channel = ch, .before = 1)'};
        descrTitle = 'Descriptive Statistics by Channel';
    end
    lines = ReportDoc.lines([{ ...
        '## __WINDOW_MD__ -- __MEASURETYPE_MD__: __COMBOLABEL_MD__ (By Group)' ...
        '' ...
        ['Difference/combination bin "__COMBOLABEL_MD__" (__RECIPE_MD__), broken down by the ' ...
         'between-subjects group. __REASON_MD__'] ...
        ReportDoc.template('combo-grouped-chunk.qmd') ...
        ''}, ...
        descrLines, ...
        ReportSections.vsZeroLines(includeVsZero), ...
        ReportSections.betweenGroupsLines(includeBetweenGroups), ...
        { ...
        ReportDoc.template('combo-grouped-channel-close.Rpart') ...
        ['  cat(as_raw_html(blank_missing(apa_gt(descr_all, "' descrTitle '"))))'] ...
        '}' ...
        ''}, ...
        plotLines(circular, includeVsZero), ...
        { ...
        '' ...
        'vszero_all <- bind_rows(vszero_list)' ...
        'if (nrow(vszero_all) > 0) {' ...
        '  cat(as_raw_html(blank_missing(apa_gt(vszero_all, "Test Result vs. Zero, by Channel and Group"))))' ...
        '  tests_used <- unique(na.omit(vszero_all$Test))' ...
        ['  caption_txt <- if (length(tests_used) == 0) "" else' ...
         ' if (all(tests_used == "One-sample t-test")) "__CAPTION_PARAM__" else' ...
         ' if (all(tests_used == "Wilcoxon signed-rank")) "__CAPTION_WILCOX__" else' ...
         ' paste("__CAPTION_PARAM__", "__CAPTION_WILCOX__")'] ...
        ReportDoc.template('combo-grouped-vszero-table.Rpart') ...
        ['  caption_txt2 <- if (length(tests_used2) == 0) "" else' ...
         ' if (all(tests_used2 == "Welch two-sample t-test")) "__CAPTION_WELCH_T__" else' ...
         ' if (all(tests_used2 == "Mann-Whitney U")) "__CAPTION_MANN_WHITNEY__" else' ...
         ' paste("__CAPTION_WELCH_T__", "__CAPTION_MANN_WHITNEY__")'] ...
        ReportDoc.template('combo-grouped-anova.qmd') ...
        }]);
    text = strjoin(lines, newline);
    text = ReportSections.fillToken(text, 'COMBOLABEL', comboLabel);
    text = ReportSections.fillToken(text, 'RECIPE', recipeText);
    text = ReportSections.fillToken(text, 'REASON', ReportSections.comboGroupedReason(includeVsZero, includeBetweenGroups));
    text = strrep(text, '__CHUNKLABEL__', ReportSections.chunkLabel('combo-grouped', windowLabel, measureType, comboLabel));
    text = strrep(text, '__YLABEL__', ReportSections.yAxisLabel(measureType));
    text = strrep(text, '__BLOCKMATCHDIAGNOSTIC__', ReportSections.blockMatchDiagnosticText());
    text = strrep(text, '__CAPTION_PARAM__', ReportSections.rLit(ReportSections.testCaption('one_sample_t')));
    text = strrep(text, '__CAPTION_WILCOX__', ReportSections.rLit(ReportSections.testCaption('wilcoxon_signed_rank_one_sample')));
    text = strrep(text, '__CAPTION_WELCH_T__', ReportSections.rLit(ReportSections.testCaption('welch_t')));
    text = strrep(text, '__CAPTION_MANN_WHITNEY__', ReportSections.rLit(ReportSections.testCaption('mann_whitney')));
    text = strrep(text, '__CAPTION_WELCH_ANOVA__', ReportSections.rLit(ReportSections.testCaption('welch_anova')));
    text = strrep(text, '__CAPTION_GAMES_HOWELL__', ReportSections.rLit(ReportSections.testCaption('games_howell')));
    block = ReportSections.fillCommonTokens(text, windowLabel, measureType, '', '');
end

function lines = plotLines(circular, includeVsZero)
%PLOTLINES  The per-group violin of the combination bin, or nothing for a
%   circular measure, which a linear axis misrepresents (see circularSection).
    if circular
        lines = {};
        return;
    end
    lines = ReportDoc.lines({ ...
        ReportSections.zeroLineStatement(includeVsZero) ...
        ReportDoc.template('combo-grouped-plot-layers.R') ...
        });
end
