function block = comboSectionDescriptiveOnly(windowLabel, measureType, comboLabel, recipeText)
%COMBOSECTIONDESCRIPTIVEONLY  A combination bin's own LATENCY or CIRCULAR
%   measure type (see isDescriptiveOnlyType): descriptive statistics and a
%   plot only, no one-sample-vs-zero test and no contribution to the
%   cross-group omnibus summary -- see descriptiveOnlyReason for why,
%   specific to which of the two categories MEASURETYPE falls into.
%   Clustered ACROSS every channel in one table + one faceted plot, same
%   as descriptiveSection -- see its own header comment for why.
    lines = { ...
        '## __WINDOW_MD__ -- __MEASURETYPE_MD__: __COMBOLABEL_MD__' ...
        '' ...
        'Difference/combination bin "__COMBOLABEL_MD__" (__RECIPE_MD__). __REASON_MD__' ...
        '' ...
        '```{r}' ...
        '#| label: __CHUNKLABEL__' ...
        '#| results: asis' ...
        'grp <- dat %>% filter(measure_type == "__MEASURETYPE_R__", window == "__WINDOW_R__", bin == "__COMBOLABEL_R__") %>% droplevels()' ...
        '__BLOCKMATCHDIAGNOSTIC__' ...
        '' ...
        'd <- grp %>% filter(!is.na(value)) %>% droplevels()' ...
        'if (nrow(d) == 0) {' ...
        '  cat("\n*No usable values for this combination bin.*\n\n")' ...
        '} else {' ...
        '  descr <- d %>% group_by(channel) %>% summarise(M = mean(value), SD = sd(value), n = n(), .groups = "drop")' ...
        '  cat(as_raw_html(blank_missing(apa_gt(descr, "Descriptive Statistics by Channel"))))' ...
        '' ...
        '  common_layers <- list(' ...
        '    geom_jitter(width = 0.05, colour = "grey40", alpha = 0.6),' ...
        '    stat_summary(fun = mean, geom = "point", size = 3, colour = "#4a7fc9"),' ...
        '    stat_summary(fun.data = mean_se, geom = "errorbar", width = 0.1, colour = "#4a7fc9"),' ...
        '    labs(x = NULL, y = "__YLABEL__"),' ...
        '    scale_x_continuous(breaks = NULL),' ...
        '    facet_wrap(~channel),' ...
        '    alz_theme()' ...
        '  )' ...
        '  p <- ggplot(d, aes(x = 1, y = value, group = 1)) + violin_layers("#4a7fc9") + common_layers' ...
        '  print(p)' ...
        '}' ...
        '```' ...
        ''};
    text = strjoin(lines, newline);
    text = ReportSections.fillToken(text, 'COMBOLABEL', comboLabel);
    text = ReportSections.fillToken(text, 'RECIPE', recipeText);
    text = ReportSections.fillToken(text, 'REASON', ReportSections.descriptiveOnlyReason(measureType));
    text = strrep(text, '__CHUNKLABEL__', ReportSections.chunkLabel('combo-desc', windowLabel, measureType, comboLabel));
    text = strrep(text, '__YLABEL__', ReportSections.yAxisLabel(measureType));
    text = strrep(text, '__BLOCKMATCHDIAGNOSTIC__', ReportSections.blockMatchDiagnosticText());
    block = ReportSections.fillCommonTokens(text, windowLabel, measureType, '', '');
end
