function block = comboSectionGrouped(windowLabel, measureType, comboLabel, recipeText, includeVsZero, includeBetweenGroups)
%COMBOSECTIONGROUPED  One combination (difference) bin, WITH a between-
%   subjects group assigned -- the grouped counterpart of comboSection/
%   comboSectionDescriptiveOnly, answering "does patients_group vs.
%   controls_group have a different DIFFERENCE (e.g. priming effect,
%   repetition effect) score", not just "is there a difference at all".
%
%   INCLUDEVSZERO (false for a latency/circular MEASURETYPE, see
%   isDescriptiveOnlyType) controls whether a one-sample-vs-zero test
%   still runs, now once PER GROUP rather than once for the whole sample
%   -- "does this effect exist at all" becomes a per-group question once
%   groups exist, same statistical-validity reasoning as the ungrouped
%   comboSection, just repeated per group.
%
%   INCLUDEBETWEENGROUPS (false only for a CIRCULAR MEASURETYPE, see
%   isCircularType) controls the actually-new comparison this function
%   adds: an independent-samples test of the combo score BETWEEN groups
%   (Welch *t*-test for 2 groups, one-way ANOVA + Tukey for 3+) -- valid
%   for a latency combo bin even though the "vs zero" test above is not
%   (a latency has no natural zero to test AGAINST, but is still an
%   ordinary linear quantity groups can be compared on), invalid only for
%   a circular quantity (phase/phaselag), for which no linear comparison
%   at all -- one-sample or between-groups -- is valid.
%
%   CLUSTERED ACROSS CHANNELS -- see pairedSection's own header comment.
%   vsZeroLines/betweenGroupsLines append into the accumulator lists
%   declared here rather than printing per channel, and this function
%   prints each combined table once, after the channel loop.
    lines = [{ ...
        '## __WINDOW_MD__ -- __MEASURETYPE_MD__: __COMBOLABEL_MD__ (By Group)' ...
        '' ...
        ['Difference/combination bin "__COMBOLABEL_MD__" (__RECIPE_MD__), broken down by the ' ...
         'between-subjects group. __REASON_MD__'] ...
        '' ...
        '```{r}' ...
        '#| label: __CHUNKLABEL__' ...
        '#| results: asis' ...
        'grp <- dat %>% filter(measure_type == "__MEASURETYPE_R__", window == "__WINDOW_R__", bin == "__COMBOLABEL_R__") %>% droplevels()' ...
        '__BLOCKMATCHDIAGNOSTIC__' ...
        '' ...
        'descr_list <- list()' ...
        'vszero_list <- list()' ...
        'betweenRes2_list <- list()' ...
        'betweenAnova_list <- list()' ...
        'betweenPw_list <- list()' ...
        'for (ch in unique(grp$channel)) {' ...
        '  tryCatch({' ...
        '  d <- grp %>% filter(channel == ch, !is.na(value)) %>% droplevels()' ...
        '  if (n_distinct(d$dataset) < 2) {' ...
        '    descr_list[[ch]] <- tibble(channel = ch,' ...
        '      Note = sprintf("Skipped: only %d subject(s) have a non-missing value for this combination bin.", n_distinct(d$dataset)))' ...
        '    next' ...
        '  }' ...
        '  tag <- str_replace_all(paste("__WINDOW_R__", "__MEASURETYPE_R__", "__COMBOLABEL_R__", ch, sep = "_"), "[^A-Za-z0-9]+", "_")' ...
        '' ...
        '  descr_list[[ch]] <- d %>% group_by(group) %>% summarise(M = mean(value), SD = sd(value), n = n(), .groups = "drop") %>%' ...
        '    mutate(channel = ch, .before = 1)'}, ...
        ReportSections.vsZeroLines(includeVsZero), ...
        ReportSections.betweenGroupsLines(includeBetweenGroups), ...
        { ...
        '  }, error = function(e) {' ...
        '    descr_list[[ch]] <<- tibble(channel = ch, Note = sprintf("Could not be analysed: %s", conditionMessage(e)))' ...
        '  })' ...
        '}' ...
        '' ...
        'descr_all <- bind_rows(descr_list)' ...
        'if (nrow(descr_all) > 0) {' ...
        '  cat(as_raw_html(blank_missing(apa_gt(descr_all, "Descriptive Statistics by Channel"))))' ...
        '}' ...
        '' ...
        ReportSections.zeroLineStatement(includeVsZero) ...
        'common_layers <- list(' ...
        '  geom_jitter(width = 0.06, alpha = 0.6),' ...
        '  zero_line,' ...
        '  stat_summary(fun = mean, geom = "point", size = 3),' ...
        '  stat_summary(fun.data = mean_se, geom = "errorbar", width = 0.1),' ...
        '  labs(x = "Group", y = "__YLABEL__"),' ...
        '  scale_colour_brewer(palette = "Set2"),' ...
        '  scale_fill_brewer(palette = "Set2"),' ...
        '  facet_wrap(~channel),' ...
        '  alz_theme(),' ...
        '  theme(legend.position = "none")' ...
        ')' ...
        'p <- ggplot(grp %>% filter(!is.na(value)), aes(group, value, colour = group, fill = group)) + violin_layers() + common_layers' ...
        'print(p)' ...
        '' ...
        'vszero_all <- bind_rows(vszero_list)' ...
        'if (nrow(vszero_all) > 0) {' ...
        '  cat(as_raw_html(blank_missing(apa_gt(vszero_all, "Test Result vs. Zero, by Channel and Group"))))' ...
        '  tests_used <- unique(na.omit(vszero_all$Test))' ...
        ['  caption_txt <- if (length(tests_used) == 0) "" else' ...
         ' if (all(tests_used == "One-sample t-test")) "__CAPTION_PARAM__" else' ...
         ' if (all(tests_used == "Wilcoxon signed-rank")) "__CAPTION_WILCOX__" else' ...
         ' paste("__CAPTION_PARAM__", "__CAPTION_WILCOX__")'] ...
        '  if (nzchar(caption_txt)) cat(sprintf("\n*%s*\n\n", caption_txt))' ...
        '}' ...
        '' ...
        'betweenRes2_all <- bind_rows(betweenRes2_list)' ...
        'if (nrow(betweenRes2_all) > 0) {' ...
        '  cat(as_raw_html(blank_missing(apa_gt(betweenRes2_all, "Test Result Between Groups, by Channel"))))' ...
        '  tests_used2 <- unique(na.omit(betweenRes2_all$Test))' ...
        ['  caption_txt2 <- if (length(tests_used2) == 0) "" else' ...
         ' if (all(tests_used2 == "Welch two-sample t-test")) "__CAPTION_WELCH_T__" else' ...
         ' if (all(tests_used2 == "Mann-Whitney U")) "__CAPTION_MANN_WHITNEY__" else' ...
         ' paste("__CAPTION_WELCH_T__", "__CAPTION_MANN_WHITNEY__")'] ...
        '  if (nzchar(caption_txt2)) cat(sprintf("\n*%s*\n\n", caption_txt2))' ...
        '}' ...
        '' ...
        'betweenAnova_all <- bind_rows(betweenAnova_list)' ...
        'if (nrow(betweenAnova_all) > 0) {' ...
        '  cat(as_raw_html(apa_gt(betweenAnova_all, "Welch One-Way ANOVA Between Groups, by Channel")))' ...
        '  cat(sprintf("\n*%s*\n\n", "__CAPTION_WELCH_ANOVA__"))' ...
        '}' ...
        'betweenPw_all <- bind_rows(betweenPw_list)' ...
        'if (nrow(betweenPw_all) > 0) {' ...
        '  cat(as_raw_html(apa_gt(betweenPw_all, "Pairwise Comparisons (Games-Howell), by Channel")))' ...
        '  cat(sprintf("\n*%s*\n\n", "__CAPTION_GAMES_HOWELL__"))' ...
        '}' ...
        '```' ...
        }];
    text = strjoin(lines, newline);
    text = ReportSections.fillToken(text, 'COMBOLABEL', comboLabel);
    text = ReportSections.fillToken(text, 'RECIPE', recipeText);
    text = ReportSections.fillToken(text, 'REASON', ReportSections.comboGroupedReason(includeVsZero, includeBetweenGroups));
    text = strrep(text, '__CHUNKLABEL__', ReportSections.chunkLabel('combo-grouped', windowLabel, measureType, comboLabel));
    text = strrep(text, '__YLABEL__', ReportSections.yAxisLabel(measureType));
    text = strrep(text, '__BLOCKMATCHDIAGNOSTIC__', ReportSections.blockMatchDiagnosticText());
    text = strrep(text, '__CAPTION_PARAM__', ReportSections.rLit(ReportSections.testCaption('one_sample_t')));
    text = strrep(text, '__CAPTION_WILCOX__', ReportSections.rLit(ReportSections.testCaption('wilcoxon_signed_rank_one_sample')));
    text = strrep(text, '__CAPTION_WELCH_T__', ReportSections.rLit(ReportSections.testCaption('welch_t')));
    text = strrep(text, '__CAPTION_MANN_WHITNEY__', ReportSections.rLit(ReportSections.testCaption('mann_whitney')));
    text = strrep(text, '__CAPTION_WELCH_ANOVA__', ReportSections.rLit(ReportSections.testCaption('welch_anova')));
    text = strrep(text, '__CAPTION_GAMES_HOWELL__', ReportSections.rLit(ReportSections.testCaption('games_howell')));
    block = ReportSections.fillCommonTokens(text, windowLabel, measureType, '', '');
end
