function block = pairedSection(windowLabel, measureType, bin1, bin2)
%PAIREDSECTION  Exactly two ordinary bins: a paired t-test, or -- when the
%   within-subject differences depart from normality -- a Wilcoxon
%   signed-rank test instead. Shapiro-Wilk decides which one is reported;
%   only one test is ever shown, not both plus a Bayes factor.
    lines = [{ ...
        '## __WINDOW_MD__ -- __MEASURETYPE_MD__' ...
        '' ...
        'Two conditions: "__BIN1_MD__" vs. "__BIN2_MD__".' ...
        '' ...
        '```{r}' ...
        '#| label: __CHUNKLABEL__' ...
        '#| results: asis' ...
        'grp <- dat %>% filter(measure_type == "__MEASURETYPE_R__", window == "__WINDOW_R__",' ...
        '                       bin %in% c("__BIN1_R__", "__BIN2_R__")) %>% droplevels()' ...
        '__BLOCKMATCHDIAGNOSTIC__' ...
        '' ...
        }, ReportSections.channelLoop('open'), { ...
        '  # !is.na(value) first: a subject missing ONE of the two bins''' ...
        '  # values (e.g. a peak-finding failure) then correctly fails the' ...
        '  # n == 2 check below rather than being counted as present with a' ...
        '  # value the test below cannot use.' ...
        '  d0 <- grp %>% filter(channel == ch, !is.na(value)) %>% droplevels()' ...
        '  counts <- d0 %>% count(dataset)' ...
        '  keep <- counts %>% filter(n == 2) %>% pull(dataset)' ...
        '  d <- d0 %>% filter(dataset %in% keep) %>% droplevels()' ...
        '  if (n_distinct(d$dataset) < 2) {' ...
        '    counts_txt <- paste(sprintf("%s (n=%d)", counts$dataset, counts$n), collapse = ", ")' ...
        '    cat(sprintf("\n\n### %s\n\n*Skipped: only %d of %d subject(s) with any non-missing value have BOTH bins present (at least 2 are needed). Rows per subject for this channel: %s.*\n\n",' ...
        '                ch, length(keep), n_distinct(d0$dataset), counts_txt))' ...
        '    next' ...
        '  }' ...
        '  tag <- str_replace_all(paste("__WINDOW_R__", "__MEASURETYPE_R__", ch, sep = "_"), "[^A-Za-z0-9]+", "_")' ...
        '' ...
        '  wide <- d %>% select(dataset, bin, value) %>% pivot_wider(names_from = bin, values_from = value)' ...
        '  diffs <- wide[["__BIN2_R__"]] - wide[["__BIN1_R__"]]' ...
        '  # Base R''s shapiro.test(), not rstatix''s shapiro_test(): the latter''s' ...
        '  # tidied $p column is only reliable for its GROUPED (data %>%' ...
        '  # group_by() %>% shapiro_test()) form -- called on a bare vector it can' ...
        '  # come back without a $p column at all. Base shapiro.test() has a' ...
        '  # stable list return ($statistic, $p.value); tryCatch handles the' ...
        '  # genuine edge cases it errors on outright (n < 3, zero variance). Not' ...
        '  # narrated -- used only to choose which test below to report.' ...
        '  shap <- tryCatch(shapiro.test(diffs), error = function(e) NULL)' ...
        '  use_parametric <- is.null(shap) || shap$p.value >= .05' ...
        '' ...
        '  # THE EFFECT SIZE MUST BE THE SAME SUBTRACTION AS THE TEST.' ...
        '  # t.test/wilcox.test below is bin2 - bin1, in the order EEG.bindesc' ...
        '  # gives, but cohens_d(value ~ bin)/wilcox_effsize subtract in the order' ...
        '  # of the FACTOR LEVELS, and preambleText builds that factor with' ...
        '  # mutate(bin = factor(bin)), whose levels are alphabetical. Re-levelling' ...
        '  # here rather than computing the effect size by hand keeps rstatix''s' ...
        '  # bootstrap CI, which a mean/sd of the difference vector would lose.' ...
        '  d_lvl <- d %>% mutate(bin = factor(bin, levels = c("__BIN2_R__", "__BIN1_R__")))' ...
        '' ...
        '  if (use_parametric) {' ...
        '    tt <- t.test(wide[["__BIN2_R__"]], wide[["__BIN1_R__"]], paired = TRUE)' ...
        '    eff <- d_lvl %>% rstatix::cohens_d(value ~ bin, paired = TRUE, ci = TRUE, ci.type = "bca", nboot = 200)' ...
        '    res <- tibble(Test = "Paired t-test", Statistic = unname(tt$statistic), df = unname(tt$parameter),' ...
        '                  p = apa_p(tt$p.value), Effect = "Cohen''s dz", Estimate = eff$effsize,' ...
        '                  CI_low = eff$conf.low, CI_high = eff$conf.high)' ...
        '    m_diff <- unname(tt$estimate); ci_lo <- tt$conf.int[1]; ci_hi <- tt$conf.int[2]' ...
        '    p_val <- tt$p.value; test_id <- "paired_t"; caption_txt <- "__CAPTION_PARAM__"' ...
        '  } else {' ...
        '    wt <- wilcox.test(wide[["__BIN2_R__"]], wide[["__BIN1_R__"]], paired = TRUE, conf.int = TRUE)' ...
        '    eff <- d_lvl %>% rstatix::wilcox_effsize(value ~ bin, paired = TRUE, ci = TRUE)' ...
        '    res <- tibble(Test = "Wilcoxon signed-rank", Statistic = unname(wt$statistic), df = NA_real_,' ...
        '                  p = apa_p(wt$p.value), Effect = "Rank-biserial r", Estimate = eff$effsize,' ...
        '                  CI_low = eff$conf.low, CI_high = eff$conf.high)' ...
        '    m_diff <- unname(wt$estimate); ci_lo <- wt$conf.int[1]; ci_hi <- wt$conf.int[2]' ...
        '    p_val <- wt$p.value; test_id <- "wilcoxon_signed_rank"; caption_txt <- "__CAPTION_WILCOX__"' ...
        '  }' ...
        '' ...
        '  cat(sprintf("\n\n### %s\n\n", ch))' ...
        '  descr <- d %>% group_by(bin) %>% summarise(M = mean(value), SD = sd(value), n = n(), .groups = "drop")' ...
        '  cat(as_raw_html(apa_gt(descr, "Descriptive Statistics")))' ...
        '' ...
        '  # THE ESTIMATE LEADS. A reader needs to know which condition was' ...
        '  # larger and by how much, in the units they measured, before the' ...
        '  # table''s significance test -- and the descriptives table above' ...
        '  # already gives the per-condition means, so this states only the' ...
        '  # comparison itself.' ...
        '  direction <- if (m_diff >= 0) "higher than" else "lower than"' ...
        '  cat(sprintf("\n%s averaged %s %s %s, 95%% CI [%s, %s].\n\n",' ...
        '              "__BIN2_MDR__", apa_num(abs(m_diff)), direction, "__BIN1_MDR__", apa_num(ci_lo), apa_num(ci_hi)))' ...
        '  cat(as_raw_html(blank_missing(apa_gt(res, "Test Result"))))' ...
        '  cat(sprintf("\n*%s*\n\n", caption_txt))' ...
        '' ...
        '  omnibus <- bind_rows(omnibus, tibble(group = tag, window = "__WINDOW_R__", measure = "__MEASURETYPE_R__", channel = ch, contrast = NA_character_, role = "primary", design = "paired_t", test = paste0(test_id, "_test"), p = p_val,' ...
        '                                        estimate = res$Estimate, conf.low = res$CI_low, conf.high = res$CI_high))' ...
        '' ...
        '  common_layers <- list(' ...
        '    geom_line(aes(group = dataset), colour = "grey75", alpha = 0.5),' ...
        '    geom_point(colour = "grey40", size = 1.4, alpha = 0.5, position = position_jitter(width = 0.04, height = 0)),' ...
        '    stat_summary(fun = mean, geom = "point", size = 2.2, colour = "#4a7fc9"),' ...
        '    stat_summary(fun.data = mean_se, geom = "errorbar", width = 0.12, colour = "#4a7fc9"),' ...
        '    labs(x = "Bin", y = "__YLABEL__"),' ...
        '    alz_theme()' ...
        '  )' ...
        '  p <- ggplot(d, aes(bin, value)) + violin_layers("#4a7fc9") + common_layers' ...
        '  print(p)' ...
        }, ReportSections.channelLoop('close'), { ...
        '```' ...
        }];
    text = strjoin(lines, newline);
    text = strrep(text, '__CHUNKLABEL__', ReportSections.chunkLabel('paired', windowLabel, measureType));
    text = strrep(text, '__YLABEL__', ReportSections.yAxisLabel(measureType));
    text = strrep(text, '__BLOCKMATCHDIAGNOSTIC__', ReportSections.blockMatchDiagnosticText());
    text = strrep(text, '__CAPTION_PARAM__', ReportSections.rLit(ReportSections.testCaption('paired_t')));
    text = strrep(text, '__CAPTION_WILCOX__', ReportSections.rLit(ReportSections.testCaption('wilcoxon_signed_rank')));
    block = ReportSections.fillCommonTokens(text, windowLabel, measureType, bin1, bin2);
end
