function block = singleTrialSection(windowLabel, measureType, binLabels)
%SINGLETRIALSECTION  A mixed model fitted to the TRIALS, not to per-subject
%   averages.
%
%   WHAT THIS BUYS OVER THE AVERAGED MODEL. Averaging first throws away
%   everything inside a subject: a subject contributing 12 usable trials
%   and one contributing 90 arrive as one number each and are weighted
%   identically, though the first estimate is far noisier. Fitting the
%   trials instead lets the model see that, weight subjects by the
%   evidence they actually carry, and estimate within-subject variance
%   rather than discarding it. This is the current standard for ERP
%   inference (Frömer et al. 2018; Volpert-Esmond & Bartholow 2021).
%
%   THE RANDOM STRUCTURE IS MAXIMAL, THEN REDUCED IF IT HAS TO BE. The
%   model tried first is value ~ bin + (1 + bin | person_id), the maximal
%   structure the design justifies (Barr et al. 2013): condition varies
%   within person, so its slope is allowed to as well. Random slopes very
%   often fail to converge or fit singularly with ERP trial counts, so a
%   singular or failed fit falls back to random intercepts and the report
%   SAYS SO in the text rather than presenting the simpler model as if it
%   had been the intention. A reader cannot otherwise tell which was fitted.
%
%   IT DOES NOT REPLACE THE AVERAGED TEST, it sits beside it, and the two
%   are expected to agree in the ordinary case. Where they disagree the
%   difference is informative rather than a fault: it usually means trial
%   counts are badly unequal, or a few subjects carry the averaged effect
%   with very noisy means.
%
%   Requires the per-trial export (exportTrialMeasurementsCSV), produced by
%   running Measure on EPOCHED data. The section is omitted when that file
%   is absent, which is the ordinary case for an averaged-only workspace.
%
%   See also EXPORTTRIALMEASUREMENTSCSV, MEASURE, LMMSECTION.
    binLabels = cellstr(string(binLabels));
    quoted = cellfun(@(b) ['"' ReportSections.rLit(b) '"'], binLabels, 'UniformOutput', false);

    lines = [{ ...
        '## __WINDOW_MD__ -- __MEASURETYPE_MD__: single-trial model' ...
        '' ...
        ['Fitted to the individual trials rather than to per-subject averages, so that ' ...
         'subjects contributing few trials are weighted as the noisier estimates they are, ' ...
         'and the within-subject variance is estimated rather than averaged away.'] ...
        '' ...
        '```{r}' ...
        '#| label: __CHUNKLABEL__' ...
        '#| results: asis' ...
        '#| fig-height: 4' ...
        'if (!exists("tdat") || is.null(tdat) || nrow(tdat) == 0) {' ...
        '  cat("\n*No per-trial export accompanied this file, so no single-trial model was fitted.*\n\n")' ...
        '} else {' ...
        '  grp <- tdat %>% filter(measure_type == "__MEASURETYPE_R__", window == "__WINDOW_R__",' ...
        '                         bin %in% c(__BINVECTOR_R__)) %>% droplevels()' ...
        ''}, ...
        ReportSections.channelLoop('open'), { ...
        '  d <- grp %>% filter(channel == ch, !is.na(value)) %>% droplevels()' ...
        '  if (n_distinct(d$person_id) < 3 || n_distinct(d$bin) < 2) {' ...
        '    cat(sprintf("\n\n### %s\n\n*Skipped: needs at least three people and two conditions.*\n\n", ch))' ...
        '    next' ...
        '  }' ...
        '  cat(sprintf("\n\n### %s\n\n", ch))' ...
        '' ...
        '  # How many trials each person actually contributed, per condition. This' ...
        '  # is the information the averaged export cannot carry, so it is stated' ...
        '  # before the model that uses it.' ...
        '  counts <- d %>% count(person_id, bin, name = "trials")' ...
        '  cat(as_raw_html(apa_gt(counts %>% pivot_wider(names_from = bin, values_from = trials),' ...
        '                         "Trials per Person")))' ...
        '  rng <- range(counts$trials)' ...
        '  cat(sprintf("\nTrial counts range from %d to %d per person and condition.\n\n", rng[1], rng[2]))' ...
        '' ...
        '  # TRIAL ORDER IS A COVARIATE, NOT A NUISANCE TO IGNORE. Single-trial' ...
        '  # ERP amplitude drifts across a session with fatigue, habituation and' ...
        '  # slow changes in alpha state, and that drift is confounded with' ...
        '  # condition whenever the design is not perfectly counterbalanced in' ...
        '  # order. Controlling for it is one of the main reasons to model trials' ...
        '  # at all, so the trial index is centred WITHIN person (a person who' ...
        '  # contributed fewer trials should not be shifted along the axis by' ...
        '  # their own count) and scaled, which also helps the model converge.' ...
        '  d <- d %>% group_by(person_id) %>%' ...
        '       mutate(trial_c = as.numeric(scale(trial))) %>% ungroup()' ...
        '  d$trial_c[!is.finite(d$trial_c)] <- 0   # a person with one trial has no spread' ...
        '' ...
        '  # MAXIMAL FIRST, THEN REDUCED IN THE ORDER THAT COSTS LEAST.' ...
        '  # Barr et al. (2013) argue for the maximal structure the design' ...
        '  # justifies; Bates et al. (2015) show that when it will not stand up' ...
        '  # the correlation between random terms is what to drop FIRST, since' ...
        '  # it is the parameter the data can least afford, and only then the' ...
        '  # slope itself. Going straight from slopes to intercepts, as an' ...
        '  # earlier version of this section did, discards a model the data may' ...
        '  # well support.' ...
        '  fit <- function(f) tryCatch(suppressMessages(suppressWarnings(' ...
        '           lmerTest::lmer(f, data = d))), error = function(e) NULL)' ...
        '  ok <- function(mm) !is.null(mm) && !isSingular(mm)' ...
        '' ...
        '  structure_used <- "random intercepts and correlated slopes"' ...
        '  m <- fit(value ~ bin + trial_c + (1 + bin | person_id))' ...
        '  if (!ok(m)) {' ...
        '    structure_used <- "random intercepts and uncorrelated slopes"' ...
        '    m <- fit(value ~ bin + trial_c + (1 + bin || person_id))' ...
        '  }' ...
        '  if (!ok(m)) {' ...
        '    structure_used <- "random intercepts only"' ...
        '    m <- fit(value ~ bin + trial_c + (1 | person_id))' ...
        '  }' ...
        '' ...
        '  if (is.null(m)) {' ...
        '    cat("\n*No single-trial model converged for this channel.*\n\n")' ...
        '  } else {' ...
        '    av <- as.data.frame(anova(m))' ...
        '    p_bin <- suppressWarnings(av[["Pr(>F)"]][1])' ...
        '    cat(as_raw_html(apa_gt(av, "Single-Trial Mixed Model (Type III, Satterthwaite)")))' ...
        '' ...
        '    # AN F WITH NO EFFECT SIZE IS WHAT THE REST OF THIS REPORT AVOIDS.' ...
        '    # With exactly two conditions the fixed effect IS the difference, in' ...
        '    # the data''s own units, so it is reported with a Wald interval and' ...
        '    # carried into the summary where the forest plot can draw it. With' ...
        '    # three or more there is no single number to quote and the estimate' ...
        '    # is left missing rather than invented from one arbitrary contrast.' ...
        '    est <- NA_real_; lo <- NA_real_; hi <- NA_real_' ...
        '    if (nlevels(droplevels(d$bin)) == 2) {' ...
        '      ci <- tryCatch(suppressMessages(confint(m, method = "Wald")), error = function(e) NULL)' ...
        '      coefs <- fixef(m)' ...
        '      term <- grep("^bin", names(coefs), value = TRUE)[1]' ...
        '      if (!is.na(term) && !is.null(ci) && term %in% rownames(ci)) {' ...
        '        est <- unname(coefs[term]); lo <- ci[term, 1]; hi <- ci[term, 2]' ...
        '        cat(sprintf("\nThe fitted condition difference is %s, 95%% CI [%s, %s] (Wald), with trial order held constant.\n\n",' ...
        '                    apa_num(est), apa_num(lo), apa_num(hi)))' ...
        '      }' ...
        '    }' ...
        '    cat(sprintf("\nThe model used %s. %s\n\n", structure_used,' ...
        '                if (identical(structure_used, "random intercepts only"))' ...
        '                  "The by-person condition slopes were dropped: with these trial counts the maximal model was singular, which means the data do not support estimating them."' ...
        '                else "")) ' ...
        '    cat(sprintf("Fitted on %d trials from %d people.\n\n", nrow(d), n_distinct(d$person_id)))' ...
        '' ...
        '    # Per-person trial distributions: the spread an average hides. Each' ...
        '    # person is one row, so an effect carried by two people with wide' ...
        '    # distributions looks different here from one shared by everybody.' ...
        '    p <- ggplot(d, aes(x = value, y = person_id, fill = bin)) +' ...
        '      geom_violin(alpha = 0.5, position = position_dodge(width = 0.7), linewidth = 0.2) +' ...
        '      labs(x = "__YAXIS_MDR__", y = NULL, fill = "condition") +' ...
        '      alz_theme()' ...
        '    print(p)' ...
        '    cat("\n\n")' ...
        '' ...
        '    # The by-person deviations the model estimated: a caterpillar plot.' ...
        '    # Flat and overlapping zero means the effect is common to everybody;' ...
        '    # a wide spread means it is not, which a fixed effect alone hides.' ...
        '    re <- tryCatch(as.data.frame(ranef(m, condVar = TRUE)), error = function(e) NULL)' ...
        '    if (!is.null(re) && nrow(re) > 0) {' ...
        '      q <- ggplot(re, aes(x = condval, y = grp,' ...
        '                          xmin = condval - 1.96 * condsd, xmax = condval + 1.96 * condsd)) +' ...
        '        geom_vline(xintercept = 0, linetype = "dashed", colour = "grey50") +' ...
        '        geom_pointrange(size = 0.25) +' ...
        '        facet_wrap(~ term, scales = "free_x") +' ...
        '        labs(x = "by-person deviation", y = NULL) +' ...
        '        alz_theme()' ...
        '      print(q)' ...
        '      cat("\n\n")' ...
        '    }' ...
        '' ...
        '    tag <- str_replace_all(paste("__WINDOW_R__", "__MEASURETYPE_R__", ch, "singletrial", sep = "_"),' ...
        '                           "[^A-Za-z0-9]+", "_")' ...
        '    omnibus <- bind_rows(omnibus, tibble(group = tag, window = "__WINDOW_R__",' ...
        '                                         measure = "__MEASURETYPE_R__", channel = ch,' ...
        '                                         contrast = NA_character_, design = "single_trial_lmm",' ...
        '                                         test = "omnibus", p = p_bin, role = "secondary",' ...
        '                                         estimate = est, conf.low = lo, conf.high = hi))' ...
        '  }' ...
        ''}, ...
        ReportSections.channelLoop('close'), { ...
        '}' ...
        '```' ...
        '' ...
        }];

    block = strjoin(lines, newline);
    block = ReportSections.fillCommonTokens(block, windowLabel, measureType, '', '');
    block = ReportSections.fillToken(block, 'YAXIS', ReportSections.yAxisLabel(measureType));
    block = strrep(block, '__BINVECTOR_R__', strjoin(quoted, ', '));
    block = strrep(block, '__BLOCKMATCHDIAGNOSTIC__', ReportSections.blockMatchDiagnosticText());
    block = strrep(block, '__CHUNKLABEL__', ...
        ReportSections.chunkLabel('singletrial', windowLabel, measureType));
end
