function block = singleTrialSection(windowLabel, measureType, binLabels)
%SINGLETRIALSECTION  A mixed model fitted to the TRIALS, not to per-subject
%   averages.
%
%   WHAT THIS BUYS OVER THE AVERAGED MODEL. Averaging first throws away
%   everything inside a subject: a subject contributing 12 usable trials
%   and one contributing 90 arrive as one number each and are weighted
%   identically, though the first estimate is far noisier. Fitting the
%   trials instead lets the model see that, weight subjects by the
%   evidence they actually carry, and estimate within-subject variance
%   rather than discarding it. This is the current standard for ERP
%   inference (Frömer et al. 2018; Volpert-Esmond & Bartholow 2021).
%
%   THE RANDOM STRUCTURE IS MAXIMAL, THEN REDUCED IF IT HAS TO BE. The
%   model tried first is value ~ bin + (1 + bin | person_id), the maximal
%   structure the design justifies (Barr et al. 2013): condition varies
%   within person, so its slope is allowed to as well. Random slopes very
%   often fail to converge or fit singularly with ERP trial counts, so a
%   singular or failed fit falls back to random intercepts, recorded in
%   the Model column of the clustered table rather than narrated per
%   channel -- a reader cannot otherwise tell which was fitted.
%
%   IT DOES NOT REPLACE THE AVERAGED TEST, it sits beside it, and the two
%   are expected to agree in the ordinary case. Where they disagree the
%   difference is informative rather than a fault: it usually means trial
%   counts are badly unequal, or a few subjects carry the averaged effect
%   with very noisy means.
%
%   Requires the per-trial export (exportTrialMeasurementsCSV), produced by
%   running Measure on EPOCHED data. The section is omitted when that file
%   is absent, which is the ordinary case for an averaged-only workspace.
%
%   CLUSTERED ACROSS CHANNELS -- see pairedSection's own header comment.
%
%   See also EXPORTTRIALMEASUREMENTSCSV, MEASURE, LMMSECTION.
    binLabels = cellstr(string(binLabels));
    quoted = cellfun(@(b) ['"' ReportSections.rLit(b) '"'], binLabels, 'UniformOutput', false);

    lines = [{ ...
        '## __WINDOW_MD__ -- __MEASURETYPE_MD__: single-trial model' ...
        '' ...
        ['Fitted to the individual trials rather than to per-subject averages, so that ' ...
         'subjects contributing few trials are weighted as the noisier estimates they are, ' ...
         'and the within-subject variance is estimated rather than averaged away.'] ...
        '' ...
        '```{r}' ...
        '#| label: __CHUNKLABEL__' ...
        '#| results: asis' ...
        '#| fig-height: 4' ...
        'if (!exists("tdat") || is.null(tdat) || nrow(tdat) == 0) {' ...
        '  cat("\n*No per-trial export accompanied this file, so no single-trial model was fitted.*\n\n")' ...
        '} else {' ...
        '  grp <- tdat %>% filter(measure_type == "__MEASURETYPE_R__", window == "__WINDOW_R__",' ...
        '                         bin %in% c(__BINVECTOR_R__)) %>% droplevels()' ...
        '' ...
        '  trials_list <- list()' ...
        '  model_list <- list()' ...
        '  results_list <- list()' ...
        '  for (ch in unique(grp$channel)) {' ...
        '    tryCatch({' ...
        '    d <- grp %>% filter(channel == ch, !is.na(value)) %>% droplevels()' ...
        '    if (n_distinct(d$person_id) < 3 || n_distinct(d$bin) < 2) {' ...
        '      model_list[[ch]] <- tibble(Channel = ch, Model = "Skipped: needs at least three people and two conditions.")' ...
        '      next' ...
        '    }' ...
        '' ...
        '    # How many trials each person actually contributed, per condition. This' ...
        '    # is the information the averaged export cannot carry.' ...
        '    counts <- d %>% count(person_id, bin, name = "trials")' ...
        '    trials_list[[ch]] <- (counts %>% pivot_wider(names_from = bin, values_from = trials)) %>%' ...
        '      mutate(channel = ch, .before = 1)' ...
        '' ...
        '    # TRIAL ORDER IS A COVARIATE, NOT A NUISANCE TO IGNORE. Single-trial' ...
        '    # ERP amplitude drifts across a session with fatigue, habituation and' ...
        '    # slow changes in alpha state, and that drift is confounded with' ...
        '    # condition whenever the design is not perfectly counterbalanced in' ...
        '    # order. Controlling for it is one of the main reasons to model trials' ...
        '    # at all, so the trial index is centred WITHIN person (a person who' ...
        '    # contributed fewer trials should not be shifted along the axis by' ...
        '    # their own count) and scaled, which also helps the model converge.' ...
        '    d <- d %>% group_by(person_id) %>%' ...
        '         mutate(trial_c = as.numeric(scale(trial))) %>% ungroup()' ...
        '    d$trial_c[!is.finite(d$trial_c)] <- 0   # a person with one trial has no spread' ...
        '' ...
        '    # MAXIMAL FIRST, THEN REDUCED IN THE ORDER THAT COSTS LEAST.' ...
        '    # Barr et al. (2013) argue for the maximal structure the design' ...
        '    # justifies; Bates et al. (2015) show that when it will not stand up' ...
        '    # the correlation between random terms is what to drop FIRST, since' ...
        '    # it is the parameter the data can least afford, and only then the' ...
        '    # slope itself. Going straight from slopes to intercepts, as an' ...
        '    # earlier version of this section did, discards a model the data may' ...
        '    # well support.' ...
        '    fit <- function(f) tryCatch(suppressMessages(suppressWarnings(' ...
        '             lmerTest::lmer(f, data = d))), error = function(e) NULL)' ...
        '    ok <- function(mm) !is.null(mm) && !isSingular(mm)' ...
        '' ...
        '    structure_used <- "Random intercepts and correlated slopes"' ...
        '    m <- fit(value ~ bin + trial_c + (1 + bin | person_id))' ...
        '    if (!ok(m)) {' ...
        '      structure_used <- "Random intercepts and uncorrelated slopes"' ...
        '      m <- fit(value ~ bin + trial_c + (1 + bin || person_id))' ...
        '    }' ...
        '    if (!ok(m)) {' ...
        '      structure_used <- "Random intercepts only (maximal model was singular)"' ...
        '      m <- fit(value ~ bin + trial_c + (1 | person_id))' ...
        '    }' ...
        '' ...
        '    if (is.null(m)) {' ...
        '      model_list[[ch]] <- tibble(Channel = ch, Model = "Did not converge")' ...
        '      next' ...
        '    }' ...
        '    model_list[[ch]] <- tibble(Channel = ch, Model = structure_used, N_trials = nrow(d), N_people = n_distinct(d$person_id))' ...
        '' ...
        '    av <- as.data.frame(anova(m))' ...
        '    p_bin <- suppressWarnings(av[["Pr(>F)"]][1])' ...
        '' ...
        '    # AN F WITH NO EFFECT SIZE IS WHAT THE REST OF THIS REPORT AVOIDS.' ...
        '    # With exactly two conditions the fixed effect IS the difference, in' ...
        '    # the data''s own units, so it is reported with a Wald interval and' ...
        '    # carried into the summary where the forest plot can draw it. With' ...
        '    # three or more there is no single number to quote and the estimate' ...
        '    # is left missing rather than invented from one arbitrary contrast.' ...
        '    est <- NA_real_; lo <- NA_real_; hi <- NA_real_' ...
        '    if (nlevels(droplevels(d$bin)) == 2) {' ...
        '      ci <- tryCatch(suppressMessages(confint(m, method = "Wald")), error = function(e) NULL)' ...
        '      coefs <- fixef(m)' ...
        '      term <- grep("^bin", names(coefs), value = TRUE)[1]' ...
        '      if (!is.na(term) && !is.null(ci) && term %in% rownames(ci)) {' ...
        '        est <- unname(coefs[term]); lo <- ci[term, 1]; hi <- ci[term, 2]' ...
        '      }' ...
        '    }' ...
        '    results_list[[ch]] <- as.data.frame(av) %>% mutate(Channel = ch, .before = 1) %>%' ...
        '      mutate(Estimate = est, CI_low = lo, CI_high = hi)' ...
        '' ...
        '    tag <- str_replace_all(paste("__WINDOW_R__", "__MEASURETYPE_R__", ch, "singletrial", sep = "_"),' ...
        '                           "[^A-Za-z0-9]+", "_")' ...
        '    omnibus <- bind_rows(omnibus, tibble(group = tag, window = "__WINDOW_R__",' ...
        '                                         measure = "__MEASURETYPE_R__", channel = ch,' ...
        '                                         contrast = NA_character_, design = "single_trial_lmm",' ...
        '                                         test = "omnibus", p = p_bin, role = "secondary",' ...
        '                                         estimate = est, conf.low = lo, conf.high = hi))' ...
        '    }, error = function(e) {' ...
        '      model_list[[ch]] <<- tibble(Channel = ch, Model = sprintf("Could not be analysed: %s", conditionMessage(e)))' ...
        '    })' ...
        '  }' ...
        '' ...
        '  trials_all <- bind_rows(trials_list)' ...
        '  if (nrow(trials_all) > 0) {' ...
        '    cat(as_raw_html(apa_gt(trials_all, "Trials per Person, by Channel")))' ...
        '  }' ...
        '' ...
        '  model_all <- bind_rows(model_list)' ...
        '  if (nrow(model_all) > 0) {' ...
        '    cat(as_raw_html(blank_missing(apa_gt(model_all, "Model Fitted, by Channel"))))' ...
        }, { ...
        ['    cat(sprintf("\n*%s*\n\n", "' ReportSections.rLit(ReportSections.testCaption('lmm')) '"))'] ...
        }, { ...
        '  }' ...
        '' ...
        '  results_all <- bind_rows(results_list)' ...
        '  if (nrow(results_all) > 0) {' ...
        '    cat(as_raw_html(blank_missing(apa_gt(results_all, "Single-Trial Mixed Model (Type III, Satterthwaite), by Channel"))))' ...
        '  }' ...
        '' ...
        '  # Per-person trial distributions: the spread an average hides. Each' ...
        '  # person is one row, so an effect carried by two people with wide' ...
        '  # distributions looks different here from one shared by everybody.' ...
        '  p <- ggplot(grp %>% filter(!is.na(value)), aes(x = value, y = person_id, fill = bin)) +' ...
        '    geom_violin(alpha = 0.5, position = position_dodge(width = 0.7), linewidth = 0.2) +' ...
        '    labs(x = "__YAXIS_MDR__", y = NULL, fill = "condition") +' ...
        '    facet_wrap(~channel) +' ...
        '    alz_theme()' ...
        '  print(p)' ...
        '}' ...
        '```' ...
        '' ...
        }];

    block = strjoin(lines, newline);
    block = ReportSections.fillCommonTokens(block, windowLabel, measureType, '', '');
    block = ReportSections.fillToken(block, 'YAXIS', ReportSections.yAxisLabel(measureType));
    block = strrep(block, '__BINVECTOR_R__', strjoin(quoted, ', '));
    block = strrep(block, '__BLOCKMATCHDIAGNOSTIC__', ReportSections.blockMatchDiagnosticText());
    block = strrep(block, '__CHUNKLABEL__', ...
        ReportSections.chunkLabel('singletrial', windowLabel, measureType));
end
