function block = spectrumSection(windowLabel, binLabels)
%SPECTRUMSECTION  The evoked amplitude spectra the frequency measurements
%   were read from, with the tested frequencies marked.
%
%   THE SPECTRAL COUNTERPART OF WAVEFORMSECTION, and it exists for exactly
%   the same reason. Every other section reports statistics ON a number
%   read at a named frequency: power at f1, signal-to-noise against the
%   neighbouring bins, phase locking across trials. None of them shows the
%   spectrum that number came from.
%
%   What that hides is specific to tagging designs and easy to miss in a
%   table. A tag that is simply not present still yields a power value and
%   an SNR near 1. A response sitting one bin away from where it was
%   measured yields a small value that looks like a weak effect rather than
%   a misplaced window. An SNR computed against neighbouring bins that are
%   themselves contaminated, by line noise or by a harmonic of the other
%   tag, is inflated or deflated with nothing in the number to say so. All
%   three are obvious the moment the spectrum is drawn with the tested
%   frequencies marked on it.
%
%   THE MARKS ARE THE FREQUENCIES ACTUALLY TESTED, read from the export
%   rather than recomputed here, so a mark cannot drift away from the value
%   reported beside it. Where the export names a frequency the spectrum
%   does not reach, the mark is simply outside the axis, which is itself
%   worth seeing.
%
%   Requires the spectra export (exportSpectraCSV); omitted when that file
%   was not written, since a spectral measurements export can exist without
%   one.
%
%   See also EXPORTSPECTRACSV, WAVEFORMSECTION, SPECTRALMEASURE.
    binLabels = cellstr(string(binLabels));
    quoted = cellfun(@(b) ['"' ReportSections.rLit(b) '"'], binLabels, 'UniformOutput', false);

    lines = { ...
        '## __WINDOW_MD__: spectra' ...
        '' ...
        ['The evoked amplitude spectra from which these measurements were taken. Dashed lines ' ...
         'mark the tested frequencies, read from the export itself so that they cannot differ ' ...
         'from the values reported above.'] ...
        '' ...
        '```{r}' ...
        '#| label: __CHUNKLABEL__' ...
        '#| results: asis' ...
        '#| fig-height: 4' ...
        'if (!exists("spec") || is.null(spec) || nrow(spec) == 0) {' ...
        '  cat("\n*No spectra export accompanied this file, so the spectra cannot be shown.*\n\n")' ...
        '} else {' ...
        '  chans <- dat %>% filter(window == "__WINDOW_R__") %>% distinct(channel) %>% pull(channel)' ...
        '  sw <- spec %>% filter(channel %in% chans, bin %in% c(__BINVECTOR_R__))' ...
        '' ...
        '  # The frequencies this window actually tested. A spectral export names' ...
        '  # them in its own window column (a label such as "10Hz"), but the' ...
        '  # numeric value lives in the measurements, so it is read from there.' ...
        '  marks <- dat %>% filter(window == "__WINDOW_R__") %>%' ...
        '           summarise(f = suppressWarnings(unique(frequency_hz))) %>% pull(f)' ...
        '  marks <- marks[is.finite(marks)]' ...
        '' ...
        '  if (nrow(sw) == 0) {' ...
        '    cat("\n*The spectra export has no matching channels or bins for this window.*\n\n")' ...
        '  } else {' ...
        '    p <- ggplot(sw, aes(x = frequency_hz, y = amplitude, colour = bin))' ...
        '    if (length(marks) > 0) {' ...
        '      p <- p + geom_vline(xintercept = marks, linetype = "dashed",' ...
        '                          colour = "grey45", linewidth = 0.4)' ...
        '    }' ...
        '    p <- p +' ...
        '      geom_line(linewidth = 0.6) +' ...
        '      facet_wrap(~ channel, scales = "free_y") +' ...
        '      labs(x = "frequency (Hz)", y = "evoked amplitude", colour = "condition") +' ...
        '      alz_theme()' ...
        '    print(p)' ...
        '    cat("\n\n")' ...
        '' ...
        '    if (length(marks) > 0) {' ...
        '      cat(sprintf("Tested at %s Hz.\n\n", paste(format(marks, trim = TRUE), collapse = ", ")))' ...
        '    }' ...
        '  }' ...
        '}' ...
        '```' ...
        '' ...
        };

    block = strjoin(lines, newline);
    block = ReportSections.fillCommonTokens(block, windowLabel, '', '', '');
    block = strrep(block, '__BINVECTOR_R__', strjoin(quoted, ', '));
    block = strrep(block, '__CHUNKLABEL__', ...
        ReportSections.chunkLabel('spectrum', windowLabel));
end
