function txt = testCaption(testId)
%TESTCAPTION  One plain-English sentence saying what a given test id actually
%   tests, for the caption printed under that test's results table. One
%   place to keep this wording consistent across every report section,
%   rather than a copy (and eventual drift) in each one.
%
%   Deliberately no inline markdown/italics inside the sentence itself: the
%   call site wraps the whole caption in one pair of asterisks (see e.g.
%   pairedSection.m), and a nested "*a *t*-test does X*" is ambiguous
%   Pandoc emphasis, not a bolded/italicised "t".
    switch testId
        case 'paired_t'
            txt = ['Tests whether the mean of each subject''s own within-subject ' ...
                   'difference between the two conditions differs from zero.'];
        case 'wilcoxon_signed_rank'
            txt = ['A rank-based alternative to the paired t-test, used because the ' ...
                   'within-subject differences departed from normality: tests whether ' ...
                   'those differences are symmetric around zero.'];
        case 'one_sample_t'
            txt = 'Tests whether the mean of this measure differs from zero.';
        case 'wilcoxon_signed_rank_one_sample'
            txt = ['A rank-based alternative to the one-sample t-test, used because the ' ...
                   'values departed from normality: tests whether the distribution is ' ...
                   'symmetric around zero.'];
        case 'welch_t'
            txt = ['Tests whether the two groups'' means differ, without assuming they ' ...
                   'share the same variance.'];
        case 'mann_whitney'
            txt = ['A rank-based alternative to the independent-samples t-test, used ' ...
                   'because the data departed from normality: tests whether one group''s ' ...
                   'values tend to be larger than the other''s.'];
        case 'welch_anova'
            txt = ['Tests whether at least one group''s mean differs from the others, ' ...
                   'without assuming the groups share the same variance.'];
        case 'games_howell'
            txt = ['Pairwise follow-up comparisons after the omnibus test above, each ' ...
                   'using its own variance estimate rather than assuming every group ' ...
                   'shares one.'];
        case 'lmm'
            txt = ['A linear mixed model estimating each condition''s mean while ' ...
                   'accounting for repeated measurements within each subject: unlike a ' ...
                   'repeated-measures ANOVA, a subject missing one condition still ' ...
                   'contributes their other data rather than being dropped entirely.'];
        case 'lmm_bf'
            txt = ['BF10 compares the model with this effect against the same model without ' ...
                   'it, each with a random intercept per person and the default priors of ' ...
                   'Rouder et al. (2012). Above 1 favours the effect, below 1 its absence. ' ...
                   'Where the model above also let the effect vary between people (a random ' ...
                   'slope), this comparison does not.'];
        case 'emmeans_holm'
            % Unconditional: the within-subjects and mixed designs run these
            % whatever the model's own test gave (lmmSection's 'bin' and
            % 'both' post-hoc policies), so the caption must not say otherwise.
            txt = ['Holm-corrected pairwise comparisons from the fitted model above, ' ...
                   'corrected among themselves. They are shown whether or not the ' ...
                   'model''s own test was significant.'];
        case 'emmeans_holm_gated'
            txt = ['Holm-corrected pairwise follow-up comparisons from the fitted model ' ...
                   'above, run only because the effect they follow up was significant.'];
        case 'circular_bootstrap_ci'
            txt = ['A percentile bootstrap confidence interval on the mean direction, ' ...
                   'valid for circular (angular) data where an ordinary linear ' ...
                   'confidence interval would not be.'];
        otherwise
            throw(MException('Alakazam:testCaption', ...
                'I do not have a caption for test id "%s".', testId));
    end
end
