function block = waveformSection(windowLabel, binLabels, grandAverageCsv)
%WAVEFORMSECTION  The grand-average waveforms the measurements were taken
%   from, with the measurement window shaded and, for a two-condition
%   design, the difference wave and its confidence band.
%
%   WHY A REPORT OF NUMBERS NEEDS A PICTURE OF THE SIGNAL. Every other
%   section here reports statistics ON a measurement: a mean amplitude
%   over 300-500 ms at Cz, tested, effect-sized and corrected. None of
%   them shows the waveform that measurement came from. A window placed
%   over the wrong peak, a polarity flip, a baseline that never got
%   applied and a component that simply is not there all produce numbers
%   that test perfectly well and mean nothing, and all four are obvious at
%   a glance on the wave. This section exists so that every number in the
%   document can be checked against the signal behind it.
%
%   THE WINDOW IS READ FROM THE MEASUREMENTS THEMSELVES, not passed in:
%   exportMeasurementsCSV already writes window_start_ms and
%   window_stop_ms beside every value, so the shaded band is by
%   construction the interval that was actually measured rather than one
%   re-derived here and able to disagree with it.
%
%   THE DIFFERENCE WAVE IS ONLY DRAWN FOR EXACTLY TWO CONDITIONS, because
%   with three or more there is no single difference to draw and picking
%   one would be an editorial claim the report has no business making.
%   NO PAIRED STANDARD ERROR IS DRAWN ON IT, and that is a limit of the
%   file rather than a choice. A paired SE needs the covariance between the
%   two conditions across subjects; a grand-average export carries only
%   each condition's own error, so the paired quantity is not recoverable
%   from it. A band appears only when there are several grand averages to
%   take one across, and is then labelled as the spread between those. The
%   alternative -- drawing each condition's own SE and letting a reader
%   read their overlap as a test -- is the misreading this section exists
%   to prevent.
%
%   Requires the grand-average export (exportGrandAveragesCSV); the
%   section is simply omitted when that file was not written, since a
%   measurements export can legitimately exist without one.
%
%   See also EXPORTGRANDAVERAGESCSV, EXPORTMEASUREMENTSCSV.
    binLabels = cellstr(string(binLabels));

    lines = ReportDoc.lines({ ...
        '## __WINDOW_MD__ -- waveforms' ...
        '' ...
        ['The grand-average waveforms these measurements were taken from. The shaded band is ' ...
         'the measurement window itself, read from the export rather than restated here, so it ' ...
         'cannot disagree with the values tested above. Ribbons are each condition''s own ' ...
         'standard error across subjects. They describe the conditions and not the difference ' ...
         'between them, and whether they overlap is not evidence about a within-subject ' ...
         'effect (see the difference wave below).'] ...
        ReportDoc.template('waveform-per-bin.qmd') ...
        });

    if numel(binLabels) == 2
        lines = ReportDoc.lines([lines, { ...
            '' ...
            ['The difference wave (__BIN2_MD__ minus __BIN1_MD__), which is the quantity the ' ...
             'paired test above is about. Note that the two conditions'' own error bands ' ...
             'overlapping in the plot above says nothing either way about a within-subject ' ...
             'effect, which is why the difference is drawn separately.'] ...
            '' ...
            ['A confidence band is shown only where there is more than one grand average to ' ...
             'take one across, and it is then the spread BETWEEN grand averages. The paired ' ...
             'standard error across subjects cannot be computed from this file: that needs the ' ...
             'covariance between the two conditions, and a grand-average export carries only ' ...
             'each condition''s own error. A band is therefore omitted rather than replaced ' ...
             'with a similar-looking quantity that means something else.'] ...
            ReportDoc.template('waveform-difference.qmd') ...
            }]);
    end

    block = strjoin(lines, newline);
    bin1 = '';  bin2 = '';
    if ~isempty(binLabels);        bin1 = binLabels{1}; end
    if numel(binLabels) >= 2;      bin2 = binLabels{2}; end
    block = ReportSections.fillCommonTokens(block, windowLabel, '', bin1, bin2);

    quoted = cellfun(@(b) ['"' ReportSections.rLit(b) '"'], binLabels, 'UniformOutput', false);
    block = strrep(block, '__BINVECTOR_R__', strjoin(quoted, ', '));
    block = strrep(block, '__CHUNKLABEL__', ...
        ReportSections.chunkLabel('wave', windowLabel));
    block = strrep(block, '__DIFFCHUNKLABEL__', ...
        ReportSections.chunkLabel('wave-diff', windowLabel));
    block = strrep(block, '__GACSV__', ReportSections.rLit(grandAverageCsv));
end
