function lines = apaHelpers()
%APAHELPERS  The APA formatting helpers every Alakazam report defines:
%   apa_p, apa_num and apa_gt, as R source lines.
%
%   WHY THIS IS ONE COPY NOW. It used to be three, one per report
%   generator, and they had already drifted: apa_gt formatted decimal
%   columns to three places in the statistical and cluster reports and to
%   two in the data-quality report, undocumented, so the same table rounded
%   differently depending on which report you had opened. The explanatory
%   comment below survived in only one of the three. Nothing had gone wrong
%   yet that anyone had noticed, which is the point: a duplicated helper
%   does not announce the moment it stops being duplicated.
%
%   THREE DECIMALS is the settled figure -- it is what two of the three
%   copies used, and what the surviving comment already described as the
%   intent ("0 decimals, not 3"). The data-quality report's tables move
%   from two places to three.
%
%   Not shared here: apa_bf (Bayes factors) and violin_layers, which only
%   the statistical report uses, and which it still defines itself. A
%   helper used once belongs where it is used.
%
%   See also REPORTDOC.YAMLHEADER, REPORTDOC.PACKAGEBOOTSTRAP.
    lines = { ...
        '# ---- APA-style formatting helpers ----' ...
        '# apa_p/apa_num both drop the leading zero APA convention omits for any' ...
        '# statistic that cannot exceed 1 in magnitude (p, r, eta-squared, ...) --' ...
        '# and, since the regex only matches a value that STARTS with "0.", leave a' ...
        '# statistic that CAN exceed 1 (t, F, M, SD, ...) untouched, so one helper' ...
        '# serves both without the caller having to say which kind of number it is.' ...
        '# Vectorised (ifelse, not if): called on a single test statistic in most' ...
        '# sections, but on a whole column at once (e.g. sig_pw$p.adj, one row per' ...
        '# significant pair) when narrating pairwise comparisons -- a scalar if()' ...
        '# on a length > 1 vector is a hard error as of R >= 4.2/4.3.' ...
        'apa_p <- function(p) {' ...
        '  ifelse(is.na(p), "= NA",' ...
        '    ifelse(p < .001, "< .001",' ...
        '      paste("=", sub("^0\\.", ".", sprintf("%.3f", p)))))' ...
        '}' ...
        'apa_num <- function(x, digits = 2) {' ...
        '  ifelse(is.na(x), "NA",' ...
        '    sub("^(-?)0\\.", "\\1.", sprintf(paste0("%.", digits, "f"), x)))' ...
        '}' ...
        '# A three-line APA table (rule above the header, rule below it, rule at the' ...
        '# foot; no vertical rules) via gt, printed with as_raw_html() so it can be' ...
        '# emitted from inside a per-channel for loop in a results:"asis" chunk --' ...
        '# gt''s own auto-print only works for a table that is a chunk''s sole,' ...
        '# top-level, unassigned result, which a table built inside a loop never is.' ...
        '# Numeric columns that happen to be whole numbers everywhere (n, df, ...)' ...
        '# are formatted with 0 decimals, not 3 -- APA never shows a sample size or' ...
        '# degrees of freedom as e.g. "10.000".' ...
        'apa_gt <- function(df, title = NULL) {' ...
        '  is_whole <- function(x) is.numeric(x) && all(x == round(x), na.rm = TRUE)' ...
        '  int_cols <- names(df)[sapply(df, is_whole)]' ...
        '  dec_cols <- setdiff(names(df)[sapply(df, is.numeric)], int_cols)' ...
        '  tbl <- gt(df)' ...
        '  if (!is.null(title)) tbl <- tab_header(tbl, title = title)' ...
        '  if (length(dec_cols) > 0) tbl <- tbl %>% fmt_number(columns = all_of(dec_cols), decimals = 3)' ...
        '  if (length(int_cols) > 0) tbl <- tbl %>% fmt_number(columns = all_of(int_cols), decimals = 0)' ...
        '  tbl %>%' ...
        '    tab_options(' ...
        '      table.border.top.style = "solid", table.border.top.width = px(1.5), table.border.top.color = "black",' ...
        '      table.border.bottom.style = "solid", table.border.bottom.width = px(1.5), table.border.bottom.color = "black",' ...
        '      column_labels.border.bottom.style = "solid", column_labels.border.bottom.width = px(1), column_labels.border.bottom.color = "black",' ...
        '      table_body.hlines.style = "none", table.border.left.style = "none", table.border.right.style = "none",' ...
        '      column_labels.font.weight = "bold", table.font.size = px(13), heading.align = "left"' ...
        '    )' ...
        '}'};
end
