function lines = yamlHeader(title)
%YAMLHEADER  The Quarto front matter every Alakazam report shares.
%   LINES = ReportDoc.yamlHeader(TITLE) returns the '---' ... '---' block as
%   a cellstr, with TITLE as the document title and everything else fixed.
%
%   Self-contained HTML so a report can be emailed as one file, and a table
%   of contents because every one of these is long enough to need it.
%
%   THE LIGHT-MODE OVERRIDE IS NOT COSMETIC. Quarto's cosmo theme follows
%   the reader's OS dark-mode setting, but the plots baked into these
%   reports are ggplot output with a white canvas and black text. On a dark
%   background the figures stay white rectangles while the prose around
%   them inverts, and axis labels sit black-on-dark. Pinning the document
%   to light keeps the page and its figures in the same world.
%
%   WHY THIS IS SHARED. Three generators used to carry their own copy of
%   this header, identical except the title, and the same was true of the
%   package bootstrap and the APA helpers. That is how apa_gt came to round
%   to three decimals in two reports and two in the third -- see
%   ReportDoc.apaHelpers, which is where that was found and fixed.
%
%   See also REPORTDOC.PACKAGEBOOTSTRAP, REPORTDOC.APAHELPERS.
    lines = { ...
        '---' ...
        ['title: "' title '"'] ...
        'format:' ...
        '  html:' ...
        '    self-contained: true' ...
        '    toc: true' ...
        '    theme: cosmo' ...
        '    include-in-header:' ...
        '      text: |' ...
        '        <meta name="color-scheme" content="light">' ...
        '        <style>' ...
        '          :root { color-scheme: light !important; }' ...
        '          html, body { background-color: #ffffff !important; }' ...
        '          #TOC, .sidebar, .toc-actions { background-color: #ffffff !important; }' ...
        '        </style>' ...
        'execute:' ...
        '  echo: false' ...
        '  warning: false' ...
        '  message: false' ...
        '---'};
end
