function [datasets, shots] = manualShots(repo) %#ok<INUSD>
%MANUALSHOTS  What every picture in the user manual shows, and on which data.
%   [DATASETS, SHOTS] = manualShots(REPO) returns the datasets the manual's
%   pictures are made from and one entry per picture, for
%   captureManualImages.
%
%   A DATASET is a raw recording (copied into a scratch workspace) and a
%   chain of named STAGES built from it, each a transformation with its
%   options applied to a parent stage. Wherever a shipped template covers a
%   stage, the options are that template's (a struct with .template and
%   .node), so the pictures show the settings the templates use. The
%   recordings are the ones DATA.md lists: ERP CORE (Kappenman et al.,
%   2021) via Luck's textbook, the RIFT study (Dimigen et al., 2025),
%   Ehinger & Dimigen's (2019) face data, EYE-EEG's reading data and
%   FieldTrip's ERP tutorial recording.
%
%   A SHOT is one picture: a transformation's dialog, a result view, the
%   main window in some state, or a dialog the app itself opens. Its name is
%   the image file's name in manual/images.
%
%   NOT EVERY BUTTON CAN BE PHOTOGRAPHED SAFELY. ERP & Report and the other
%   exports open a system file picker first, which no timer can reach, and
%   Data Quality Report has no dialog at all: pressing it writes a report
%   into the workspace's Reports folder. The 'workspace' dataset is a real
%   one, so neither is on this list.
%
%   See also CAPTUREMANUALIMAGES.
    tpl = @(file, node) struct('template', file, 'node', node);
    % A template node with some of its options replaced (captureManualImages'
    % resolveParams applies OVERRIDE over the template's own).
    tplWith = @(file, node, override) struct('template', file, 'node', node, 'override', override);
    ch02 = 'library/templates/luck/ch02-N400-one-participant.alztemplate';
    ch08 = 'library/templates/luck/ch08-N2pc.alztemplate';
    ch09 = 'library/templates/luck/ch09-MMN-with-ICA.alztemplate';
    ch10 = 'library/templates/luck/ch10-LRP.alztemplate';
    rift = 'library/templates/dimigen-rift-simplified.alztemplate';
    face = 'library/templates/FaceSaccadesDeconvolution.alztemplate';
    reading = 'library/templates/ReadingDeconvolution.alztemplate';
    fterp = 'library/templates/fieldtrip/preprocessing-erp.alztemplate';
    init = struct('Param', 'Init');

    % ---- options the templates do not carry -------------------------------
    tfOpts = struct('MinFreq', 3, 'MaxFreq', 30, 'NumFreqs', 28, 'MinCycles', 3, ...
        'MaxCycles', 8, 'BaselineStart', -200, 'BaselineStop', 0);
    fourierOpts = struct('Output', 'PSD', 'FullSpectrum', false, 'Window', 'Hanning', ...
        'Window_Length', 10, 'Resolution', 'Max', 'ResVal', 1);
    welchOpts = struct('SegmentSeconds', 2, 'Overlap', 50, 'Window', 'Hanning');
    covOpts = struct('Channels', {{}}, 'Statistic', 'Correlation', 'Shrinkage', 'Ledoit-Wolf', ...
        'Start', 300, 'Stop', 500);
    xcorrOpts = struct('RefChannel', 'VEOG', 'Channels', {{}}, 'MaxLagMs', 100, ...
        'MinPairs', 20, 'Start', 0, 'Stop', 0);
    % Three detectors, for a Rejection breakdown with something to show: the
    % manual's Table/Figure on it quotes these numbers (93 of 231 epochs).
    threeDetectors = struct('Method', {{'Absolute threshold', 'Step function', ...
        'Moving-window peak-to-peak'}}, 'Minimum', -100, 'Maximum', 100, ...
        'Threshold', 100, 'Window', 200, 'Step', 50, 'TestStart', 0, 'TestStop', 0, ...
        'Channels', 'All channels', 'Scope', 'Whole epoch');
    detrendOpts = struct('Channels', {{}}, 'Order', '1 - linear', 'Method', 'Robust (Huber)', ...
        'FitStart', -200, 'FitStop', 0);
    rectifyOpts = struct('Channels', {{}}, 'Mode', 'Full wave (|x|)');
    % The automated cleaning steps with their defaults, except PREP's line
    % frequency: ERP CORE was recorded in California, on 60 Hz mains.
    prepOpts = struct('LineFrequency', '60', 'DeviationThreshold', 5, ...
        'HighFrequencyThreshold', 5, 'CorrelationThreshold', 0.4, 'Ransac', true, ...
        'IgnoreBoundaries', false);
    asrOpts = struct('FlatlineSeconds', 5, 'ChannelCorrelation', 0.8, 'LineNoiseSD', 4, ...
        'BurstCriterion', 20, 'BurstHandling', 'Repaired', 'RejectWindows', false, ...
        'WindowCriterion', 0.25);
    autorejectOpts = struct('Folds', 10, 'Interpolate', '');
    % The time-frequency picture needs longer epochs than the ERP's -200 to
    % 800 ms: half a 3-cycle wavelet at 3 Hz is 480 ms, and TimeFrequency
    % leaves blank every sample that close to an end of the epoch, so with
    % the ERP's epochs no frequency below 16.5 Hz would have a baseline. The
    % same bins epoched from -1000 to 1500 ms give every one a -200 to 0 ms
    % baseline, and show the blank edges the manual describes.
    longEpoch = struct('epoch', struct('lo', -1000, 'hi', 1500, 'unit', 'ms'));
    resampleOpts = struct('NewRate', 128);
    % The Filter dialog with every part of it at work, at the N400
    % recordings' 200 Hz: an automatic 0.1 Hz high-pass, a 30 Hz low-pass
    % whose order is set by hand, and a line-noise band-stop from the Filter
    % Designer. The designed filter is the struct designedFilterFromObject
    % makes, written out here because this list is read before the app has
    % put the Filter folder on the path.
    lineNoiseStop = designfilt('bandstopiir', 'FilterOrder', 4, 'HalfPowerFrequency1', 48, ...
        'HalfPowerFrequency2', 52, 'SampleRate', 200);
    filterOpts = struct('perChannel', false, ...
        'highpass', struct('enabled', true, 'freq', 0.1, 'db', 40, 'auto', true, 'transition', [], 'order', []), ...
        'lowpass', struct('enabled', true, 'freq', 30, 'db', 60, 'auto', false, 'transition', [], 'order', 160), ...
        'notch', struct('enabled', false, 'freq', 50, 'db', 40, 'auto', true, 'transition', [], 'order', [], 'width', 2), ...
        'designed', struct('enabled', true, 'kind', 'iir', 'b', [], 'sos', lineNoiseStop.Coefficients, ...
            'srate', 200, 'order', 4, 'linearPhase', false, 'response', 'bandstop', ...
            'source', 'digitalFilter "lineNoiseStop"'));
    rerefOpts = struct('mode', 'Specific channels', 'refChannels', {{'P9', 'P10'}}, ...
        'exclude', {{}}, 'keepref', true, 'implicitRef', '');
    collapseOpts = struct('leftBins', {{'Left target'}}, 'rightBins', {{'Right target'}}, ...
        'pairing', 'auto', 'contraLabel', 'Contra', 'ipsiLabel', 'Ipsi');
    ressOpts = struct('rows', struct('label', {'RESS60Hz', 'RESS64Hz'}, 'freq', {60, 64}, ...
        'bins', {{'RIFT 60Hz'}, {'RIFT 64Hz'}}), 'includeMastoids', false, ...
        'timeStart', 883, 'timeStop', 8594, 'peakFWHM', 0.5, 'neighbourDistance', 1, ...
        'neighbourFWHM', 1, 'shrinkage', 0.01);
    ressSpecOpts = struct('rows', struct('label', {'60Hz', '64Hz'}, 'freq', {'60', '64'}, ...
        'channels', {'RESS60Hz Oz', 'RESS64Hz Oz'}), 'fundamentals', '', ...
        'refChannel', 'Photodiode', 'method', 'Hann', 'tapers', 3, 'snrNeighbours', 10, ...
        'snrGuard', 1, 'coherenceMethod', 'frames', ...
        'crossf', struct('enabled', false, 'Method', 'frames', 'WinSize', 510, ...
        'TimeStart', [], 'TimeStop', []));
    ressTime = struct('channels', struct('mode', '(off)', 'labels', {{}}), ...
        'time', struct('mode', 'Keep', 'range', [883 8594]), ...
        'points', struct('mode', '(off)', 'range', [1 1]), ...
        'trials', struct('mode', '(off)', 'indices', []));
    sourceOpts = struct('Method', 'mne', 'Orientation', 'normal', 'SourceSpace', 5124, ...
        'TimeWindow', [-200 795], 'ResampleHz', 200, 'RegParam', 0.05, ...
        'NoiseCovariance', 'baseline', 'SNR', 3, ...
        'WindowStart', -200, 'WindowStop', 795);
    regionOpts = struct('Atlas', 'AAL', 'Value', 'Signed mean', 'Method', 'dSPM', ...
        'SourceSpace', '5124', 'NoiseCovariance', 'auto', 'SNR', 3, 'RegParam', 0.05);
    % The dialog shows the default optimiser, FieldTrip's choice; the fit
    % behind the result picture uses fminsearch, which runs on every MATLAB,
    % where FieldTrip's choice (fminunc) may not (see DipoleFit). The example
    % is an early sensory response, the visual response to the faces of the
    % Figure 11 recording around its first peak (102 ms), where one focal
    % generator in each hemisphere is a fair assumption.
    dipoleDialogOpts = struct('Bins', {{'Stimulus'}}, 'WindowStart', 82, 'WindowStop', 122, ...
        'Model', 'Mirrored pair', 'GridResolution', 10);
    dipoleOpts = dipoleDialogOpts;
    dipoleOpts.Optimiser = 'fminsearch';
    beamformerOpts = struct('Method', 'LCMV (time domain)', 'Frequency', 10, 'Smoothing', 4, ...
        'ActiveStart', 300, 'ActiveStop', 500, 'BaselineStart', -200, 'BaselineStop', 0, ...
        'SourceModel', 'Cortical sheet', 'SourceSpace', '5124', 'GridResolution', 10, 'Lambda', 5);
    beamformerGridOpts = beamformerOpts;
    beamformerGridOpts.SourceModel = 'Volume grid';

    % ---- datasets ----------------------------------------------------------
    datasets = struct();
    datasets.n400 = dataset('n400', 'Data/Luck/ch2/6_N400_preprocessed.set', { ...
        stg('filtered', 'raw', 'Filter', tpl(ch02, 1)), ...
        stg('epoched', 'filtered', 'DefineBins', tpl(ch02, 2)), ...
        stg('baseline', 'epoched', 'Baseline', tpl(ch02, 3)), ...
        stg('clean', 'baseline', 'ArtefactDetect', tpl(ch02, 4)), ...
        stg('clean3', 'baseline', 'ArtefactDetect', threeDetectors), ...
        stg('average', 'clean', 'Average', tpl(ch02, 5)), ...
        stg('scalp', 'average', 'ScalpDistribution', init), ...
        stg('brain', 'average', 'Brain3D', init), ...
        stg('epochedLong', 'filtered', 'DefineBins', tplWith(ch02, 2, longEpoch)), ...
        stg('baselineLong', 'epochedLong', 'Baseline', tpl(ch02, 3)), ...
        stg('cleanLong', 'baselineLong', 'ArtefactDetect', tpl(ch02, 4)), ...
        stg('tf', 'cleanLong', 'TimeFrequency', tfOpts), ...
        stg('autoreject', 'baseline', 'AutoReject', autorejectOpts), ...
        stg('fourier', 'clean', 'Fourier', fourierOpts), ...
        stg('spectrum', 'fourier', 'Average', init), ...
        stg('welch', 'filtered', 'Welch', welchOpts), ...
        stg('covariance', 'clean', 'Covariance', covOpts), ...
        stg('xcorr', 'clean', 'CrossCorrelation', xcorrOpts), ...
        stg('source', 'average', 'SourceEstimate', sourceOpts), ...
        stg('sourceBrain', 'source', 'Brain3D', init), ...
        stg('regions', 'average', 'SourceRegions', regionOpts), ...
        stg('beamformer', 'clean', 'Beamformer', beamformerOpts), ...
        stg('beamformerGrid', 'clean', 'Beamformer', beamformerGridOpts)});
    datasets.n400unref = dataset('n400unref', 'Data/Luck/ch5/6_N400_unreferenced.set', {});
    datasets.lrp = dataset('lrp', 'Data/Luck/ch10/1_LRP_continuous.set', { ...
        stg('bins', 'raw', 'DefineBins', tpl(ch10, 1)), ...
        stg('derived', 'bins', 'DeriveChannels', tpl(ch10, 2)), ...
        stg('baseline', 'derived', 'Baseline', tpl(ch10, 3)), ...
        stg('clean', 'baseline', 'ArtefactDetect', tpl(ch10, 4)), ...
        stg('average', 'clean', 'Average', tpl(ch10, 5))});
    datasets.n2pc = dataset('n2pc', 'Data/Luck/ch8/15_N2pc_ICA_preprocessed.set', { ...
        stg('bins', 'raw', 'DefineBins', tpl(ch08, 1)), ...
        stg('derived', 'bins', 'DeriveChannels', tpl(ch08, 2)), ...
        stg('baseline', 'derived', 'Baseline', tpl(ch08, 3)), ...
        stg('clean', 'baseline', 'ArtefactDetect', tpl(ch08, 4)), ...
        stg('average', 'clean', 'Average', tpl(ch08, 5)), ...
        stg('collapsed', 'average', 'CollapseHemispheres', collapseOpts)});
    datasets.mmn = dataset('mmn', 'Data/Luck/ch9/1_MMN_preprocessed.set', { ...
        stg('ica', 'raw', 'AutoEyeICA', tpl(ch09, 1))});
    datasets.rift = dataset('rift', 'Data/RIFT/eeg_raw_set/ThriftyRIFT_1.set', { ...
        stg('selected', 'raw', 'SelectData', tpl(rift, 1)), ...
        stg('reref', 'selected', 'ReRef', tpl(rift, 2)), ...
        stg('filtered', 'reref', 'Filter', tpl(rift, 3)), ...
        stg('bins', 'filtered', 'DefineBins', tpl(rift, 4)), ...
        stg('cohmap', 'bins', 'CoherenceMap', tpl(rift, 5)), ...
        stg('cohtopo', 'bins', 'CoherenceTopography', tpl(rift, 6)), ...
        stg('steady', 'bins', 'SelectData', tpl(rift, 7)), ...
        stg('spectral', 'steady', 'SpectralMeasure', tpl(rift, 8)), ...
        stg('ress', 'bins', 'RESS', ressOpts), ...
        stg('ressSteady', 'ress', 'SelectData', ressTime), ...
        stg('ressSpectral', 'ressSteady', 'SpectralMeasure', ressSpecOpts)});
    datasets.face = dataset('face', 'Data/opendata/face_saccades_opendata_fig10.set', { ...
        stg('waveforms', 'raw', 'Deconvolve', tpl(face, 1)), ...
        stg('trials', 'raw', 'Deconvolve', tpl(face, 2)), ...
        stg('epochs', 'raw', 'DefineBins', tpl(face, 3)), ...
        stg('baseline', 'epochs', 'Baseline', tpl(face, 4)), ...
        stg('clean', 'baseline', 'ArtefactDetect', tpl(face, 5)), ...
        stg('average', 'clean', 'Average', tpl(face, 6)), ...
        stg('dipole', 'average', 'DipoleFit', dipoleOpts), ...
        stg('terms', 'raw', 'Deconvolve', tpl(face, 7))});
    datasets.reading = dataset('reading', {'Data/reading/reading_eeg.set', ...
        'Data/reading/reading_eeg.fdt', 'Data/reading/reading_eeg.asc'}, { ...
        stg('joined', 'raw', 'EyeTracking', tpl(reading, 1))});
    % FieldTrip's ERP tutorial recording, with its template applied for the
    % main window's picture (chapter 20).
    erpFiles = strcat('Data/FieldTrip/preprocessing_erp/s04', {'.vhdr', '.vmrk', '.eeg'});
    datasets.fterp = dataset('fterp', erpFiles, { ...
        stg('reref', 'raw', 'ReRef', tpl(fterp, 1))});
    datasets.fterp.template = fterp;
    datasets.ui = dataset('ui', 'Data/Luck/ch2/6_N400_preprocessed.set', {});
    datasets.ui.template = ch02;          % a real branch in the tree
    datasets.group = struct('key', 'group', 'kind', 'workspace', 'workspace', 'Chapter3.wksp', ...
        'files', {{}}, 'stages', struct('name', {}, 'parent', {}, 'transform', {}, 'params', {}), ...
        'template', '');

    % ---- pictures ----------------------------------------------------------
    list = { ...
        ... % The interface (a scratch workspace with the ch02 template applied).
        shot('ui-main', 'ui', 'window', 'select', 'Average', 'channel', 'CPz', 'crop', 'window'), ...
        shot('ui-ribbon-home', 'ui', 'window', 'ribbonTab', 'home', 'crop', 'ribbon'), ...
        shot('ui-ribbon-tools', 'ui', 'window', 'ribbonTab', 'tools', 'crop', 'ribbon'), ...
        shot('ui-ribbon-grandaverage', 'ui', 'window', 'ribbonTab', 'grandAverage', 'crop', 'ribbon'), ...
        shot('ui-ribbon-export', 'ui', 'window', 'ribbonTab', 'measurements', 'crop', 'ribbon'), ...
        shot('ui-settings-graphics', 'ui', 'appdialog', 'action', 'settings', 'dialogTab', 'Graphics'), ...
        shot('ui-settings-bands', 'ui', 'appdialog', 'action', 'settings', 'dialogTab', 'Frequency bands'), ...
        shot('ui-settings-processing', 'ui', 'appdialog', 'action', 'settings', 'dialogTab', 'Processing'), ...
        shot('ui-workspace-editor', 'ui', 'appdialog', 'action', 'editWorkspace'), ...
        shot('ui-continuous', 'ui', 'window', 'select', 'Filter', 'crop', 'plot'), ...
        ... % Grand averages, statistics and reports (the Chapter 3 workspace).
        shot('ga-define', 'group', 'appdialog', 'action', 'defineGrandAverage', 'settle', 6), ...
        shot('ga-view', 'group', 'window', 'select', 'All subjects', 'tree', 'GrandAveragesTree', 'channel', 'Pz', 'crop', 'plot'), ...
        shot('ga-cluster', 'group', 'appdialog', 'action', 'clusterStats', 'settle', 6), ...
        shot('ga-design', 'group', 'appdialog', 'action', 'showDesign', 'settle', 6), ...
        shot('ga-grouping', 'group', 'appdialog', 'action', 'editSubjects', 'settle', 6), ...
        shot('ga-report', 'group', 'window', 'select', 'Data Quality*', 'tree', 'ReportsTree', 'crop', 'plot'), ...
        ... % Worked examples: FieldTrip's ERP tutorial (chapter 20).
        shot('fterp-main', 'fterp', 'window', 'select', 'Average', 'channel', '28', 'crop', 'window'), ...
        shot('fterp-derive-dialog', 'fterp', 'dialog', 'transform', 'DeriveChannels', 'input', 'reref', 'seed', tpl(fterp, 2)), ...
        ... % Preprocessing.
        shot('filter-dialog', 'n400', 'dialog', 'transform', 'Filter', 'input', 'raw', 'seed', filterOpts), ...
        shot('reref-dialog', 'n400unref', 'dialog', 'transform', 'ReRef', 'input', 'raw', 'seed', rerefOpts), ...
        shot('resample-dialog', 'n400', 'dialog', 'transform', 'Resample', 'input', 'raw', 'seed', resampleOpts), ...
        shot('selectdata-dialog', 'n400', 'dialog', 'transform', 'SelectData', 'input', 'raw'), ...
        shot('interpolate-dialog', 'n400', 'dialog', 'transform', 'Interpolate', 'input', 'raw'), ...
        shot('channeleditor-dialog', 'n400', 'dialog', 'transform', 'ChannelEditor', 'input', 'raw', 'settle', 6), ...
        shot('eventeditor-dialog', 'n400', 'dialog', 'transform', 'EventEditor', 'input', 'raw', 'settle', 6), ...
        shot('derivechannels-dialog', 'lrp', 'dialog', 'transform', 'DeriveChannels', 'input', 'bins', 'seed', tpl(ch10, 2)), ...
        shot('derivechannels-result', 'lrp', 'view', 'input', 'average', 'channel', 'C34'), ...
        shot('dcdetrend-dialog', 'n400', 'dialog', 'transform', 'DCDetrend', 'input', 'epoched', 'seed', detrendOpts), ...
        shot('rectify-dialog', 'n400', 'dialog', 'transform', 'Rectify', 'input', 'raw', 'seed', rectifyOpts), ...
        shot('baseline-dialog', 'n400', 'dialog', 'transform', 'Baseline', 'input', 'epoched', 'seed', tpl(ch02, 3)), ...
        shot('eyetracking-dialog', 'reading', 'dialog', 'transform', 'EyeTracking', 'input', 'raw', 'seed', tpl(reading, 1)), ...
        shot('eyetracking-result', 'reading', 'view', 'input', 'joined'), ...
        ... % Artefacts.
        shot('artefactdetect-dialog', 'n400', 'dialog', 'transform', 'ArtefactDetect', 'input', 'baseline', 'seed', tpl(ch02, 4)), ...
        shot('artefactdetect-result', 'n400', 'view', 'input', 'clean', 'channel', 'FP1'), ...
        shot('rejectionbreakdown-dialog', 'n400', 'call', 'input', 'clean3', 'action', ...
            @(EEG, app) RejectionBreakdownDialog(EEG.etc.alz.artefactDetectors, ...
            'ArtefactDetect', app.MainFigure)), ...
        shot('manualreject-dialog', 'n400', 'dialog', 'transform', 'ManualReject', 'input', 'baseline', 'settle', 8), ...
        shot('autoreject-dialog', 'n400', 'dialog', 'transform', 'AutoReject', 'input', 'baseline', 'seed', autorejectOpts), ...
        shot('autoreject-result', 'n400', 'view', 'input', 'autoreject', 'channel', 'FP1'), ...
        shot('prep-dialog', 'n400unref', 'dialog', 'transform', 'PREP', 'input', 'raw', 'seed', prepOpts), ...
        shot('asr-dialog', 'n400', 'dialog', 'transform', 'ASR', 'input', 'filtered', 'seed', asrOpts), ...
        shot('autoeyeica-dialog', 'mmn', 'dialog', 'transform', 'AutoEyeICA', 'input', 'raw', 'seed', tpl(ch09, 1)), ...
        shot('autogedai-dialog', 'mmn', 'dialog', 'transform', 'AutoGEDAI', 'input', 'raw', 'seed', tpl('library/templates/N400.alztemplate', 1)), ...
        shot('removecomponents-dialog', 'mmn', 'dialog', 'transform', 'RemoveComponents', 'input', 'ica', 'settle', 10), ...
        ... % Epoching and averaging.
        shot('definebins-dialog', 'n400', 'dialog', 'transform', 'DefineBins', 'input', 'filtered', 'seed', tpl(ch02, 2)), ...
        shot('definebins-result', 'n400', 'view', 'input', 'baseline', 'channel', 'CPz'), ...
        shot('average-result', 'n400', 'view', 'input', 'average', 'channel', 'CPz'), ...
        shot('collapse-dialog', 'n2pc', 'dialog', 'transform', 'CollapseHemispheres', 'input', 'average', 'seed', collapseOpts), ...
        shot('collapse-result', 'n2pc', 'view', 'input', 'collapsed', 'channel', 'PO7', 'only', {'Contra', 'Ipsi'}), ...
        shot('deconvolve-dialog', 'face', 'dialog', 'transform', 'Deconvolve', 'input', 'raw', 'seed', tpl(face, 1), 'settle', 25), ...
        shot('deconvolve-waveforms', 'face', 'view', 'input', 'waveforms', 'overlay', 'average', 'channel', 'Oz', 'only', {'Stimulus'}), ...
        shot('deconvolve-stimulus-plain', 'face', 'view', 'input', 'baseline', 'channel', 'Oz', 'bin', 'Stimulus', 'sort', 'Next saccade'), ...
        shot('deconvolve-stimulus-corrected', 'face', 'view', 'input', 'trials', 'channel', 'Oz', 'bin', 'Stimulus', 'sort', 'Next saccade'), ...
        shot('deconvolve-button-plain', 'face', 'view', 'input', 'baseline', 'channel', 'Oz', 'bin', 'Button', 'sort', 'Previous stimonset'), ...
        shot('deconvolve-button-corrected', 'face', 'view', 'input', 'trials', 'channel', 'Oz', 'bin', 'Button', 'sort', 'Previous stimonset'), ...
        shot('deconvolve-terms', 'face', 'view', 'input', 'terms', 'channel', 'Oz', 'only', {'Saccade'}), ...
        ... % Frequency and component analysis.
        shot('fourier-dialog', 'n400', 'dialog', 'transform', 'Fourier', 'input', 'clean', 'seed', fourierOpts), ...
        shot('fourier-result', 'n400', 'view', 'input', 'spectrum', 'channel', 'Oz'), ...
        shot('welch-dialog', 'n400', 'dialog', 'transform', 'Welch', 'input', 'filtered', 'seed', welchOpts), ...
        shot('welch-result', 'n400', 'view', 'input', 'welch', 'channel', 'Oz'), ...
        shot('timefrequency-dialog', 'n400', 'dialog', 'transform', 'TimeFrequency', 'input', 'clean', 'seed', tfOpts), ...
        shot('timefrequency-result', 'n400', 'view', 'input', 'tf', 'channel', 'Oz'), ...
        shot('covariance-dialog', 'n400', 'dialog', 'transform', 'Covariance', 'input', 'clean', 'seed', covOpts), ...
        shot('covariance-result', 'n400', 'view', 'input', 'covariance'), ...
        shot('crosscorrelation-dialog', 'n400', 'dialog', 'transform', 'CrossCorrelation', 'input', 'clean', 'seed', xcorrOpts), ...
        shot('crosscorrelation-result', 'n400', 'view', 'input', 'xcorr'), ...
        shot('measure-dialog', 'n400', 'dialog', 'transform', 'Measure', 'input', 'average', 'seed', tpl(ch02, 6), 'settle', 6), ...
        shot('sourceestimate-dialog', 'n400', 'dialog', 'transform', 'SourceEstimate', 'input', 'average', 'seed', sourceOpts), ...
        shot('sourceestimate-result', 'n400', 'view', 'input', 'sourceBrain', 'bin', 'N400', 'time', 400, 'projection', 'dSPM'), ...
        shot('sourceregions-dialog', 'n400', 'dialog', 'transform', 'SourceRegions', 'input', 'average', 'seed', regionOpts), ...
        shot('sourceregions-result', 'n400', 'view', 'input', 'regions', 'channel', 'Temporal_Mid_L'), ...
        shot('dipolefit-dialog', 'face', 'dialog', 'transform', 'DipoleFit', 'input', 'average', 'seed', dipoleDialogOpts), ...
        shot('dipolefit-result', 'face', 'view', 'input', 'dipole'), ...
        shot('beamformer-dialog', 'n400', 'dialog', 'transform', 'Beamformer', 'input', 'clean', 'seed', beamformerOpts), ...
        shot('beamformer-result', 'n400', 'view', 'input', 'beamformer'), ...
        shot('beamformer-grid', 'n400', 'view', 'input', 'beamformerGrid'), ...
        shot('coherencemap-dialog', 'rift', 'dialog', 'transform', 'CoherenceMap', 'input', 'bins', 'seed', tpl(rift, 5)), ...
        shot('coherencemap-result', 'rift', 'view', 'input', 'cohmap', 'channel', 'Oz'), ...
        shot('coherencetopography-dialog', 'rift', 'dialog', 'transform', 'CoherenceTopography', 'input', 'bins', 'seed', tpl(rift, 6)), ...
        shot('coherencetopography-result', 'rift', 'view', 'input', 'cohtopo'), ...
        shot('spectralmeasure-dialog', 'rift', 'dialog', 'transform', 'SpectralMeasure', 'input', 'steady', 'seed', tpl(rift, 8), 'settle', 6), ...
        shot('spectralmeasure-result', 'rift', 'view', 'input', 'spectral', 'channel', 'Oz', 'bin', 'RIFT 60Hz', 'xlim', [0 100]), ...
        shot('ress-dialog', 'rift', 'dialog', 'transform', 'RESS', 'input', 'bins', 'seed', ressOpts, 'settle', 6), ...
        shot('ress-result', 'rift', 'view', 'input', 'ressSpectral', 'channel', 'RESS60Hz', 'bin', 'RIFT 60Hz', 'xlim', [0 100]), ...
        ... % Plots.
        shot('scalp-result', 'n400', 'view', 'input', 'scalp', 'bin', 'N400', 'time', 400), ...
        shot('brain3d-result', 'n400', 'view', 'input', 'brain', 'bin', 'N400', 'time', 400)};
    shots = [list{:}];
end

% ======================================================================= %
function ds = dataset(key, files, stages)
    ds = struct('key', key, 'kind', 'recording', 'workspace', '', 'files', {cellstr(files)}, ...
        'stages', [stages{:}], 'template', '');
    if isempty(stages)
        ds.stages = struct('name', {}, 'parent', {}, 'transform', {}, 'params', {});
    end
end

function s = stg(name, parent, transform, params)
    s = struct('name', name, 'parent', parent, 'transform', transform, 'params', params);
end

function s = shot(name, dataset, kind, varargin)
%SHOT  One picture. Kinds: 'dialog' (a transformation's own dialog on the
%   stage INPUT, its fields seeded with SEED), 'view' (the stage INPUT's
%   result view), 'window' (the main window, after selecting SELECT in TREE
%   and showing RIBBONTAB), 'appdialog' (the dialog behind a ribbon button,
%   ACTION), 'method' (the window an app method opens, ACTION) and 'call'
%   (a dialog opened on the stage INPUT by ACTION, a function of EEG and
%   the app). There is no kind for a uialert, which exportapp cannot
%   capture. A view is
%   put in its state by CHANNEL, BIN, SORT (an ERP image's sort key), ONLY
%   (the series an ERP plot shows), TIME (a scalp map's instant),
%   PROJECTION (Brain3D's), OVERLAY (a stage drawn in the same plot) and
%   XLIM (a spectrum's frequency range).
%   CROP is 'plot', 'ribbon' or 'window'; SETTLE the seconds a dialog is
%   given to draw; DIALOGTAB the tab a tabbed dialog is shown on.
    s = struct('name', name, 'dataset', dataset, 'kind', kind, 'input', '', ...
        'transform', '', 'seed', [], 'settle', 4, 'dialogTab', '', 'channel', '', ...
        'bin', '', 'sort', '', 'only', {{}}, 'time', [], 'projection', '', 'overlay', '', ...
        'select', '', 'tree', 'Tree', 'ribbonTab', '', 'crop', 'plot', 'action', '', ...
        'xlim', []);
    for k = 1:2:numel(varargin)
        s.(varargin{k}) = varargin{k + 1};
    end
end
