function qmdText = generateClusterStatsReport(summary, statCsvName, waveformCsvName, outlineCsvName, nullCsvName)
%GENERATECLUSTERSTATSREPORT  A Quarto (.qmd) report for one ClusterStats()
%   result: rendering it (self-contained HTML) produces narrative prose
%   explaining the test that ran, a summary table of every cluster found,
%   an overview heatmap of the test statistic across the whole channel x
%   time grid, and, for the strongest few clusters, a topographic plot
%   (where) and a time-course plot (when) each.
%
%   Unlike generateQuartoReport.m (whose R code runs the actual
%   statistical tests, since rstatix/lme4/etc. can do that from a flat
%   CSV), the cluster-permutation test itself has ALREADY run in MATLAB
%   by the time this is called -- FieldTrip is a MATLAB toolbox, R has no
%   equivalent -- so this report's own R code only narrates and PLOTS a
%   precomputed result; SUMMARY (see ClusterStats.m) supplies every number
%   it narrates, and STATCSVNAME/WAVEFORMCSVNAME/OUTLINECSVNAME (bare
%   filenames, resolved relative to the .qmd's own folder -- see
%   exportClusterStatsCSVs.m) supply what it plots.
%
%   Requires the R packages tidyverse and gt (auto-installed by the
%   report's own setup chunk on first render, same as
%   generateQuartoReport.m) plus a working Quarto installation to actually
%   render the .qmd this function returns into HTML.
%
%   See also EXPORTCLUSTERSTATSCSVS, CLUSTERSTATS, ALAKAZAM.ONCLUSTERSTATS.
    lines = [ ...
        preambleLines(summary, statCsvName, waveformCsvName, outlineCsvName, nullCsvName), ...
        introLines(summary), ...
        summaryTableLines(), ...
        heatmapLines(), ...
        nullDistributionLines(), ...
        clusterDetailLines(summary)];
    qmdText = strjoin(lines, newline);
end

% ======================================================================= %
%  Preamble
% ======================================================================= %
function lines = preambleLines(summary, statCsvName, waveformCsvName, outlineCsvName, nullCsvName)
    lines = ReportDoc.lines([ReportDoc.yamlHeader('Alakazam Cluster Statistics Report'), { ...
        ReportDoc.template('cs-setup.Rpart') ...
        }, ReportDoc.packageBootstrap({'tidyverse', 'gt'}), { ...
        '' ...
        sprintf('stat_df     <- read_csv("%s", show_col_types = FALSE)', rLit(statCsvName)) ...
        sprintf('waveform_df <- read_csv("%s", show_col_types = FALSE)', rLit(waveformCsvName)) ...
        sprintf('outline_df  <- read_csv("%s", show_col_types = FALSE)', rLit(outlineCsvName)) ...
        sprintf('null_file   <- "%s"', rLit(nullCsvName)) ...
        'null_df     <- if (file.exists(null_file)) read_csv(null_file, show_col_types = FALSE) else NULL' ...
        '' ...
        }, ReportDoc.apaHelpers(), { ...
        '```' ...
        ''}]);
end

% ======================================================================= %
%  Intro narrative
% ======================================================================= %
function lines = introLines(summary)
    nSig = sum([summary.clusters.significant]);
    lines = { ...
        '## Cluster Statistics' ...
        '' ...
        sprintf('%s', mdLit(contrastSentence(summary.contrast))) ...
        '' ...
        sprintf('Tested across %d subject(s), %s permutation(s), %s.', ...
            summary.nSubjects, permutationLabel(summary.opts.numrandomization), ...
            correctionSentence(summary.opts)) ...
        '' ...
        sprintf(['%d cluster(s) were found (positive and negative together); %d were significant ' ...
            'at %s.'], numel(summary.clusters), nSig, alphaClause(summary.opts.alpha)) ...
        '' ...
        ['This is a whole-scalp, whole-epoch test: unlike a pre-chosen channel/window ' ...
         'analysis, it does not assume in advance where or when an effect should appear. ' ...
         'A **cluster** is a contiguous group of (channel, time) points that all crossed the ' ...
         'cluster-forming threshold in the same direction; its own p-value comes from comparing ' ...
         'its summed test statistic against a null distribution built by repeatedly shuffling ' ...
         'condition/group labels and re-running the same clustering procedure, so it already ' ...
         'accounts for having tested every channel and time point at once, rather than needing a ' ...
         'separate per-comparison correction.'] ...
        '' ...
        ['**What a significant cluster licenses you to say.** That the conditions differ ' ...
         'somewhere in the space that was tested, at the *p*-value reported for that cluster, ' ...
         'already corrected for having looked everywhere at once. That the difference ran in ' ...
         'the cluster''s own direction, since its sign is the sign of the statistic that built ' ...
         'it. And, as plain description of this dataset rather than as inference, which ' ...
         'channels and times it covered.'] ...
        '' ...
        ['**What buys back a claim about where or when** is restricting the test in advance. ' ...
         'A test run over one window and one set of channels has that window and those ' ...
         'channels as its hypothesis, so a significant result there *is* the statement that an ' ...
         'effect exists in them. Localisation comes from choosing the space before looking, ' ...
         'not from reading the boundaries of a cluster afterwards; the two routes answer ' ...
         'different questions and this report answers the second.'] ...
        '' ...
        ['A cluster that is **not** significant is not evidence that the conditions do not ' ...
         'differ, and no individual (channel, time) point inside a significant cluster is ' ...
         'itself protected: the correction is for the test as a whole.'] ...
        ''};
end

function s = contrastSentence(contrast)
    switch contrast.mode
        case 'vsZero'
            s = sprintf('Bin "%s" was tested against zero, within subjects.', contrast.bin);
        case 'paired'
            s = sprintf('Bin "%s" was tested against bin "%s", within subjects (paired).', ...
                contrast.binA, contrast.binB);
        case 'independent'
            s = sprintf('Bin "%s" was tested between two groups (independent samples).', contrast.bin);
    end
end

function s = correctionSentence(opts)
%CORRECTIONSENTENCE  How the test was corrected, naming only the thresholds
%   that actually applied to it.
%
%   TFCE HAS NO CLUSTER-FORMING THRESHOLD. Not choosing one is the whole
%   reason to use it (see ClusterStats' own options: clusteralpha is ignored
%   for 'tfce'), so printing the unused value beside it described a test that
%   was never run, and invited a reader to report a threshold that had no
%   effect on the result.
%
%   THE BACKSLASH BEFORE alpha IS DOUBLED HERE AND MUST NOT BE ANYWHERE ELSE.
%   These are sprintf FORMAT strings, where \\ emits one backslash (and a lone
%   \a would emit a BEL character, not the letters). The bug this replaces had
%   the same '$\\alpha$' as a sprintf ARGUMENT instead, substituted through a
%   %s, where nothing unescapes anything: both backslashes reached the Quarto
%   and LaTeX printed \alpha as text rather than the letter.
    if strcmpi(opts.correctm, 'tfce')
        s = sprintf(['TFCE correction (no cluster-forming threshold is chosen, which is what ' ...
            'TFCE is for; significance at $\\alpha$ = %s)'], numToStr(opts.alpha));
    else
        s = sprintf('cluster correction (cluster-forming *p* < %s, cluster-level $\\alpha$ = %s)', ...
            numToStr(opts.clusteralpha), numToStr(opts.alpha));
    end
end

function s = alphaClause(alpha)
    s = sprintf('*p* < %s', numToStr(alpha));
end

function s = numToStr(x)
    s = regexprep(sprintf('%.4g', x), '^0\.', '.');
end

function s = permutationLabel(numrandomization)
%PERMUTATIONLABEL  NUMRANDOMIZATION for narration -- a plain count, or
%   "all (exhaustive)" when ClusterStats.resolveNumRandomization upgraded
%   it to FieldTrip's own 'all' (an exhaustive 2^N sign-flip enumeration,
%   not a number of randomizations to pass through %d, which would
%   otherwise print each character of "all" as its own code point).
    if ischar(numrandomization) || isstring(numrandomization)
        s = 'all (exhaustive)';
    else
        s = sprintf('%d', numrandomization);
    end
end

% ======================================================================= %
%  Summary table
% ======================================================================= %
function lines = summaryTableLines()
    lines = ReportDoc.template('cs-cluster-summary-table.qmd');
end

% ======================================================================= %
%  Overview heatmap
% ======================================================================= %
function lines = heatmapLines()
    lines = ReportDoc.lines({ ...
        '## Overview: Test Statistic Across Every Channel and Time Point' ...
        '' ...
        ['The full grid the cluster test ran over. Tile colour is the raw test statistic ' ...
         '(before clustering); a black outline marks a point belonging to a cluster reported above.'] ...
        ReportDoc.template('cs-overview-heatmap.qmd') ...
        });
end

% ======================================================================= %
%  Per-cluster detail (strongest few, already p-sorted -- see this file's
%  own header on why not every spurious tiny cluster gets a full section)
% ======================================================================= %
function lines = clusterDetailLines(summary)
%CLUSTERDETAILLINES  The strongest clusters, one section each.
%
%   THE HEADING USED TO SAY "Where and When", which is the one reading this
%   analysis cannot support, directly above a sentence listing channels and a
%   time range. The report's own caveat said so, but it was emitted further
%   down beside the null distribution, so a reader met the claim first and the
%   correction later. The caveat now opens this section instead: the sentence
%   that invites the error and the sentence that forbids it belong together.
    lines = {'## The Strongest Clusters' '' ...
        ['A cluster''s extent is a by-product of the cluster-forming threshold and the ' ...
         'noise, not an estimate of anything. The channels and times below say where the ' ...
         'statistic ran extreme in this dataset; they do not say where or when the effect ' ...
         'begins and ends, and the *p*-value belongs to the test as a whole rather than to ' ...
         'those boundaries (Sassenhagen & Draschkow, 2019).'] ''};
    nShow = min(5, numel(summary.clusters));
    if nShow == 0
        lines = [lines, {'No clusters to show.' ''}];
        return;
    end
    space = testedSpace(summary);
    for r = 1:nShow
        c = summary.clusters(r);
        lines = [lines, oneClusterLines(r, c, space)]; %#ok<AGROW>
    end
end

function space = testedSpace(summary)
%TESTEDSPACE  How large the tested channel x time space was, read from
%   FieldTrip's own stat (summary.stat.label / .time). NaN where it cannot be
%   read, which is how a summary from before this existed still reports.
    space = struct('nChannels', NaN, 'spanMs', NaN);
    if ~isfield(summary, 'stat') || ~isstruct(summary.stat)
        return;
    end
    if isfield(summary.stat, 'label')
        space.nChannels = numel(summary.stat.label);
    end
    if isfield(summary.stat, 'time') && numel(summary.stat.time) > 1
        space.spanMs = (max(summary.stat.time) - min(summary.stat.time)) * 1000;
    end
end

function lines = coverageLines(c, space)
%COVERAGELINES  How much of the tested space this cluster covers, in the
%   report rather than left to the reader to work out from a list of channel
%   names. A cluster covering nearly everything is the common case people
%   over-read: it is what a broad sustained difference produces, and its
%   boundaries then carry almost no information at all.
    lines = {};
    if ~isfinite(space.nChannels) || ~isfinite(space.spanMs) || space.spanMs <= 0
        return;
    end
    spanMs = c.timeRangeMs(2) - c.timeRangeMs(1);
    text = sprintf('It covers %d of the %d channel(s) tested, and %.0f of the %.0f ms.', ...
        numel(c.channels), space.nChannels, spanMs, space.spanMs);
    if numel(c.channels) / space.nChannels >= 2/3 && spanMs / space.spanMs >= 0.5
        text = [text ' That is most of the space the test looked at, so its extent says ' ...
            'very little: a cluster this broad is what a sustained, widespread difference ' ...
            'produces, and it cannot be told apart from one confined to part of that space.'];
    end
    lines = {'' text};
end

function lines = oneClusterLines(rank, c, space)
    sigWord = 'not significant';
    if c.significant
        sigWord = 'significant';
    end
    chLit = rLit(strjoin(c.channels, ', '));
    heading = { ...
        sprintf('### Cluster %d (%s, %s)', rank, c.sign, sigWord) ...
        '' ...
        sprintf(['A %s cluster spanning %s, %.0f to %.0f ms (*p* %s, %d point(s)).'], ...
            c.sign, mdLit(strjoin(c.channels, ', ')), c.timeRangeMs(1), c.timeRangeMs(2), ...
            pStr(c.pValue), c.nPoints)};
    lines = [heading, coverageLines(c, space), { ...
        '' ...
        '::: {layout-ncol=2}' ...
        '' ...
        sprintf('```{r}') ...
        sprintf('#| label: topo-%d', rank) ...
        sprintf('#| fig-width: 4') ...
        sprintf('#| fig-height: 4') ...
        sprintf('t_lo <- %g; t_hi <- %g', c.timeRangeMs(1), c.timeRangeMs(2)) ...
        sprintf('pts <- stat_df %%>%% filter(time_ms >= t_lo, time_ms <= t_hi) %%>%%') ...
        sprintf('  group_by(channel, x, y) %%>%% summarise(statistic = mean(statistic), .groups = "drop")') ...
        sprintf('in_cluster <- stat_df %%>%% filter(channel %%in%% c(%s), time_ms >= t_lo, time_ms <= t_hi) %%>%%', ...
            strjoin(cellfun(@(ch) ['"' rLit(ch) '"'], c.channels, 'UniformOutput', false), ', ')) ...
        sprintf('  distinct(channel)') ...
        sprintf('tp <- ggplot() +') ...
        sprintf('  geom_path(data = outline_df, aes(x = x, y = y, group = outline_id), colour = "grey60") +') ...
        sprintf('  geom_point(data = pts, aes(x = x, y = y, colour = statistic), size = 5) +') ...
        sprintf(['  geom_point(data = pts %%>%% filter(channel %%in%% in_cluster$channel), ' ...
            'aes(x = x, y = y), shape = 1, size = 7, colour = "black", stroke = 1) +']) ...
        sprintf(['  geom_text(data = pts, aes(x = x, y = y, label = channel), ' ...
            'size = 2.2, vjust = -1.1, colour = "grey20") +']) ...
        sprintf('  scale_colour_gradient2(low = "#c0392b", mid = "white", high = "#2980b9", midpoint = 0) +') ...
        sprintf('  coord_fixed() + theme_void() + labs(title = "Where (mean over cluster window)")') ...
        sprintf('print(tp)') ...
        '```' ...
        '' ...
        sprintf('```{r}') ...
        sprintf('#| label: timecourse-%d', rank) ...
        sprintf('#| fig-width: 5') ...
        sprintf('#| fig-height: 4') ...
        sprintf('wf <- waveform_df %%>%% filter(channel %%in%% c(%s))', ...
            strjoin(cellfun(@(ch) ['"' rLit(ch) '"'], c.channels, 'UniformOutput', false), ', ')) ...
        sprintf('tc <- ggplot(wf, aes(x = time_ms, y = value, colour = condition, fill = condition)) +') ...
        sprintf('  annotate("rect", xmin = t_lo, xmax = t_hi, ymin = -Inf, ymax = Inf, alpha = 0.12, fill = "grey40") +') ...
        sprintf('  stat_summary(fun = mean, geom = "line", linewidth = 0.8) +') ...
        sprintf('  stat_summary(fun.data = mean_se, geom = "ribbon", alpha = 0.15, colour = NA) +') ...
        sprintf('  geom_hline(yintercept = 0, linetype = "dashed", colour = "grey60") +') ...
        sprintf('  labs(x = "Time (ms)", y = "Amplitude", title = "When (shaded = cluster window)") +') ...
        sprintf('  alz_theme()') ...
        sprintf('print(tc)') ...
        '```' ...
        '' ...
        ':::' ...
        ''}];
end

function s = pStr(p)
    if p < .001
        s = '< .001';
    else
        s = ['= ' regexprep(sprintf('%.3f', p), '^0\.', '.')];
    end
end

% ======================================================================= %
%  String-escaping helpers (see generateQuartoReport.m's own copies of
%  these -- duplicated rather than shared, both local-only there too)
% ======================================================================= %
function s = rLit(matlabText)
    s = strrep(char(matlabText), '\', '\\');
    s = strrep(s, '"', '\"');
end

function s = mdLit(matlabText)
    s = char(matlabText);
    special = {'\', '*', '_', '#', '[', ']', '`', '<', '>'};
    for i = 1:numel(special)
        s = strrep(s, special{i}, ['\' special{i}]);
    end
end

function lines = nullDistributionLines()
%NULLDISTRIBUTIONLINES  The permutation null distribution, with the observed
%   cluster masses marked on it.
%
%   THE TEST MADE VISIBLE. A cluster-based permutation test compares one
%   number -- a cluster's mass, the summed statistic over its points --
%   against the distribution of that same number under relabelling. Every
%   other figure in this report shows WHERE and WHEN an effect was; this
%   one shows the comparison the p-value actually came from. Without it a
%   reader is asked to take "p = .03" on trust.
%
%   What it answers at a glance: how far into the tail the observed cluster
%   sits, whether the null is tight or broad, and -- the question a single
%   p-value cannot address -- whether the largest cluster is exceptional or
%   merely the largest of several similar ones.
%
%   Absent for TFCE, which scores each point by the support it gathers
%   across thresholds rather than forming discrete clusters, so there is no
%   cluster mass and no distribution of one. The section says so instead of
%   drawing an empty panel.
    lines = ReportDoc.lines({ ...
        ReportDoc.template('cs-null-distribution.qmd') ...
        ['A cluster-level *p*-value indicates that an effect exists somewhere within the ' ...
         'cluster. It ' ...
         'is not a statement about the cluster''s boundaries: its extent in time and across ' ...
         'channels is a property of the threshold and the data together, so the onset, offset ' ...
         'and topography visible above should not be read as estimates of when or where the ' ...
         'effect begins and ends (Sassenhagen & Draschkow, 2019).'] ...
        '' ''});
end
