function qmdText = generateDataQualityReport(entries, summaryCsvName, trialCsvName, smeCsvName, measureCsvName, provenanceCsvName)
%GENERATEDATAQUALITYREPORT  A Quarto (.qmd) report on per-subject ERP data
%   quality: rendering it (self-contained HTML) produces a per-subject
%   overview table, the condition-wise rejection figure that is the whole
%   point of the exercise, per-trial noise distributions, a subject x
%   channel noise map, and a short "worth a look" list naming the subjects
%   and channels that stand out.
%
%   Adapted from the data-quality assessment section of Mathot &
%   Vilotijevic (2023), "Methods in cognitive pupillometry: Design,
%   preprocessing, and statistical analysis" (Behav Res Methods 55,
%   3055-3077) -- see dataQualityMetrics.m's own header for the
%   pupillometry-to-ERP mapping each metric comes from, and for the two
%   places the translation deliberately departs from the original.
%
%   Like generateClusterStatsReport.m (and unlike generateQuartoReport.m,
%   whose R code runs the actual statistical tests), every number here was
%   already computed in MATLAB by dataQualityMetrics; this report's own R
%   code narrates, tabulates and plots a precomputed result. The one
%   exception is the omnibus test for whether rejection rate differs
%   BETWEEN bins, which is a genuine inferential question about the export
%   as a whole rather than about any one subject, so it belongs with the
%   other cross-subject statistics in R.
%
%   ENTRIES is the same struct array exportDataQualityCSVs was handed (only
%   its length and grouping are used here, to decide which sections can
%   run at all); SUMMARYCSVNAME/TRIALCSVNAME are bare filenames, resolved
%   relative to the .qmd's own folder.
%
%   Requires the R packages tidyverse and gt (auto-installed by the
%   report's own setup chunk on first render, same as the other two report
%   generators) plus a working Quarto installation.
%
%   See also DATAQUALITYMETRICS, EXPORTDATAQUALITYCSVS,
%   ALAKAZAM.ONEXPORTDATAQUALITY.
    if isempty(entries)
        throw(MException('Alakazam:generateDataQualityReport', ...
            ['I''m afraid a data-quality report needs at least one Averaged dataset ' ...
             'with segmented data behind it.']));
    end
    hasGroups = numel(distinctGroups(entries)) >= 2;
    if nargin < 4 || isempty(smeCsvName)
        smeCsvName = '';
    end
    if nargin < 5 || isempty(measureCsvName)
        measureCsvName = '';
    end
    if nargin < 6 || isempty(provenanceCsvName)
        provenanceCsvName = '';
    end

    lines = [ ...
        preambleLines(summaryCsvName, trialCsvName, smeCsvName, measureCsvName, ...
            provenanceCsvName), ...
        introLines(numel(entries)), ...
        overviewLines(), ...
        rejectionByBinLines(), ...
        baselineNoiseLines(), ...
        noiseOverSessionLines(), ...
        channelNoiseLines(), ...
        flaggedByChannelLines(), ...
        provenanceLines(provenanceCsvName), ...
        smeLines(smeCsvName), ...
        precisionByTrialCountLines(), ...
        dependabilityLines(measureCsvName), ...
        groupComparisonLines(hasGroups), ...
        attentionLines()];
    qmdText = strjoin(lines, newline);
end

% ======================================================================= %
function lines = flaggedByChannelLines()
%FLAGGEDBYCHANNELLINES  How many trials each channel was flagged in, per
%   subject, as a count rather than a proportion.
%
%   THE MAP ABOVE ANSWERS A DIFFERENT QUESTION. Noise by Channel is
%   coloured by median pre-stimulus SD and marks a channel flagged in more
%   than 20% of trials with a cross. That is a threshold, not a number: it
%   separates 21% from 19% and says nothing about whether a flagged
%   channel lost 12 trials or 200, which is the quantity that decides
%   whether to interpolate it, drop it, or leave it.
%
%   Counts, not percentages, and printed in the cell. A percentage hides
%   the trial count it is a percentage of, and two subjects at 30% are not
%   comparable when one ran 40 trials and the other 400. The percentage is
%   kept as the fill, so the eye still finds the worst cells first while
%   the number gives the amount.
%
%   Peripherals are marked rather than hidden. An EOG channel exceeds any
%   threshold set for scalp EEG on every blink, so it is flagged on a large
%   fraction of trials whenever artefact detection tests it, and appearing
%   here at 60% is correct rather than a fault. Hiding it would conceal
%   that the detector is spending its threshold on the eyes; labelling it
%   lets a reader skip it and read the scalp channels, which are the ones a
%   decision hangs on. See ArtefactDetect's own "Channels to test" option.
    lines = ReportDoc.lines({ ...
        '### Trials flagged, per channel and subject' ...
        '' ...
        ['The number of trials in which each channel was flagged, for each subject. ' ...
         'Colour is that count as a proportion of the subject''s own trials, so the ' ...
         'worst cells stand out, and the number in the cell is the count itself, ' ...
         'which is what a decision to interpolate or exclude a channel actually ' ...
         'rests on.'] ...
        ReportDoc.template('dq-flagged-by-channel.qmd') ...
        '' ''});
end

% ======================================================================= %
function packages = dependabilityPackages(measureCsvName)
%DEPENDABILITYPACKAGES  lme4 only when there is something to fit with it.
%   A report that loads it unconditionally makes every quality render wait
%   for an install it will not use, on the many workspaces where Measure
%   was never run on epoched data.
    packages = {'tidyverse', 'gt'};
    if ~isempty(measureCsvName)
        packages = [packages, {'lme4'}];
    end
end

function line = measureReadLine(measureCsvName)
%MEASUREREADLINE  The per-trial MEASURE values, which are a different file
%   from this report's own per-trial noise export: that one carries
%   pre-stimulus SD per trial, this one carries the scored amplitude of
%   each trial, and only the second can estimate dependability.
    if isempty(measureCsvName)
        line = 'meas <- NULL';
        return;
    end
    line = sprintf(['meas <- if (file.exists("%s")) read_csv("%s", show_col_types = FALSE) ' ...
        'else NULL'], rLit(measureCsvName), rLit(measureCsvName));
end

function lines = dependabilityLines(measureCsvName)
%DEPENDABILITYLINES  Dependability from generalizability theory, and the
%   trial count a target dependability would need.
%
%   THE QUESTION THE REST OF THIS REPORT ONLY GESTURES AT. Rejection rates
%   say how much was lost. SME says what the loss cost, in the units of the
%   measure. Neither says whether the measure is reliable enough to
%   correlate with anything, which is the question behind every "how many
%   trials do I need" a reader has ever asked, and it is the question
%   generalizability theory answers (Clayson & Miller, 2017).
%
%   G THEORY IN ONE PARAGRAPH. Score a component on single trials and the
%   variance splits in two: variance BETWEEN people, which is the signal a
%   correlation or a group difference can use, and variance WITHIN a person
%   across trials, which is noise that averaging reduces. Dependability is
%   the first as a fraction of what an average of n trials actually
%   measures, sigma_p^2 / (sigma_p^2 + sigma_e^2 / n). It rises with trial
%   count without bound in principle, which is why the useful output is not
%   the coefficient alone but the n that reaches a target.
%
%   FITTED WITH lmer, NOT BY ANOVA MEAN SQUARES. Trial counts differ per
%   person after rejection, sometimes by a factor of three, and the ANOVA
%   estimator assumes they do not. A random-intercept model handles the
%   imbalance properly and is the one place in this report that needs a
%   package beyond tidyverse.
%
%   ONLY WHERE Measure RAN ON EPOCHED DATA. Averaged measurements carry one
%   value per person and condition, from which no within-person variance is
%   recoverable at all. The section says so rather than approximating, since
%   precisionByTrialCountLines already gives the honest approximation.
    if isempty(measureCsvName)
        lines = { ...
            '## Dependability' ...
            '' ...
            ['Not computed for this report. Dependability needs the scored value of ' ...
             '**each trial**, and no dataset in this workspace carried per-trial ' ...
             'measurements. To get them, run `Measure` on the **epoched** node rather ' ...
             'than on the Average: the same window definitions then yield one value ' ...
             'per trial instead of one per bin, and this section computes itself the ' ...
             'next time the report is generated. In the absence of those values, ' ...
             '*Precision Against Trial Count* above gives an approximation, and is ' ...
             'labelled as such.'] ...
            '' ''};
        return;
    end
    lines = ReportDoc.lines({ ...
        '## Dependability' ...
        '' ...
        ['The reliability of each measure, and the number of trials a target ' ...
         'reliability would require. Single-trial amplitude varies both between ' ...
         'people, which is the variance any correlation or group difference uses, ' ...
         'and within a person from trial to trial, which is noise that averaging ' ...
         'reduces. Dependability is the first of these as a fraction of what an ' ...
         'average of *n* trials measures, and is the quantity generalizability ' ...
         'theory estimates (Clayson & Miller, 2017).'] ...
        ReportDoc.template('dq-dependability.qmd') ...
        ['The last two columns are design quantities rather than criteria. They ' ...
         'assume that additional trials would resemble the existing ones, an ' ...
         'assumption that fatigue and drift weaken towards the end of a long ' ...
         'session, so the counts are a lower bound on the required effort. A ' ...
         'score whose dependability is below about .70 constrains any correlation ' ...
         'it can enter, irrespective of sample size.'] ...
        '' ''});
end

% ======================================================================= %
function labels = distinctGroups(entries)
    groups = {entries.group};
    labels = unique(groups(~cellfun(@isempty, groups)));
end

% ======================================================================= %
%  Preamble
% ======================================================================= %
function lines = preambleLines(summaryCsvName, trialCsvName, smeCsvName, measureCsvName, provenanceCsvName)
    lines = ReportDoc.lines([ReportDoc.yamlHeader('Alakazam Data Quality Report'), { ...
        ReportDoc.template('dq-setup.Rpart') ...
        }, ReportDoc.packageBootstrap(dependabilityPackages(measureCsvName)), { ...
        '' ...
        sprintf('qual <- read_csv("%s", show_col_types = FALSE)', rLit(summaryCsvName)) ...
        sprintf('trl  <- read_csv("%s", show_col_types = FALSE)', rLit(trialCsvName)) ...
        smeReadLine(smeCsvName) ...
        provenanceReadLine(provenanceCsvName) ...
        measureReadLine(measureCsvName) ...
        ReportDoc.template('dq-intro.qmd') ...
        }, ReportDoc.apaHelpers(), { ...
        '```' ...
        ''}]);
end

function line = smeReadLine(smeCsvName)
%SMEREADLINE  Read the per-window SME table, or stand in an empty one of
%   the same shape when this export had no Measure results to score. The
%   section below then needs only ONE emptiness check (nrow == 0), rather
%   than separate "file absent" and "file empty" branches that would both
%   have to be kept in step with it.
    if isempty(smeCsvName)
        line = ['wsme <- tibble(dataset = character(), group = character(), window = character(), ' ...
            'bin = character(), channel = character(), measure = character(), method = character(), ' ...
            'sme_uv = double(), score = double())'];
    else
        line = sprintf('wsme <- read_csv("%s", show_col_types = FALSE)', rLit(smeCsvName));
    end
end

% ======================================================================= %
%  Intro
% ======================================================================= %
function line = provenanceReadLine(provenanceCsvName)
%PROVENANCEREADLINE  Read the provenance CSV, or stand in an empty frame.
%   Guarded by file.exists for the same reason smeReadLine is: a report
%   regenerated beside an older export, or rendered from a stem whose
%   companion files have been moved, should lose one section rather than
%   fail to render at all.
    if isempty(provenanceCsvName)
        line = ['prov <- ' emptyProvenanceFrame()];
        return;
    end
    line = sprintf('prov <- if (file.exists("%s")) read_csv("%s", show_col_types = FALSE) else %s', ...
        rLit(provenanceCsvName), rLit(provenanceCsvName), emptyProvenanceFrame());
end

function frame = emptyProvenanceFrame()
%EMPTYPROVENANCEFRAME  The stand-in tibble for a missing provenance CSV.
%   EVERY column the three tables below reference must be declared here, or
%   the fallback errors on the workspace it exists to protect. Written once
%   and used by both branches so the two cannot drift apart.
    frame = ['tibble(dataset = character(), group = character(), ' ...
        'session = character(), step = character(), item = character(), ' ...
        'n = numeric(), n_total = numeric(), pct = numeric(), n_unique = numeric(), ' ...
        'channel_epochs = numeric(), channels_tested = numeric(), scope = character(), ' ...
        'threshold = numeric(), components = character(), ' ...
        'n_samples_rejected = numeric(), n_samples = numeric(), sensai = numeric(), ' ...
        'enova_epoch_max = numeric(), enova_epoch_median = numeric(), ' ...
        'enova_channel_max = numeric(), n_excluded = numeric(), ' ...
        'pct_within_one = numeric(), mean_offset_ms = numeric(), detail = character())'];
end

function lines = provenanceLines(provenanceCsvName)
%PROVENANCELINES  What each cleaning step actually did: which detector cost
%   which trials, and what the correction steps removed.
%
%   The sections above say how much data was lost. This one says what lost
%   it, which is the part that tells you what to change. Rejection and
%   correction are recorded on the dataset as they run, so this is a report
%   of what happened rather than a re-derivation of it.
%
%   A NOTE ON ONE ESCAPE BELOW, because getting it wrong cost a whole
%   report: a literal double quote inside an emitted R string is \" and NOT
%   \\". This is MATLAB source writing R source, and a MATLAB single-quoted
%   literal passes backslashes through untouched, so \\" arrives in the .qmd
%   as \\" -- which R reads as a literal backslash followed by a quote that
%   CLOSES the string. The chunk becomes a syntax error and Quarto renders
%   nothing at all. Compare the callout-tip line in attentionLines, which
%   does it right. (The opposite convention applies to a backslash meant for
%   the OUTPUT, such as LaTeX's \chi: there \\ is correct, because R's parser
%   consumes one level before cat ever runs. See rejectionByBinLines.)
%
%   Two more things this function's own shape demands. The emitted prose
%   below carries NO APOSTROPHES: one inside a MATLAB single-quoted literal
%   has to be doubled, and rephrasing to avoid it is cheaper than an escape
%   that a later edit can break. And NO COMMENT LINE may sit inside the
%   lines = {...} literal: every line there ends with a continuation, so a
%   comment ends the row and the cell becomes a vertcat of rows of unequal
%   width. Comments about the emitted R belong in the R, as # lines.
    if isempty(provenanceCsvName)
        lines = {};
        return;
    end
    lines = ReportDoc.lines({ ...
        '## What the Cleaning Steps Did' ...
        '' ...
        ['How much data was lost is above; this is what lost it. Each cleaning step ' ...
         'records what it did as it runs, so these are the decisions themselves rather ' ...
         'than an estimate of them.'] ...
        '' ...
        ['A table per step, and only for the steps that ran. They are kept separate ' ...
         'because they count different things: epochs for rejection, components for ' ...
         'ICA, channels and samples for GEDAI. One combined table could only have ' ...
         'labelled its count column "n", which no reader could interpret.'] ...
        ReportDoc.template('dq-provenance.qmd') ...
        });
end

function lines = introLines(nEntries)
    lines = ReportDoc.lines({ ...
        '## What This Report Is' ...
        '' ...
        sprintf(['Data quality for each of the %d subject(s) whose Average currently sits in this ' ...
            'workspace, computed from the segmented data each average was built from.'], nEntries) ...
        '' ...
        ['The quantity of interest is not the total amount of data lost, but **whether the loss ' ...
         'is even across conditions**. An even rejection rate reduces statistical power. An ' ...
         'uneven one affects validity, because the surviving trials in one condition are no ' ...
         'longer a representative sample of that condition.'] ...
        '' ...
        'What each metric is:' ...
        '' ...
        '| Metric | What it indicates |' ...
        '|---|---|' ...
        ['| % trials rejected | How much of the recording survived artefact rejection. See the note ' ...
         'directly below: with no artefact step in the chain, an empty trial means an epoch that ' ...
         'could not be cut, not one anything rejected |'] ...
        ['| % trials truncated | Trials whose epoch ran off the start or end of the recording. They ' ...
         'still enter the average, with less data at the ends than their neighbours |'] ...
        ['| % trials rejected **per bin** | Whether that loss is even across conditions. This is ' ...
         'the metric that affects validity rather than only statistical power |'] ...
        ['| % channel-epochs flagged | Loss confined to single channels rather than whole trials, ' ...
         'usually one bad electrode. Note this is a share of *all* channel-epochs: one electrode ' ...
         'dead in every trial of a 64-channel montage is only 1.6% here, so read it with the ' ...
         'per-channel map below rather than on its own |'] ...
        ['| % channel-epochs interpolated | Channel-epochs that were *reconstructed* from ' ...
         'neighbouring electrodes rather than discarded. Not loss, but not measurement either: ' ...
         'these samples are an estimate, and a spatially widespread artefact (a blink spans the ' ...
         'frontal electrodes at once) can be reproduced rather than removed by the reconstruction |'] ...
        ['| Pre-stimulus SD (uV) | Per-trial noise. Measured as *variability* over the pre-stimulus ' ...
         'window, not its mean, which baseline correction sets to zero by construction |'] ...
        ['| % baseline outlier trials | Trials whose pre-stimulus noise is extreme *for that ' ...
         'subject*, at \|z\| > 2 against their own distribution |'] ...
        ['| SME (uV) | Standardized measurement error (Luck et al., 2021), the established ' ...
         'single-subject quality statistic in ERP research |'] ...
        ['| Dependability | How much of the variance in a scored measure is between people rather ' ...
         'than within them, and so how many trials a target reliability would take (Clayson & ' ...
         'Miller, 2017). It is the only metric here that bears on whether a measure can ' ...
         'support a correlation. Computed where `Measure` was run on the epoched node, since it ' ...
         'needs the score of every trial rather than of the average |'] ...
        '' ...
        ['Nothing below has been excluded from the data. Exclusion criteria are best set in ' ...
         'advance and reported openly, so this report describes what is present and leaves the ' ...
         'decision to the user.'] ...
        ReportDoc.template('dq-empty-trial-provenance.qmd') ...
        });
end

% ======================================================================= %
%  Per-subject overview
% ======================================================================= %
function lines = overviewLines()
    lines = ReportDoc.template('dq-subject-overview.qmd');
end

% ======================================================================= %
%  Rejection by bin -- the central figure
% ======================================================================= %
function lines = rejectionByBinLines()
    lines = ReportDoc.lines({ ...
        '## Rejection Rate by Condition' ...
        '' ...
        ['One line per subject, one point per bin. Flat lines indicate even loss across ' ...
         'conditions. A line sloping consistently in the same direction as the others indicates ' ...
         'that rejection removed more trials from one condition than from another, in which ' ...
         'case ' ...
         'the surviving averages are not comparable in the way the analysis assumes.'] ...
        ReportDoc.template('dq-rejection-by-bin.qmd') ...
        });
end

% ======================================================================= %
%  Per-trial baseline noise
% ======================================================================= %
function lines = baselineNoiseLines()
    lines = ReportDoc.lines({ ...
        '## Per-Trial Noise Distribution' ...
        '' ...
        ['Each trial''s pre-stimulus standard deviation, meaned across channels. A typical ' ...
         'recording gives a roughly unimodal, right-skewed distribution. A second mode well to ' ...
         'the right indicates a block of trials recorded under changed conditions (an electrode ' ...
         'drying out, a participant becoming restless) rather than variation around a single ' ...
         'mean.'] ...
        ReportDoc.template('dq-baseline-hist.qmd') ...
        ['Pooling subjects, as above, combines people who recorded at different ' ...
         'overall noise levels. The z-scores below are computed **within each subject**, which is ' ...
         'what makes the \|z\| > 2 cutoff meaningful here: it identifies a trial as unusual ' ...
         '*for that person*, rather than identifying that person as noisy overall.'] ...
        ReportDoc.template('dq-baseline-z.qmd') ...
        });
end

% ======================================================================= %
%  Noise across the session
% ======================================================================= %
function lines = noiseOverSessionLines()
    lines = ReportDoc.lines({ ...
        '## Noise Across the Session' ...
        '' ...
        ['A check for degradation over the course of a recording (a participant settling or ' ...
         'slumping, or an electrode drying out): pre-stimulus noise against trial number. A flat ' ...
         'cloud indicates no systematic change. A rising trend indicates that later trials are ' ...
         'noisier than earlier ones, which affects the analysis if condition order was not ' ...
         'counterbalanced.'] ...
        '' ...
        ['**Each panel has its own y-axis.** The question addressed here is whether a subject ' ...
         'drifts over the course of their own session, and a shared axis would compress every ' ...
         'quiet subject into a line at the base of the panel, obscuring that trend. The ' ...
         'consequence is that panels cannot be compared with each other directly, so the dashed ' ...
         'line marks the median across all subjects: it lies at the same value in every panel, ' ...
         'and its position indicates whether a steep-looking slope represents a large drift or a ' ...
         'small one magnified by a narrow axis. For comparison of overall noise levels between ' ...
         'subjects, the channel map below and the overview table are both on a single scale.'] ...
        ReportDoc.template('dq-noise-over-session.qmd') ...
        });
end

% ======================================================================= %
%  Per-channel noise
% ======================================================================= %
function lines = channelNoiseLines()
    lines = ReportDoc.lines({ ...
        '## Noise by Channel' ...
        '' ...
        ['Which electrodes, on which subjects. A whole row standing out is a noisy recording; a ' ...
         'single bright cell is one bad electrode on one subject, which is the case for which ' ...
         'interpolation is intended.'] ...
        '' ...
        ['Colour is noise **among the samples that survived**, so the worst channels are the ones ' ...
         'colour cannot show: a channel rejected in every trial has nothing left to take a median ' ...
         'of and would otherwise sit here as an unremarkable grey cell, and an interpolated one ' ...
         'shows the noise of its neighbours rather than its own. Both are marked instead of left ' ...
         'to the colour scale.'] ...
        ReportDoc.template('dq-channel-noise-map.qmd') ...
        });
end

% ======================================================================= %
%  SME
% ======================================================================= %
function lines = smeLines(~)
    lines = ReportDoc.lines([{ ...
        '## Standardized Measurement Error' ...
        '' ...
        ['SME (Luck et al., 2021) is the established single-subject quality statistic in ERP ' ...
         'research. Unlike a rejection rate, it combines how noisy the single trials were **and** ' ...
         'how many of them survived into one value in the units of the measurement itself: the ' ...
         'standard error expected if the same subject were recorded again in the same condition. ' ...
         'Smaller values indicate greater precision, and the statistic is comparable across ' ...
         'subjects in a way a rejection percentage is not.'] ...
        '' ...
        '### Whole-epoch SME' ...
        '' ...
        ['A single value per subject, over the whole epoch. Useful for an initial comparison, ' ...
         'but see the following section: SME is strictly interpretable only for the score that ' ...
         'is reported, and this value averages across time ranges in which a subject may have ' ...
         'been variously clean and noisy.'] ...
        ReportDoc.template('dq-sme-plot.qmd') ...
        ''}, windowSmeLines()]);
end

function lines = windowSmeLines()
%WINDOWSMELINES  Per-Measure-window SME: the grain Luck et al. actually
%   argue for, and the one that can be quoted in a methods section.
    lines = ReportDoc.lines({ ...
        '### SME per measurement window' ...
        '' ...
        ['This is the value to report in a methods section. SME describes the error on **a ' ...
         'specific score**, so it is computed here for each Measure window on the score that ' ...
         'window produces, from the single trials behind each subject''s average.'] ...
        '' ...
        ['Two estimators are used, chosen automatically per score type. Mean amplitude has a closed ' ...
         'form, because the mean amplitude of the average is exactly the average of the per-trial ' ...
         'mean amplitudes, so its standard error is simply SD/sqrt(*n*) (**analytic**). Every other ' ...
         'score is a non-linear function of the waveform: the peak of the average is not the average ' ...
         'of the peaks, so no such identity exists and there is no closed form. Those are ' ...
         '**bootstrapped** instead, by repeatedly resampling trials with replacement, re-averaging, ' ...
         're-scoring, and taking the spread of the result.'] ...
        ReportDoc.template('dq-window-sme-table.qmd') ...
        });
end

% ======================================================================= %
%  Between-groups check
% ======================================================================= %
function lines = groupComparisonLines(hasGroups)
%GROUPCOMPARISONLINES  A between-subjects counterpart to the by-bin figure,
%   emitted only when the workspace actually has two or more groups (see
%   WorkSpace.editSubjects). Uneven quality BETWEEN groups is the same
%   threat to validity as uneven quality between bins, one level up: a
%   patient group that blinks more than a control group produces a group
%   difference in the ERP that is not a group difference in the brain.
    if ~hasGroups
        lines = {};
        return;
    end
    lines = ReportDoc.lines({ ...
        '## Quality by Between-Subjects Group' ...
        '' ...
        ['The same concern as the by-condition figure, one level up. If one group''s data is ' ...
         'systematically noisier or more heavily rejected than another''s, any group difference ' ...
         'you find in the ERP has a competing explanation that has nothing to do with the brain.'] ...
        ReportDoc.template('dq-quality-by-group.qmd') ...
        });
end

% ======================================================================= %
%  Closing: what to look at
% ======================================================================= %
function lines = precisionByTrialCountLines()
%PRECISIONBYTRIALCOUNTLINES  Measurement precision against surviving trial
%   count, with the theoretical curve drawn through it.
%
%   THE QUESTION EVERY REJECTION DECISION IS REALLY ASKING. The rest of this
%   report says how many trials each subject lost. It does not say what that
%   loss cost, and those are different questions: losing 40 trials from 200
%   barely moves the estimate, losing 20 from 40 changes what the average
%   means. The standardised measurement error answers it directly, because
%   it is the standard error of the very quantity being measured (Luck et
%   al., 2021), and plotting it against surviving trial count turns a
%   diagnostic into a design number.
%
%   The reference curve is 1/sqrt(n). Averaging independent trials reduces
%   the standard error by that factor and no faster, so a subject sitting
%   well above the curve is not short of trials but noisy within them, which
%   collecting more of would not fix. That distinction is the practical
%   value of the figure: it separates "run more trials" from "this
%   recording has a problem".
%
%   NOT A DEPENDABILITY COEFFICIENT, and no longer the only answer here.
%   Generalizability theory (Clayson & Miller, 2017) estimates how many
%   trials a given component needs for a target reliability, which is the
%   fuller answer to the same question and needs per-trial VALUES of the
%   measure rather than per-trial noise. dependabilityLines below computes
%   exactly that when the per-trial measurement export is present. This
%   figure stays because it needs nothing beyond SME and so is always
%   available, and because it separates two failures the coefficient pools:
%   a subject short of trials sits on the curve, one noisy within them sits
%   above it.
    lines = ReportDoc.lines({ ...
        '## Precision Against Trial Count' ...
        '' ...
        ['The measurement precision obtained from the trials that survived, per subject. The ' ...
         'standardised measurement error is the standard error of the measure itself, so it ' ...
         'addresses what a rejection rate does not: not how much data was lost, but the effect ' ...
         'of that loss on the estimate.'] ...
        ReportDoc.template('dq-precision-by-trials.qmd') ...
        ['This is an approximation to the question generalizability theory answers properly ' ...
         '(Clayson & Miller, 2017): how many trials a given component needs to reach a target ' ...
         'reliability. That calculation uses the per-trial values of the measure itself rather ' ...
         'than per-trial noise, which this report does not yet read.'] ...
        '' ''});
end

function lines = attentionLines()
    lines = ReportDoc.lines({ ...
        '## Worth a Look' ...
        '' ...
        ['A shortlist for inspection, not a set of exclusion decisions. Nothing here has been ' ...
         'excluded, and none of these thresholds is a standard: they are conventional starting ' ...
         'points, set at values that merit a second look rather than at values that are ' ...
         'correct. Whether a subject at 35% rejection is usable depends on the initial trial ' ...
         'count and on what is being measured.'] ...
        ReportDoc.template('dq-attention-list.qmd') ...
        ['| More than **25%** of trials discarded | At a quarter of the data gone, the surviving ' ...
         'trials are no longer a random subset: whatever removed them (drowsiness, movement, ' ...
         'drift) is systematic, and is likely to correlate with condition or with time in the ' ...
         'session. Below roughly this level, loss behaves more like attrition than like bias |'] ...
        ['| Fewer than **20** surviving trials in a bin that began with more than 20 | Noise in an ' ...
         'average falls as 1/sqrt(*n*), so returns diminish quickly, but below about 20 trials the ' ...
         'average is still visibly unstable for a typical ERP component and the SME grows sharply. ' ...
         'Luck et al. (2021) argue the SME column is the better guide here, since it accounts for ' ...
         'how noisy the individual trials actually were; this count is the cruder proxy that needs ' ...
         'no measurement window to have been defined yet. The second half of the condition matters: ' ...
         'a bin designed with 15 trials has not lost anything, and flagging it would report the ' ...
         'design rather than the data |'] ...
        ['| A channel flagged in more than **20%** of trials | A channel that fails this often is ' ...
         'usually a bad electrode rather than an occasional artefact, and one persistently bad ' ...
         'channel is a case for interpolation rather than for discarding trials |'] ...
        ['| A channel interpolated in more than **20%** of trials | The same threshold applied to ' ...
         'repair rather than loss. Interpolated samples pass every other check in this report as ' ...
         'ordinary data, so this is the only place a mostly-reconstructed channel appears |'] ...
        ['| A subject more than **3 MAD** noisier than the sample median | Median absolute ' ...
         'deviation rather than standard deviation, because with a handful of subjects the very ' ...
         'outliers being looked for would inflate an SD enough to hide inside it. 3 MAD is the ' ...
         'usual robust-statistics analogue of a 3-sigma rule |'] ...
        ['| Any trial truncated at a recording boundary | Not a threshold: any occurrence is ' ...
         'reported, because such a trial still enters the average with less data at the ends ' ...
         'than its neighbours, and no other section of the report would reveal it |'] ...
        '' ...
        ['These are applied per subject, and the report flags rather than acts. Exclusion criteria ' ...
         'are best fixed in advance and reported openly, which a threshold discovered after ' ...
         'looking at the data is not.'] ...
        '' ...
        '' ...
        '## References' ...
        '' ...
        ['Luck, S. J., Stewart, A. X., Simmons, A. M., & Kappenman, E. S. (2021). Standardized ' ...
         'measurement error: A universal metric of data quality for averaged event-related ' ...
         'potentials. *Psychophysiology*, 58(6), e13793.'] ...
        '' ...
        ['Ros, T., Ferat, V., Huang, Y., Colangelo, C., Kia, S. M., Wolfers, T., Vulliemoz, S., & ' ...
         'Michela, A. (2025). Return of the GEDAI: Unsupervised EEG denoising based on ' ...
         'leadfield filtering. *bioRxiv* (preprint, not yet peer reviewed). ' ...
         'https://doi.org/10.1101/2025.10.04.680449'] ...
        ''});
end

% ======================================================================= %
function s = rLit(matlabText)
    s = strrep(char(matlabText), '\', '\\');
    s = strrep(s, '"', '\"');
end
