function qmdText = generateSourceClusterStatsReport(summary, assets, extras)
%GENERATESOURCECLUSTERSTATSREPORT  A Quarto report for a source-space
%   cluster permutation test.
%
%   QMDTEXT = generateSourceClusterStatsReport(SUMMARY, ASSETS) assembles
%   the document from SourceClusterStats' own return value and the figures
%   generateSourceClusterAssets rendered from it.
%
%   PURE MARKDOWN, NO R CHUNK, unlike the scalp cluster report. The
%   difference is not about who runs the test: the permutation runs in
%   MATLAB for both, since FieldTrip is a MATLAB toolbox. It is about the
%   figures. The scalp report exports long-format CSVs and has R plot a
%   heatmap, topographies and waveforms from them; this report's figures are
%   cortical surfaces, which cannot be drawn from a flat CSV without
%   shipping the mesh with it, so they are rendered in MATLAB and the
%   document is plain markdown. It therefore also renders on a machine with
%   no R at all.
%
%   THE DOCUMENT LEADS WITH WHAT THE TEST DOES NOT SHOW. Cluster inference
%   is among the most over-read results in the literature: a significant
%   cluster establishes that an effect exists somewhere in a space-time
%   region, and specifically does NOT license a claim about where it starts,
%   stops, or which gyrus it occupies. Stating that after the tables would
%   be stating it after it has already been misread, so it comes first.
%
%   See also SOURCECLUSTERSTATS, GENERATESOURCECLUSTERASSETS,
%   GENERATECLUSTERSTATSREPORT, TRANSTOOLS.DESCRIBECLUSTER,
%   TRANSTOOLS.POINTSPREADFUNCTION.
    if nargin < 3 || isempty(extras)
        extras = struct('UnthresholdedMapPath', '', 'NullDistributionPath', '', ...
            'PointSpreadPath', '', 'PointSpread', []);
    end

    lines = [ReportDoc.yamlHeader('Alakazam Source Cluster Statistics'), { ...
        '' ...
        '<!--' ...
        'Alakazam: source-space cluster permutation report.' ...
        'Auto-generated. Every figure and number was computed in MATLAB; this' ...
        'document is markdown only and needs no R packages to render.' ...
        'Render with: quarto render <this file>.qmd' ...
        '-->' ...
        ''}, ...
        methodLines(summary), ...
        forwardModelLines(summary), ...
        limitationLines(summary), ...
        pointSpreadLines(summary, extras), ...
        resultLines(summary, assets), ...
        subjectLines(summary), ...
        nullDistributionLines(summary, extras), ...
        appendixLines(extras), ...
        provenanceLines(summary)];

    qmdText = char(strjoin(lines, newline));
end

% ======================================================================= %
function lines = methodLines(summary)
%METHODLINES  What was actually run, in the words a methods section needs.
%   Read off SUMMARY.opts rather than restated from the dialog's defaults,
%   so the document describes the analysis that ran and not the one that was
%   requested -- numrandomization in particular can be raised to exhaustive
%   by resolveNumRandomization without the analyst asking.
    opts = summary.opts;
    lines = { ...
        '## What was tested' ...
        '' ...
        sprintf('%s, across %d subjects, on cortical source estimates.', ...
            contrastSentence(summary.contrast), summary.nSubjects) ...
        '' ...
        '| Setting | Value |' ...
        '| --- | --- |' ...
        sprintf('| Inverse method | %s |', methodName(opts.Method)) ...
        sprintf('| Orientation | %s |', orientationName(opts.Orientation)) ...
        sprintf('| Source space | template cortical sheet, %d vertices |', ...
            numel(summary.vertexLabels)) ...
        sprintf('| Time window | %s |', windowText(summary.times)) ...
        sprintf('| Sampling for the test | %.0f Hz |', samplingHz(summary.times)) ...
        sprintf('| Regularisation | %s |', regularisationText(summary)) ...
        sprintf('| Noise covariance | %s |', provenanceField(summary, 'noiseCovariance', 'not recorded')) ...
        sprintf('| Multiple-comparison correction | %s |', correctionName(opts.correctm)) ...
        correctionParameterRow(summary) ...
        sprintf('| Permutations | %s |', permutationText(opts.numrandomization)) ...
        sprintf('| Smallest attainable p | %s |', smallestPText(opts.numrandomization)) ...
        sprintf('| Alpha | %g, %s |', opts.alpha, tailText(opts.tail)) ...
        '' ...
        ['Only the contrast above was tested. If several contrasts were run on ' ...
         'these data, nothing here corrects across them: the correction below is ' ...
         'family-wise over the vertex-by-time volume of this one test.'] ...
        ''};
end

function row = correctionParameterRow(summary)
%CORRECTIONPARAMETERROW  The correction's OWN free parameters.
%   TFCE's E and H are choices, and a cluster-forming alpha applies only to
%   the classic method. Printing clusteralpha under TFCE, as an earlier
%   version did, states that a threshold was used when none was.
    opts = summary.opts;
    if strcmpi(opts.correctm, 'tfce')
        tfce = provenanceField(summary, 'tfce', struct('variant', 'exact', 'E', 0.5, 'H', 2));
        row = sprintf(['| TFCE parameters | %s variant, E = %g, H = %g ' ...
            '(no cluster-forming threshold is used) |'], tfce.variant, tfce.E, tfce.H);
    else
        row = sprintf('| Cluster-forming threshold | p < %g, minimum %d neighbours |', ...
            opts.clusteralpha, TransTools.FieldOr(opts, 'minnbchan', 0));
    end
end

function lines = forwardModelLines(summary)
%FORWARDMODELLINES  How the scalp data was mapped onto the cortex.
%   Its own table because these are a separate set of reporting items from
%   the statistics, and because every entry in it is a template rather than
%   a measurement of these participants. Stating that plainly is the point.
    if ~isfield(summary, 'provenance')
        lines = {};
        return;
    end
    % EVERY FIELD READ THROUGH A FALLBACK, none directly. A summary can
    % reach here from an older cached run, or with provenance only partly
    % filled, and a report generator is the wrong place to discover that:
    % the analysis has already finished by the time this runs, so an
    % "Unrecognized field name" here throws away work that succeeded. The
    % same assumption -- that a struct holds what its name suggests -- has
    % already cost one crash on a bin whose trial count was text.
    p = summary.provenance;
    lines = { ...
        '## The forward model' ...
        '' ...
        '| Component | Value |' ...
        '| --- | --- |' ...
        sprintf('| Head model | %s |', provenanceField(summary, 'headModel', 'not recorded')) ...
        sprintf('| Electrode positions | %s |', provenanceField(summary, 'electrodes', 'not recorded')) ...
        sprintf('| Coregistration | %s |', provenanceField(summary, 'coregistration', 'not recorded')) ...
        sprintf('| Source space | %s, %s vertices |', ...
            provenanceField(summary, 'sourceTemplate', 'not recorded'), ...
            countText(provenanceField(summary, 'nVertices', NaN))) ...
        sprintf('| Vertex adjacency | %s |', provenanceField(summary, 'adjacency', 'not recorded')) ...
        sprintf('| Channels used | %s |', channelsText(summary)) ...
        sprintf('| Reference | %s |', provenanceField(summary, 'reference', 'not recorded')) ...
        sprintf('| Variance explained by the fitted sources | %s |', varianceExplainedText(p)) ...
        '' ...
        ['Channels whose labels the 10-5 template does not recognise are dropped ' ...
         'rather than placed by guesswork, so the channel count may be lower than ' ...
         'the recording''s own. Where subjects differ, the analysis uses only what ' ...
         'they share: how many spatial patterns a forward model can distinguish is ' ...
         'bounded by that number, so a single reduced montage limits the whole ' ...
         'group, and excluding that subject may yield more information than including ' ...
         'them.'] ...
        '' ...
        ['A high variance explained is expected here and is not evidence that ' ...
         'the model is correct. There are far more vertices than electrodes, so ' ...
         'the inverse can reproduce almost any scalp data almost exactly, and a ' ...
         'near-total fit is a property of the problem rather than a validation ' ...
         'of the solution. The quantity is informative in the negative case: a ' ...
         'subject whose fit is substantially poorer than the others indicates a ' ...
         'problem with that subject''s channels or reference.'] ...
        ''};
end

function lines = subjectLines(summary)
%SUBJECTLINES  Who was in it, with the two per-subject numbers that bear on
%   a source estimate: how many trials were averaged, and how much of that
%   subject's scalp data the fitted sources actually account for.
    % Each field is checked, not just the struct: a provenance carrying
    % channels but no subject table is a perfectly ordinary shape, and
    % reading .subjects off it errored the whole document rather than
    % skipping one section.
    if ~isfield(summary, 'provenance') || ~isfield(summary.provenance, 'subjects') || ...
            isempty(summary.provenance.subjects)
        lines = {};
        return;
    end
    rows = summary.provenance.subjects;
    lines = {'## Subjects' '' ...
        '| Subject | Trials in contrast | Unexplained variance |' '| --- | --- | --- |'};
    for i = 1:numel(rows)
        lines{end + 1} = sprintf('| %s | %s | %s |', ...
            ReportSections.mdLit(rows(i).id), trialsCell(rows(i)), ...
            percentText(rows(i).residualVariance)); %#ok<AGROW>
    end
    lines = [lines, {'' ...
        ['Unexplained variance is the fraction of a subject''s scalp data the ' ...
         'fitted sources do not reproduce. It checks the forward model, not the ' ...
         'effect: a value near 100% means the model failed for that subject and ' ...
         'their source estimate should not be trusted. It is not defined for ' ...
         'sLORETA, whose filter output is a standardised statistic rather than a ' ...
         'current, and appears as "n/a" there.'] ''}];
end

function lines = nullDistributionLines(summary, extras)
%NULLDISTRIBUTIONLINES  The permutation null, and the observed extreme on it.
%   Placed after the clusters and before the appendix: it is not a result,
%   but unlike the unthresholded map it is the direct evidence for the
%   p-values just quoted, so a reader meets it while those are still in
%   mind.
    if ~isfield(extras, 'NullDistributionPath') || isempty(extras.NullDistributionPath)
        lines = missingNullLines(summary);
        return;
    end
    lines = { ...
        '## The permutation null' ...
        '' ...
        sprintf('![The null distribution of the maximum statistic, with the observed extreme marked](<%s>)', ...
            extras.NullDistributionPath) ...
        '' ...
        ['Each bar counts relabellings of the subjects that produced a maximum of ' ...
         'that magnitude somewhere in the vertex-by-time volume. The marked line is ' ...
         'the value obtained under the true labelling. The p-value of a corrected ' ...
         'test is the proportion of the distribution at or beyond that line, so the ' ...
         'figure shows the comparison from which each p-value above was derived.'] ...
        '' ...
        ['Three features of the figure are informative: the position of the observed ' ...
         'value within the tail, which is more specific than a p-value rounded to ' ...
         'three decimal places; the width of the null distribution, since a wide ' ...
         'distribution indicates limited ability to distinguish the effect from ' ...
         'relabelling at this sample size; and whether the observed value is ' ...
         'separated from the bulk of the distribution or lies at its edge.'] ...
        '' ...
        smallestAttainableLine(summary) ...
        ''};
end

function lines = missingNullLines(summary)
%MISSINGNULLLINES  Say why there is no figure, rather than omitting it.
%   The unaccelerated route runs FieldTrip's own correctm='tfce', which
%   does not return the per-permutation extremes, so there is nothing to
%   draw. Silence would read as "this analysis had no null distribution",
%   which is wrong: it had one and did not keep it.
    if ~isfield(summary, 'opts') || ~isfield(summary.opts, 'Accelerate') || ...
            summary.opts.Accelerate
        lines = {};
        return;
    end
    lines = { ...
        '## The permutation null' ...
        '' ...
        ['This run used FieldTrip''s own TFCE correction, which does not return ' ...
         'the per-permutation extremes, so the null distribution behind the ' ...
         'p-values above cannot be drawn. The accelerated route (the default) ' ...
         'keeps them and this section then shows the distribution itself. ' ...
         'Nothing about the test differs; only what it reported back.'] ...
        ''};
end

function line = smallestAttainableLine(summary)
%SMALLESTATTAINABLELINE  Restate the resolution of the test beside the
%   figure, where a reader is looking at the very draws that set it.
    n = NaN;
    if isfield(summary, 'opts') && isfield(summary.opts, 'numrandomization')
        n = summary.opts.numrandomization;
    end
    if ~isnumeric(n) || ~isscalar(n) || ~isfinite(n)
        line = ['The smallest p this test can report is set by the number of ' ...
                'permutations drawn, so a p at that floor means "no relabelling ' ...
                'reached this", not "vanishingly improbable".'];
        return;
    end
    line = sprintf(['With %d permutations the smallest p this test can report is ' ...
        '%.4g, so a p at that floor means "no relabelling reached this value", ' ...
        'not "vanishingly improbable".'], n, 1 / (n + 1));
end

function lines = appendixLines(extras)
%APPENDIXLINES  The unthresholded statistic, once, at the end.
%   At the end deliberately: it is a check on the analysis rather than a
%   result, and placing it beside the cluster figures would invite reading
%   it as one.
    if ~isfield(extras, 'UnthresholdedMapPath') || isempty(extras.UnthresholdedMapPath)
        lines = {};
        return;
    end
    lines = { ...
        '## Appendix: the unthresholded statistic' ...
        '' ...
        sprintf('![The test statistic across the whole cortex](<%s>)', extras.UnthresholdedMapPath) ...
        '' ...
        ['The test statistic across the cortex, averaged over the tested window, ' ...
         'with no masking and no threshold applied. None of this map is a result: ' ...
         'the test makes no claim about any vertex except through the clusters ' ...
         'reported above. It is included because a masked map does not show how ' ...
         'close the remaining cortex came to threshold, and because the statistic ' ...
         'to which the correction was applied is part of the record.'] ...
        ''};
end

function lines = provenanceLines(summary)
%PROVENANCELINES  What produced this document.
%   Last, because nobody reads it until they need it, and then they need it
%   exactly. Required by COBIDAS MEEG (Pernet et al., 2020): an inverse
%   solution or a permutation scheme can change between releases, and a
%   result without a version is not reproducible.
    if ~isfield(summary, 'provenance')
        lines = {};
        return;
    end
    v = provenanceField(summary, 'software', struct());
    lines = { ...
        '## Software' ...
        '' ...
        '| Component | Version |' ...
        '| --- | --- |' ...
        sprintf('| MATLAB | %s |', ReportSections.mdLit(softwareField(v, 'matlab'))) ...
        sprintf('| FieldTrip | %s |', ReportSections.mdLit(softwareField(v, 'fieldtrip'))) ...
        sprintf('| Alakazam | %s |', ReportSections.mdLit(softwareField(v, 'alakazam'))) ...
        '' ...
        ['Permutations are drawn with a seed taken fresh for each run, so ' ...
         'repeating this analysis gives slightly different p-values. That ' ...
         'variation is the Monte Carlo error of the test, and it shrinks as the ' ...
         'permutation count rises.'] ...
        ''};
end

% ---- provenance formatting helpers -------------------------------------- %
function value = provenanceField(summary, field, fallback)
    value = fallback;
    if isfield(summary, 'provenance') && isfield(summary.provenance, field)
        value = summary.provenance.(field);
    end
end

function s = regularisationText(summary)
%REGULARISATIONTEXT  Both the dimensionless knob and the absolute lambda it
%   produced. The knob is what the analyst set; the absolute value is what
%   the inverse actually used, and only the latter reproduces the result.
    reg = provenanceField(summary, 'regParam', TransTools.FieldOr(summary.opts, 'RegParam', NaN));
    lambda = provenanceField(summary, 'lambda', NaN);
    if isfinite(lambda)
        s = sprintf('RegParam %g, giving lambda = %.4g', reg, lambda);
    else
        s = sprintf('RegParam %g', reg);
    end
end

function s = channelsText(summary)
%CHANNELSTEXT  The shared montage, and what it cost.
%   A vertex-wise test must use the channels every subject has, so one
%   subject with a reduced montage sets the count for everyone. Reporting
%   only the shared number reads as though nothing was given up.
    shared = provenanceField(summary, 'nChannels', NaN);
    counts = provenanceField(summary, 'subjectChannels', []);
    if isempty(counts) || ~isnumeric(counts)
        s = sprintf('%s, shared by every subject', countText(shared));
        return;
    end
    if min(counts) == max(counts)
        s = sprintf('%s, and every subject carries exactly these', countText(shared));
        return;
    end
    limiting = provenanceField(summary, 'limitingSubject', '');
    s = sprintf(['%s, the set shared by all %d subjects. They carry %d to %d ' ...
        'channels each (median %d)'], countText(shared), numel(counts), ...
        min(counts), max(counts), round(median(counts)));
    if ~isempty(limiting)
        s = sprintf('%s; %s has the fewest and therefore sets this montage', ...
            s, ReportSections.mdLit(limiting));
    end
end

function s = varianceExplainedText(p)
    if ~isfield(p, 'residualVariance') || all(isnan(p.residualVariance))
        s = 'not defined for this inverse (see Subjects)';
        return;
    end
    rv = p.residualVariance(~isnan(p.residualVariance));
    s = sprintf('%.1f%% to %.1f%% across subjects and bins', ...
        100 * (1 - max(rv)), 100 * (1 - min(rv)));
end

function s = softwareField(v, name)
    if isstruct(v) && isfield(v, name) && ~isempty(v.(name))
        s = char(string(v.(name)));
    else
        s = 'unknown';
    end
end

function s = trialsCell(row)
%TRIALSCELL  A trial count, or the bins' own description when there is no
%   single number to give (a difference bin records '39-161', not a count).
    if isfield(row, 'trialsText') && ~isempty(row.trialsText)
        s = ReportSections.mdLit(row.trialsText);
        return;
    end
    if ~isfield(row, 'trials')
        s = 'not recorded';
        return;
    end
    s = countText(row.trials);
end

function s = countText(n)
    if ~isnumeric(n) || ~isscalar(n) || isnan(n)
        s = 'not recorded';
    else
        s = sprintf('%d', round(n));
    end
end

function s = percentText(x)
    if ~isnumeric(x) || ~isscalar(x) || isnan(x)
        s = 'n/a';
    else
        s = sprintf('%.0f%%', 100 * x);
    end
end

function s = permutationText(n)
    if ischar(n) || isstring(n)
        s = 'all (exhaustive)';
    else
        s = sprintf('%d', n);
    end
end

function s = smallestPText(n)
%SMALLESTPTEXT  A Monte Carlo p-value cannot fall below 1/(N+1). Stated so
%   that "p < 0.001" is read as the resolution of the test rather than as a
%   vanishingly small probability.
    if ischar(n) || isstring(n)
        s = 'exact (every permutation enumerated)';
    else
        s = sprintf('%.4g (= 1/(%d+1), the resolution of a Monte Carlo test)', ...
            1 / (double(n) + 1), n);
    end
end

function lines = limitationLines(summary)
%LIMITATIONLINES  Placed before the results, deliberately, see this file's
%   own header.
%
%   THE QUANTITATIVE PARAGRAPHS ARE APPENDED INSIDE THIS BLOCKQUOTE, not
%   emitted beside it. Each begins with its own '>' and continues the same
%   callout; a blank line between them would split one caveat into three
%   and let a reader stop after the first. resolutionParagraph was written
%   and then never called at all, which is how it came to be documented in
%   the readme while appearing in no report.
    lines = { ...
        '## How to read this' ...
        '' ...
        '> **A significant cluster indicates that an effect exists, not where it is.**' ...
        '> Cluster-based permutation controls the family-wise error rate over the' ...
        '> whole vertex-by-time volume at once. It supports the statement that the' ...
        '> conditions differ. It does not support the statement that the difference' ...
        '> is located in a particular region or confined to a particular latency' ...
        '> range: a cluster''s boundaries are the points at which a statistic crossed' ...
        '> a threshold, and not the onset and offset of the effect.' ...
        '>' ...
        '> **The head model is a template.** Template anatomy, template electrode' ...
        '> positions, and a few dozen channels explaining tens of thousands of' ...
        '> vertices. The anatomical labels below name where the model places the' ...
        '> activity, which carries far more uncertainty than any p-value here' ...
        '> expresses. The peak coordinates are given alongside the region names so' ...
        '> that precision can be judged rather than assumed.' ...
        '>' ...
        '> **Neighbouring vertices are not independent.** The inverse is spatially' ...
        '> smooth, so an apparently focal cluster reflects the method''s point-spread' ...
        '> in part. This is the reason the correction is cluster-based rather than' ...
        '> per-vertex, and the reason cluster extent should not be interpreted as a' ...
        '> measurement of the size of the effect.'};

    lines = [lines, resolutionParagraph(summary), meshDependenceLines(summary), {''}];
end

function lines = meshDependenceLines(summary)
%MESHDEPENDENCELINES  That the cortical sheet is part of the analysis, not
%   a setting beside it.
%
%   MEASURED, NOT REASONED. TFCE counts extent in vertices, so a denser
%   sheet gives every supra-threshold region more of them and the enhanced
%   statistic grows with the mesh. One real contrast (7 subjects, 250-400
%   ms, dSPM, signed) run at three sheets gave max|TFCE| of 6795 at 5124
%   vertices, 11858 at 8196 and 16329 at 20484. The statistic is therefore
%   not comparable across sheets even for identical data, and the scaling
%   is sub-linear in vertex count (4x the vertices, 2.4x the statistic), so
%   it is not a factor a reader could divide out either.
%
%   The p-value is a different matter and is not claimed here: the null is
%   built on the same sheet and scales with it, so much of this cancels.
%   What did not cancel was WHERE. The coarsest sheet put the peak 38 mm
%   from the peak the two finer sheets agreed on, which is the same order
%   as the localisation error the paragraph above reaches on entirely
%   separate grounds.
    if ~isfield(summary, 'opts') || ~isfield(summary.opts, 'SourceSpace')
        lines = {};
        return;
    end
    lines = { ...
        '>' ...
        sprintf(['> **The cortical sheet affects the statistic.** This test ran on ' ...
                 'the %d-vertex template sheet. TFCE measures spatial extent by ' ...
                 'counting vertices, so the enhanced statistic increases with the ' ...
                 'density of the sheet. In one contrast measured for this purpose ' ...
                 '(7 subjects, 250 to 400 ms, dSPM, signed) the maximum was 6795 at ' ...
                 '5124 vertices, 11858 at 8196 and 16329 at 20484 for identical ' ...
                 'data; the increase is sub-linear in vertex count and so cannot be ' ...
                 'removed by rescaling. Statistic values obtained on different ' ...
                 'sheets are therefore not comparable. In the same contrast the peak ' ...
                 'location differed by 38 mm between the coarsest sheet and the two ' ...
                 'finer ones, which agreed with each other. The sheet should be ' ...
                 'reported alongside any peak coordinate.'], ...
                 summary.opts.SourceSpace) ...
        };
end

function lines = resolutionParagraph(summary)
%RESOLUTIONPARAGRAPH  How finely this montage can localise, in numbers.
%
%   The limitations above make the argument in words: many more vertices
%   than electrodes, so a good fit proves little. This states the size of
%   it, because "the map is smoother than it looks" and "the map carries
%   about thirty independent numbers spread over five thousand vertices"
%   are read very differently, and only the second stops a reader quoting
%   a peak vertex as a location.
%
%   The rank bound is exact and computed here: an N-electrode montage,
%   average-referenced, gives a leadfield of rank at most N-1, and no
%   inverse of any kind can recover more independent spatial patterns than
%   that. The millimetre figure is illustrative rather than computed --
%   it comes from resolution-matrix analysis of a 29-channel montage on
%   this same template (peak localisation error, median 42 mm, noise-free)
%   and is quoted as an order of magnitude, not as this study's own number.
    nVert = 0;
    if isfield(summary, 'vertexLabels')
        nVert = numel(summary.vertexLabels);
    elseif isfield(summary, 'opts') && isfield(summary.opts, 'SourceSpace')
        nVert = summary.opts.SourceSpace;
    end

    nChan = 0;
    if isfield(summary, 'provenance') && isfield(summary.provenance, 'channels')
        chans = summary.provenance.channels;
        if iscell(chans) && ~isempty(chans)
            chans = chans{1};
        end
        nChan = numel(chans);
    end

    if nVert <= 0 || nChan <= 1
        lines = {};
        return;   % nothing computable; say nothing rather than guess
    end

    rank = nChan - 1;
    perNumber = round(nVert / rank);
    lines = { ...
        '>' ...
        sprintf(['> **How much detail the map can carry.** %d electrodes, average-referenced, ' ...
                 'give a leadfield of rank at most %d, so the %d vertices drawn on the cortex ' ...
                 'are described by approximately %d independent values, or roughly %d vertices ' ...
                 'per value. The spatial smoothness of the map is therefore interpolation ' ...
                 'rather than measurement. Resolution analyses of comparable montages on this ' ...
                 'template report a median peak localisation error in the tens of millimetres ' ...
                 'under noise-free conditions, which indicates the spatial scale at which a ' ...
                 'peak can be interpreted: sufficient to distinguish posterior from anterior ' ...
                 'regions, and not one gyrus from an adjacent one.'], ...
                 nChan, rank, nVert, rank, perNumber) ...
        };
end

function lines = pointSpreadLines(summary, extras)
%POINTSPREADLINES  The resolution limit as a picture, immediately after the
%   same limit as prose.
%
%   PLACED BETWEEN THE CAVEATS AND THE RESULTS, deliberately, for the reason
%   this file's header gives about the caveats themselves: a reader who
%   meets it after the cluster maps has already read those maps as a
%   measurement of extent. It is its own section rather than another
%   paragraph in the blockquote because a figure cannot go inside a callout
%   without breaking it, and because this one is worth stopping at.
%
%   THE PARAGRAPH ABOVE IT SAYS "APPROXIMATELY N INDEPENDENT VALUES OVER
%   THOUSANDS OF VERTICES". That is the same fact, and it is read as an
%   abstraction. This is the fact drawn on the cortex the results are drawn
%   on, at the vertex the results peak at.
%
%   Omitted entirely when the figure was not rendered. Unlike the missing
%   permutation null, there is nothing worth telling a reader here: the
%   figure is absent because the forward model was not in memory, which is a
%   fact about the session and not about the analysis.
    if ~isfield(extras, 'PointSpreadPath') || isempty(extras.PointSpreadPath)
        lines = {};
        return;
    end

    lines = { ...
        '## What one vertex can resolve' ...
        '' ...
        sprintf('![The estimate this analysis returns for a single active vertex](<%s>)', ...
            extras.PointSpreadPath) ...
        '' ...
        ['This figure is not a result. It is what this analysis would report if ' ...
         'exactly one vertex of the cortex were active and nothing else were: the ' ...
         'scalp pattern that vertex produces, put back through the same inverse, ' ...
         'the same regularisation and the same orientation constraint every map ' ...
         'above was computed with. The marked circle is the vertex that was ' ...
         'active. Everything else in the figure is the method, not the brain.'] ...
        ''};

    lines = [lines, foldingLines(summary), pointSpreadNumbers(extras), { ...
        ['Read the cluster maps above beside this one. A region of this size is ' ...
         'what a single generator looks like through this forward model, so the ' ...
         'extent of a cluster is not evidence about the extent of an effect, and a ' ...
         'peak coordinate describes a neighbourhood of roughly this width rather ' ...
         'than a location. The vertex drawn is the analysis''s own peak, so this ' ...
         'is the resolution available where the result is being read rather than ' ...
         'an average over the cortex.'] ...
        ''}];
end

function lines = foldingLines(summary)
%FOLDINGLINES  Why a single source comes out red on one bank and blue on the
%   next, on a signed map.
%
%   Said because it is otherwise misread, and misread in the worst possible
%   direction: alternating colour in a figure captioned "one active vertex"
%   looks like evidence of several sources, when it is the same current seen
%   through normals that point opposite ways. Only relevant to a signed map,
%   so it is only stated for one.
    if ~isfield(summary, 'opts') || ...
            ~strcmpi(TransTools.FieldOr(summary.opts, 'Orientation', 'magnitude'), 'normal')
        lines = {};
        return;
    end
    lines = { ...
        ['The alternating red and blue is the folding of the cortex rather than ' ...
         'several sources. This analysis projects each vertex onto its own ' ...
         'cortical normal so that polarity is kept, and the two banks of a sulcus ' ...
         'face opposite ways, so one estimated current takes opposite signs across ' ...
         'a fold. The same effect is present in the cluster maps above.'] ...
        ''};
end

function lines = pointSpreadNumbers(extras)
%POINTSPREADNUMBERS  The two measurements the figure carries, in words.
%   Quoted from the figure's own metrics rather than described, because
%   "broad" and "peaks 41 mm away" are read very differently, which is the
%   same argument the resolution paragraph above makes for its rank bound.
    info = [];
    if isfield(extras, 'PointSpread')
        info = extras.PointSpread;
    end
    if isempty(info) || ~isstruct(info) || ~isfinite(info.PeakErrorMm) || ...
            ~isfinite(info.DispersionMm)
        lines = {};
        return;
    end

    lines = { ...
        sprintf(['That estimate peaks %.0f mm from the vertex that was actually ' ...
                 'active, and has a spatial dispersion of %.0f mm, which is the ' ...
                 'average distance the estimate of that vertex is drawn from. ' ...
                 'Nothing here was smoothed; the spread is the resolution of the ' ...
                 'measurement itself.'], info.PeakErrorMm, info.DispersionMm) ...
        '' ...
        ['The two numbers describe different limits. A displaced peak means the ' ...
         'estimate is in the wrong place. A large dispersion means it is in ' ...
         'roughly the right place and draws on far more cortex than the map ' ...
         'suggests. Distributed inverse methods differ in which of the two they ' ...
         'incur, and neither is removed by a denser sheet or a finer colour ' ...
         'scale.'] ...
        ''};
end

function lines = resultLines(summary, assets)
    lines = {'## Clusters' ''};

    if isempty(summary.clusters)
        lines = [lines, { ...
            'The permutation found no candidate clusters at all: no vertex-by-time' ...
            'point reached the threshold for cluster formation. There is no effect' ...
            'here at this sensitivity, which is a result, not a failure to run.' ''}];
        return;
    end

    significant = summary.clusters([summary.clusters.significant]);
    if isempty(significant)
        lines = [lines, { ...
            sprintf(['The permutation formed %d candidate cluster(s), none of which ' ...
                     'survived correction (smallest p = %.3f). Candidate clusters are ' ...
                     'formed routinely from noise, so this is a null result rather than ' ...
                     'a near-miss, and the clusters below are listed only for ' ...
                     'completeness.'], numel(summary.clusters), min([summary.clusters.pValue])) ...
            ''}];
    end

    lines = [lines, { ...
        '| # | Direction | p | Vertices | Time range | Location |' ...
        '| --- | --- | --- | --- | --- | --- |'}];
    for k = 1:numel(assets)
        a = assets(k);
        lines{end + 1} = sprintf('| %d | %s | %s | %d | %.0f to %.0f ms | %s |', ...
            a.Index, a.Sign, pValueText(a.PValue), a.NVertices, ...
            a.TimeRangeMs(1), a.TimeRangeMs(2), ...
            ReportSections.mdLit(a.Description.Text)); %#ok<AGROW>
    end
    lines{end + 1} = '';

    for k = 1:numel(assets)
        a = assets(k);
        lines = [lines, { ...
            sprintf('### Cluster %d (%s, %s)', a.Index, a.Sign, pValueText(a.PValue)) ...
            '' ...
            ReportSections.mdLit(a.Description.Text) ...
            '' ...
            }, truncationLines(a), { ...
            '::: {.panel-tabset}' ...
            '' ...
            '#### Where' ...
            '' ...
            sprintf('![Cluster %d on the cortical surface](<%s>)', a.Index, a.MapPath) ...
            '' ...
            'Each hemisphere is shown from the side and from the midline, so that the' ...
            'whole cortical sheet is visible: a single three-quarter view hides the' ...
            'medial wall entirely, and a cluster that is absent would look the same as' ...
            'one that is merely facing away. All four panels share one scale.' ...
            '' ...
            'Coloured by the cluster''s own statistic, averaged over its time range,' ...
            'red for positive and blue for negative. Vertices outside the cluster are' ...
            'not shaded: nothing below threshold is drawn, so the picture shows what' ...
            'was found rather than what was tested.' ...
            '' ...
            '#### When' ...
            '' ...
            sprintf('![Cluster %d over time](<%s>)', a.Index, a.TimeCoursePath) ...
            '' ...
            'The statistic averaged across the cluster''s vertices, over the whole' ...
            'tested window. The shaded band is the cluster''s extent, where the' ...
            'statistic crossed threshold, which is not the same as where the effect' ...
            'started and stopped.' ...
            '' ...
            'Time is latency within the epoch, in milliseconds relative to the' ...
            'time-locking event, the same axis an ERP waveform is drawn on. It spans' ...
            'the tested window rather than the whole epoch, so if it looks narrower' ...
            'than the recording, that is the **Time window** setting reported above' ...
            'and not a property of the data.' ...
            '' ...
            ':::' ...
            ''}]; %#ok<AGROW>

        if ~isempty(a.Description.Regions)
            lines = [lines, regionTableLines(a.Description)]; %#ok<AGROW>
        end
    end
end

function lines = regionTableLines(description)
%REGIONTABLELINES  Where the cluster's vertices fall, by share.
%   A distribution rather than a single label, because a cluster crossing a
%   regional boundary is the normal case and naming only its peak would
%   hide that.
    lines = {'Vertices by region:' '' '| Region | Share of cluster |' '| --- | --- |'};
    show = min(5, numel(description.Regions));
    for r = 1:show
        lines{end + 1} = sprintf('| %s | %.0f%% |', ...
            ReportSections.mdLit(description.Regions{r}), 100 * description.RegionShare(r)); %#ok<AGROW>
    end
    lines{end + 1} = '';
end

function lines = truncationLines(asset)
%TRUNCATIONLINES  Say so when a cluster runs into the edge of the analysis
%   window, because its reported time range is then a property of the
%   window rather than of the effect.
    if ~asset.TouchesWindowEdge
        lines = {};
        return;
    end
    lines = { ...
        ['> This cluster reaches the edge of the tested time window, so its time ' ...
         'range is limited by where the analysis looked rather than by where the ' ...
         'effect ended. Widen the window to see its true extent.'] ...
        ''};
end

% ---- small formatting helpers ------------------------------------------- %
function s = contrastSentence(contrast)
    switch contrast.mode
        case 'vsZero'
            s = sprintf('Bin "%s" tested against zero', contrast.bin);
        case 'paired'
            s = sprintf('Bin "%s" compared with bin "%s" within each subject', ...
                contrast.binA, contrast.binB);
        case 'independent'
            s = sprintf('Bin "%s" compared between groups', contrast.bin);
        otherwise
            s = 'An unrecognised contrast';
    end
end

function s = methodName(method)
%METHODNAME  The displayed name plus its expansion. The name itself comes
%   from TransTools.SourceMethodName so this table, the dialog that
%   configured the run and the on-screen summary cannot disagree about
%   which method ran.
    [name, gloss] = TransTools.SourceMethodName(method);
    if isempty(gloss)
        s = name;
    else
        s = sprintf('%s (%s)', name, gloss);
    end
end

function s = orientationName(orientation)
    if strcmpi(orientation, 'normal')
        s = 'signed, projected onto the cortical normal';
    else
        s = 'magnitude (unsigned)';
    end
end

function s = correctionName(correctm)
    switch lower(char(string(correctm)))
        case 'tfce'
            s = 'threshold-free cluster enhancement (Smith & Nichols, 2009)';
        case 'cluster'
            s = 'cluster-based permutation (Maris & Oostenveld, 2007)';
        otherwise
            s = char(string(correctm));
    end
end

function s = windowText(times)
    s = sprintf('%.0f to %.0f ms', times(1), times(end));
end

function hz = samplingHz(times)
    if numel(times) < 2
        hz = NaN;
        return;
    end
    hz = 1000 / median(diff(times));
end

function s = tailText(tail)
    if tail == 0
        s = 'two-sided';
    elseif tail > 0
        s = 'one-sided (positive)';
    else
        s = 'one-sided (negative)';
    end
end

function s = pValueText(p)
%PVALUETEXT  A permutation p-value cannot be smaller than 1/nPermutations,
%   so it is reported at its resolution rather than as a spuriously precise
%   decimal or as a bare "0".
    if p <= 0
        s = 'p < 0.001';
    elseif p < 0.001
        s = 'p < 0.001';
    else
        s = sprintf('p = %.3f', p);
    end
end
