function requireContinuous(EEG)
%REQUIRECONTINUOUS  Refuse anything but continuous data, and say why.
%   Unfold.requireContinuous(EEG) throws Alakazam:Unfold:NeedsContinuous
%   unless EEG.DataFormat is CONTINUOUS.
%
%   IT IS A FILE OF ITS OWN so that Deconvolve can check it before it opens a
%   dialog, while Unfold.binModel checks it as the first step of validating a
%   whole design, without two copies of the explanation drifting apart. The
%   explanation is the point: this is the one precondition a user cannot work
%   around by choosing different settings, so the message has to say which
%   node to run it on instead.
%
%   See also UNFOLD.BINMODEL, DECONVOLVE.
    format = char(string(TransTools.FieldOr(EEG, 'DataFormat', 'not set')));
    if strcmpi(format, 'CONTINUOUS'); return; end

    throw(MException('Alakazam:Unfold:NeedsContinuous', '%s', sprintf([ ...
        'Deconvolution needs continuous (unsegmented) data, and this dataset is not ' ...
        '(DataFormat = "%s"), I''m afraid. Would you run it on the continuous recording ' ...
        'itself, the node you would give to DefineBins? It asks for the bins it should ' ...
        'fit when it starts, in the same language DefineBins uses, so it does not need ' ...
        'an already binned dataset.\n\nSeparating responses that overlap in time is only ' ...
        'possible while the recording is still one continuous stretch, and cutting it ' ...
        'into epochs is exactly what destroys that: an epoched node no longer holds the ' ...
        'continuous data to fit against, so there is nothing this could work from. That ' ...
        'is also why a DefineBins node with an epoch window set cannot be used here, ' ...
        'even though it is the one node that carries bins.'], format)));
end
