function [rel, k] = parseTimelock(T, kStart, aliases, binIndex)
%PARSETIMELOCK  timelock <relation>  -- reuse the expression parser, require
%   one relation.
    [node, kLocal] = DefineBinsEngine.parseExprTokens(T(kStart:end), aliases);
    if ~isstruct(node) || ~strcmp(node.op, 'rel')
        DefineBinsEngine.throwParseError(DefineBinsEngine.tokAt(T, kStart).pos, sprintf([ ...
            'bin %g: I''m afraid ''timelock'' needs exactly one relation after it, to say ' ...
            'which neighbouring event to centre the epoch on -- for example, ' ...
            'timelock next(118). A bare code, or a combination of terms, is not a ' ...
            'relation on its own.'], ...
            binIndex));
    end
    rel = node;
    k   = kStart + kLocal - 1;
end
