function [name, node] = parseLetStatement(stmt, aliases)
%PARSELETSTATEMENT  let <ident> = <expr>   (any bin expression: codes,
%   relations, not/and/or/parens, and earlier aliases). Spliced in wherever
%   the alias is referenced, so evalNode sees exactly the same tree it would
%   if the alias's text had been written out inline -- a relation inside an
%   alias is evaluated relative to whatever candidate event the reference
%   site is evaluated at, same as if it had not been factored out.
    [~,     rest] = DefineBinsEngine.expectTok(stmt, "kw", "let", 'the keyword ''let''');
    [nameT, rest] = DefineBinsEngine.expectTok(rest, "ident", 'a name for this alias, right after ''let''');
    name = char(nameT.val);
    if isempty(rest) || ~(rest(1).kind == "punc" && rest(1).val == "=")
        DefineBinsEngine.throwParseError(nameT.pos + nameT.len, sprintf([ ...
            'let %s needs an ''='' next, I''m afraid, followed by what %s should stand ' ...
            'for -- for example, let %s = 112, or let %s = next(118) within (200,1200] ms.'], ...
            name, name, name, name));
    end
    rest = rest(2:end);
    if isempty(rest)
        DefineBinsEngine.throwParseError(-1, sprintf([ ...
            'let %s = ... needs something after the ''='', I''m afraid -- a code, a code ' ...
            'set, a relation, or any combination of these with not/and/or, for example ' ...
            'let %s = {112 122} or let %s = next(118) within (200,1200] ms.'], ...
            name, name, name));
    end
    [node, k] = DefineBinsEngine.parseExprTokens(rest, aliases);
    if k <= numel(rest)
        DefineBinsEngine.throwParseError(rest(k).pos, sprintf([ ...
            'let %s: I followed everything up to here as one expression, but there ' ...
            'is a little more text after it that I could not quite fit in -- perhaps a ' ...
            'stray character, or two expressions that need ''and''/''or'' between them.'], name));
    end
end
