function block = anovaSection(windowLabel, measureType, binLabels)
%ANOVASECTION  Three or more ordinary bins: a linear mixed model (subject
%   random intercept AND slope for bin -- the "maximal" structure
%   justified by the design, Barr et al., 2013 -- falling back to a
%   random-intercept-only model if that does not converge to a non-
%   singular fit), replacing the repeated-measures ANOVA this section
%   used to run. Chosen specifically because RM-ANOVA (and this section's
%   own former complete-cases-only filtering) require every subject to
%   have every bin, dropping anyone missing even one -- an LMM fits
%   directly on every non-missing (subject, bin) observation instead, so
%   a subject missing one bin still contributes their other bins rather
%   than being excluded from the channel entirely. Reports the omnibus
%   fixed-effect F-test (Satterthwaite df, via lmerTest), marginal R^2
%   (variance explained by bin alone, via performance::r2_nakagawa),
%   standardized fixed-effect coefficients (effectsize::
%   standardize_parameters), and Holm-corrected model-based pairwise
%   contrasts (emmeans -- also missing-data-tolerant, unlike a plain
%   paired *t*-test over raw differences), plus a Friedman test as a
%   rank-based robustness check -- run on the (usually smaller) complete-
%   cases-only subset, since a rank test over a subject x bin table has
%   no missing-data-tolerant form the way the LMM above does.
    binVectorR = strjoin(cellfun(@(b) ['"' ReportSections.rLit(b) '"'], binLabels, 'UniformOutput', false), ', ');
    binListMd = strjoin(cellfun(@(b) ReportSections.mdLit(b), binLabels, 'UniformOutput', false), ', ');
    lines = { ...
        '## __WINDOW_MD__ -- __MEASURETYPE_MD__' ...
        '' ...
        ['__NBINS__ conditions: ' binListMd '.'] ...
        '' ...
        '```{r}' ...
        '#| label: __CHUNKLABEL__' ...
        '#| results: asis' ...
        'grp <- dat %>% filter(measure_type == "__MEASURETYPE_R__", window == "__WINDOW_R__",' ...
        ['                       bin %in% c(' binVectorR ')) %>% droplevels()'] ...
        '__BLOCKMATCHDIAGNOSTIC__' ...
        '' ...
        'for (ch in unique(grp$channel)) {' ...
        '  # The whole per-channel body is one tryCatch: an unanticipated' ...
        '  # error on ONE channel would otherwise abort this entire chunk --' ...
        '  # and, since Quarto halts the whole render on any chunk error,' ...
        '  # every section after it too -- rather than just costing this one' ...
        '  # channel''s own results.' ...
        '  tryCatch({' ...
        '  d <- grp %>% filter(channel == ch, !is.na(value)) %>% droplevels()' ...
        '  if (n_distinct(d$dataset) < 2) {' ...
        '    cat(sprintf("\n\n### %s\n\n*Skipped: fewer than two subjects have a usable value for this channel.*\n\n", ch))' ...
        '    next' ...
        '  }' ...
        '  tag <- str_replace_all(paste("__WINDOW_R__", "__MEASURETYPE_R__", ch, sep = "_"), "[^A-Za-z0-9]+", "_")' ...
        '' ...
        '  cat(sprintf("\n\n### %s\n\n", ch))' ...
        '  descr <- d %>% group_by(bin) %>% summarise(M = mean(value), SD = sd(value), n = n(), .groups = "drop")' ...
        '  cat(as_raw_html(apa_gt(descr, "Descriptive Statistics")))' ...
        '' ...
        '  n_bins_expected <- n_distinct(d$bin)' ...
        '  complete_subjects <- d %>% count(dataset) %>% filter(n == n_bins_expected) %>% pull(dataset)' ...
        '  cat(sprintf("\n%d subject(s) contributed at least one usable value here; %d had all %d conditions present.\n\n",' ...
        '              n_distinct(d$dataset), length(complete_subjects), n_bins_expected))' ...
        '' ...
        '  m <- tryCatch(lmerTest::lmer(value ~ bin + (1 + bin | dataset), data = d,' ...
        '                               control = lme4::lmerControl(optimizer = "bobyqa")), error = function(e) NULL)' ...
        '  used_maximal <- !is.null(m) && !lme4::isSingular(m)' ...
        '  if (is.null(m) || lme4::isSingular(m)) {' ...
        '    m <- tryCatch(lmerTest::lmer(value ~ bin + (1 | dataset), data = d,' ...
        '                                 control = lme4::lmerControl(optimizer = "bobyqa")), error = function(e) NULL)' ...
        '  }' ...
        '' ...
        '  p_bin <- NA_real_' ...
        '  r2m <- NA_real_' ...
        '  eta_bin <- NULL' ...
        '  if (is.null(m)) {' ...
        '    cat("\n*The linear mixed model did not fit for this channel.*\n\n")' ...
        '  } else {' ...
        '    if (!used_maximal) {' ...
        '      cat("\n*The maximal model (a random intercept AND slope per subject) did not converge to a\n")' ...
        '      cat("non-singular fit -- likely too few subjects/observations for that many random parameters --\n")' ...
        '      cat("so a random-intercept-only model was used instead.*\n\n")' ...
        '    }' ...
        '    aov_tab <- as.data.frame(anova(m))' ...
        '    if ("bin" %in% rownames(aov_tab)) {' ...
        '      binRow <- aov_tab["bin", ]' ...
        '      p_bin <- binRow[["Pr(>F)"]]' ...
        '      sig_txt <- if (p_bin < .05) "a significant" else "no significant"' ...
        '      cat(sprintf("\nA linear mixed model (subject random intercept%s, bin as a fixed effect) revealed %s\n",' ...
        '                  if (used_maximal) " and slope" else "", sig_txt))' ...
        '      cat(sprintf("effect of bin, *F*(%s, %s) = %s, *p* %s.\n",' ...
        '                  apa_num(binRow[["NumDF"]], 1), apa_num(binRow[["DenDF"]], 1), apa_num(binRow[["F value"]]), apa_p(p_bin)))' ...
        '      # Partial eta-squared, converted from the F-test above, not the' ...
        '      # marginal R^2 below -- unlike R^2 (a single whole-model number, so a' ...
        '      # forest plot of it is one point with no spread to show for a design' ...
        '      # with only one within-subjects factor), eta-squared carries an actual' ...
        '      # confidence interval (Steiger, 2004, via the noncentral F), so it is' ...
        '      # what feeds the cross-report forest plot below -- something with a' ...
        '      # real interval to plot, not just a lone dot.' ...
        '      eta_bin <- tryCatch(effectsize::F_to_eta2(binRow[["F value"]], binRow[["NumDF"]], binRow[["DenDF"]], ci = 0.95),' ...
        '                          error = function(e) NULL)' ...
        '      if (!is.null(eta_bin)) {' ...
        '        cat(sprintf(" Partial eta-squared = %s, 95%% CI [%s, %s].\n\n",' ...
        '                    apa_num(eta_bin$Eta2_partial, 3), apa_num(eta_bin$CI_low, 3), apa_num(eta_bin$CI_high, 3)))' ...
        '      } else {' ...
        '        cat("\n\n")' ...
        '      }' ...
        '    }' ...
        '    r2_tab <- tryCatch({ invisible(utils::capture.output(res <- performance::r2_nakagawa(m))); res }, error = function(e) NULL)' ...
        '    if (!is.null(r2_tab)) {' ...
        '      r2m <- as.numeric(r2_tab$R2_marginal)' ...
        '      cat(sprintf("Marginal *R*<sup>2</sup> (variance explained by bin alone) = %s.\n\n", apa_num(r2m, 3)))' ...
        '    }' ...
        '    std_params <- tryCatch(as.data.frame(effectsize::standardize_parameters(m, method = "basic")),' ...
        '                           error = function(e) NULL)' ...
        '    if (!is.null(std_params)) {' ...
        '      cat(as_raw_html(apa_gt(std_params, "Standardized Fixed-Effect Coefficients")))' ...
        '    }' ...
        '    cat(as_raw_html(apa_gt(aov_tab, "Linear Mixed Model: Fixed-Effect Test (Satterthwaite df)")))' ...
        '' ...
        '    emm <- tryCatch(emmeans::emmeans(m, pairwise ~ bin, adjust = "holm"), error = function(e) NULL)' ...
        '    if (!is.null(emm)) {' ...
        '      pw <- as.data.frame(emm$contrasts)' ...
        '      sig_pw <- pw %>% filter(p.value < .05)' ...
        '      if (nrow(sig_pw) > 0) {' ...
        '        pair_txt <- sprintf("%s, *p* %s", sig_pw$contrast, apa_p(sig_pw$p.value))' ...
        '        cat(sprintf("\nHolm-corrected model-based pairwise comparisons showed significant differences for: %s.\n\n",' ...
        '                    paste(pair_txt, collapse = "; ")))' ...
        '      } else {' ...
        '        cat("\nNo pairwise comparison survived Holm correction.\n\n")' ...
        '      }' ...
        '      cat(as_raw_html(apa_gt(pw, "Pairwise Comparisons (Holm-Corrected, Model-Based)")))' ...
        '    }' ...
        '  }' ...
        '' ...
        '  if (length(complete_subjects) >= 2) {' ...
        '    d_complete <- d %>% filter(dataset %in% complete_subjects) %>% droplevels()' ...
        '    fr <- tryCatch(friedman_test(data = d_complete, value ~ bin | dataset), error = function(e) NULL)' ...
        '    if (!is.null(fr)) {' ...
        '      sig_txt <- if (fr$p < .05) "was significant" else "was not significant"' ...
        '      cat(sprintf("\nA Friedman test, run on the %d subject(s) with complete data as a rank-based\n", length(complete_subjects)))' ...
        '      cat(sprintf("robustness check, %s, chi-squared(%s) = %s, *p* %s.\n\n", sig_txt, fr$df, apa_num(fr$statistic), apa_p(fr$p)))' ...
        '    }' ...
        '  }' ...
        '' ...
        '  eta_est <- if (is.null(eta_bin)) NA_real_ else eta_bin$Eta2_partial' ...
        '  eta_lo  <- if (is.null(eta_bin)) NA_real_ else eta_bin$CI_low' ...
        '  eta_hi  <- if (is.null(eta_bin)) NA_real_ else eta_bin$CI_high' ...
        '  omnibus <- bind_rows(omnibus, tibble(group = tag, design = "lmm_within", test = "omnibus", p = p_bin,' ...
        '                                        estimate = eta_est, conf.low = eta_lo, conf.high = eta_hi))' ...
        '' ...
        '  common_layers <- list(' ...
        '    geom_line(aes(group = dataset), colour = "grey75", alpha = 0.5),' ...
        '    geom_point(colour = "grey40", size = 1.4, alpha = 0.5, position = position_jitter(width = 0.04, height = 0)),' ...
        '    stat_summary(fun = mean, geom = "point", size = 2.2, colour = "#4a7fc9"),' ...
        '    stat_summary(fun.data = mean_se, geom = "errorbar", width = 0.12, colour = "#4a7fc9"),' ...
        '    labs(x = "Bin", y = "__YLABEL__"),' ...
        '    theme_pubr()' ...
        '  )' ...
        '  p <- ggplot(d, aes(bin, value)) + violin_layers("#4a7fc9") + common_layers' ...
        '  print(p)' ...
        '  }, error = function(e) {' ...
        '    cat(sprintf("\n\n### %s\n\n*Could not be analysed: %s*\n\n", ch, conditionMessage(e)))' ...
        '  })' ...
        '}' ...
        '```' ...
        };
    text = strjoin(lines, newline);
    text = strrep(text, '__NBINS__', num2str(numel(binLabels)));
    text = strrep(text, '__CHUNKLABEL__', ReportSections.chunkLabel('anova', windowLabel, measureType));
    text = strrep(text, '__YLABEL__', ReportSections.yAxisLabel(measureType));
    text = strrep(text, '__BLOCKMATCHDIAGNOSTIC__', ReportSections.blockMatchDiagnosticText());
    block = ReportSections.fillCommonTokens(text, windowLabel, measureType, '', '');
end

