function block = betweenSection(windowLabel, measureType, binLabel)
%BETWEENSECTION  Exactly one ordinary bin, but a between-subjects group is
%   assigned (see WorkSpace.editSubjects/distinctGroups) -- so, unlike
%   descriptiveSection's own single-bin, no-comparison-possible case,
%   there IS a comparison here: independent-samples across groups.
%   n_distinct(d$group) is checked PER CHANNEL at R runtime, not decided
%   once in MATLAB (unlike ordinaryLabels/comboBins), since it can
%   legitimately vary channel to channel once NA values are dropped -- an
%   independent-samples *t*-test (2 groups) or a one-way ANOVA + Tukey
%   post-hoc (3+ groups), mirroring pairedSection/lmmSection's own
%   split for the WITHIN-subjects case one bin count up.
    lines = [{ ...
        '## __WINDOW_MD__ -- __MEASURETYPE_MD__ (Between Subjects)' ...
        '' ...
        'Single condition ("__BIN1_MD__"), compared BETWEEN the between-subjects groups.' ...
        '' ...
        '```{r}' ...
        '#| label: __CHUNKLABEL__' ...
        '#| results: asis' ...
        'grp <- dat %>% filter(measure_type == "__MEASURETYPE_R__", window == "__WINDOW_R__", bin == "__BIN1_R__") %>% droplevels()' ...
        '__BLOCKMATCHDIAGNOSTIC__' ...
        '' ...
        }, ReportSections.channelLoop('open'), { ...
        '  d <- grp %>% filter(channel == ch, !is.na(value)) %>% droplevels()' ...
        '  n_groups <- n_distinct(d$group)' ...
        '  if (n_groups < 2 || nrow(d) < 2) {' ...
        '    cat(sprintf("\n\n### %s\n\n*Skipped: fewer than two groups have a usable value for this channel.*\n\n", ch))' ...
        '    next' ...
        '  }' ...
        '  tag <- str_replace_all(paste("__WINDOW_R__", "__MEASURETYPE_R__", ch, sep = "_"), "[^A-Za-z0-9]+", "_")' ...
        '' ...
        '  cat(sprintf("\n\n### %s\n\n", ch))' ...
        '  descr <- d %>% group_by(group) %>% summarise(M = mean(value), SD = sd(value), n = n(), .groups = "drop")' ...
        '  cat(as_raw_html(apa_gt(descr, "Descriptive Statistics")))' ...
        '' ...
        '  if (n_groups == 2) {' ...
        '    tt <- t.test(value ~ group, data = d)' ...
        '    dcohen <- d %>% rstatix::cohens_d(value ~ group, ci = TRUE, ci.type = "bca", nboot = 200)' ...
        '    wt <- wilcox.test(value ~ group, data = d)' ...
        '    bf <- tryCatch(as.vector(BayesFactor::ttestBF(formula = value ~ group, data = as.data.frame(d))),' ...
        '                   error = function(e) NA_real_)' ...
        '' ...
        '    sig_txt <- if (tt$p.value < .05) "a significant" else "no significant"' ...
        '    cat(sprintf("\nA Welch two-sample *t*-test (unequal variances assumed) found %s difference\n", sig_txt))' ...
        '    cat(sprintf("between groups, *t*(%s) = %s, *p* %s, Cohen''s *d* = %s (%s), 95%% CI [%s, %s].\n",' ...
        '                apa_num(tt$parameter, 1), apa_num(tt$statistic), apa_p(tt$p.value), apa_num(dcohen$effsize), dcohen$magnitude,' ...
        '                apa_num(dcohen$conf.low), apa_num(dcohen$conf.high)))' ...
        '    cat(sprintf("A Mann-Whitney *U* test, run as a robustness check alongside it, gave *W* = %s, *p* %s;\n",' ...
        '                apa_num(wt$statistic), apa_p(wt$p.value)))' ...
        '    cat(sprintf("a Bayesian independent-samples *t*-test gave BF~10~ = %s.\n\n", apa_bf(bf)))' ...
        '' ...
        '    omnibus <- bind_rows(omnibus, tibble(group = tag, design = "indep_t", test = "welch_t_test", p = tt$p.value,' ...
        '                                          estimate = dcohen$effsize, conf.low = dcohen$conf.low, conf.high = dcohen$conf.high))' ...
        '  } else {' ...
        '    # Welch''s one-way ANOVA, not the classic (Fisher) one -- it does not' ...
        '    # assume equal variances across groups, which is routinely violated' ...
        '    # and rarely checked; matches the 2-group branch above already using' ...
        '    # Welch''s t-test rather than Student''s for the same reason (Delacre' ...
        '    # et al., 2019). Games-Howell is its matching post-hoc, for the same' ...
        '    # reason Tukey (which assumes equal variances/group sizes) is not used.' ...
        '    aov <- tryCatch(welch_anova_test(data = d, formula = value ~ group), error = function(e) NULL)' ...
        '    p_grp <- NA_real_' ...
        '    if (!is.null(aov)) {' ...
        '      p_grp <- aov$p[1]' ...
        '      sig_txt <- if (p_grp < .05) "a significant" else "no significant"' ...
        '      cat(sprintf("\nA Welch one-way ANOVA (unequal variances assumed) revealed %s effect of group,\n", sig_txt))' ...
        '      cat(sprintf("*F*(%s, %s) = %s, *p* %s.\n\n",' ...
        '                  apa_num(aov$DFn[1], 1), apa_num(aov$DFd[1], 1), apa_num(aov$statistic[1]), apa_p(p_grp)))' ...
        '      cat(as_raw_html(apa_gt(as.data.frame(aov), "Welch One-Way ANOVA")))' ...
        '    }' ...
        '' ...
        '    pw <- d %>% games_howell_test(value ~ group)' ...
        '    sig_pw <- pw %>% filter(p.adj < .05)' ...
        '    if (nrow(sig_pw) > 0) {' ...
        '      pair_txt <- sprintf("%s vs. %s, *p* %s, *M*~diff~ = %s, 95%% CI [%s, %s]",' ...
        '                          sig_pw$group1, sig_pw$group2, apa_p(sig_pw$p.adj),' ...
        '                          apa_num(sig_pw$estimate), apa_num(sig_pw$conf.low), apa_num(sig_pw$conf.high))' ...
        '      cat(sprintf("\nGames-Howell pairwise comparisons showed significant differences between: %s.\n\n",' ...
        '                  paste(pair_txt, collapse = "; ")))' ...
        '    } else {' ...
        '      cat("\nNo pairwise comparison survived the Games-Howell correction.\n\n")' ...
        '    }' ...
        '    cat(as_raw_html(apa_gt(pw, "Pairwise Comparisons (Games-Howell)")))' ...
        '' ...
        '    omnibus <- bind_rows(omnibus, tibble(group = tag, design = "welch_anova", test = "omnibus", p = p_grp,' ...
        '                                          estimate = NA_real_, conf.low = NA_real_, conf.high = NA_real_))' ...
        '  }' ...
        '' ...
        '  common_layers <- list(' ...
        '    geom_jitter(width = 0.06, alpha = 0.6),' ...
        '    stat_summary(fun = mean, geom = "point", size = 3),' ...
        '    stat_summary(fun.data = mean_se, geom = "errorbar", width = 0.1),' ...
        '    labs(x = "Group", y = "__YLABEL__"),' ...
        '    scale_colour_brewer(palette = "Set2"),' ...
        '    scale_fill_brewer(palette = "Set2"),' ...
        '    theme_pubr(),' ...
        '    theme(legend.position = "none")' ...
        '  )' ...
        '  p <- ggplot(d, aes(group, value, colour = group, fill = group)) + violin_layers() + common_layers' ...
        '  print(p)' ...
        }, ReportSections.channelLoop('close'), { ...
        '```' ...
        }];
    text = strjoin(lines, newline);
    text = strrep(text, '__CHUNKLABEL__', ReportSections.chunkLabel('between', windowLabel, measureType));
    text = strrep(text, '__YLABEL__', ReportSections.yAxisLabel(measureType));
    text = strrep(text, '__BLOCKMATCHDIAGNOSTIC__', ReportSections.blockMatchDiagnosticText());
    block = ReportSections.fillCommonTokens(text, windowLabel, measureType, binLabel, '');
end

