function lines = betweenGroupsLines(includeBetweenGroups)
%BETWEENGROUPSLINES  The actually-new comparison comboSectionGrouped adds:
%   an independent-samples test of the combo score BETWEEN groups --
%   spliced in when INCLUDEBETWEENGROUPS, {} (no-op) otherwise. Mirrors
%   betweenSection's own 2-group-t-test/3+-group-one-way-ANOVA split,
%   just on a combination bin's already-differenced score instead of an
%   ordinary bin's raw one.
    if ~includeBetweenGroups
        lines = {};
        return;
    end
    lines = { ...
        '' ...
        '  n_groups <- n_distinct(d$group)' ...
        '  if (n_groups < 2) {' ...
        '    cat("\n*Only one group has a usable value for this channel; the between-group comparison could not be run.*\n\n")' ...
        '  } else if (n_groups == 2) {' ...
        '    tt <- t.test(value ~ group, data = d)' ...
        '    dcohen <- d %>% rstatix::cohens_d(value ~ group, ci = TRUE, ci.type = "bca", nboot = 200)' ...
        '    bf <- tryCatch(as.vector(BayesFactor::ttestBF(formula = value ~ group, data = as.data.frame(d))),' ...
        '                   error = function(e) NA_real_)' ...
        '    sig_txt <- if (tt$p.value < .05) "a significant" else "no significant"' ...
        '    cat(sprintf("\nA Welch two-sample *t*-test found %s difference in __COMBOLABEL_MD__ between groups,\n", sig_txt))' ...
        '    cat(sprintf("*t*(%s) = %s, *p* %s, Cohen''s *d* = %s (%s), 95%% CI [%s, %s], BF~10~ = %s.\n\n",' ...
        '                apa_num(tt$parameter, 1), apa_num(tt$statistic), apa_p(tt$p.value), apa_num(dcohen$effsize), dcohen$magnitude,' ...
        '                apa_num(dcohen$conf.low), apa_num(dcohen$conf.high), apa_bf(bf)))' ...
        '' ...
        '    omnibus <- bind_rows(omnibus, tibble(group = tag, design = "between_group_combo", test = "welch_t_test", p = tt$p.value,' ...
        '                                          estimate = dcohen$effsize, conf.low = dcohen$conf.low, conf.high = dcohen$conf.high))' ...
        '  } else {' ...
        '    # Welch ANOVA + Games-Howell, not classic ANOVA + Tukey -- see' ...
        '    # betweenSection''s own comment on this same choice.' ...
        '    aov <- tryCatch(welch_anova_test(data = d, formula = value ~ group), error = function(e) NULL)' ...
        '    p_grp <- NA_real_' ...
        '    if (!is.null(aov)) {' ...
        '      p_grp <- aov$p[1]' ...
        '      sig_txt <- if (p_grp < .05) "a significant" else "no significant"' ...
        '      cat(sprintf("\nA Welch one-way ANOVA found %s difference in __COMBOLABEL_MD__ between groups, *F*(%s, %s) = %s, *p* %s.\n\n",' ...
        '                  sig_txt, apa_num(aov$DFn[1], 1), apa_num(aov$DFd[1], 1), apa_num(aov$statistic[1]), apa_p(p_grp)))' ...
        '      cat(as_raw_html(apa_gt(as.data.frame(aov), "Welch One-Way ANOVA")))' ...
        '    }' ...
        '' ...
        '    pw <- d %>% games_howell_test(value ~ group)' ...
        '    sig_pw <- pw %>% filter(p.adj < .05)' ...
        '    if (nrow(sig_pw) > 0) {' ...
        '      pair_txt <- sprintf("%s vs. %s, *p* %s, *M*~diff~ = %s, 95%% CI [%s, %s]",' ...
        '                          sig_pw$group1, sig_pw$group2, apa_p(sig_pw$p.adj),' ...
        '                          apa_num(sig_pw$estimate), apa_num(sig_pw$conf.low), apa_num(sig_pw$conf.high))' ...
        '      cat(sprintf("\nGames-Howell pairwise comparisons showed significant differences between: %s.\n\n",' ...
        '                  paste(pair_txt, collapse = "; ")))' ...
        '    } else {' ...
        '      cat("\nNo pairwise comparison survived the Games-Howell correction.\n\n")' ...
        '    }' ...
        '    cat(as_raw_html(apa_gt(pw, "Pairwise Comparisons (Games-Howell)")))' ...
        '' ...
        '    omnibus <- bind_rows(omnibus, tibble(group = tag, design = "between_group_combo", test = "welch_anova", p = p_grp,' ...
        '                                          estimate = NA_real_, conf.low = NA_real_, conf.high = NA_real_))' ...
        '  }'};
end

