function block = circularSection(windowLabel, measureType, binLabels)
%CIRCULARSECTION  Ordinary bins whose measure type is CIRCULAR (see
%   isCircularType): circular descriptive statistics, and no linear test.
%
%   WHY THIS EXISTS. A Spectral export's 'phase' and 'phaselag' are angles
%   that wrap at +/-pi, and every ordinary-bin route in this report is
%   linear: pairedSection runs a t-test, lmmSection fits lmerTest::lmer,
%   descriptiveSection summarises with mean() and sd(). None of those mean
%   anything on a circle. The arithmetic mean of 179 and -179 degrees is
%   0, which is the point exactly opposite where the data actually sit,
%   and an sd computed the same way is larger the more tightly the angles
%   cluster around the wrap.
%
%   The combination-bin branch already refused these types a linear test
%   (comboSectionDescriptiveOnly), so before this existed one report could
%   state in one section that a linear test of 'phase' was invalid and in
%   the next section report exactly such a test on the same measure.
%
%   WHAT IT REPORTS INSTEAD, and why not simply nothing. The two standard
%   first-order circular statistics need no package beyond base R:
%
%     mean angle       atan2(mean(sin(t)), mean(cos(t)))
%     resultant length R = sqrt(mean(sin(t))^2 + mean(cos(t))^2), in [0,1]
%
%   R is the concentration: 1 means every subject had the same angle, 0
%   means they are spread evenly around the circle and the mean angle is
%   meaningless. Reporting the mean angle without R would be the circular
%   equivalent of a mean without an SD, so the two always appear together.
%
%   NO TEST IS OFFERED. A Rayleigh or Watson-Williams test would be the
%   right instrument, and both are genuinely useful, but they belong in a
%   deliberate decision about which circular test this pipeline endorses
%   rather than in the fix for a routing defect. The section says so
%   rather than leaving the reader to wonder.
%
%   See also ISCIRCULARTYPE, DESCRIPTIVEONLYREASON, DESCRIPTIVESECTION.
    binLabels = cellstr(string(binLabels));

    lines = [{ ...
        '## __WINDOW_MD__ -- __MEASURETYPE_MD__' ...
        '' ...
        ['Conditions: __BINLIST_MD__. ' ...
         'This is a circular quantity (an angle that wraps at +/-pi radians), so the linear ' ...
         'comparisons used elsewhere in this report are not valid for it: the arithmetic mean ' ...
         'of two angles either side of the wrap lands opposite where the data are. ' ...
         'Circular descriptive statistics are reported instead, and no test is run.'] ...
        '' ...
        '```{r}' ...
        '#| label: __CHUNKLABEL__' ...
        '#| results: asis' ...
        'grp <- dat %>% filter(measure_type == "__MEASURETYPE_R__", window == "__WINDOW_R__") %>% droplevels()' ...
        '__BLOCKMATCHDIAGNOSTIC__' ...
        '' ...
        }, ReportSections.channelLoop('open'), { ...
        '  d <- grp %>% filter(channel == ch, !is.na(value)) %>% droplevels()' ...
        '  if (nrow(d) < 1) {' ...
        '    cat(sprintf("\n\n### %s\n\n*Skipped: no usable observations.*\n\n", ch))' ...
        '    next' ...
        '  }' ...
        '  cat(sprintf("\n\n### %s\n\n", ch))' ...
        '' ...
        '  # First-order circular statistics, in base R. mean_angle is the' ...
        '  # direction of the resultant vector; R_bar is its length, which is 1' ...
        '  # when every subject agrees and 0 when they are spread evenly, in' ...
        '  # which case the mean angle carries no information at all.' ...
        '  circ <- d %>% group_by(bin) %>% summarise(' ...
        '    mean_angle_rad = atan2(mean(sin(value)), mean(cos(value))),' ...
        '    R_bar = sqrt(mean(sin(value))^2 + mean(cos(value))^2),' ...
        '    n = n(), .groups = "drop") %>%' ...
        '    mutate(mean_angle_deg = mean_angle_rad * 180 / pi)' ...
        '  cat(as_raw_html(apa_gt(circ, "Circular Descriptive Statistics")))' ...
        '' ...
        '  # Plotted on the circle rather than on a line, for the same reason the' ...
        '  # statistics are circular: a linear axis puts -pi and +pi at opposite' ...
        '  # ends of the plot when they are the same direction.' ...
        '  p <- ggplot(d, aes(x = value, fill = bin)) +' ...
        '    geom_histogram(bins = 24, alpha = 0.7, position = "identity") +' ...
        '    coord_polar(theta = "x", start = -pi) +' ...
        '    scale_x_continuous(limits = c(-pi, pi),' ...
        '                       breaks = c(-pi, -pi/2, 0, pi/2, pi),' ...
        '                       labels = c("-180", "-90", "0", "90", "180")) +' ...
        '    labs(x = "phase (degrees)", y = "count", fill = "condition") +' ...
        '    theme_minimal()' ...
        '  print(p)' ...
        '  cat("\n\n")' ...
        ''}, ...
        ReportSections.channelLoop('close'), { ...
        '```' ...
        '' ...
        }];

    block = strjoin(lines, newline);
    % Empty bin slots: this section names every ordinary bin in one list
    % (__BINLIST__) rather than filling the one/two named slots the paired
    % and single-bin sections use, so BIN1/BIN2 are passed through empty,
    % which fillToken documents as a no-op.
    block = ReportSections.fillCommonTokens(block, windowLabel, measureType, '', '');
    block = ReportSections.fillToken(block, 'BINLIST', strjoin(binLabels, ', '));
    block = strrep(block, '__BLOCKMATCHDIAGNOSTIC__', ReportSections.blockMatchDiagnosticText());
    block = strrep(block, '__CHUNKLABEL__', ...
        ReportSections.chunkLabel('circ', windowLabel, measureType));
end
