function block = coherenceSection()
%COHERENCESECTION  The time-resolved coherence to the reference: the trace
%   that justifies a steady-state window, and the time x frequency map.
%
%   WHAT THIS ADDS THAT NOTHING ELSE SHOWED. The scalar coherence a tagging
%   analysis tests is one number per subject, condition and channel, taken
%   over a steady-state window the analyst chose. Nothing in the report
%   showed where that window came from, or whether the tagged response was
%   present outside it, because the CoherenceMap result could be looked at
%   in the application and nowhere else.
%
%   THE TRACE IS THE MORE USEFUL OF THE TWO, and it is drawn first. Rise,
%   plateau and fall are visible on it directly, so a window that starts
%   inside the fade-in or ends after the response has gone is obvious
%   rather than a thing to be taken on trust. It covers every channel,
%   since it costs almost nothing to write (see exportCoherenceCSVs).
%
%   THE MAP ANSWERS THE OTHER QUESTION: whether the response sits at the
%   tagged frequency alone or smears across neighbours, which is what
%   separates a tag from broadband noise that happens to peak nearby. It is
%   written for a few channels only, and the section says which and why:
%   the whole plane for every channel is about 37 MB a subject.
%
%   NO TEST IS RUN HERE, deliberately. The inference in a tagging design is
%   on the scalar coherence, which the sections above already handle. A
%   test over the time x frequency plane needs a cluster-based permutation
%   over that plane, which is a different mechanism from anything in this
%   report, and offering an uncorrected one per cell would be worse than
%   offering none.
%
%   See also EXPORTCOHERENCECSVS, SPECTRUMSECTION, COHERENCEMAP.
    lines = { ...
        '## Coherence over time' ...
        '' ...
        ['Coherence between each channel and the reference at the tagged frequency, ' ...
         'against time. The tagged frequency is read from the exported map itself, as ' ...
         'the frequency carrying most coherence in each condition, so it cannot differ ' ...
         'from the data drawn beside it.'] ...
        '' ...
        '```{r}' ...
        '#| label: coherence-trace' ...
        '#| results: asis' ...
        '#| fig-height: 4' ...
        'if (!exists("cohtrace") || is.null(cohtrace) || nrow(cohtrace) == 0) {' ...
        '  cat("\n*No coherence export accompanied this file, so the time course cannot be shown.*\n\n")' ...
        '} else {' ...
        '  # Averaged over subjects per channel, bin and time. Individual' ...
        '  # subjects are not drawn: with more than a handful the panel becomes' ...
        '  # unreadable, and the question here is the shape of the response, not' ...
        '  # how one person differed.' ...
        '  tr <- cohtrace %>%' ...
        '    group_by(bin, channel, time_ms, tag_hz) %>%' ...
        '    summarise(coherence = mean(coherence, na.rm = TRUE),' ...
        '              n = n(), .groups = "drop")' ...
        '' ...
        '  # The strongest channels are drawn over the rest rather than instead' ...
        '  # of them: the faint lines are what show that the response is where it' ...
        '  # should be and absent where it should not.' ...
        '  best <- tr %>% group_by(channel) %>%' ...
        '    summarise(peak = max(coherence, na.rm = TRUE), .groups = "drop") %>%' ...
        '    arrange(desc(peak)) %>% head(4) %>% pull(channel)' ...
        '' ...
        '  p <- ggplot(tr, aes(time_ms, coherence, group = channel)) +' ...
        '    geom_line(colour = "grey80", linewidth = 0.3) +' ...
        '    geom_line(data = tr %>% filter(channel %in% best),' ...
        '              aes(colour = channel), linewidth = 0.8) +' ...
        '    facet_wrap(~ bin) +' ...
        '    labs(x = "Time (ms)", y = "Coherence to reference", colour = "channel") +' ...
        '    theme_pubr()' ...
        '  print(p)' ...
        '' ...
        '  tags <- tr %>% group_by(bin) %>% summarise(f = first(tag_hz), .groups = "drop")' ...
        '  cat(sprintf("\n\nTagged frequency per condition: %s.\n\n",' ...
        '      paste(sprintf("%s at %.2f Hz", tags$bin, tags$f), collapse = "; ")))' ...
        '  cat(sprintf("Averaged over %d recording(s). The grey lines are the remaining channels.\n\n",' ...
        '      max(tr$n, na.rm = TRUE)))' ...
        '}' ...
        '```' ...
        '' ...
        ['Read the window an analysis measures over against this figure. A window ' ...
         'that begins inside the rise, or ends after the response has decayed, ' ...
         'includes samples in which the tag was not being tracked, which lowers the ' ...
         'measured coherence for reasons that have nothing to do with the condition.'] ...
        '' ...
        '## Coherence over time and frequency' ...
        '' ...
        ['The full plane for the channels with the strongest response. Written for a ' ...
         'few channels rather than all of them: the whole plane for a 64-channel ' ...
         'montage is around 37 MB per recording, and a tagging figure shows a handful ' ...
         'of channels in any case. Which channels were chosen is a display decision ' ...
         'taken after seeing the data, which is safe here because nothing in this ' ...
         'section is tested.'] ...
        '' ...
        '```{r}' ...
        '#| label: coherence-map' ...
        '#| results: asis' ...
        '#| fig-height: 6' ...
        'if (!exists("cohmap") || is.null(cohmap) || nrow(cohmap) == 0) {' ...
        '  cat("\n*No coherence map accompanied this file.*\n\n")' ...
        '} else {' ...
        '  mp <- cohmap %>%' ...
        '    group_by(bin, channel, time_ms, frequency_hz) %>%' ...
        '    summarise(coherence = mean(coherence, na.rm = TRUE), .groups = "drop")' ...
        '' ...
        '  p <- ggplot(mp, aes(time_ms, frequency_hz, fill = coherence)) +' ...
        '    geom_raster(interpolate = TRUE) +' ...
        '    facet_grid(channel ~ bin) +' ...
        '    scale_fill_viridis_c(option = "magma", name = "coherence") +' ...
        '    labs(x = "Time (ms)", y = "Frequency (Hz)") +' ...
        '    theme_minimal(base_size = 9)' ...
        '  print(p)' ...
        '' ...
        '  cat(sprintf("\n\nChannels shown: %s.\n\n",' ...
        '      paste(sort(unique(mp$channel)), collapse = ", ")))' ...
        '}' ...
        '```' ...
        '' ...
        ['A tagged response should be confined to its own frequency row. Coherence ' ...
         'spread across neighbouring frequencies indicates broadband activity rather ' ...
         'than tracking of the flicker, and coherence present before the stimulus ' ...
         'indicates a reference channel picking up something other than the display.'] ...
        '' ''};

    block = strjoin(lines, newline);
end
