function block = comboSectionDescriptiveOnly(windowLabel, measureType, comboLabel, recipeText)
%COMBOSECTIONDESCRIPTIVEONLY  A combination bin's own LATENCY or CIRCULAR
%   measure type (see isDescriptiveOnlyType): descriptive statistics and a
%   plot only, no one-sample-vs-zero test and no contribution to the
%   cross-group omnibus summary -- see descriptiveOnlyReason for why,
%   specific to which of the two categories MEASURETYPE falls into.
    lines = { ...
        '## __WINDOW_MD__ -- __MEASURETYPE_MD__: __COMBOLABEL_MD__' ...
        '' ...
        'Difference/combination bin "__COMBOLABEL_MD__" (__RECIPE_MD__). __REASON_MD__' ...
        '' ...
        '```{r}' ...
        '#| label: __CHUNKLABEL__' ...
        '#| results: asis' ...
        'grp <- dat %>% filter(measure_type == "__MEASURETYPE_R__", window == "__WINDOW_R__", bin == "__COMBOLABEL_R__") %>% droplevels()' ...
        '__BLOCKMATCHDIAGNOSTIC__' ...
        '' ...
        'for (ch in unique(grp$channel)) {' ...
        '  tryCatch({' ...
        '  d <- grp %>% filter(channel == ch, !is.na(value))' ...
        '  if (n_distinct(d$dataset) < 2) {' ...
        '    cat(sprintf("\n\n### %s\n\n*Skipped: only %d subject(s) have a non-missing value for this combination bin (at least 2 are needed).*\n\n",' ...
        '                ch, n_distinct(d$dataset)))' ...
        '    next' ...
        '  }' ...
        '' ...
        '  cat(sprintf("\n\n### %s\n\n", ch))' ...
        '  descr <- d %>% summarise(M = mean(value), SD = sd(value), n = n())' ...
        '  cat(sprintf("*M* = %s, *SD* = %s, *n* = %d.\n\n", apa_num(descr$M), apa_num(descr$SD), descr$n))' ...
        '  cat(as_raw_html(apa_gt(descr, "Descriptive Statistics")))' ...
        '' ...
        '  common_layers <- list(' ...
        '    geom_jitter(width = 0.05, colour = "grey40", alpha = 0.6),' ...
        '    stat_summary(fun = mean, geom = "point", size = 3, colour = "#4a7fc9"),' ...
        '    stat_summary(fun.data = mean_se, geom = "errorbar", width = 0.1, colour = "#4a7fc9"),' ...
        '    labs(x = NULL, y = "__YLABEL__"),' ...
        '    scale_x_continuous(breaks = NULL),' ...
        '    theme_pubr()' ...
        '  )' ...
        '  p <- ggplot(d, aes(x = 1, y = value, group = 1)) + violin_layers("#4a7fc9") + common_layers' ...
        '  print(p)' ...
        '  }, error = function(e) {' ...
        '    cat(sprintf("\n\n### %s\n\n*Could not be analysed: %s*\n\n", ch, conditionMessage(e)))' ...
        '  })' ...
        '}' ...
        '```' ...
        };
    text = strjoin(lines, newline);
    text = ReportSections.fillToken(text, 'COMBOLABEL', comboLabel);
    text = ReportSections.fillToken(text, 'RECIPE', recipeText);
    text = ReportSections.fillToken(text, 'REASON', ReportSections.descriptiveOnlyReason(measureType));
    text = strrep(text, '__CHUNKLABEL__', ReportSections.chunkLabel('combo-desc', windowLabel, measureType, comboLabel));
    text = strrep(text, '__YLABEL__', ReportSections.yAxisLabel(measureType));
    text = strrep(text, '__BLOCKMATCHDIAGNOSTIC__', ReportSections.blockMatchDiagnosticText());
    block = ReportSections.fillCommonTokens(text, windowLabel, measureType, '', '');
end

