function block = comboSectionGrouped(windowLabel, measureType, comboLabel, recipeText, includeVsZero, includeBetweenGroups)
%COMBOSECTIONGROUPED  One combination (difference) bin, WITH a between-
%   subjects group assigned -- the grouped counterpart of comboSection/
%   comboSectionDescriptiveOnly, answering "does patients_group vs.
%   controls_group have a different DIFFERENCE (e.g. priming effect,
%   repetition effect) score", not just "is there a difference at all".
%
%   INCLUDEVSZERO (false for a latency/circular MEASURETYPE, see
%   isDescriptiveOnlyType) controls whether a one-sample-vs-zero test
%   still runs, now once PER GROUP rather than once for the whole sample
%   -- "does this effect exist at all" becomes a per-group question once
%   groups exist, same statistical-validity reasoning as the ungrouped
%   comboSection, just repeated per group.
%
%   INCLUDEBETWEENGROUPS (false only for a CIRCULAR MEASURETYPE, see
%   isCircularType) controls the actually-new comparison this function
%   adds: an independent-samples test of the combo score BETWEEN groups
%   (Welch *t*-test for 2 groups, one-way ANOVA + Tukey for 3+) -- valid
%   for a latency combo bin even though the "vs zero" test above is not
%   (a latency has no natural zero to test AGAINST, but is still an
%   ordinary linear quantity groups can be compared on), invalid only for
%   a circular quantity (phase/phaselag), for which no linear comparison
%   at all -- one-sample or between-groups -- is valid.
    lines = [{ ...
        '## __WINDOW_MD__ -- __MEASURETYPE_MD__: __COMBOLABEL_MD__ (By Group)' ...
        '' ...
        ['Difference/combination bin "__COMBOLABEL_MD__" (__RECIPE_MD__), broken down by the ' ...
         'between-subjects group. __REASON_MD__'] ...
        '' ...
        '```{r}' ...
        '#| label: __CHUNKLABEL__' ...
        '#| results: asis' ...
        'grp <- dat %>% filter(measure_type == "__MEASURETYPE_R__", window == "__WINDOW_R__", bin == "__COMBOLABEL_R__") %>% droplevels()' ...
        '__BLOCKMATCHDIAGNOSTIC__' ...
        '' ...
        }, ReportSections.channelLoop('open'), { ...
        '  d <- grp %>% filter(channel == ch, !is.na(value)) %>% droplevels()' ...
        '  if (n_distinct(d$dataset) < 2) {' ...
        '    cat(sprintf("\n\n### %s\n\n*Skipped: only %d subject(s) have a non-missing value for this combination bin (at least 2 are needed).*\n\n",' ...
        '                ch, n_distinct(d$dataset)))' ...
        '    next' ...
        '  }' ...
        '  tag <- str_replace_all(paste("__WINDOW_R__", "__MEASURETYPE_R__", "__COMBOLABEL_R__", ch, sep = "_"), "[^A-Za-z0-9]+", "_")' ...
        '' ...
        '  cat(sprintf("\n\n### %s\n\n", ch))' ...
        '  descr <- d %>% group_by(group) %>% summarise(M = mean(value), SD = sd(value), n = n(), .groups = "drop")' ...
        '  cat(as_raw_html(apa_gt(descr, "Descriptive Statistics")))'}, ...
        ReportSections.vsZeroLines(includeVsZero), ...
        ReportSections.betweenGroupsLines(includeBetweenGroups), ...
        { ...
        '' ...
        ReportSections.zeroLineStatement(includeVsZero) ...
        '  common_layers <- list(' ...
        '    geom_jitter(width = 0.06, alpha = 0.6),' ...
        '    zero_line,' ...
        '    stat_summary(fun = mean, geom = "point", size = 3),' ...
        '    stat_summary(fun.data = mean_se, geom = "errorbar", width = 0.1),' ...
        '    labs(x = "Group", y = "__YLABEL__"),' ...
        '    scale_colour_brewer(palette = "Set2"),' ...
        '    scale_fill_brewer(palette = "Set2"),' ...
        '    theme_pubr(),' ...
        '    theme(legend.position = "none")' ...
        '  )' ...
        '  p <- ggplot(d, aes(group, value, colour = group, fill = group)) + violin_layers() + common_layers' ...
        '  print(p)' ...
        }, ReportSections.channelLoop('close'), { ...
        '```' ...
        }];
    text = strjoin(lines, newline);
    text = ReportSections.fillToken(text, 'COMBOLABEL', comboLabel);
    text = ReportSections.fillToken(text, 'RECIPE', recipeText);
    text = ReportSections.fillToken(text, 'REASON', ReportSections.comboGroupedReason(includeVsZero, includeBetweenGroups));
    text = strrep(text, '__CHUNKLABEL__', ReportSections.chunkLabel('combo-grouped', windowLabel, measureType, comboLabel));
    text = strrep(text, '__YLABEL__', ReportSections.yAxisLabel(measureType));
    text = strrep(text, '__BLOCKMATCHDIAGNOSTIC__', ReportSections.blockMatchDiagnosticText());
    block = ReportSections.fillCommonTokens(text, windowLabel, measureType, '', '');
end

