function block = descriptiveSection(windowLabel, measureType, binLabel)
%DESCRIPTIVESECTION  Exactly one ordinary bin: nothing to compare, so just
%   a per-channel descriptive-statistics table and a one-sample plot.
    lines = [{ ...
        '## __WINDOW_MD__ -- __MEASURETYPE_MD__' ...
        '' ...
        'Single condition ("__BIN1_MD__"); descriptive statistics only, no comparison possible.' ...
        '' ...
        '```{r}' ...
        '#| label: __CHUNKLABEL__' ...
        '#| results: asis' ...
        'grp <- dat %>% filter(measure_type == "__MEASURETYPE_R__", window == "__WINDOW_R__", bin == "__BIN1_R__")' ...
        '__BLOCKMATCHDIAGNOSTIC__' ...
        '' ...
        }, ReportSections.channelLoop('open'), { ...
        '  d <- grp %>% filter(channel == ch, !is.na(value)) %>% droplevels()' ...
        '  if (nrow(d) == 0) next' ...
        '  tag <- str_replace_all(paste("__WINDOW_R__", "__MEASURETYPE_R__", ch, sep = "_"), "[^A-Za-z0-9]+", "_")' ...
        '' ...
        '  cat(sprintf("\n\n### %s\n\n", ch))' ...
        '  descr <- d %>% summarise(M = mean(value), SD = sd(value), n = n())' ...
        '  cat(sprintf("*M* = %s, *SD* = %s, *n* = %d.\n\n", apa_num(descr$M), apa_num(descr$SD), descr$n))' ...
        '  cat(as_raw_html(apa_gt(descr, "Descriptive Statistics")))' ...
        '' ...
        '  common_layers <- list(' ...
        '    geom_jitter(width = 0.05, colour = "grey40", alpha = 0.6),' ...
        '    stat_summary(fun = mean, geom = "point", size = 3, colour = "#4a7fc9"),' ...
        '    stat_summary(fun.data = mean_se, geom = "errorbar", width = 0.1, colour = "#4a7fc9"),' ...
        '    labs(x = NULL, y = "__YLABEL__"),' ...
        '    scale_x_continuous(breaks = NULL),' ...
        '    theme_pubr()' ...
        '  )' ...
        '  p <- ggplot(d, aes(x = 1, y = value, group = 1)) + violin_layers("#4a7fc9") + common_layers' ...
        '  print(p)' ...
        }, ReportSections.channelLoop('close'), { ...
        '```' ...
        }];
    text = strjoin(lines, newline);
    text = strrep(text, '__CHUNKLABEL__', ReportSections.chunkLabel('desc', windowLabel, measureType));
    text = strrep(text, '__YLABEL__', ReportSections.yAxisLabel(measureType));
    text = strrep(text, '__BLOCKMATCHDIAGNOSTIC__', ReportSections.blockMatchDiagnosticText());
    block = ReportSections.fillCommonTokens(text, windowLabel, measureType, binLabel, '');
end

