function block = lmmSection(windowLabel, measureType, binLabels, plan)
%LMMSECTION  The linear mixed model section, for every design that gets one.
%   Replaces anovaSection, mixedSection and sessionSection, which were three
%   copies of one section: 75 identical contiguous lines between the last
%   two, 48 and 46 between the other pairs. Everything that actually varied
%   is derived from PLAN (see reportDesignPlan) in presentation() below.
%
%   The four designs it covers, by what PLAN says the factors are:
%
%     bin                      the within-subjects LMM ("anova-" chunks)
%     bin x group              the mixed design    ("mixed-" chunks)
%     bin x session            repeated sessions   ("session-" chunks)
%     bin x session x group    both, two-way only  ("session-" chunks)
%
%   WHY AN LMM AND NOT A REPEATED-MEASURES ANOVA. RM-ANOVA requires every
%   subject to have every bin and drops anyone missing even one; an LMM
%   fits on every non-missing (subject, bin) observation, so a subject
%   missing one bin still contributes their other bins rather than being
%   excluded from the channel entirely. The maximal random structure a
%   design justifies is fitted first (random intercept AND slope for bin,
%   Barr et al., 2013), falling back to intercept-only if that does not
%   converge to a non-singular fit, and the report says which was used.
%
%   GROUPED BY PERSON, NOT BY RECORDING. The random effect is on person_id.
%   Where nobody has set a person, WorkSpace.personFor returns the
%   recording's own name and the two are identical; where sessions exist,
%   grouping by recording would treat one person's two visits as
%   independent subjects and understate every standard error.
%
%   NO THREE-WAY INTERACTION. With all three factors the formula is
%   (bin + session + group)^2: every main effect and every two-way
%   interaction, and nothing beyond. reportDesignPlan builds it that way and
%   this section simply prints what it was given.
%
%   POST-HOC POLICY VARIES BY DESIGN, deliberately, and is named rather
%   than implied -- see postHocLines(). The session designs are strict (at
%   most one family, and only following a significant term); the older two
%   keep the unconditional contrasts they have always run, so that merging
%   these three files changed no existing report's statistics.
%
%   See also REPORTDESIGNPLAN, PAIREDSECTION, BETWEENSECTION.
    view = presentation(plan);

    binVectorR = strjoin(cellfun(@(b) ['"' ReportSections.rLit(b) '"'], binLabels, 'UniformOutput', false), ', ');
    binListMd = strjoin(cellfun(@(b) ReportSections.mdLit(b), binLabels, 'UniformOutput', false), ', ');

    lines = [{ ...
        ['## __WINDOW_MD__ -- __MEASURETYPE_MD__' view.headingSuffix] ...
        '' ...
        ['__NBINS__ conditions: ' binListMd view.introTail] ...
        ''}, ...
        view.modelNote, ...
        { ...
        '```{r}' ...
        '#| label: __CHUNKLABEL__' ...
        '#| results: asis' ...
        'grp <- dat %>% filter(measure_type == "__MEASURETYPE_R__", window == "__WINDOW_R__",' ...
        ['                       bin %in% c(' binVectorR ')) %>% droplevels()']}, ...
        view.prepare, ...
        { ...
        '__BLOCKMATCHDIAGNOSTIC__' ...
        '' ...
        }, ReportSections.channelLoop('open'), { ...
        '  d <- grp %>% filter(channel == ch, !is.na(value)) %>% droplevels()' ...
        ['  if (' view.skipCondition ') {'] ...
        ['    cat(sprintf("\n\n### %s\n\n*Skipped: ' view.skipReason '.*\n\n", ch))'] ...
        '    next' ...
        '  }' ...
        '  tag <- str_replace_all(paste("__WINDOW_R__", "__MEASURETYPE_R__", ch, sep = "_"), "[^A-Za-z0-9]+", "_")' ...
        '' ...
        '  cat(sprintf("\n\n### %s\n\n", ch))' ...
        ['  descr <- d %>% group_by(' view.descrGrouping ') %>% summarise(M = mean(value), SD = sd(value), n = n(), .groups = "drop")'] ...
        '  cat(as_raw_html(apa_gt(descr, "Descriptive Statistics")))' ...
        ''}, ...
        view.countLines, ...
        { ...
        '' ...
        ['  m <- tryCatch(lmerTest::lmer(value ~ ' plan.fixed ' + ' plan.random ', data = d,'] ...
        '                               control = lme4::lmerControl(optimizer = "bobyqa")), error = function(e) NULL)' ...
        '  used_maximal <- !is.null(m) && !lme4::isSingular(m)' ...
        '  if (is.null(m) || lme4::isSingular(m)) {' ...
        ['    m <- tryCatch(lmerTest::lmer(value ~ ' plan.fixed ' + ' plan.randomFallback ', data = d,'] ...
        '                                 control = lme4::lmerControl(optimizer = "bobyqa")), error = function(e) NULL)' ...
        '  }' ...
        '' ...
        '  p_head <- NA_real_' ...
        '  p_bin <- NA_real_' ...
        '  r2m <- NA_real_' ...
        '  eta_head <- NULL' ...
        '  if (is.null(m)) {' ...
        '    cat("\n*The linear mixed model did not fit for this channel.*\n\n")' ...
        '  } else {' ...
        '    if (!used_maximal) {' ...
        '      cat("\n*The maximal model (a random intercept AND slope per subject) did not converge to a\n")' ...
        '      cat("non-singular fit -- likely too few subjects/observations for that many random parameters --\n")' ...
        '      cat("so a random-intercept-only model was used instead.*\n\n")' ...
        '    }' ...
        ['    cat(sprintf("\nA linear mixed model was fitted (fixed effects: ' plan.fixed ...
             '; a per-subject random intercept%s).\n\n",'] ...
        '                if (used_maximal) " and slope for bin" else ""))' ...
        '    aov_tab <- as.data.frame(anova(m))' ...
        ['    for (eff in c(' view.effectVector ')) {'] ...
        '      if (eff %in% rownames(aov_tab)) {' ...
        '        effRow <- aov_tab[eff, ]' ...
        '        eff_p <- effRow[["Pr(>F)"]]' ...
        '        sig_txt <- if (eff_p < .05) "a significant" else "no significant"' ...
        '        cat(sprintf("\nThe model revealed %s effect of %s, *F*(%s, %s) = %s, *p* %s.\n",' ...
        '                    sig_txt, eff, apa_num(effRow[["NumDF"]], 1), apa_num(effRow[["DenDF"]], 1),' ...
        '                    apa_num(effRow[["F value"]]), apa_p(eff_p)))' ...
        '        # Partial eta-squared, converted from the F-test above, not the' ...
        '        # marginal R^2 below -- unlike R^2 (a single whole-model number, so' ...
        '        # a forest plot of it is one point with no spread to show),' ...
        '        # eta-squared carries an actual confidence interval (Steiger, 2004,' ...
        '        # via the noncentral F), so it is what feeds the cross-report forest' ...
        '        # plot below: something with a real interval to plot, not a lone dot.' ...
        '        eta_eff <- tryCatch(effectsize::F_to_eta2(effRow[["F value"]], effRow[["NumDF"]], effRow[["DenDF"]], ci = 0.95),' ...
        '                            error = function(e) NULL)' ...
        '        if (!is.null(eta_eff)) {' ...
        '          cat(sprintf(" Partial eta-squared = %s, 95%% CI [%s, %s].\n\n",' ...
        '                      apa_num(eta_eff$Eta2_partial, 3), apa_num(eta_eff$CI_low, 3), apa_num(eta_eff$CI_high, 3)))' ...
        '        } else {' ...
        '          cat("\n\n")' ...
        '        }' ...
        ['        if (eff == "' view.headlineEffect '") {'] ...
        '          p_head <- eff_p' ...
        '          eta_head <- eta_eff' ...
        '        }' ...
        '        if (eff == "bin") {' ...
        '          p_bin <- eff_p' ...
        '        }' ...
        '      }' ...
        '    }' ...
        '    r2_tab <- tryCatch({ invisible(utils::capture.output(res <- performance::r2_nakagawa(m))); res }, error = function(e) NULL)' ...
        '    if (!is.null(r2_tab)) {' ...
        '      r2m <- as.numeric(r2_tab$R2_marginal)' ...
        ['      cat(sprintf("Marginal *R*<sup>2</sup> (variance explained by ' view.r2Blurb ') = %s.\n\n",'] ...
        '                  apa_num(r2m, 3)))' ...
        '    }' ...
        '    std_params <- tryCatch(as.data.frame(effectsize::standardize_parameters(m, method = "basic")),' ...
        '                           error = function(e) NULL)' ...
        '    if (!is.null(std_params)) {' ...
        '      cat(as_raw_html(apa_gt(std_params, "Standardized Fixed-Effect Coefficients")))' ...
        '    }' ...
        '    # lmerTest::anova() carries the effect names as ROW names, and gt()' ...
        '    # drops row names unless asked for a stub -- so this table used to print' ...
        '    # as columns of numbers with no way to tell which row was which effect.' ...
        '    # Promoted to a real first column for display only: aov_tab itself keeps' ...
        '    # its row names, because the narrative above indexes it by them.' ...
        '    # check.names = FALSE or "Pr(>F)" would be mangled into "Pr..F.".' ...
        '    aov_disp <- data.frame(Effect = rownames(aov_tab), aov_tab, check.names = FALSE)' ...
        ['    cat(as_raw_html(apa_gt(aov_disp, "' view.anovaTableTitle '")))'] ...
        ''}, ...
        postHocLines(view.postHoc), ...
        { ...
        '  }' ...
        ''}, ...
        view.robustness, ...
        { ...
        '  eta_est <- if (is.null(eta_head)) NA_real_ else eta_head$Eta2_partial' ...
        '  eta_lo  <- if (is.null(eta_head)) NA_real_ else eta_head$CI_low' ...
        '  eta_hi  <- if (is.null(eta_head)) NA_real_ else eta_head$CI_high' ...
        ['  omnibus <- bind_rows(omnibus, tibble(group = tag, design = "' view.designTag ...
         '", test = "' view.testName '", p = p_head,'] ...
        '                                        estimate = eta_est, conf.low = eta_lo, conf.high = eta_hi))' ...
        '' ...
        '  common_layers <- list(' ...
        '    geom_line(aes(group = dataset), colour = "grey75", alpha = 0.5),' ...
        '    geom_point(colour = "grey40", size = 1.4, alpha = 0.5, position = position_jitter(width = 0.04, height = 0)),' ...
        '    stat_summary(fun = mean, geom = "point", size = 2.2, colour = "#4a7fc9"),' ...
        '    stat_summary(fun.data = mean_se, geom = "errorbar", width = 0.12, colour = "#4a7fc9"),'}, ...
        view.facet, ...
        { ...
        '    labs(x = "Bin", y = "__YLABEL__"),' ...
        '    theme_pubr()' ...
        '  )' ...
        '  p <- ggplot(d, aes(bin, value)) + violin_layers("#4a7fc9") + common_layers' ...
        '  print(p)' ...
        }, ReportSections.channelLoop('close'), { ...
        '```'}];

    text = strjoin(lines, newline);
    text = strrep(text, '__NBINS__', num2str(numel(binLabels)));
    text = strrep(text, '__CHUNKLABEL__', ReportSections.chunkLabel(view.chunkPrefix, windowLabel, measureType));
    text = strrep(text, '__YLABEL__', ReportSections.yAxisLabel(measureType));
    text = strrep(text, '__BLOCKMATCHDIAGNOSTIC__', ReportSections.blockMatchDiagnosticText());
    block = ReportSections.fillCommonTokens(text, windowLabel, measureType, '', '');
end

% ======================================================================= %
function view = presentation(plan)
%PRESENTATION  Everything that differs between the four designs, in one
%   place, derived from the plan rather than from a flag the caller passes.
%
%   This function IS the merge: the three former section files differed in
%   exactly these fields and in nothing else. Reading it top to bottom is
%   the quickest way to see what a design change actually changes.
    hasSession = numel(plan.withinFactors) > 1;
    hasGroup = ~isempty(plan.betweenFactors);

    % ---- chunk label prefix. Stable, because reports and tests both name
    % sections by it; the design's identity is public API here.
    if hasSession
        view.chunkPrefix = 'session';
    elseif hasGroup
        view.chunkPrefix = 'mixed';
    else
        view.chunkPrefix = 'anova';
    end

    % ---- heading, intro and the effects the narrative walks through
    if hasSession && hasGroup
        view.headingSuffix = ' (Session x Group)';
        view.introTail = ' -- within subjects, crossed with session and with the between-subjects group.';
        view.descrGrouping = 'group, session, bin';
        view.effectVector = '"bin", "session", "group", "bin:session", "bin:group", "session:group"';
        view.r2Blurb = 'bin, session, group and their two-way interactions together';
        view.facet = {'    facet_grid(group ~ session),'};
    elseif hasSession
        view.headingSuffix = ' (Session)';
        view.introTail = ' -- within subjects, crossed with session.';
        view.descrGrouping = 'session, bin';
        view.effectVector = '"bin", "session", "bin:session"';
        view.r2Blurb = 'bin, session and their interaction together';
        view.facet = {'    facet_wrap(~ session),'};
    elseif hasGroup
        view.headingSuffix = ' (Mixed Design)';
        view.introTail = ' -- within subjects, crossed with the between-subjects group.';
        view.descrGrouping = 'group, bin';
        view.effectVector = '"group", "bin", "bin:group"';
        view.r2Blurb = 'bin, group and their interaction together';
        view.facet = {};
    else
        view.headingSuffix = '';
        view.introTail = '.';
        view.descrGrouping = 'bin';
        view.effectVector = '"bin"';
        view.r2Blurb = 'bin alone';
        view.facet = {};
    end

    % ---- the row this section contributes to the cross-report summary.
    % The headline is the interaction the design exists to test, or the
    % main effect of bin when there is no interaction to have.
    % postHoc is named here rather than inferred at the call site: it is a
    % statistical policy, and it should be visible next to the design it
    % belongs to. See postHocLines for what each name means and why the two
    % older designs are not strict.
    if hasSession
        view.designTag = 'lmm_session';
        view.headlineEffect = 'bin:session';
        view.testName = 'bin_x_session';
        view.postHoc = 'strict';
    elseif hasGroup
        view.designTag = 'lmm_mixed';
        view.headlineEffect = 'bin:group';
        view.testName = 'group_x_bin_interaction';
        view.postHoc = 'both';
    else
        view.designTag = 'lmm_within';
        view.headlineEffect = 'bin';
        view.testName = 'omnibus';
        view.postHoc = 'bin';
    end

    if numel(strsplit(view.effectVector, ',')) > 1
        view.anovaTableTitle = 'Linear Mixed Model: Fixed-Effect Tests (Satterthwaite df)';
    else
        view.anovaTableTitle = 'Linear Mixed Model: Fixed-Effect Test (Satterthwaite df)';
    end

    % ---- the skip guard. Counted in PEOPLE: a between- or within-subjects
    % term's own n is the number of people, not the number of files.
    conditions = {'n_distinct(d$person_id) < 2'};
    reasons = {'fewer than two subjects'};
    if hasGroup
        conditions{end + 1} = 'n_distinct(d$group) < 2';
        reasons{end + 1} = 'fewer than two groups';
    end
    if hasSession
        conditions{end + 1} = 'n_distinct(d$session) < 2';
        reasons{end + 1} = 'fewer than two sessions';
    end
    view.skipCondition = strjoin(conditions, ' || ');
    view.skipReason = [strjoin(reasons, ', or ') ', have a usable value for this channel'];

    % ---- session needs its factor built before the loop; nothing else does
    if hasSession
        view.prepare = {'grp <- grp %>% mutate(session = factor(session))'};
    else
        view.prepare = {};
    end

    % ---- the design note under the heading, for designs worth spelling out
    if hasSession
        view.modelNote = {['Fixed effects: `' plan.fixed '`. Random effects: `' plan.random '`.'], ''};
    else
        view.modelNote = {};
    end

    % ---- the per-channel counts, and the rank-based robustness check.
    %
    % The Friedman test needs a complete subject x bin table, which only the
    % bin-only design reliably has: a person with two sessions contributes
    % two rows per bin, and a between-subjects design is not what a
    % within-subjects rank test describes. So it runs for that design alone,
    % keyed on the RECORDING (a rank check over recordings), while the model
    % above remains the statement about people.
    if hasSession
        view.countLines = { ...
            '  # Counted in PEOPLE, not recordings: the whole reason this design' ...
            '  # exists is that one person can appear here more than once.' ...
            '  cat(sprintf("\n%d subject(s) across %d session(s) contributed at least one usable value here.\n\n",' ...
            '              n_distinct(d$person_id), n_distinct(d$session)))'};
        view.robustness = {};
        return;
    end

    view.countLines = { ...
        '  n_bins_expected <- n_distinct(d$bin)' ...
        '  complete_subjects <- d %>% count(dataset) %>% filter(n == n_bins_expected) %>% pull(dataset)' ...
        '  cat(sprintf("\n%d subject(s) contributed at least one usable value here; %d recording(s) had all %d conditions present.\n\n",' ...
        '              n_distinct(d$person_id), length(complete_subjects), n_bins_expected))'};

    if hasGroup
        view.robustness = {};
        return;
    end
    view.robustness = { ...
        '  # Keyed on the RECORDING, not the person: a rank test over a' ...
        '  # subject x bin table needs one value per cell, which a person with' ...
        '  # two sessions does not have. This is a robustness check on the' ...
        '  # recordings, and the model above is the statement about people.' ...
        '  if (length(complete_subjects) >= 2) {' ...
        '    d_complete <- d %>% filter(dataset %in% complete_subjects) %>% droplevels()' ...
        '    fr <- tryCatch(friedman_test(data = d_complete, value ~ bin | dataset), error = function(e) NULL)' ...
        '    if (!is.null(fr)) {' ...
        '      sig_txt <- if (fr$p < .05) "was significant" else "was not significant"' ...
        '      cat(sprintf("\nA Friedman test, run on the %d recording(s) with complete data as a rank-based\n", length(complete_subjects)))' ...
        '      cat(sprintf("robustness check, %s, chi-squared(%s) = %s, *p* %s.\n\n", sig_txt, fr$df, apa_num(fr$statistic), apa_p(fr$p)))' ...
        '    }' ...
        '  }' ...
        ''};
end

% ======================================================================= %
function lines = postHocLines(policy)
%POSTHOCLINES  The follow-up contrasts, by named policy.
%
%   'strict'  At most one family, and only when the term it follows is
%             significant: the interaction first, then the main effect of
%             bin, then nothing. A report that runs every family it can
%             think of has spent its alpha before anyone decided what the
%             question was. Further contrasts belong to the analyst, and
%             both emmeans and the fitted model are in scope for adding
%             them right there in the .qmd.
%
%   'bin'     One unconditional family over bins. What the within-subjects
%             design has always run.
%
%   'both'    Within-group and between-group families, both unconditional.
%             What the mixed design has always run.
%
%   The older two are not strict because making them so would have changed
%   the statistics in existing reports as a side effect of merging three
%   files into one. Switching them is a one-line change here if that is
%   wanted; it is a statistical decision, not a refactoring one.
    switch policy
        case 'strict'
            lines = { ...
                '    # ---- post-hoc, deliberately at most one family ----------------' ...
                '    posthoc <- NULL' ...
                '    posthoc_what <- ""' ...
                '    if (!is.na(p_head) && p_head < .05) {' ...
                '      posthoc <- tryCatch(emmeans::emmeans(m, pairwise ~ bin | session, adjust = "holm"), error = function(e) NULL)' ...
                '      posthoc_what <- "simple effects of bin within each session"' ...
                '    } else if (!is.na(p_bin) && p_bin < .05) {' ...
                '      posthoc <- tryCatch(emmeans::emmeans(m, pairwise ~ bin, adjust = "holm"), error = function(e) NULL)' ...
                '      posthoc_what <- "pairwise comparisons between bins"' ...
                '    } else {' ...
                '      cat("\nNo post-hoc contrasts were run: neither the bin x session interaction nor the\n")' ...
                '      cat("main effect of bin reached significance, so there is nothing for them to follow up.\n\n")' ...
                '    }' ...
                '    if (!is.null(posthoc)) {' ...
                '      pw <- as.data.frame(posthoc$contrasts)' ...
                '      sig_pw <- pw %>% filter(p.value < .05)' ...
                '      if (nrow(sig_pw) > 0) {' ...
                '        pair_txt <- sprintf("%s, *p* %s", sig_pw$contrast, apa_p(sig_pw$p.value))' ...
                '        cat(sprintf("\nHolm-corrected %s showed significant differences for: %s.\n\n",' ...
                '                    posthoc_what, paste(pair_txt, collapse = "; ")))' ...
                '      } else {' ...
                '        cat(sprintf("\nNo contrast among the %s survived Holm correction.\n\n", posthoc_what))' ...
                '      }' ...
                '      cat(as_raw_html(apa_gt(pw, "Post-Hoc Contrasts (Holm-Corrected, Model-Based)")))' ...
                '    }'};

        case 'bin'
            lines = { ...
                '    emm <- tryCatch(emmeans::emmeans(m, pairwise ~ bin, adjust = "holm"), error = function(e) NULL)' ...
                '    if (!is.null(emm)) {' ...
                '      pw <- as.data.frame(emm$contrasts)' ...
                '      sig_pw <- pw %>% filter(p.value < .05)' ...
                '      if (nrow(sig_pw) > 0) {' ...
                '        pair_txt <- sprintf("%s, *p* %s", sig_pw$contrast, apa_p(sig_pw$p.value))' ...
                '        cat(sprintf("\nHolm-corrected model-based pairwise comparisons showed significant differences for: %s.\n\n",' ...
                '                    paste(pair_txt, collapse = "; ")))' ...
                '      } else {' ...
                '        cat("\nNo pairwise comparison survived Holm correction.\n\n")' ...
                '      }' ...
                '      cat(as_raw_html(apa_gt(pw, "Pairwise Comparisons (Holm-Corrected, Model-Based)")))' ...
                '    }'};

        case 'both'
            lines = { ...
                '    emm_within <- tryCatch(emmeans::emmeans(m, pairwise ~ bin | group, adjust = "holm"), error = function(e) NULL)' ...
                '    if (!is.null(emm_within)) {' ...
                '      pwc_within <- as.data.frame(emm_within$contrasts)' ...
                '      sig_within <- pwc_within %>% filter(p.value < .05)' ...
                '      if (nrow(sig_within) > 0) {' ...
                '        pair_txt <- sprintf("within %s: %s, *p* %s", sig_within$group, sig_within$contrast, apa_p(sig_within$p.value))' ...
                '        cat(sprintf("\nHolm-corrected model-based within-group comparisons showed significant differences %s.\n\n",' ...
                '                    paste(pair_txt, collapse = "; ")))' ...
                '      } else {' ...
                '        cat("\nNo within-group pairwise comparison survived Holm correction.\n\n")' ...
                '      }' ...
                '      cat(as_raw_html(apa_gt(pwc_within, "Within-Group Pairwise Comparisons (Holm-Corrected, Model-Based)")))' ...
                '    }' ...
                '' ...
                '    emm_between <- tryCatch(emmeans::emmeans(m, pairwise ~ group | bin, adjust = "holm"), error = function(e) NULL)' ...
                '    if (!is.null(emm_between)) {' ...
                '      pwc_between <- as.data.frame(emm_between$contrasts)' ...
                '      sig_between <- pwc_between %>% filter(p.value < .05)' ...
                '      if (nrow(sig_between) > 0) {' ...
                '        pair_txt <- sprintf("at %s: %s, *p* %s", sig_between$bin, sig_between$contrast, apa_p(sig_between$p.value))' ...
                '        cat(sprintf("\nHolm-corrected model-based between-group comparisons showed significant differences %s.\n\n",' ...
                '                    paste(pair_txt, collapse = "; ")))' ...
                '      } else {' ...
                '        cat("\nNo between-group pairwise comparison survived Holm correction.\n\n")' ...
                '      }' ...
                '      cat(as_raw_html(apa_gt(pwc_between, "Between-Group Pairwise Comparisons (Holm-Corrected, Model-Based)")))' ...
                '    }'};

        otherwise
            throw(MException('Alakazam:lmmSection:postHoc', ...
                'I am afraid "%s" is not a post-hoc policy I know.', policy));
    end
end
