function block = mixedSection(windowLabel, measureType, binLabels)
%MIXEDSECTION  Two or more ordinary bins AND a between-subjects group
%   assigned -- a mixed (split-plot) design: bin is the within-subjects
%   factor (as in anovaSection), group is the between-subjects factor (as
%   in betweenSection). Like anovaSection, this now fits a linear mixed
%   model (value ~ bin * group, subject random intercept AND slope for
%   bin -- group cannot have a random slope, it is between-subjects, so
%   there is no within-subject variation to fit one against) rather than
%   a mixed ANOVA -- for the same reason: a subject missing one bin used
%   to be dropped from the WHOLE channel, where the LMM instead fits on
%   every non-missing (subject, bin) observation directly. Reports all
%   three fixed-effect tests (group, bin, group:bin -- Satterthwaite df),
%   one overall marginal R^2, standardized coefficients, and model-based
%   Holm-corrected post-hoc via emmeans, split the same two ways the
%   rstatix-based version was: pairwise bin contrasts WITHIN each group,
%   and pairwise group contrasts WITHIN each bin. The interaction's own
%   p-value (not the main effects') is what feeds the cross-report
%   omnibus summary, since the interaction is usually the actually-
%   interesting result in a mixed design (do the groups differ in how
%   they respond to condition), and each section can only contribute one
%   row per channel to keep that summary's own multiple-comparison
%   correction meaningful.
    binVectorR = strjoin(cellfun(@(b) ['"' ReportSections.rLit(b) '"'], binLabels, 'UniformOutput', false), ', ');
    binListMd = strjoin(cellfun(@(b) ReportSections.mdLit(b), binLabels, 'UniformOutput', false), ', ');
    lines = { ...
        '## __WINDOW_MD__ -- __MEASURETYPE_MD__ (Mixed Design)' ...
        '' ...
        ['__NBINS__ conditions: ' binListMd ' -- within subjects, crossed with the between-subjects group.'] ...
        '' ...
        '```{r}' ...
        '#| label: __CHUNKLABEL__' ...
        '#| results: asis' ...
        'grp <- dat %>% filter(measure_type == "__MEASURETYPE_R__", window == "__WINDOW_R__",' ...
        ['                       bin %in% c(' binVectorR ')) %>% droplevels()'] ...
        '__BLOCKMATCHDIAGNOSTIC__' ...
        '' ...
        'for (ch in unique(grp$channel)) {' ...
        '  # See descriptiveSection''s own comment on this same tryCatch/next' ...
        '  # pattern: one channel''s failure must not abort the whole render.' ...
        '  tryCatch({' ...
        '  d <- grp %>% filter(channel == ch, !is.na(value)) %>% droplevels()' ...
        '  if (n_distinct(d$dataset) < 2 || n_distinct(d$group) < 2) {' ...
        '    cat(sprintf("\n\n### %s\n\n*Skipped: fewer than two subjects, or fewer than two groups, have a usable value for this channel.*\n\n", ch))' ...
        '    next' ...
        '  }' ...
        '  tag <- str_replace_all(paste("__WINDOW_R__", "__MEASURETYPE_R__", ch, sep = "_"), "[^A-Za-z0-9]+", "_")' ...
        '' ...
        '  cat(sprintf("\n\n### %s\n\n", ch))' ...
        '  descr <- d %>% group_by(group, bin) %>% summarise(M = mean(value), SD = sd(value), n = n(), .groups = "drop")' ...
        '  cat(as_raw_html(apa_gt(descr, "Descriptive Statistics")))' ...
        '' ...
        '  n_bins_expected <- n_distinct(d$bin)' ...
        '  complete_subjects <- d %>% count(dataset) %>% filter(n == n_bins_expected) %>% pull(dataset)' ...
        '  cat(sprintf("\n%d subject(s) contributed at least one usable value here; %d had all %d conditions present.\n\n",' ...
        '              n_distinct(d$dataset), length(complete_subjects), n_bins_expected))' ...
        '' ...
        '  m <- tryCatch(lmerTest::lmer(value ~ bin * group + (1 + bin | dataset), data = d,' ...
        '                               control = lme4::lmerControl(optimizer = "bobyqa")), error = function(e) NULL)' ...
        '  used_maximal <- !is.null(m) && !lme4::isSingular(m)' ...
        '  if (is.null(m) || lme4::isSingular(m)) {' ...
        '    m <- tryCatch(lmerTest::lmer(value ~ bin * group + (1 | dataset), data = d,' ...
        '                                 control = lme4::lmerControl(optimizer = "bobyqa")), error = function(e) NULL)' ...
        '  }' ...
        '' ...
        '  p_int <- NA_real_' ...
        '  r2m <- NA_real_' ...
        '  eta_int <- NULL' ...
        '  if (is.null(m)) {' ...
        '    cat("\n*The linear mixed model did not fit for this channel.*\n\n")' ...
        '  } else {' ...
        '    if (!used_maximal) {' ...
        '      cat("\n*The maximal model (a random intercept AND slope per subject) did not converge to a\n")' ...
        '      cat("non-singular fit -- likely too few subjects/observations for that many random parameters --\n")' ...
        '      cat("so a random-intercept-only model was used instead.*\n\n")' ...
        '    }' ...
        '    aov_tab <- as.data.frame(anova(m))' ...
        '    for (eff in c("group", "bin", "bin:group")) {' ...
        '      if (eff %in% rownames(aov_tab)) {' ...
        '        effRow <- aov_tab[eff, ]' ...
        '        eff_p <- effRow[["Pr(>F)"]]' ...
        '        sig_txt <- if (eff_p < .05) "a significant" else "no significant"' ...
        '        cat(sprintf("\nThe linear mixed model revealed %s effect of %s, *F*(%s, %s) = %s, *p* %s.\n",' ...
        '                    sig_txt, eff, apa_num(effRow[["NumDF"]], 1), apa_num(effRow[["DenDF"]], 1),' ...
        '                    apa_num(effRow[["F value"]]), apa_p(eff_p)))' ...
        '        # Partial eta-squared + CI for THIS effect -- see anovaSection''s' ...
        '        # own comment on why this (not marginal R^2) is what feeds the' ...
        '        # cross-report forest plot: an interval to actually plot, not a' ...
        '        # single dot.' ...
        '        eta_eff <- tryCatch(effectsize::F_to_eta2(effRow[["F value"]], effRow[["NumDF"]], effRow[["DenDF"]], ci = 0.95),' ...
        '                            error = function(e) NULL)' ...
        '        if (!is.null(eta_eff)) {' ...
        '          cat(sprintf(" Partial eta-squared = %s, 95%% CI [%s, %s].\n\n",' ...
        '                      apa_num(eta_eff$Eta2_partial, 3), apa_num(eta_eff$CI_low, 3), apa_num(eta_eff$CI_high, 3)))' ...
        '        } else {' ...
        '          cat("\n\n")' ...
        '        }' ...
        '        if (eff == "bin:group") {' ...
        '          p_int <- eff_p' ...
        '          eta_int <- eta_eff' ...
        '        }' ...
        '      }' ...
        '    }' ...
        '    r2_tab <- tryCatch({ invisible(utils::capture.output(res <- performance::r2_nakagawa(m))); res }, error = function(e) NULL)' ...
        '    if (!is.null(r2_tab)) {' ...
        '      r2m <- as.numeric(r2_tab$R2_marginal)' ...
        '      cat(sprintf("Marginal *R*<sup>2</sup> (variance explained by bin, group and their interaction together) = %s.\n\n",' ...
        '                  apa_num(r2m, 3)))' ...
        '    }' ...
        '    std_params <- tryCatch(as.data.frame(effectsize::standardize_parameters(m, method = "basic")),' ...
        '                           error = function(e) NULL)' ...
        '    if (!is.null(std_params)) {' ...
        '      cat(as_raw_html(apa_gt(std_params, "Standardized Fixed-Effect Coefficients")))' ...
        '    }' ...
        '    cat(as_raw_html(apa_gt(aov_tab, "Linear Mixed Model: Fixed-Effect Tests (Satterthwaite df)")))' ...
        '' ...
        '    emm_within <- tryCatch(emmeans::emmeans(m, pairwise ~ bin | group, adjust = "holm"), error = function(e) NULL)' ...
        '    if (!is.null(emm_within)) {' ...
        '      pwc_within <- as.data.frame(emm_within$contrasts)' ...
        '      sig_within <- pwc_within %>% filter(p.value < .05)' ...
        '      if (nrow(sig_within) > 0) {' ...
        '        pair_txt <- sprintf("within %s: %s, *p* %s", sig_within$group, sig_within$contrast, apa_p(sig_within$p.value))' ...
        '        cat(sprintf("\nHolm-corrected model-based within-group comparisons showed significant differences %s.\n\n",' ...
        '                    paste(pair_txt, collapse = "; ")))' ...
        '      } else {' ...
        '        cat("\nNo within-group pairwise comparison survived Holm correction.\n\n")' ...
        '      }' ...
        '      cat(as_raw_html(apa_gt(pwc_within, "Within-Group Pairwise Comparisons (Holm-Corrected, Model-Based)")))' ...
        '    }' ...
        '' ...
        '    emm_between <- tryCatch(emmeans::emmeans(m, pairwise ~ group | bin, adjust = "holm"), error = function(e) NULL)' ...
        '    if (!is.null(emm_between)) {' ...
        '      pwc_between <- as.data.frame(emm_between$contrasts)' ...
        '      sig_between <- pwc_between %>% filter(p.value < .05)' ...
        '      if (nrow(sig_between) > 0) {' ...
        '        pair_txt <- sprintf("at %s: %s, *p* %s", sig_between$bin, sig_between$contrast, apa_p(sig_between$p.value))' ...
        '        cat(sprintf("\nHolm-corrected model-based between-group comparisons showed significant differences %s.\n\n",' ...
        '                    paste(pair_txt, collapse = "; ")))' ...
        '      } else {' ...
        '        cat("\nNo between-group pairwise comparison survived Holm correction.\n\n")' ...
        '      }' ...
        '      cat(as_raw_html(apa_gt(pwc_between, "Between-Group Pairwise Comparisons (Holm-Corrected, Model-Based)")))' ...
        '    }' ...
        '  }' ...
        '' ...
        '  eta_est <- if (is.null(eta_int)) NA_real_ else eta_int$Eta2_partial' ...
        '  eta_lo  <- if (is.null(eta_int)) NA_real_ else eta_int$CI_low' ...
        '  eta_hi  <- if (is.null(eta_int)) NA_real_ else eta_int$CI_high' ...
        '  omnibus <- bind_rows(omnibus, tibble(group = tag, design = "lmm_mixed", test = "group_x_bin_interaction", p = p_int,' ...
        '                                        estimate = eta_est, conf.low = eta_lo, conf.high = eta_hi))' ...
        '' ...
        '  p <- ggplot(d, aes(bin, value, colour = group, fill = group)) +' ...
        '    geom_violin(alpha = 0.15, position = position_dodge(0.7), trim = FALSE, linewidth = 0.4) +' ...
        '    geom_point(alpha = 0.4, size = 1.2, position = position_jitterdodge(jitter.width = 0.08, dodge.width = 0.7)) +' ...
        '    stat_summary(fun = mean, geom = "point", size = 2.2, position = position_dodge(0.7)) +' ...
        '    stat_summary(fun.data = mean_se, geom = "errorbar", width = 0.12, position = position_dodge(0.7)) +' ...
        '    labs(x = "Bin", y = "__YLABEL__", colour = "Group", fill = "Group") +' ...
        '    scale_colour_brewer(palette = "Set2") +' ...
        '    scale_fill_brewer(palette = "Set2") +' ...
        '    theme_pubr()' ...
        '  print(p)' ...
        '  }, error = function(e) {' ...
        '    cat(sprintf("\n\n### %s\n\n*Could not be analysed: %s*\n\n", ch, conditionMessage(e)))' ...
        '  })' ...
        '}' ...
        '```' ...
        };
    text = strjoin(lines, newline);
    text = strrep(text, '__NBINS__', num2str(numel(binLabels)));
    text = strrep(text, '__CHUNKLABEL__', ReportSections.chunkLabel('mixed', windowLabel, measureType));
    text = strrep(text, '__YLABEL__', ReportSections.yAxisLabel(measureType));
    text = strrep(text, '__BLOCKMATCHDIAGNOSTIC__', ReportSections.blockMatchDiagnosticText());
    block = ReportSections.fillCommonTokens(text, windowLabel, measureType, '', '');
end

