function block = pairedSection(windowLabel, measureType, bin1, bin2)
%PAIREDSECTION  Exactly two ordinary bins: paired t-test + Cohen's dz,
%   with a Wilcoxon signed-rank robustness check.
    lines = { ...
        '## __WINDOW_MD__ -- __MEASURETYPE_MD__' ...
        '' ...
        'Two conditions: "__BIN1_MD__" vs. "__BIN2_MD__".' ...
        '' ...
        '```{r}' ...
        '#| label: __CHUNKLABEL__' ...
        '#| results: asis' ...
        'grp <- dat %>% filter(measure_type == "__MEASURETYPE_R__", window == "__WINDOW_R__",' ...
        '                       bin %in% c("__BIN1_R__", "__BIN2_R__")) %>% droplevels()' ...
        '__BLOCKMATCHDIAGNOSTIC__' ...
        '' ...
        'for (ch in unique(grp$channel)) {' ...
        '  # The whole per-channel body is one tryCatch: an unanticipated' ...
        '  # error on ONE channel would otherwise abort this entire chunk --' ...
        '  # and, since Quarto halts the whole render on any chunk error,' ...
        '  # every section after it too -- rather than just costing this one' ...
        '  # channel''s own results.' ...
        '  tryCatch({' ...
        '  # !is.na(value) first: a subject missing ONE of the two bins''' ...
        '  # values (e.g. a peak-finding failure) then correctly fails the' ...
        '  # n == 2 check below rather than being counted as present with a' ...
        '  # value the tests below cannot use.' ...
        '  d0 <- grp %>% filter(channel == ch, !is.na(value)) %>% droplevels()' ...
        '  counts <- d0 %>% count(dataset)' ...
        '  keep <- counts %>% filter(n == 2) %>% pull(dataset)' ...
        '  d <- d0 %>% filter(dataset %in% keep) %>% droplevels()' ...
        '  if (n_distinct(d$dataset) < 2) {' ...
        '    counts_txt <- paste(sprintf("%s (n=%d)", counts$dataset, counts$n), collapse = ", ")' ...
        '    cat(sprintf("\n\n### %s\n\n*Skipped: only %d of %d subject(s) with any non-missing value have BOTH bins present (at least 2 are needed). Rows per subject for this channel: %s.*\n\n",' ...
        '                ch, length(keep), n_distinct(d0$dataset), counts_txt))' ...
        '    next' ...
        '  }' ...
        '  tag <- str_replace_all(paste("__WINDOW_R__", "__MEASURETYPE_R__", ch, sep = "_"), "[^A-Za-z0-9]+", "_")' ...
        '' ...
        '  wide <- d %>% select(dataset, bin, value) %>% pivot_wider(names_from = bin, values_from = value)' ...
        '  diffs <- wide[["__BIN2_R__"]] - wide[["__BIN1_R__"]]' ...
        '  # Base R''s shapiro.test(), not rstatix''s shapiro_test(): the latter''s' ...
        '  # tidied $p column is only reliable for its GROUPED (data %>%' ...
        '  # group_by() %>% shapiro_test()) form -- called on a bare vector it can' ...
        '  # come back without a $p column at all. Base shapiro.test() has a' ...
        '  # stable list return ($statistic, $p.value); tryCatch handles the' ...
        '  # genuine edge cases it errors on outright (n < 3, zero variance)' ...
        '  # rather than relying on any particular empty-result shape.' ...
        '  shap <- tryCatch(shapiro.test(diffs), error = function(e) NULL)' ...
        '  tt <- t.test(wide[["__BIN2_R__"]], wide[["__BIN1_R__"]], paired = TRUE)' ...
        '  dz <- d %>% rstatix::cohens_d(value ~ bin, paired = TRUE, ci = TRUE, ci.type = "bca", nboot = 200)' ...
        '  wt <- wilcox.test(wide[["__BIN2_R__"]], wide[["__BIN1_R__"]], paired = TRUE)' ...
        '  bf <- tryCatch(as.vector(BayesFactor::ttestBF(x = wide[["__BIN2_R__"]], y = wide[["__BIN1_R__"]], paired = TRUE)),' ...
        '                 error = function(e) NA_real_)' ...
        '' ...
        '  cat(sprintf("\n\n### %s\n\n", ch))' ...
        '  descr <- d %>% group_by(bin) %>% summarise(M = mean(value), SD = sd(value), n = n(), .groups = "drop")' ...
        '  cat(as_raw_html(apa_gt(descr, "Descriptive Statistics")))' ...
        '' ...
        '  if (is.null(shap)) {' ...
        '    cat("\nNormality of the paired differences could not be assessed (fewer than 3 usable observations, or no variability among them).\n\n")' ...
        '  } else {' ...
        '    normal_txt <- if (shap$p.value >= .05) "did not depart from normality" else "departed from normality (consider the Wilcoxon test below)"' ...
        '    cat(sprintf("\nA Shapiro-Wilk test indicated the paired differences %s, *W* = %s, *p* %s.\n\n",' ...
        '                normal_txt, apa_num(unname(shap$statistic)), apa_p(shap$p.value)))' ...
        '  }' ...
        '' ...
        '  sig_txt <- if (tt$p.value < .05) "a significant" else "no significant"' ...
        '  cat(sprintf("\nA paired-samples *t*-test found %s difference between __BIN1_MD__ and __BIN2_MD__,\n", sig_txt))' ...
        '  cat(sprintf("*t*(%d) = %s, *p* %s, Cohen''s *d~z~* = %s (%s), 95%% CI [%s, %s].\n",' ...
        '              round(tt$parameter), apa_num(tt$statistic), apa_p(tt$p.value), apa_num(dz$effsize), dz$magnitude,' ...
        '              apa_num(dz$conf.low), apa_num(dz$conf.high)))' ...
        '  cat(sprintf("A Wilcoxon signed-rank test, run as a robustness check alongside it, gave *V* = %s, *p* %s;\n",' ...
        '              apa_num(wt$statistic), apa_p(wt$p.value)))' ...
        '  cat(sprintf("a Bayesian paired *t*-test gave BF~10~ = %s.\n\n", apa_bf(bf)))' ...
        '' ...
        '  omnibus <- bind_rows(omnibus, tibble(group = tag, design = "paired_t", test = "paired_t_test", p = tt$p.value,' ...
        '                                        estimate = dz$effsize, conf.low = dz$conf.low, conf.high = dz$conf.high))' ...
        '' ...
        '  common_layers <- list(' ...
        '    geom_line(aes(group = dataset), colour = "grey75", alpha = 0.5),' ...
        '    geom_point(colour = "grey40", size = 1.4, alpha = 0.5, position = position_jitter(width = 0.04, height = 0)),' ...
        '    stat_summary(fun = mean, geom = "point", size = 2.2, colour = "#4a7fc9"),' ...
        '    stat_summary(fun.data = mean_se, geom = "errorbar", width = 0.12, colour = "#4a7fc9"),' ...
        '    labs(x = "Bin", y = "__YLABEL__"),' ...
        '    theme_pubr()' ...
        '  )' ...
        '  p <- ggplot(d, aes(bin, value)) + violin_layers("#4a7fc9") + common_layers' ...
        '  print(p)' ...
        '  }, error = function(e) {' ...
        '    cat(sprintf("\n\n### %s\n\n*Could not be analysed: %s*\n\n", ch, conditionMessage(e)))' ...
        '  })' ...
        '}' ...
        '```' ...
        };
    text = strjoin(lines, newline);
    text = strrep(text, '__CHUNKLABEL__', ReportSections.chunkLabel('paired', windowLabel, measureType));
    text = strrep(text, '__YLABEL__', ReportSections.yAxisLabel(measureType));
    text = strrep(text, '__BLOCKMATCHDIAGNOSTIC__', ReportSections.blockMatchDiagnosticText());
    block = ReportSections.fillCommonTokens(text, windowLabel, measureType, bin1, bin2);
end

