function lines = vsZeroLines(includeVsZero)
%VSZEROLINES  The per-group one-sample-vs-zero test, spliced into
%   comboSectionGrouped when INCLUDEVSZERO -- {} (no-op) otherwise.
    if ~includeVsZero
        lines = {};
        return;
    end
    lines = { ...
        '' ...
        '  # One-sample-vs-zero, once PER GROUP: with groups present, "does' ...
        '  # this effect exist at all" becomes a per-group question -- never' ...
        '  # folded into the between-groups comparison below, which asks a' ...
        '  # different thing (does the effect DIFFER between groups, not' ...
        '  # whether it exists in either one).' ...
        '  vs_zero <- d %>% group_by(group) %>% group_modify(~ {' ...
        '    tt <- tryCatch(t.test(.x$value, mu = 0), error = function(e) NULL)' ...
        '    dz <- tryCatch(.x %>% rstatix::cohens_d(value ~ 1, mu = 0, ci = TRUE, ci.type = "bca", nboot = 200),' ...
        '                   error = function(e) tibble(effsize = NA_real_, conf.low = NA_real_, conf.high = NA_real_))' ...
        '    bf <- tryCatch(as.vector(BayesFactor::ttestBF(x = .x$value, mu = 0)), error = function(e) NA_real_)' ...
        '    if (is.null(tt)) return(tibble(M = mean(.x$value), n = nrow(.x), statistic = NA_real_, df = NA_real_, p = NA_real_,' ...
        '                                    d = NA_real_, d_lo = NA_real_, d_hi = NA_real_, bf = NA_real_))' ...
        '    tibble(M = mean(.x$value), n = nrow(.x), statistic = unname(tt$statistic), df = unname(tt$parameter), p = tt$p.value,' ...
        '           d = dz$effsize, d_lo = dz$conf.low, d_hi = dz$conf.high, bf = bf)' ...
        '  }) %>% ungroup()' ...
        '  for (gi in seq_len(nrow(vs_zero))) {' ...
        '    row <- vs_zero[gi, ]' ...
        '    if (is.na(row$p)) {' ...
        '      cat(sprintf("\nWithin %s, __COMBOLABEL_MD__ could not be tested against zero (fewer than 2 usable observations).\n\n", row$group))' ...
        '    } else {' ...
        '      sig_txt <- if (row$p < .05) "differed significantly" else "did not differ significantly"' ...
        '      cat(sprintf("\nWithin %s, __COMBOLABEL_MD__ %s from zero, *t*(%d) = %s, *p* %s, *M* = %s, Cohen''s\n",' ...
        '                  row$group, sig_txt, round(row$df), apa_num(row$statistic), apa_p(row$p), apa_num(row$M)))' ...
        '      cat(sprintf("*d* = %s, 95%% CI [%s, %s], BF~10~ = %s.\n\n",' ...
        '                  apa_num(row$d), apa_num(row$d_lo), apa_num(row$d_hi), apa_bf(row$bf)))' ...
        '    }' ...
        '  }'};
end

