function s = yAxisLabel(measureType)
%YAXISLABEL  A plot's y-axis label for MEASURETYPE. ERP amplitude/area
%   types fall back to the generic "Value": their physical unit (uV or
%   uV.ms) depends on the recording's own calibration, which this
%   generator has no way to know. Every other type (ERP latencies;
%   every Spectral Measure type -- power, amplitude, snr, itc, phase,
%   coherence, phaselag) has a fixed, calibration-independent label, so
%   those are always labelled precisely.
    labels = struct( ...
        'peak_latency',            'Latency (ms)', ...
        'fractional_peak_latency', 'Latency (ms)', ...
        'fractional_area_latency', 'Latency (ms)', ...
        'power',                   'Power', ...
        'amplitude',               'Amplitude', ...
        'snr',                     'SNR', ...
        'itc',                     'ITC', ...
        'phase',                   'Phase (rad)', ...
        'coherence',               'Coherence', ...
        'phaselag',                'Phase lag (rad)');
    if isfield(labels, measureType)
        s = labels.(measureType);
    else
        s = 'Value';
    end
end

