function qmdText = generateQuartoReport(entries, csvFileName)
%GENERATEQUARTOREPORT  A design-aware Quarto (.qmd) report for an exported
%   measurements CSV: rendering it (self-contained HTML) produces a short,
%   APA-styled results report -- narrative prose with inline-computed
%   statistics, APA-formatted tables (gt), and embedded plots -- rather
%   than a plain R console script. Replaces the earlier generateRScript.m,
%   which this supersedes: same design-aware bin classification and
%   rstatix computations underneath (see this file's own block functions),
%   only the OUTPUT layer changed, from cat()/print() console text to
%   Quarto markdown + APA prose.
%
%   Design (see this file's own block functions for the exact rstatix
%   calls, unchanged from generateRScript.m's own choices):
%     - 1 ordinary bin: descriptive statistics only -- no comparison is
%       possible.
%     - 2 ordinary bins: a paired t-test + Cohen's dz, with a Wilcoxon
%       signed-rank robustness check and a Shapiro-Wilk normality note.
%     - 3+ ordinary bins: a repeated-measures ANOVA (Type III) + Holm-
%       corrected pairwise paired t-tests + Cohen's dz per pair, with a
%       Friedman test robustness check.
%     - Each COMBINATION (difference) bin, separately: a one-sample
%       t-test (and Wilcoxon) against zero -- never folded into the
%       omnibus test above, since a combination bin's scores are a linear
%       combination of the OTHER bins', not an independent condition, so
%       including it there would be statistically invalid.
%   Every block's own key p-value also feeds one final cross-group
%   summary table, BH/FDR-corrected across every channel x window x
%   measure group the export produced, not just within one group's own
%   pairwise tests.
%
%   Unlike an APA manuscript's usual terse, no-explanation results prose,
%   generateRScript.m's own console version also carried short "what does
%   this test mean" explainer text throughout, aimed at a reader learning
%   the statistics alongside the results -- deliberately dropped here:
%   an APA-styled report reads as results prose (a repeated-measures
%   ANOVA revealed a significant effect of bin, F(...) = ..., p = ...),
%   not a statistics tutorial.
%
%   ENTRIES/CSVFILENAME: see generateRScript.m's own header comment for
%   both (unchanged) -- ENTRIES(1).EEG carries the bin/window structure
%   (EEG.bindesc, EEG.measurements), CSVFILENAME is the bare file name the
%   report's own read_csv() call references, relative to where the report
%   itself is written.
%
%   Requires the R packages tidyverse, rstatix, ggpubr and gt (auto-
%   installed by the report's own setup chunk on first render) plus a
%   working Quarto installation (https://quarto.org) to actually render
%   the .qmd this function returns into HTML.
%
%   See also EXPORTMEASUREMENTSCSV, MEASUREROWTYPES, MEASUREROWVALUE.
    if isempty(entries)
        throw(MException('Alakazam:generateQuartoReport', ...
            'generateQuartoReport needs at least one Measure result to build a report from.'));
    end
    EEG = entries(1).EEG;
    if ~isfield(EEG, 'measurements') || isempty(EEG.measurements)
        throw(MException('Alakazam:generateQuartoReport', ...
            'generateQuartoReport needs a dataset with at least one Measure window (EEG.measurements).'));
    end

    [ordinaryLabels, comboBins] = classifyBins(EEG);

    sections = {};
    for w = 1:numel(EEG.measurements)
        win = EEG.measurements{w};
        types = measureRowTypes(win);
        for ti = 1:numel(types)
            windowLabel = char(string(win.label));
            measureType = types{ti};

            if numel(ordinaryLabels) == 1
                sections{end + 1} = descriptiveSection(windowLabel, measureType, ordinaryLabels{1}); %#ok<AGROW>
            elseif numel(ordinaryLabels) == 2
                sections{end + 1} = pairedSection(windowLabel, measureType, ordinaryLabels{1}, ordinaryLabels{2}); %#ok<AGROW>
            elseif numel(ordinaryLabels) >= 3
                sections{end + 1} = anovaSection(windowLabel, measureType, ordinaryLabels); %#ok<AGROW>
            end
            for cb = 1:numel(comboBins)
                sections{end + 1} = comboSection(windowLabel, measureType, ...
                    comboBins(cb).label, comboBins(cb).recipeText); %#ok<AGROW>
            end
        end
    end

    parts = [{preambleText(csvFileName)}, sections, {closingText()}];
    qmdText = char(strjoin(parts, [newline newline]));
end

% ======================================================================= %
%  Bin classification -- identical to generateRScript.m's own (the whole
%  point of doing this in MATLAB, not R): EEG.bindesc(b).combo is not
%  recoverable from the flat CSV at all.
% ======================================================================= %
function [ordinaryLabels, comboBins] = classifyBins(EEG)
%CLASSIFYBINS  ORDINARYLABELS (cellstr, real conditions) and COMBOBINS (a
%   struct array, .label/.recipeText, one per DefineBins/Average
%   combination bin) from EEG.bindesc. A dataset with no bindesc at all
%   (an unbinned Average) is treated as one implicit ordinary bin, "1" --
%   csvBinLabel's own fallback for exactly this case, so this matches
%   whatever bin value actually ended up in the CSV.
    comboBins = struct('label', {}, 'recipeText', {});
    if ~isfield(EEG, 'bindesc') || isempty(EEG.bindesc)
        ordinaryLabels = {'1'};
        return;
    end
    bindesc = EEG.bindesc;
    isCombo = false(1, numel(bindesc));
    if isfield(bindesc, 'combo')
        isCombo = ~cellfun(@isempty, {bindesc.combo});
    end
    ordinaryLabels = {bindesc(~isCombo).label};
    for b = find(isCombo)
        comboBins(end + 1) = struct('label', char(string(bindesc(b).label)), ...
            'recipeText', comboRecipeText(bindesc, bindesc(b))); %#ok<AGROW>
    end
end

function txt = comboRecipeText(bindesc, entry)
%COMBORECIPETEXT  A combination bin's own recipe as readable text, e.g.
%   "Rare - Frequent" or "0.5*Left + 0.5*Right" -- entry.combo's own .bin
%   values are referenced bins' .index (Average.m's own convention), not
%   array positions, so they are mapped back to a label via bindesc's own
%   .index field.
    indices = [bindesc.index];
    parts = strings(1, numel(entry.combo));
    for t = 1:numel(entry.combo)
        refLabel = bindesc(indices == entry.combo(t).bin).label;
        coeff = entry.combo(t).coeff;
        if t == 1
            if coeff < 0; sgn = "-"; else; sgn = ""; end
        else
            if coeff < 0; sgn = " - "; else; sgn = " + "; end
        end
        if abs(coeff) == 1
            magTxt = "";
        else
            magTxt = string(sprintf('%.3g*', abs(coeff)));
        end
        parts(t) = sgn + magTxt + string(refLabel);
    end
    txt = char(strjoin(parts, ""));
end

% ======================================================================= %
%  Text assembly: strrep-based token substitution, NOT sprintf -- R's own
%  pipe operator (%>%) is full of literal '%' characters that sprintf
%  would misread as format specifiers, so every section below is built by
%  substituting __TOKEN__ placeholders into a literal template instead.
%  Every label needs TWO escaped forms, since it can appear in two
%  different contexts: __X_MD__ (mdLit-escaped) for Quarto markdown
%  prose/headings, __X_R__ (rLit-escaped) for inside an R string literal
%  in a code chunk -- see fillToken.
% ======================================================================= %
function s = rLit(matlabText)
%RLIT  MATLABTEXT as a safe R double-quoted string literal's INNER text
%   (caller still supplies the surrounding quotes): backslashes and
%   double quotes escaped, so a bin/window label an analyst happened to
%   type with one of those characters cannot break the generated R
%   syntax.
    s = strrep(char(matlabText), '\', '\\');
    s = strrep(s, '"', '\"');
end

function s = mdLit(matlabText)
%MDLIT  MATLABTEXT as safe inline Quarto/Pandoc markdown text: escapes
%   the characters markdown gives special meaning outside a code span
%   (\ * _ # [ ] ` < >), so a bin/window label an analyst happened to
%   type with one of those characters cannot corrupt the rendered
%   heading/prose around it (e.g. turn part of a label into unintended
%   italics, or be swallowed as a raw HTML tag).
    s = char(matlabText);
    special = {'\', '*', '_', '#', '[', ']', '`', '<', '>'};
    for i = 1:numel(special)
        s = strrep(s, special{i}, ['\' special{i}]);
    end
end

function s = labelPiece(matlabText)
%LABELPIECE  MATLABTEXT as a safe, lowercase, hyphenated fragment for a
%   Quarto/knitr chunk label (letters, digits, hyphens only -- unlike
%   R/MATLAB identifiers, a chunk label is not restricted to start with a
%   letter, but IS restricted to have no spaces and no characters knitr
%   would choke on, so this is deliberately more conservative than
%   strictly required). Never empty (falls back to "x"), so a blank
%   window/measure-type piece never collapses two different labels into
%   the same "--" run.
    s = lower(char(matlabText));
    s = regexprep(s, '[^a-z0-9]+', '-');
    s = regexprep(s, '^-+|-+$', '');
    if isempty(s)
        s = 'x';
    end
end

function s = chunkLabel(varargin)
%CHUNKLABEL  A unique, valid Quarto/knitr chunk label built from one or
%   more MATLAB text pieces (e.g. a section kind tag, window label,
%   measure type, combo-bin label), each sanitised via labelPiece and
%   joined with hyphens. Uniqueness across the whole document follows
%   from generateQuartoReport's own main loop: each combination of
%   (section kind, window, measure type[, combo label]) is only ever
%   assembled into one chunk.
    pieces = cellfun(@labelPiece, varargin, 'UniformOutput', false);
    s = strjoin(pieces, '-');
end

function text = fillToken(text, token, value)
%FILLTOKEN  Substitute __TOKEN_MD__ (mdLit-escaped) and __TOKEN_R__
%   (rLit-escaped) occurrences of TOKEN with VALUE in TEXT. A no-op for
%   either placeholder VALUE does not contain (empty VALUE is passed
%   through as an empty string on both sides, matching a section that
%   does not use one of the two bin slots, e.g. descriptiveSection's
%   unused BIN2).
    text = strrep(text, ['__' token '_MD__'], mdLit(value));
    text = strrep(text, ['__' token '_R__'], rLit(value));
end

function text = fillCommonTokens(text, windowLabel, measureType, bin1, bin2)
%FILLCOMMONTOKENS  Substitute the tokens every section shares (WINDOW,
%   MEASURETYPE, BIN1, BIN2), each in both its _MD and _R form.
    text = fillToken(text, 'WINDOW', windowLabel);
    text = fillToken(text, 'MEASURETYPE', measureType);
    text = fillToken(text, 'BIN1', bin1);
    text = fillToken(text, 'BIN2', bin2);
end

function text = preambleText(csvFileName)
    lines = { ...
        '---' ...
        'title: "Alakazam ERP Statistical Report"' ...
        'format:' ...
        '  html:' ...
        '    self-contained: true' ...
        '    toc: true' ...
        '    theme: cosmo' ...
        'execute:' ...
        '  echo: false' ...
        '  warning: false' ...
        '  message: false' ...
        '---' ...
        '' ...
        '<!--' ...
        'Alakazam -- statistical report for exported ERP measurements.' ...
        'Auto-generated, DESIGN-AWARE: unlike a generic report, this one was built' ...
        'specifically for this export''s own bins/windows -- each section below runs' ...
        'the test appropriate to what THAT window/measure actually has (a paired' ...
        't-test for two conditions, a repeated-measures ANOVA for three or more, a' ...
        'one-sample test against zero for a difference/combination bin), rather than' ...
        'one generic loop re-discovering the design at runtime. Edit freely: this is' ...
        'a sensible starting point, not the last word on your design or your prose.' ...
        'Render with: quarto render <this file>.qmd' ...
        '-->' ...
        '' ...
        '```{r}' ...
        '#| label: setup' ...
        '#| include: false' ...
        'pkgs <- c("tidyverse", "rstatix", "ggpubr", "gt")' ...
        'missing <- pkgs[!pkgs %in% rownames(installed.packages())]' ...
        'if (length(missing)) install.packages(missing, repos = "https://cloud.r-project.org")' ...
        'invisible(lapply(pkgs, library, character.only = TRUE))' ...
        '' ...
        'csv_file <- "__CSVFILE_R__"' ...
        'dat <- read_csv(csv_file, show_col_types = FALSE) %>%' ...
        '  filter(dataset_type == "subject") %>%' ...
        '  mutate(dataset = factor(dataset), bin = factor(bin))' ...
        '' ...
        'if (n_distinct(dat$dataset) < 2) {' ...
        '  stop("Need at least two subjects (dataset_type == subject) for statistics.")' ...
        '}' ...
        '' ...
        '# One row per test run below (design/group/p), so the closing section can' ...
        '# report a BH/FDR-adjusted summary ACROSS every group tested, not just' ...
        '# within one group''s own pairwise comparisons.' ...
        'omnibus <- tibble(group = character(), design = character(), test = character(), p = double())' ...
        '' ...
        '# ---- APA-style formatting helpers ----' ...
        '# apa_p/apa_num both drop the leading zero APA convention omits for any' ...
        '# statistic that cannot exceed 1 in magnitude (p, r, eta-squared, ...) --' ...
        '# and, since the regex only matches a value that STARTS with "0.", leave a' ...
        '# statistic that CAN exceed 1 (t, F, M, SD, ...) untouched, so one helper' ...
        '# serves both without the caller having to say which kind of number it is.' ...
        '# Vectorised (ifelse, not if): called on a single test statistic in most' ...
        '# sections, but on a whole column at once (e.g. sig_pw$p.adj, one row per' ...
        '# significant pair) when narrating the ANOVA''s pairwise comparisons -- a' ...
        '# scalar if() on a length > 1 vector is a hard error as of R >= 4.2/4.3.' ...
        'apa_p <- function(p) {' ...
        '  ifelse(is.na(p), "= NA",' ...
        '    ifelse(p < .001, "< .001",' ...
        '      paste("=", sub("^0\\.", ".", sprintf("%.3f", p)))))' ...
        '}' ...
        'apa_num <- function(x, digits = 2) {' ...
        '  ifelse(is.na(x), "NA",' ...
        '    sub("^(-?)0\\.", "\\1.", sprintf(paste0("%.", digits, "f"), x)))' ...
        '}' ...
        '# A three-line APA table (rule above the header, rule below it, rule at the' ...
        '# foot; no vertical rules) via gt, printed with as_raw_html() so it can be' ...
        '# emitted from inside a per-channel for loop in a results:"asis" chunk --' ...
        '# gt''s own auto-print only works for a table that is a chunk''s sole,' ...
        '# top-level, unassigned result, which a table built inside a loop never is.' ...
        '# Numeric columns that happen to be whole numbers everywhere (n, df, ...)' ...
        '# are formatted with 0 decimals, not 3 -- APA never shows a sample size or' ...
        '# degrees of freedom as e.g. "10.000".' ...
        'apa_gt <- function(df, title = NULL) {' ...
        '  is_whole <- function(x) is.numeric(x) && all(x == round(x), na.rm = TRUE)' ...
        '  int_cols <- names(df)[sapply(df, is_whole)]' ...
        '  dec_cols <- setdiff(names(df)[sapply(df, is.numeric)], int_cols)' ...
        '  tbl <- gt(df)' ...
        '  if (!is.null(title)) tbl <- tab_header(tbl, title = title)' ...
        '  if (length(dec_cols) > 0) tbl <- tbl %>% fmt_number(columns = all_of(dec_cols), decimals = 3)' ...
        '  if (length(int_cols) > 0) tbl <- tbl %>% fmt_number(columns = all_of(int_cols), decimals = 0)' ...
        '  tbl %>%' ...
        '    tab_options(' ...
        '      table.border.top.style = "solid", table.border.top.width = px(1.5), table.border.top.color = "black",' ...
        '      table.border.bottom.style = "solid", table.border.bottom.width = px(1.5), table.border.bottom.color = "black",' ...
        '      column_labels.border.bottom.style = "solid", column_labels.border.bottom.width = px(1), column_labels.border.bottom.color = "black",' ...
        '      table_body.hlines.style = "none", table.border.left.style = "none", table.border.right.style = "none",' ...
        '      column_labels.font.weight = "bold", table.font.size = px(13), heading.align = "left"' ...
        '    )' ...
        '}' ...
        '```' ...
        };
    text = strrep(strjoin(lines, newline), '__CSVFILE_R__', rLit(csvFileName));
end

function block = descriptiveSection(windowLabel, measureType, binLabel)
%DESCRIPTIVESECTION  Exactly one ordinary bin: nothing to compare, so just
%   a per-channel descriptive-statistics table and a one-sample plot.
    lines = { ...
        '## __WINDOW_MD__ -- __MEASURETYPE_MD__' ...
        '' ...
        'Single condition ("__BIN1_MD__"); descriptive statistics only, no comparison possible.' ...
        '' ...
        '```{r}' ...
        '#| label: __CHUNKLABEL__' ...
        '#| results: asis' ...
        'grp <- dat %>% filter(measure_type == "__MEASURETYPE_R__", window == "__WINDOW_R__", bin == "__BIN1_R__")' ...
        '' ...
        'for (ch in unique(grp$channel)) {' ...
        '  # The whole per-channel body is one tryCatch: an unanticipated' ...
        '  # error on ONE channel (a statistical edge case a later Measure' ...
        '  # window/dataset combination happens to trigger) would otherwise' ...
        '  # abort this entire chunk -- and, since Quarto halts the whole' ...
        '  # render on any chunk error, every section after it too -- rather' ...
        '  # than just costing this one channel''s own results.' ...
        '  tryCatch({' ...
        '  # !is.na(value): a Measure window can leave value NA for a given' ...
        '  # subject/channel (e.g. a peak-finding failure, or an unresolved' ...
        '  # combination bin -- see Measure.m''s own header comment) without' ...
        '  # missing the row entirely, so this cannot be filtered out just by' ...
        '  # row count/dataset count alone.' ...
        '  d <- grp %>% filter(channel == ch, !is.na(value))' ...
        '  if (nrow(d) == 0) next' ...
        '  tag <- str_replace_all(paste("__WINDOW_R__", "__MEASURETYPE_R__", ch, sep = "_"), "[^A-Za-z0-9]+", "_")' ...
        '' ...
        '  cat(sprintf("\n\n### %s\n\n", ch))' ...
        '  descr <- d %>% summarise(M = mean(value), SD = sd(value), n = n())' ...
        '  cat(sprintf("*M* = %s, *SD* = %s, *n* = %d.\n\n", apa_num(descr$M), apa_num(descr$SD), descr$n))' ...
        '  cat(as_raw_html(apa_gt(descr, "Descriptive Statistics")))' ...
        '' ...
        '  p <- ggplot(d, aes(x = 1, y = value)) +' ...
        '    geom_violin(aes(group = 1), fill = "#4a7fc9", alpha = 0.15, colour = "#4a7fc9",' ...
        '                trim = FALSE, linewidth = 0.4, width = 0.6) +' ...
        '    geom_jitter(width = 0.05, colour = "grey40", alpha = 0.6) +' ...
        '    stat_summary(fun = mean, geom = "point", size = 3, colour = "#4a7fc9") +' ...
        '    stat_summary(fun.data = mean_se, geom = "errorbar", width = 0.1, colour = "#4a7fc9") +' ...
        '    labs(x = NULL, y = "__YLABEL__") +' ...
        '    scale_x_continuous(breaks = NULL) +' ...
        '    theme_pubr()' ...
        '  print(p)' ...
        '  }, error = function(e) {' ...
        '    cat(sprintf("\n\n### %s\n\n*Could not be analysed: %s*\n\n", ch, conditionMessage(e)))' ...
        '  })' ...
        '}' ...
        '```' ...
        };
    text = strjoin(lines, newline);
    text = strrep(text, '__CHUNKLABEL__', chunkLabel('desc', windowLabel, measureType));
    text = strrep(text, '__YLABEL__', yAxisLabel(measureType));
    block = fillCommonTokens(text, windowLabel, measureType, binLabel, '');
end

function block = pairedSection(windowLabel, measureType, bin1, bin2)
%PAIREDSECTION  Exactly two ordinary bins: paired t-test + Cohen's dz,
%   with a Wilcoxon signed-rank robustness check.
    lines = { ...
        '## __WINDOW_MD__ -- __MEASURETYPE_MD__' ...
        '' ...
        'Two conditions: "__BIN1_MD__" vs. "__BIN2_MD__".' ...
        '' ...
        '```{r}' ...
        '#| label: __CHUNKLABEL__' ...
        '#| results: asis' ...
        'grp <- dat %>% filter(measure_type == "__MEASURETYPE_R__", window == "__WINDOW_R__",' ...
        '                       bin %in% c("__BIN1_R__", "__BIN2_R__")) %>% droplevels()' ...
        '' ...
        'for (ch in unique(grp$channel)) {' ...
        '  # The whole per-channel body is one tryCatch: an unanticipated' ...
        '  # error on ONE channel would otherwise abort this entire chunk --' ...
        '  # and, since Quarto halts the whole render on any chunk error,' ...
        '  # every section after it too -- rather than just costing this one' ...
        '  # channel''s own results.' ...
        '  tryCatch({' ...
        '  # !is.na(value) first: a subject missing ONE of the two bins''' ...
        '  # values (e.g. a peak-finding failure) then correctly fails the' ...
        '  # n == 2 check below rather than being counted as present with a' ...
        '  # value the tests below cannot use.' ...
        '  d <- grp %>% filter(channel == ch, !is.na(value)) %>% droplevels()' ...
        '  keep <- d %>% count(dataset) %>% filter(n == 2) %>% pull(dataset)' ...
        '  d <- d %>% filter(dataset %in% keep) %>% droplevels()' ...
        '  if (n_distinct(d$dataset) < 2) next' ...
        '  tag <- str_replace_all(paste("__WINDOW_R__", "__MEASURETYPE_R__", ch, sep = "_"), "[^A-Za-z0-9]+", "_")' ...
        '' ...
        '  wide <- d %>% select(dataset, bin, value) %>% pivot_wider(names_from = bin, values_from = value)' ...
        '  diffs <- wide[["__BIN2_R__"]] - wide[["__BIN1_R__"]]' ...
        '  # Base R''s shapiro.test(), not rstatix''s shapiro_test(): the latter''s' ...
        '  # tidied $p column is only reliable for its GROUPED (data %>%' ...
        '  # group_by() %>% shapiro_test()) form -- called on a bare vector it can' ...
        '  # come back without a $p column at all. Base shapiro.test() has a' ...
        '  # stable list return ($statistic, $p.value); tryCatch handles the' ...
        '  # genuine edge cases it errors on outright (n < 3, zero variance)' ...
        '  # rather than relying on any particular empty-result shape.' ...
        '  shap <- tryCatch(shapiro.test(diffs), error = function(e) NULL)' ...
        '  tt <- t.test(wide[["__BIN2_R__"]], wide[["__BIN1_R__"]], paired = TRUE)' ...
        '  dz <- d %>% cohens_d(value ~ bin, paired = TRUE)' ...
        '  wt <- wilcox.test(wide[["__BIN2_R__"]], wide[["__BIN1_R__"]], paired = TRUE)' ...
        '' ...
        '  cat(sprintf("\n\n### %s\n\n", ch))' ...
        '  descr <- d %>% group_by(bin) %>% summarise(M = mean(value), SD = sd(value), n = n(), .groups = "drop")' ...
        '  cat(as_raw_html(apa_gt(descr, "Descriptive Statistics")))' ...
        '' ...
        '  if (is.null(shap)) {' ...
        '    cat("\nNormality of the paired differences could not be assessed (fewer than 3 usable observations, or no variability among them).\n\n")' ...
        '  } else {' ...
        '    normal_txt <- if (shap$p.value >= .05) "did not depart from normality" else "departed from normality (consider the Wilcoxon test below)"' ...
        '    cat(sprintf("\nA Shapiro-Wilk test indicated the paired differences %s, *W* = %s, *p* %s.\n\n",' ...
        '                normal_txt, apa_num(unname(shap$statistic)), apa_p(shap$p.value)))' ...
        '  }' ...
        '' ...
        '  sig_txt <- if (tt$p.value < .05) "a significant" else "no significant"' ...
        '  cat(sprintf("\nA paired-samples *t*-test found %s difference between __BIN1_MD__ and __BIN2_MD__,\n", sig_txt))' ...
        '  cat(sprintf("*t*(%d) = %s, *p* %s, Cohen''s *d~z~* = %s (%s). A Wilcoxon signed-rank test, run\n",' ...
        '              round(tt$parameter), apa_num(tt$statistic), apa_p(tt$p.value), apa_num(dz$effsize), dz$magnitude))' ...
        '  cat(sprintf("as a robustness check alongside it, gave *V* = %s, *p* %s.\n\n", apa_num(wt$statistic), apa_p(wt$p.value)))' ...
        '' ...
        '  omnibus <- bind_rows(omnibus, tibble(group = tag, design = "paired_t", test = "paired_t_test", p = tt$p.value))' ...
        '' ...
        '  p <- ggplot(d, aes(bin, value)) +' ...
        '    geom_violin(fill = "#4a7fc9", alpha = 0.15, colour = "#4a7fc9", trim = FALSE, linewidth = 0.4) +' ...
        '    geom_line(aes(group = dataset), colour = "grey75", alpha = 0.5) +' ...
        '    geom_point(colour = "grey40", size = 1.4, alpha = 0.5, position = position_jitter(width = 0.04, height = 0)) +' ...
        '    stat_summary(fun = mean, geom = "point", size = 2.2, colour = "#4a7fc9") +' ...
        '    stat_summary(fun.data = mean_se, geom = "errorbar", width = 0.12, colour = "#4a7fc9") +' ...
        '    labs(x = "Bin", y = "__YLABEL__") +' ...
        '    theme_pubr()' ...
        '  print(p)' ...
        '  }, error = function(e) {' ...
        '    cat(sprintf("\n\n### %s\n\n*Could not be analysed: %s*\n\n", ch, conditionMessage(e)))' ...
        '  })' ...
        '}' ...
        '```' ...
        };
    text = strjoin(lines, newline);
    text = strrep(text, '__CHUNKLABEL__', chunkLabel('paired', windowLabel, measureType));
    text = strrep(text, '__YLABEL__', yAxisLabel(measureType));
    block = fillCommonTokens(text, windowLabel, measureType, bin1, bin2);
end

function block = anovaSection(windowLabel, measureType, binLabels)
%ANOVASECTION  Three or more ordinary bins: repeated-measures ANOVA
%   (Type III) + Holm-corrected pairwise paired t-tests + Cohen's dz per
%   pair, with a Friedman test robustness check.
    binVectorR = strjoin(cellfun(@(b) ['"' rLit(b) '"'], binLabels, 'UniformOutput', false), ', ');
    binListMd = strjoin(cellfun(@(b) mdLit(b), binLabels, 'UniformOutput', false), ', ');
    lines = { ...
        '## __WINDOW_MD__ -- __MEASURETYPE_MD__' ...
        '' ...
        ['__NBINS__ conditions: ' binListMd '.'] ...
        '' ...
        '```{r}' ...
        '#| label: __CHUNKLABEL__' ...
        '#| results: asis' ...
        'grp <- dat %>% filter(measure_type == "__MEASURETYPE_R__", window == "__WINDOW_R__",' ...
        ['                       bin %in% c(' binVectorR ')) %>% droplevels()'] ...
        '' ...
        'for (ch in unique(grp$channel)) {' ...
        '  # The whole per-channel body is one tryCatch: an unanticipated' ...
        '  # error on ONE channel would otherwise abort this entire chunk --' ...
        '  # and, since Quarto halts the whole render on any chunk error,' ...
        '  # every section after it too -- rather than just costing this one' ...
        '  # channel''s own results.' ...
        '  tryCatch({' ...
        '  # !is.na(value) first: a subject missing even one bin''s value' ...
        '  # (e.g. a peak-finding failure, or an unresolved combination bin)' ...
        '  # then correctly fails the below n == n_distinct(bin) check rather' ...
        '  # than being counted as present with a value the tests cannot use.' ...
        '  d <- grp %>% filter(channel == ch, !is.na(value)) %>% droplevels()' ...
        '  keep <- d %>% count(dataset) %>% filter(n == n_distinct(d$bin)) %>% pull(dataset)' ...
        '  d <- d %>% filter(dataset %in% keep) %>% droplevels()' ...
        '  if (n_distinct(d$dataset) < 2) next' ...
        '  tag <- str_replace_all(paste("__WINDOW_R__", "__MEASURETYPE_R__", ch, sep = "_"), "[^A-Za-z0-9]+", "_")' ...
        '' ...
        '  cat(sprintf("\n\n### %s\n\n", ch))' ...
        '  descr <- d %>% group_by(bin) %>% summarise(M = mean(value), SD = sd(value), n = n(), .groups = "drop")' ...
        '  cat(as_raw_html(apa_gt(descr, "Descriptive Statistics")))' ...
        '' ...
        '  # Per-bin, not rstatix''s grouped shapiro_test(): that pipeline' ...
        '  # (group_by %>% shapiro_test, via doo()/map()) does not catch a' ...
        '  # per-group failure -- one bin with fewer than 3 usable values' ...
        '  # aborts the WHOLE mutate()/map() call, not just that bin''s row,' ...
        '  # which crashes this entire chunk (and halts the whole render).' ...
        '  # group_modify + tryCatch isolates each bin''s own test instead.' ...
        '  shap <- d %>% group_by(bin) %>% group_modify(~ {' ...
        '    st <- tryCatch(shapiro.test(.x$value), error = function(e) NULL)' ...
        '    if (is.null(st)) tibble(statistic = NA_real_, p = NA_real_)' ...
        '    else tibble(statistic = unname(st$statistic), p = st$p.value)' ...
        '  }) %>% ungroup()' ...
        '  if (any(is.na(shap$p))) {' ...
        '    cat(sprintf("\nNormality could not be assessed for: %s (fewer than 3 usable observations, or no variability among them).\n\n",' ...
        '                paste(shap$bin[is.na(shap$p)], collapse = ", ")))' ...
        '  }' ...
        '  if (all(shap$p >= .05, na.rm = TRUE)) {' ...
        '    cat("\nShapiro-Wilk tests indicated no departure from normality in any assessable condition (all *p*s > .05).\n\n")' ...
        '  } else if (any(shap$p < .05, na.rm = TRUE)) {' ...
        '    cat(sprintf("\nShapiro-Wilk tests indicated a departure from normality in at least one condition (%s);\n",' ...
        '                paste(shap$bin[!is.na(shap$p) & shap$p < .05], collapse = ", ")))' ...
        '    cat("the Friedman test below should be considered alongside the ANOVA.\n\n")' ...
        '  }' ...
        '' ...
        '  aov <- tryCatch(anova_test(data = d, dv = value, wid = dataset, within = bin), error = function(e) NULL)' ...
        '  p_bin <- NA_real_' ...
        '  if (!is.null(aov)) {' ...
        '    tab <- get_anova_table(aov)' ...
        '    if ("bin" %in% tab$Effect) {' ...
        '      binRow <- tab[tab$Effect == "bin", ][1, ]' ...
        '      p_bin <- binRow$p' ...
        '      sig_txt <- if (p_bin < .05) "a significant" else "no significant"' ...
        '      cat(sprintf("\nA repeated-measures ANOVA (Type III sum of squares) revealed %s effect of bin,\n", sig_txt))' ...
        '      cat(sprintf("*F*(%s, %s) = %s, *p* %s, generalized eta-squared = %s.\n\n",' ...
        '                  binRow$DFn, binRow$DFd, apa_num(binRow$F), apa_p(p_bin), apa_num(binRow$ges, 3)))' ...
        '    }' ...
        '    cat(as_raw_html(apa_gt(as.data.frame(tab), "Repeated-Measures ANOVA (Type III)")))' ...
        '  }' ...
        '' ...
        '  pw   <- d %>% pairwise_t_test(value ~ bin, paired = TRUE, p.adjust.method = "holm")' ...
        '  pw_d <- d %>% cohens_d(value ~ bin, paired = TRUE)' ...
        '  sig_pw <- pw %>% left_join(pw_d, by = c("group1", "group2"), suffix = c("", ".d")) %>% filter(p.adj < .05)' ...
        '  if (nrow(sig_pw) > 0) {' ...
        '    pair_txt <- sprintf("%s vs. %s, *p* %s, Cohen''s *d~z~* = %s (%s)",' ...
        '                        sig_pw$group1, sig_pw$group2, apa_p(sig_pw$p.adj), apa_num(sig_pw$effsize), sig_pw$magnitude)' ...
        '    cat(sprintf("\nHolm-corrected pairwise comparisons showed significant differences between: %s.\n\n",' ...
        '                paste(pair_txt, collapse = "; ")))' ...
        '  } else {' ...
        '    cat("\nNo pairwise comparison survived Holm correction.\n\n")' ...
        '  }' ...
        '  cat(as_raw_html(apa_gt(pw, "Pairwise Comparisons (Holm-Corrected)")))' ...
        '' ...
        '  fr <- tryCatch(friedman_test(data = d, value ~ bin | dataset), error = function(e) NULL)' ...
        '  if (!is.null(fr)) {' ...
        '    sig_txt <- if (fr$p < .05) "was significant" else "was not significant"' ...
        '    cat(sprintf("\nA Friedman test, run as a rank-based robustness check, %s, chi-squared(%s) = %s, *p* %s.\n\n",' ...
        '                sig_txt, fr$df, apa_num(fr$statistic), apa_p(fr$p)))' ...
        '  }' ...
        '' ...
        '  omnibus <- bind_rows(omnibus, tibble(group = tag, design = "rm_anova", test = "omnibus", p = p_bin))' ...
        '' ...
        '  pw_xy <- pw %>% add_xy_position(x = "bin")' ...
        '  p <- ggplot(d, aes(bin, value)) +' ...
        '    geom_violin(fill = "#4a7fc9", alpha = 0.15, colour = "#4a7fc9", trim = FALSE, linewidth = 0.4) +' ...
        '    geom_line(aes(group = dataset), colour = "grey75", alpha = 0.5) +' ...
        '    geom_point(colour = "grey40", size = 1.4, alpha = 0.5, position = position_jitter(width = 0.04, height = 0)) +' ...
        '    stat_summary(fun = mean, geom = "point", size = 2.2, colour = "#4a7fc9") +' ...
        '    stat_summary(fun.data = mean_se, geom = "errorbar", width = 0.12, colour = "#4a7fc9") +' ...
        '    stat_pvalue_manual(pw_xy, hide.ns = TRUE, tip.length = 0.01) +' ...
        '    labs(x = "Bin", y = "__YLABEL__") +' ...
        '    theme_pubr()' ...
        '  print(p)' ...
        '  }, error = function(e) {' ...
        '    cat(sprintf("\n\n### %s\n\n*Could not be analysed: %s*\n\n", ch, conditionMessage(e)))' ...
        '  })' ...
        '}' ...
        '```' ...
        };
    text = strjoin(lines, newline);
    text = strrep(text, '__NBINS__', num2str(numel(binLabels)));
    text = strrep(text, '__CHUNKLABEL__', chunkLabel('anova', windowLabel, measureType));
    text = strrep(text, '__YLABEL__', yAxisLabel(measureType));
    block = fillCommonTokens(text, windowLabel, measureType, '', '');
end

function tf = isLatencyType(measureType)
%ISLATENCYTYPE  True when MEASURETYPE (one of measureRowTypes.m's own
%   return values: peak_amplitude, peak_latency, mean_amplitude,
%   area_signed/rectified/positive/negative, fractional_peak_latency,
%   fractional_area_latency) is a LATENCY (ms), not an amplitude or area
%   (uV / uV.ms). A combination bin's amplitude/area score has a natural
%   "zero" to test against (no difference between the conditions it
%   combines) -- but its latency does not: Measure.m computes a
%   combination bin's own fractional/peak latency on the DIFFERENCE
%   WAVEFORM itself (bin4's average minus bin3's, say), a genuine point in
%   time, not an arithmetic difference of two separately-measured
%   latencies -- so "is this latency significantly different from 0 ms"
%   has no meaningful null hypothesis behind it. See comboSection's own
%   header comment for how this changes what gets reported.
    tf = any(strcmp(measureType, {'peak_latency', 'fractional_peak_latency', 'fractional_area_latency'}));
end

function s = yAxisLabel(measureType)
%YAXISLABEL  A plot's y-axis label for MEASURETYPE: "Latency (ms)" for a
%   latency measure type (see isLatencyType), "Value" otherwise. An
%   amplitude/area's own physical unit (uV or uV.ms) depends on the
%   recording's own calibration, which this generator has no way to know,
%   so "Value" stays the honest, accurate default there -- but a latency
%   is always ms regardless of calibration, so it can always be labelled.
    if isLatencyType(measureType)
        s = 'Latency (ms)';
    else
        s = 'Value';
    end
end

function block = comboSection(windowLabel, measureType, comboLabel, recipeText)
%COMBOSECTION  One combination (difference) bin. For an amplitude/area
%   measure type: a one-sample t-test (and Wilcoxon) against zero -- run
%   entirely separately from the omnibus test above, never as one more
%   level within it (see this file's own header comment for why that
%   would be statistically invalid). For a LATENCY measure type (see
%   isLatencyType): descriptive statistics only, no test -- zero has no
%   meaningful interpretation as "no effect" for a latency the way it
%   does for an amplitude/area difference.
    if isLatencyType(measureType)
        block = comboSectionDescriptiveOnly(windowLabel, measureType, comboLabel, recipeText);
        return;
    end
    lines = { ...
        '## __WINDOW_MD__ -- __MEASURETYPE_MD__: __COMBOLABEL_MD__' ...
        '' ...
        'Difference/combination bin "__COMBOLABEL_MD__" (__RECIPE_MD__). Tested against zero, not folded' ...
        'into any omnibus test over the ordinary bins above, since its own scores are a linear' ...
        'combination of the other bins'' scores, not an independent condition.' ...
        '' ...
        '```{r}' ...
        '#| label: __CHUNKLABEL__' ...
        '#| results: asis' ...
        'grp <- dat %>% filter(measure_type == "__MEASURETYPE_R__", window == "__WINDOW_R__", bin == "__COMBOLABEL_R__") %>% droplevels()' ...
        '' ...
        'for (ch in unique(grp$channel)) {' ...
        '  # The whole per-channel body is one tryCatch: an unanticipated' ...
        '  # error on ONE channel would otherwise abort this entire chunk --' ...
        '  # and, since Quarto halts the whole render on any chunk error,' ...
        '  # every section after it too -- rather than just costing this one' ...
        '  # channel''s own results.' ...
        '  tryCatch({' ...
        '  # !is.na(value): a combination bin is left NA per Average.m/Measure.m' ...
        '  # for a subject it could not resolve (see Measure.m''s own header' ...
        '  # comment) without dropping that subject''s row entirely, so' ...
        '  # n_distinct(dataset) below must be counted AFTER this filter, not' ...
        '  # before, or a subject with an unusable NA value still counts as' ...
        '  # "present".' ...
        '  d <- grp %>% filter(channel == ch, !is.na(value))' ...
        '  if (n_distinct(d$dataset) < 2) next' ...
        '  tag <- str_replace_all(paste("__WINDOW_R__", "__MEASURETYPE_R__", "__COMBOLABEL_R__", ch, sep = "_"), "[^A-Za-z0-9]+", "_")' ...
        '' ...
        '  # Base R''s shapiro.test(), not rstatix''s shapiro_test(): the latter''s' ...
        '  # tidied $p column is only reliable for its GROUPED (data %>%' ...
        '  # group_by() %>% shapiro_test()) form -- called on a bare vector it can' ...
        '  # come back without a $p column at all. Base shapiro.test() has a' ...
        '  # stable list return ($statistic, $p.value); tryCatch handles the' ...
        '  # genuine edge cases it errors on outright (n < 3, zero variance)' ...
        '  # rather than relying on any particular empty-result shape.' ...
        '  shap <- tryCatch(shapiro.test(d$value), error = function(e) NULL)' ...
        '  tt <- t.test(d$value, mu = 0)' ...
        '  wt <- wilcox.test(d$value, mu = 0)' ...
        '' ...
        '  cat(sprintf("\n\n### %s\n\n", ch))' ...
        '  descr <- d %>% summarise(M = mean(value), SD = sd(value), n = n())' ...
        '  cat(as_raw_html(apa_gt(descr, "Descriptive Statistics")))' ...
        '' ...
        '  if (is.null(shap)) {' ...
        '    cat("\nNormality of __COMBOLABEL_MD__ could not be assessed (fewer than 3 usable observations, or no variability among them).\n\n")' ...
        '  } else {' ...
        '    normal_txt <- if (shap$p.value >= .05) "did not depart from normality" else "departed from normality (consider the Wilcoxon test below)"' ...
        '    cat(sprintf("\nA Shapiro-Wilk test indicated __COMBOLABEL_MD__ %s, *W* = %s, *p* %s.\n\n",' ...
        '                normal_txt, apa_num(unname(shap$statistic)), apa_p(shap$p.value)))' ...
        '  }' ...
        '' ...
        '  sig_txt <- if (tt$p.value < .05) "differed significantly" else "did not differ significantly"' ...
        '  cat(sprintf("\nA one-sample *t*-test found __COMBOLABEL_MD__ %s from zero, *t*(%d) = %s, *p* %s,\n",' ...
        '              sig_txt, round(tt$parameter), apa_num(tt$statistic), apa_p(tt$p.value)))' ...
        '  cat(sprintf("*M* = %s. A Wilcoxon signed-rank test, run as a robustness check alongside it,\n", apa_num(mean(d$value))))' ...
        '  cat(sprintf("gave *V* = %s, *p* %s.\n\n", apa_num(wt$statistic), apa_p(wt$p.value)))' ...
        '' ...
        '  omnibus <- bind_rows(omnibus, tibble(group = tag, design = "one_sample_vs_0", test = "one_sample_t_test", p = tt$p.value))' ...
        '' ...
        '  p <- ggplot(d, aes(x = 1, y = value)) +' ...
        '    geom_violin(aes(group = 1), fill = "#4a7fc9", alpha = 0.15, colour = "#4a7fc9",' ...
        '                trim = FALSE, linewidth = 0.4, width = 0.6) +' ...
        '    geom_jitter(width = 0.05, colour = "grey40", alpha = 0.6) +' ...
        '    geom_hline(yintercept = 0, linetype = "dashed", colour = "grey50") +' ...
        '    stat_summary(fun = mean, geom = "point", size = 3, colour = "#4a7fc9") +' ...
        '    stat_summary(fun.data = mean_se, geom = "errorbar", width = 0.1, colour = "#4a7fc9") +' ...
        '    labs(x = NULL, y = "__YLABEL__") +' ...
        '    scale_x_continuous(breaks = NULL) +' ...
        '    theme_pubr()' ...
        '  print(p)' ...
        '  }, error = function(e) {' ...
        '    cat(sprintf("\n\n### %s\n\n*Could not be analysed: %s*\n\n", ch, conditionMessage(e)))' ...
        '  })' ...
        '}' ...
        '```' ...
        };
    text = strjoin(lines, newline);
    text = fillToken(text, 'COMBOLABEL', comboLabel);
    text = fillToken(text, 'RECIPE', recipeText);
    text = strrep(text, '__CHUNKLABEL__', chunkLabel('combo', windowLabel, measureType, comboLabel));
    text = strrep(text, '__YLABEL__', yAxisLabel(measureType));
    block = fillCommonTokens(text, windowLabel, measureType, '', '');
end

function block = comboSectionDescriptiveOnly(windowLabel, measureType, comboLabel, recipeText)
%COMBOSECTIONDESCRIPTIVEONLY  A combination bin's own LATENCY measure type
%   (see isLatencyType): descriptive statistics and a plot only, no
%   one-sample-vs-zero test and no contribution to the cross-group
%   omnibus summary -- there is no meaningful null hypothesis "this
%   latency equals 0 ms" the way there is for an amplitude/area
%   difference, so nothing here is a test result to report or correct
%   for multiple comparisons.
    lines = { ...
        '## __WINDOW_MD__ -- __MEASURETYPE_MD__: __COMBOLABEL_MD__' ...
        '' ...
        'Difference/combination bin "__COMBOLABEL_MD__" (__RECIPE_MD__). A latency has no natural' ...
        '"zero" to test against the way an amplitude/area difference does (zero would mean "no' ...
        'difference"; a latency near 0 ms means nothing of the kind), so only descriptive' ...
        'statistics are reported here.' ...
        '' ...
        '```{r}' ...
        '#| label: __CHUNKLABEL__' ...
        '#| results: asis' ...
        'grp <- dat %>% filter(measure_type == "__MEASURETYPE_R__", window == "__WINDOW_R__", bin == "__COMBOLABEL_R__") %>% droplevels()' ...
        '' ...
        'for (ch in unique(grp$channel)) {' ...
        '  tryCatch({' ...
        '  d <- grp %>% filter(channel == ch, !is.na(value))' ...
        '  if (n_distinct(d$dataset) < 2) next' ...
        '' ...
        '  cat(sprintf("\n\n### %s\n\n", ch))' ...
        '  descr <- d %>% summarise(M = mean(value), SD = sd(value), n = n())' ...
        '  cat(sprintf("*M* = %s ms, *SD* = %s ms, *n* = %d.\n\n", apa_num(descr$M), apa_num(descr$SD), descr$n))' ...
        '  cat(as_raw_html(apa_gt(descr, "Descriptive Statistics")))' ...
        '' ...
        '  p <- ggplot(d, aes(x = 1, y = value)) +' ...
        '    geom_violin(aes(group = 1), fill = "#4a7fc9", alpha = 0.15, colour = "#4a7fc9",' ...
        '                trim = FALSE, linewidth = 0.4, width = 0.6) +' ...
        '    geom_jitter(width = 0.05, colour = "grey40", alpha = 0.6) +' ...
        '    stat_summary(fun = mean, geom = "point", size = 3, colour = "#4a7fc9") +' ...
        '    stat_summary(fun.data = mean_se, geom = "errorbar", width = 0.1, colour = "#4a7fc9") +' ...
        '    labs(x = NULL, y = "Latency (ms)") +' ...
        '    scale_x_continuous(breaks = NULL) +' ...
        '    theme_pubr()' ...
        '  print(p)' ...
        '  }, error = function(e) {' ...
        '    cat(sprintf("\n\n### %s\n\n*Could not be analysed: %s*\n\n", ch, conditionMessage(e)))' ...
        '  })' ...
        '}' ...
        '```' ...
        };
    text = strjoin(lines, newline);
    text = fillToken(text, 'COMBOLABEL', comboLabel);
    text = fillToken(text, 'RECIPE', recipeText);
    text = strrep(text, '__CHUNKLABEL__', chunkLabel('combo-desc', windowLabel, measureType, comboLabel));
    block = fillCommonTokens(text, windowLabel, measureType, '', '');
end

function text = closingText()
    lines = { ...
        '## Summary Across All Tests' ...
        '' ...
        '```{r}' ...
        '#| label: summary-all-tests' ...
        '#| results: asis' ...
        'if (nrow(omnibus) > 0) {' ...
        '  omnibus2 <- omnibus %>% filter(!is.na(p)) %>% mutate(p_bh = p.adjust(p, method = "BH"))' ...
        '  cat(sprintf("\nAcross %d test(s), %d were significant at *p* < .05 uncorrected, and %d remained\n",' ...
        '              nrow(omnibus2), sum(omnibus2$p < .05, na.rm = TRUE), sum(omnibus2$p_bh < .05, na.rm = TRUE)))' ...
        '  cat("significant after Benjamini-Hochberg (BH/FDR) correction across all of them.\n\n")' ...
        '  cat(as_raw_html(apa_gt(omnibus2, "Summary of All Tests (BH-Corrected)")))' ...
        '} else {' ...
        '  cat("\nNo tests were run.\n\n")' ...
        '}' ...
        '```' ...
        };
    text = strjoin(lines, newline);
end
