function qmdText = generateQuartoReport(entries, csvFileName, sourceEstimates, grandAverageCsv, trialCsv, spectraCsv)
%GENERATEQUARTOREPORT  A design-aware Quarto (.qmd) report for an exported
%   measurements CSV: rendering it (self-contained HTML) produces a short,
%   APA-styled results report -- narrative prose with inline-computed
%   statistics, APA-formatted tables (gt), and embedded plots -- rather
%   than a plain R console script.
%
%   This file is the orchestrator. It works out what design the export
%   actually has, picks one section builder per window/frequency x measure
%   type, and assembles the document (preamble + sections + closing
%   summary). The section builders themselves -- one Quarto/R template per
%   statistical design, plus the token-substitution and escaping helpers
%   they share (rLit, mdLit, fillToken, ...) -- live one-per-file in
%   +ReportSections alongside this file, and the scaffolding every Alakazam
%   report shares (YAML header, package bootstrap, APA helpers) lives in
%   +ReportDoc. So this file does not also have to be the place every R
%   template lives.
%
%   THE DESIGN IS DERIVED ONCE, at the top, and everything downstream reads
%   it rather than re-deciding:
%
%     designRecords     report entries -> the record shape deriveDesign reads
%     deriveDesign      the factors, their levels, and the cells they cross into
%     reportDesignPlan  which model that design supports, and what it gave up
%     classifyBins      ordinary vs combination bins, from EEG.bindesc
%
%   deriveDesign is the same function behind the Show Design panel, so the
%   panel and the report cannot disagree about the same recordings. Both
%   classifyBins and the plan are MATLAB-side decisions for the same
%   reason: EEG.bindesc(b).combo, the subject's group and the subject's
%   person/session are not recoverable from the flat CSV, so a generic R
%   script re-discovering the design at runtime could not make them.
%
%   WHAT EACH DESIGN GETS (see the section builders for the exact calls):
%     - 1 ordinary bin, no groups: descriptive statistics only -- no
%       comparison is possible.
%     - 1 ordinary bin, 2+ groups: a between-subjects test (Welch t /
%       Welch ANOVA + Games-Howell), betweenSection.
%     - 2 ordinary bins, nothing else: a paired t-test + Cohen's dz, with
%       a Wilcoxon signed-rank robustness check and a Shapiro-Wilk note.
%     - Any other multi-bin design: lmmSection, a linear mixed model whose
%       fixed effects come from the plan -- bin, bin * group, bin * session,
%       or (bin + session + group)^2 (every main effect and every two-way
%       interaction; the three-way is deliberately omitted). Random effect
%       (1 + bin | person_id), falling back to an intercept-only model on a
%       singular fit, and to a simpler FIXED structure, with the reason
%       printed, when the recordings cannot support session.
%     - Each COMBINATION (difference) bin, separately: a one-sample t-test
%       (and Wilcoxon) against zero -- never folded into the omnibus test
%       above, since a combination bin's scores are a linear combination of
%       the OTHER bins', not an independent condition, so including it
%       there would be statistically invalid.
%
%   An LMM rather than a repeated-measures ANOVA, throughout: a subject
%   missing one bin still contributes their other bins instead of being
%   dropped from the whole channel. Grouped by person rather than by
%   recording, so a person measured in two sessions counts once.
%
%   Every block's own key p-value also feeds one final cross-report summary
%   table, BH/FDR-corrected across every channel x window x measure group
%   the export produced, not just within one group's own pairwise tests.
%
%   The prose is results prose, not a statistics tutorial: an APA-styled
%   report states what was found ("The model revealed a significant effect
%   of bin, F(...) = ..., p = ..."), and leaves explaining what a test means
%   to the reader's own textbook.
%
%   ENTRIES is the struct array Alakazam.collectEntriesWithField produces:
%   one element per dataset, carrying .subject, .datasetType
%   ('subject'/'grand_average'), .group, .person, .session and a loaded
%   .EEG. ENTRIES(1).EEG supplies the bin structure (EEG.bindesc) plus
%   either EEG.measurements (an ERP export -- see measureRowTypes) or
%   EEG.spectralMeasures (a Spectral export -- see spectralBlocks),
%   auto-detected from whichever field is present, so onExportMeasurements
%   and onExportSpectral call this the same way. The remaining fields carry
%   the design, and reach the generated R through the CSV.
%
%   CSVFILENAME is the bare file name the report's own read_csv() call
%   references, relative to where the report itself is written.
%
%   SOURCEESTIMATES is optional: generateSourceEstimateReportAssets' own
%   return value (a struct array, possibly empty/omitted). When non-empty,
%   a "Source Estimate (Exploratory)" section is appended after the
%   statistical summary, built by ReportSections.sourceEstimateSection --
%   pure markdown (pre-rendered images, pre-computed fit percentages), so
%   accepting this argument adds no R/FieldTrip dependency to THIS
%   function; it stays exactly the text-assembly orchestrator its own
%   header already describes. Omitting the argument (every existing call
%   site does) reproduces the exact same document as before this section
%   existed -- see GenerateQuartoReportTest for the guard that pins that.
%
%   Rendering needs a working Quarto installation (https://quarto.org) and
%   R with tidyverse, rstatix, ggpubr, gt, BayesFactor, lme4, lmerTest,
%   emmeans, performance and effectsize -- the setup chunk installs
%   whichever are missing on the first render.
%
%   See also DERIVEDESIGN, REPORTDESIGNPLAN, DESIGNRECORDS,
%   EXPORTMEASUREMENTSCSV, EXPORTSPECTRALCSV, MEASUREROWTYPES,
%   GENERATESOURCEESTIMATEREPORTASSETS, REPORTSECTIONS.SOURCEESTIMATESECTION.
    if nargin < 4
        grandAverageCsv = '';
    end
    if nargin < 5
        trialCsv = '';
    end
    if nargin < 6
        spectraCsv = '';
    end
    if isempty(entries)
        throw(MException('Alakazam:generateQuartoReport', ...
            'I''m afraid generateQuartoReport needs at least one Measure result to build a report from.'));
    end
    EEG = entries(1).EEG;
    hasErp      = isfield(EEG, 'measurements') && ~isempty(EEG.measurements);
    hasSpectral = isfield(EEG, 'spectralMeasures') && ~isempty(EEG.spectralMeasures);
    if ~hasErp && ~hasSpectral
        throw(MException('Alakazam:generateQuartoReport', ...
            ['I''m afraid generateQuartoReport needs a dataset with at least one Measure window ' ...
             '(EEG.measurements) or Spectral Measure (EEG.spectralMeasures).']));
    end
    if hasErp
        reportTitle = 'ERP';
        groupColumn = 'window';
        blocks = erpBlocks(EEG);
    else
        reportTitle = 'Spectral';
        groupColumn = 'frequency_label';
        blocks = spectralBlocks(EEG);
    end

    [ordinaryLabels, comboBins] = classifyBins(EEG);

    % Between-subjects grouping (see WorkSpace.editSubjects/groupFor): a
    % MATLAB-side decision, not rediscovered per section in R, mirroring
    % how ordinaryLabels/comboBins above are also decided once here rather
    % than per chunk. >= 2 DISTINCT non-blank group labels across the
    % export's own subject entries is what actually activates the
    % between/mixed path below -- a workspace where nobody has been
    % assigned a group (or everybody shares one label) renders exactly as
    % it always has, no opt-in flag needed.
    % THE DESIGN IS DERIVED ONCE, here, and every later decision reads it.
    % reportDesignPlan settles which factors the recordings actually
    % support, the model formula that follows, and whether a richer model
    % had to be given up (which the preamble then prints, so an unestimable
    % interaction lmer would have silently mangled becomes a stated
    % limitation instead). Nothing below re-derives any of that: hasGroups
    % used to be worked out separately from the same entries, which is two
    % answers to one question and exactly one too many.
    design = deriveDesign(designRecords(entries));
    plan = reportDesignPlan(design);
    hasGroups = ~isempty(plan.betweenFactors);

    useSession = numel(plan.withinFactors) > 1;

    % A linear mixed model is what every multi-bin design gets EXCEPT the
    % plain two-bin within-subjects case, which stays a paired t-test: with
    % exactly two conditions and no other factor, the t-test is the same
    % comparison stated more simply, and it carries a Bayes factor and a
    % Wilcoxon check an LMM section does not.
    useLmm = hasGroups || useSession;

    sections = {};

    % A DESIGN WITH NO ORDINARY BINS USED TO FAIL SILENTLY. When every
    % bindesc entry carries a .combo, the dispatch below has nothing to
    % match and simply emits no omnibus section -- and said nothing about
    % it, so the document still had its headings, still rendered, and
    % still ended with a summary, while the comparison a reader would
    % assume was there was absent. The combination bins are analysed
    % perfectly well, so the report is worth producing; it just has to say
    % what it does not contain.
    if isempty(ordinaryLabels)
        sections{end + 1} = strjoin({ ...
            '## Condition comparison', ...
            '', ...
            ['This design has no ordinary condition bins: every bin defined for it is a ' ...
             'combination (difference) bin. There is therefore nothing to compare between ' ...
             'conditions, and no omnibus section appears below. The combination bins ' ...
             'themselves are analysed in full, each in its own section.'], ...
            '', ''}, newline);
    end

    for bl = 1:numel(blocks)
        blockLabel = blocks(bl).label;
        types = blocks(bl).measureTypes;

        % ONCE PER WINDOW, NOT PER MEASURE TYPE. The waveform belongs to the
        % window, not to whichever quantity was read off it: mean amplitude
        % and peak latency over 300-500 ms are two numbers from one wave, and
        % drawing it twice would say otherwise.
        if ~isempty(grandAverageCsv) && ~isempty(ordinaryLabels)
            sections{end + 1} = ReportSections.waveformSection(blockLabel, ordinaryLabels, grandAverageCsv); %#ok<AGROW>
        end

        % The spectral counterpart, once per frequency block. Only one of the
        % two can apply to any given export: a measurements CSV carries time
        % windows and a spectral one carries frequencies, and neither
        % accompanying file is written for the other kind.
        if ~isempty(spectraCsv) && ~isempty(ordinaryLabels)
            sections{end + 1} = ReportSections.spectrumSection(blockLabel, ordinaryLabels); %#ok<AGROW>
        end
        for ti = 1:numel(types)
            measureType = types{ti};

            if ReportSections.isCircularType(measureType)
                % CIRCULAR TYPES LEAVE THE LINEAR CHAIN BEFORE IT STARTS.
                % Every branch below is linear -- a t-test, a mixed model,
                % or a mean/SD -- and none of them mean anything on angles
                % that wrap at +/-pi. The combination-bin branch further
                % down has always refused these types a linear test, so
                % without this the same document could call such a test
                % invalid in one section and report it in the next.
                sections{end + 1} = ReportSections.circularSection(blockLabel, measureType, ordinaryLabels); %#ok<AGROW>
            elseif isscalar(ordinaryLabels)
                if hasGroups
                    sections{end + 1} = ReportSections.betweenSection(blockLabel, measureType, ordinaryLabels{1}); %#ok<AGROW>
                else
                    sections{end + 1} = ReportSections.descriptiveSection(blockLabel, measureType, ordinaryLabels{1}); %#ok<AGROW>
                end
            elseif numel(ordinaryLabels) == 2 && ~useLmm
                sections{end + 1} = ReportSections.pairedSection(blockLabel, measureType, ordinaryLabels{1}, ordinaryLabels{2}); %#ok<AGROW>
            elseif numel(ordinaryLabels) >= 2
                % One section for every design that gets a linear mixed
                % model. Which of the four it is -- bin, bin x group,
                % bin x session, or all three two-way -- is read off the
                % plan inside lmmSection, not decided again here.
                sections{end + 1} = ReportSections.lmmSection(blockLabel, measureType, ordinaryLabels, plan); %#ok<AGROW>
            end
            % BESIDE the averaged model, never instead of it: the two answer
            % the same question from different data, and a reader comparing
            % them learns something a single number cannot say.
            if ~isempty(trialCsv) && numel(ordinaryLabels) >= 2 && ...
                    ~ReportSections.isCircularType(measureType)
                sections{end + 1} = ReportSections.singleTrialSection(blockLabel, measureType, ordinaryLabels); %#ok<AGROW>
            end

            for cb = 1:numel(comboBins)
                if hasGroups
                    % includeVsZero: skip for latency/circular types, same
                    % reason as the no-groups path (isDescriptiveOnlyType).
                    % includeBetweenGroups: skip ONLY for circular types --
                    % unlike the "vs zero" test, an ordinary linear
                    % between-groups comparison (a latency IS on a linear
                    % scale) is perfectly valid for a latency combo bin,
                    % just not for a circular one (see isCircularType).
                    sections{end + 1} = ReportSections.comboSectionGrouped(blockLabel, measureType, ...
                        comboBins(cb).label, comboBins(cb).recipeText, ...
                        ~ReportSections.isDescriptiveOnlyType(measureType), ~ReportSections.isCircularType(measureType)); %#ok<AGROW>
                else
                    sections{end + 1} = ReportSections.comboSection(blockLabel, measureType, ...
                        comboBins(cb).label, comboBins(cb).recipeText); %#ok<AGROW>
                end
            end
        end
    end

    parts = [{preambleText(csvFileName, reportTitle, groupColumn, hasGroups, plan, ...
                          grandAverageCsv, trialCsv, spectraCsv)}, {readersGuideText()}, ...
             sections, {closingText()}];
    parts = uniqueChunkLabels(parts);

    % Appended LAST, after the statistical summary, not interleaved with
    % the per-window sections above: this is an exploratory, non-
    % statistical addendum (no p-value, nothing feeds the omnibus table),
    % so it reads as a supplementary appendix to the confirmatory testing
    % above rather than as part of it. nargin < 3 (every pre-existing call
    % site) and an empty/omitted SOURCEESTIMATES both leave PARTS, and so
    % QMDTEXT, byte-for-byte identical to before this argument existed.
    if nargin >= 3 && ~isempty(sourceEstimates)
        sourceText = ReportSections.sourceEstimateSection(sourceEstimates);
        if ~isempty(sourceText)
            parts = [parts, {sourceText}];
        end
    end

    qmdText = char(strjoin(parts, [newline newline]));
end

function blocks = erpBlocks(EEG)
%ERPBLOCKS  One block per Measure window, .label/.measureTypes (from
%   measureRowTypes) -- the ERP counterpart of spectralBlocks.
    blocks = struct('label', {}, 'measureTypes', {});
    for w = 1:numel(EEG.measurements)
        win = EEG.measurements{w};
        blocks(end + 1) = struct('label', char(string(win.label)), ...
            'measureTypes', {measureRowTypes(win)}); %#ok<AGROW>
    end
end

function blocks = spectralBlocks(EEG)
%SPECTRALBLOCKS  One block per named frequency in EEG.spectralMeasures,
%   .label/.measureTypes -- the Spectral counterpart of erpBlocks. Every
%   named frequency always carries power/amplitude/snr/itc/phase (see
%   SpectralMeasure.m); coherence/phaselag are additional, only present
%   when that frequency was measured against a reference channel --
%   exactly mirroring exportSpectralCSV.m's own writeEntry, so this can
%   never claim a measure_type the CSV does not actually have a column
%   value for.
    blocks = struct('label', {}, 'measureTypes', {});
    for w = 1:numel(EEG.spectralMeasures)
        m = EEG.spectralMeasures{w};
        types = {'power', 'amplitude', 'snr', 'itc', 'phase'};
        if ~isempty(strtrim(char(string(m.refChannel))))
            types = [types, {'coherence', 'phaselag'}]; %#ok<AGROW>
        end
        blocks(end + 1) = struct('label', char(string(m.label)), 'measureTypes', {types}); %#ok<AGROW>
    end
end

% ======================================================================= %
%  Bin classification -- done in MATLAB, not R, for the same reason the
%  design is: EEG.bindesc(b).combo is not recoverable from the flat CSV
%  at all.
% ======================================================================= %
function [ordinaryLabels, comboBins] = classifyBins(EEG)
%CLASSIFYBINS  ORDINARYLABELS (cellstr, real conditions) and COMBOBINS (a
%   struct array, .label/.recipeText, one per DefineBins/Average
%   combination bin) from EEG.bindesc. A dataset with no bindesc at all
%   (an unbinned Average) is treated as one implicit ordinary bin, "1" --
%   csvBinLabel's own fallback for exactly this case, so this matches
%   whatever bin value actually ended up in the CSV.
    comboBins = struct('label', {}, 'recipeText', {});
    if ~isfield(EEG, 'bindesc') || isempty(EEG.bindesc)
        ordinaryLabels = {'1'};
        return;
    end
    bindesc = EEG.bindesc;
    isCombo = false(1, numel(bindesc));
    if isfield(bindesc, 'combo')
        isCombo = ~cellfun(@isempty, {bindesc.combo});
    end
    ordinaryLabels = {bindesc(~isCombo).label};
    for b = find(isCombo)
        comboBins(end + 1) = struct('label', char(string(bindesc(b).label)), ...
            'recipeText', comboRecipeText(bindesc, bindesc(b))); %#ok<AGROW>
    end
end

function txt = comboRecipeText(bindesc, entry)
%COMBORECIPETEXT  A combination bin's own recipe as readable text, e.g.
%   "Rare - Frequent" or "0.5*Left + 0.5*Right" -- entry.combo's own .bin
%   values are referenced bins' .index (Average.m's own convention), not
%   array positions, so they are mapped back to a label via bindesc's own
%   .index field.
    indices = [bindesc.index];
    parts = strings(1, numel(entry.combo));
    for t = 1:numel(entry.combo)
        refLabel = bindesc(indices == entry.combo(t).bin).label;
        coeff = entry.combo(t).coeff;
        if t == 1
            if coeff < 0; sgn = "-"; else; sgn = ""; end
        else
            if coeff < 0; sgn = " - "; else; sgn = " + "; end
        end
        if abs(coeff) == 1
            magTxt = "";
        else
            magTxt = string(sprintf('%.3g*', abs(coeff)));
        end
        parts(t) = sgn + magTxt + string(refLabel);
    end
    txt = char(strjoin(parts, ""));
end

function parts = uniqueChunkLabels(parts)
%UNIQUECHUNKLABELS  Make every '#| label:' in the document distinct.
%
%   ReportSections.labelPiece is lossy on purpose -- it lowercases and
%   collapses every run of non-alphanumerics to a single hyphen -- so two
%   different window or measure labels can sanitise to the same chunk
%   label. 'N400 (a)' and 'N400 [a]' both become 'n400-a'. knitr then
%   refuses the document outright at render time, and R's own parse()
%   cannot warn about it, because parse() never looks at '#|' option
%   lines: the failure arrives only once someone tries to render.
%
%   Resolved at assembly rather than in labelPiece, because uniqueness is
%   a property of the whole document and no single section can know what
%   the others chose. A repeat gets '-2', '-3' and so on appended, which
%   keeps the readable stem that makes these labels worth having.
    seen = containers.Map('KeyType', 'char', 'ValueType', 'double');
    for i = 1:numel(parts)
        lines = strsplit(parts{i}, newline);
        changed = false;
        for k = 1:numel(lines)
            token = regexp(lines{k}, '^#\|\s*label:\s*(\S+)\s*$', 'tokens', 'once');
            if isempty(token)
                continue;
            end
            label = token{1};
            if isKey(seen, label)
                seen(label) = seen(label) + 1;
                lines{k} = sprintf('#| label: %s-%d', label, seen(label));
                changed = true;
            else
                seen(label) = 1;
            end
        end
        if changed
            parts{i} = strjoin(lines, newline);
        end
    end
end

function text = readersGuideText()
%READERSGUIDETEXT  A short orientation, placed before the results.
%
%   The document now distinguishes primary from secondary tests, reports
%   estimates before verdicts, and carries Bayes factors beside p-values.
%   Each of those is a deliberate choice, and a reader who does not know
%   which choice was made can misread the numbers in a specific and
%   predictable way: treating a secondary row as an independent finding,
%   or reading a large p as evidence of no effect. Saying so once, at the
%   top, costs a paragraph and prevents both.
    lines = { ...
        '## How to read this report' ...
        '' ...
        ['Each result below is stated as an **estimate first**: which condition was larger, ' ...
         'by how much, and with what confidence interval. The test decision follows it. ' ...
         'The interval is the more useful number of the two: it says which effect sizes are ' ...
         'compatible with these data, where a *p*-value only says whether zero is among them.'] ...
        '' ...
        ['**Primary and secondary tests.** The planned condition comparisons form one family ' ...
         'and are corrected together for multiple comparisons (Benjamini-Hochberg, controlling ' ...
         'the false discovery rate). Difference-bin tests and single-trial re-analyses are ' ...
         'reported as *secondary*: they are further looks at those same hypotheses rather than ' ...
         'additional ones, so they carry an uncorrected *p* and no adjusted value. Correcting ' ...
         'across them would enlarge the family with rows that add no independent information, ' ...
         'which makes the adjustment look stricter while protecting against nothing.'] ...
        '' ...
        ['**Bayes factors** appear beside the *t*-tests because a non-significant *p* does not ' ...
         'distinguish evidence for no effect from no evidence either way. BF~10~ above 1 favours ' ...
         'a difference, below 1 favours its absence, and the accompanying word gives the ' ...
         'conventional reading of its size.'] ...
        '' ...
        ['**Effect sizes** are given with confidence intervals wherever the test provides them. ' ...
         'A standardised effect (Cohen''s *d*, partial eta-squared) is comparable across studies; ' ...
         'the raw difference in the measurement''s own units is what is interpretable in this ' ...
         'one. Both are reported where both exist.'] ...
        '' ...
        ['**What is not claimed.** These tests were run on the windows, channels and conditions ' ...
         'chosen during analysis. Where those choices were made after seeing the data, the ' ...
         '*p*-values below are optimistic in a way no correction here can repair, and the ' ...
         'estimates and intervals are the parts worth carrying forward.'] ...
        '' ''};
    text = strjoin(lines, newline);
end

function text = preambleText(csvFileName, reportTitle, groupColumn, hasGroups, plan, grandAverageCsv, trialCsv, spectraCsv)
%PREAMBLETEXT  The YAML header + setup chunk shared by every report kind.
%   REPORTTITLE ("ERP" or "Spectral") names the report in its own title
%   and intro comment. GROUPCOLUMN is the CSV column that plays "window"'s
%   role for this report kind (literally "window" for an ERP export,
%   "frequency_label" for a Spectral one -- see exportMeasurementsCSV.m/
%   exportSpectralCSV.m's own column lists). Every +ReportSections
%   section-builder function (descriptiveSection, pairedSection, ...)
%   hardcodes `window ==` in its own R filter -- rather than threading GROUPCOLUMN
%   through every one of them, the read chunk here renames GROUPCOLUMN to
%   "window" ONCE, right after read_csv, so the rest of the generated R
%   code (and every section-builder function that emits it) does not need
%   to know or care which report kind it is building for.
%
%   HASGROUPS (from the plan's own betweenFactors) does the
%   same thing for the CSV's "group" column: when true, every subject
%   with no group assigned is dropped from `dat` HERE, once, with a
%   printed diagnostic -- so betweenSection and lmmSection can both just
%   assume every remaining row already has a usable group, the same way
%   every section already assumes dataset_type == "subject" was already
%   filtered for it.
    readLines = {'dat <- read_csv(csv_file, show_col_types = FALSE) %>%'};
    if ~strcmp(groupColumn, 'window')
        readLines{end + 1} = sprintf('  rename(window = %s) %%>%%', groupColumn);
    end
    readLines = [readLines, { ...
        '  filter(dataset_type == "subject") %>%' ...
        '  mutate(dataset = factor(dataset), bin = factor(bin))' ...
        '' ...
        }];

    % THE GRAND AVERAGES, WHEN THERE ARE ANY. Read here, once, into `ga`,
    % so waveformSection can simply use it. Guarded on the file existing
    % rather than on it having been named: a report can be rendered from a
    % directory the export was moved out of, and losing the waveforms is a
    % far better outcome than an unrenderable document. Sections that use
    % `ga` all check nrow() first for the same reason.
    if isempty(grandAverageCsv)
        readLines = [readLines, {'ga <- NULL'}];
    else
        readLines = [readLines, { ...
            sprintf('ga_file <- "%s"', ReportSections.rLit(grandAverageCsv)) ...
            'ga <- if (file.exists(ga_file)) read_csv(ga_file, show_col_types = FALSE) else NULL' ...
            'if (!is.null(ga)) ga <- ga %>% mutate(bin = as.character(bin), channel = as.character(channel))' ...
            }];
    end

    % THE TRIALS, when a per-trial export accompanied this one. Same
    % best-effort guard as the grand averages: a missing file costs the
    % single-trial sections, never the document.
    if isempty(trialCsv)
        readLines = [readLines, {'tdat <- NULL'}];
    else
        readLines = [readLines, { ...
            sprintf('trial_file <- "%s"', ReportSections.rLit(trialCsv)) ...
            'tdat <- if (file.exists(trial_file)) read_csv(trial_file, show_col_types = FALSE) else NULL' ...
            'if (!is.null(tdat)) tdat <- tdat %>% filter(dataset_type == "subject") %>%' ...
            '  mutate(person_id = as.character(person_id), bin = factor(bin),' ...
            '         channel = as.character(channel))' ...
            }];
    end

    % The spectra, when a spectral export wrote them. Same best-effort guard
    % as the grand averages and the trials: a missing file costs the figure,
    % never the document.
    if isempty(spectraCsv)
        readLines = [readLines, {'spec <- NULL'}];
    else
        readLines = [readLines, { ...
            sprintf('spec_file <- "%s"', ReportSections.rLit(spectraCsv)) ...
            'spec <- if (file.exists(spec_file)) read_csv(spec_file, show_col_types = FALSE) else NULL' ...
            'if (!is.null(spec)) spec <- spec %>% filter(dataset_type == "subject") %>%' ...
            '  mutate(bin = as.character(bin), channel = as.character(channel))' ...
            }];
    end

    readLines = [readLines, { ...
        '' ...
        '# person_id and session are what make a subject a subject rather than a' ...
        '# recording (see WorkSpace.personFor/sessionFor). Both are written by every' ...
        '# current export, but a CSV produced before they existed has neither, and a' ...
        '# report should still render against one: person then falls back to the' ...
        '# recording itself, which is exactly what personFor does when nobody has' ...
        '# said otherwise, so the models below are unchanged for such a file.' ...
        'if (!"person_id" %in% names(dat)) dat$person_id <- as.character(dat$dataset)' ...
        'if (!"session" %in% names(dat)) dat$session <- ""' ...
        'dat <- dat %>%' ...
        '  mutate(person_id = as.character(person_id),' ...
        '         person_id = factor(ifelse(is.na(person_id) | person_id == "",' ...
        '                                   as.character(dataset), person_id)),' ...
        '         session = as.character(session),' ...
        '         session = ifelse(is.na(session), "", session))'}];

    lines = [ReportDoc.yamlHeader(['Alakazam ' reportTitle ' Statistical Report']), { ...
        '' ...
        '<!--' ...
        ['Alakazam: statistical report for exported ' reportTitle ' measurements.'] ...
        'Auto-generated, DESIGN-AWARE: unlike a generic report, this one was built' ...
        'specifically for this export''s own bins/windows, so each section below runs' ...
        'the test appropriate to what THAT window/measure actually has (a paired' ...
        't-test for two conditions, a repeated-measures ANOVA for three or more, a' ...
        'one-sample test against zero for a difference/combination bin), rather than' ...
        'one generic loop re-discovering the design at runtime. Edit freely: this is' ...
        'a sensible starting point, not the last word on your design or your prose.' ...
        'Render with: quarto render <this file>.qmd' ...
        '-->' ...
        '' ...
        '```{r}' ...
        '#| label: setup' ...
        '#| include: false' ...
        }, ReportDoc.packageBootstrap({'tidyverse', 'rstatix', 'ggpubr', 'gt', ...
            'BayesFactor', 'lme4', 'lmerTest', 'emmeans', 'performance', 'effectsize'}), { ...
        '' ...
        'csv_file <- "__CSVFILE_R__"'}, ...
        readLines, ...
        { ...
        '' ...
        'if (n_distinct(dat$dataset) < 2) {' ...
        '  stop("Need at least two subjects (dataset_type == subject) for statistics.")' ...
        '}' ...
        ''}, ...
        groupFilterLines(hasGroups), ...
        { ...
        '' ...
        '# One row per test run below (design/group/p, plus its own effect size' ...
        '# estimate/CI where the test provides one), so the closing section can' ...
        '# report a BH/FDR-adjusted summary ACROSS every group tested (not just' ...
        '# within one group''s own pairwise comparisons) and a forest plot of every' ...
        '# effect size alongside it. estimate/conf.low/conf.high are NA for a test' ...
        '# that does not report a CI-bearing effect size (e.g. an omnibus ANOVA''s' ...
        '# own generalized eta-squared, which rstatix does not attach a CI to).' ...
        '# group is the glued-together key kept for continuity; the four columns' ...
        '# after it are the same information taken apart, which is what makes a' ...
        '# summary row readable. A tag like "N400_mean_amplitude_N400_Cz" is' ...
        '# window + measure + contrast + channel, and the doubled "N400" there is' ...
        '# simply a combination bin sharing the window''s name -- unreadable glued,' ...
        '# obvious in columns.' ...
        'omnibus <- tibble(group = character(), window = character(), measure = character(),' ...
        '                  channel = character(), contrast = character(),' ...
        '                  design = character(), test = character(), p = double(),' ...
        '                  role = character(),' ...
        '                  estimate = double(), conf.low = double(), conf.high = double())' ...
        '' ...
        }, ReportDoc.apaHelpers(), { ...
        '# Classifies a Bayes factor (BF10, alternative over null) by conventional' ...
        '# strength-of-evidence bands (Lee & Wagenmakers, 2013, after Jeffreys, 1961)' ...
        '# and formats it -- used everywhere a Bayesian t-test runs alongside the' ...
        '# frequentist one as a robustness check, the same slot Wilcoxon/Mann-' ...
        '# Whitney/Friedman already occupy: BF10 > 1 favours the alternative' ...
        '# (H1 over H0), < 1 favours the null, so a small BF10 is itself informative' ...
        '# (evidence FOR "no effect", not just "not enough evidence for an effect")' ...
        '# in a way a non-significant p-value alone cannot say.' ...
        'apa_bf <- function(bf) {' ...
        '  if (is.na(bf)) return("NA")' ...
        '  bf10 <- if (bf < 1) 1 / bf else bf' ...
        '  band <- cut(bf10, breaks = c(0, 1, 3, 10, 30, 100, Inf),' ...
        '              labels = c("anecdotal", "anecdotal", "moderate", "strong", "very strong", "extreme"),' ...
        '              right = FALSE, include.lowest = TRUE)' ...
        '  # In words, not hypothesis labels. "moderate evidence for H1" asks the' ...
        '  # reader to remember which hypothesis was numbered which; "moderate' ...
        '  # evidence for a difference" does not.' ...
        '  favours <- if (bf >= 1) "a difference" else "no difference"' ...
        '  sprintf("%s (%s evidence for %s)", apa_num(bf, 2), as.character(band), favours)' ...
        '}' ...
        '# The violin distribution layer every per-channel plot below uses. FILL,' ...
        '# when given, is a literal colour for a single-distribution plot; omitted' ...
        '# (NULL) so the violin instead inherits the plot''s own colour/fill' ...
        '# aesthetic (e.g. aes(colour = group, fill = group)) for a multi-group plot.' ...
        '# A RAINCLOUD, not a bare violin. The violin used to sit directly' ...
        '# behind the individual points, so the density and the observations' ...
        '# that produced it obscured each other and neither could be read. Here' ...
        '# the density and a narrow box are nudged aside, leaving the points' ...
        '# clear: distribution, quartiles and raw data at once, which is what' ...
        '# lets a reader see bimodality or a single subject carrying an effect.' ...
        'violin_layers <- function(fill = NULL, nudge = 0.17) {' ...
        '  shape <- list(alpha = 0.15, trim = FALSE, linewidth = 0.4, width = 0.5,' ...
        '                position = position_nudge(x = nudge))' ...
        '  box <- list(alpha = 0.25, width = 0.09, outlier.shape = NA, linewidth = 0.4,' ...
        '              position = position_nudge(x = nudge))' ...
        '  if (!is.null(fill)) {' ...
        '    shape <- c(shape, list(fill = fill, colour = fill))' ...
        '    box <- c(box, list(fill = fill, colour = fill))' ...
        '  }' ...
        '  list(do.call(geom_violin, shape), do.call(geom_boxplot, box))' ...
        '}' ...
        '' ...
        '# THE EFFECT ITSELF, AS A PICTURE. The plots above show the conditions;' ...
        '# this shows the difference between them, which is the quantity every' ...
        '# test in this report is actually about and the only one whose' ...
        '# interval answers "how big is it". The bootstrap distribution behind' ...
        '# the interval is drawn rather than summarised, so a skewed or' ...
        '# multi-modal one cannot hide inside a symmetric-looking [lo, hi].' ...
        '#' ...
        '# The zero line is always drawn: a panel whose axis excludes zero makes' ...
        '# any effect look decisive, and where zero sits relative to the' ...
        '# interval is the whole point of the figure.' ...
        'estimation_panel <- function(values, ylab = "Mean difference", colour = "#4a7fc9") {' ...
        '  v <- values[is.finite(values)]' ...
        '  n <- length(v)' ...
        '  if (n < 3) return(NULL)' ...
        '  set.seed(20260101)' ...
        '  draws <- replicate(2000, mean(sample(v, n, replace = TRUE)))' ...
        '  ci <- unname(quantile(draws, c(0.025, 0.975)))' ...
        '  ggplot(tibble(v = draws), aes(x = 1, y = v)) +' ...
        '    geom_violin(fill = colour, colour = colour, alpha = 0.15, trim = FALSE,' ...
        '                width = 0.55, linewidth = 0.4) +' ...
        '    geom_hline(yintercept = 0, colour = "grey55", linetype = "dashed") +' ...
        '    annotate("pointrange", x = 1, y = mean(v), ymin = ci[1], ymax = ci[2],' ...
        '             colour = colour, linewidth = 0.9, size = 0.45) +' ...
        '    scale_x_continuous(breaks = NULL, limits = c(0.4, 1.6)) +' ...
        '    labs(x = NULL, y = ylab,' ...
        '         caption = sprintf("bootstrap distribution of the mean, 2000 resamples; 95%% CI [%s, %s]",' ...
        '                           apa_num(ci[1]), apa_num(ci[2]))) +' ...
        '    theme_pubr()' ...
        '}' ...
        '```' ...
        }, ...
        groupsSummaryChunk(hasGroups), ...
        designNoteLines(plan)];
    text = strrep(strjoin(lines, newline), '__CSVFILE_R__', ReportSections.rLit(csvFileName));
end

function lines = groupFilterLines(hasGroups)
%GROUPFILTERLINES  R lines (still inside the invisible setup chunk) that
%   drop every subject with no group assigned from `dat`, once, when
%   HASGROUPS -- see preambleText's own comment. {} (a no-op splice) when
%   HASGROUPS is false, so a report with no between-subjects grouping
%   generates byte-identical R to before this feature existed.
    if ~hasGroups
        lines = {};
        return;
    end
    lines = { ...
        '' ...
        '# Between-subjects group (see WorkSpace.editSubjects): every subject with' ...
        '# no group assigned is unusable for the group-based tests every section' ...
        '# below now runs, so they are set aside here, once, rather than each' ...
        '# section re-deriving the same exclusion from scratch.' ...
        'ungrouped_subjects <- dat %>% filter(is.na(group) | group == "") %>% distinct(dataset) %>% pull(dataset)' ...
        'dat <- dat %>% filter(!is.na(group), group != "") %>% mutate(group = factor(group))' ...
        'if (n_distinct(dat$group) < 2) {' ...
        '  stop("Need at least two groups with a usable subject for between-subjects/mixed statistics.")' ...
        '}'};
end

function lines = designNoteLines(plan)
%DESIGNNOTELINES  A short, visible statement of the model the report is
%   about to fit, and of anything it had to give up to fit it.
%
%   Two separate jobs. The first is ordinary courtesy: a reader should not
%   have to reverse-engineer the design from the F-tests, so when session
%   is in play the formula is printed once, near the top.
%
%   The second matters more. When session was recorded but could not be
%   used -- an empty group x session cell, a cell holding one subject, or
%   nobody actually measured twice -- reportDesignPlan drops it and this
%   prints WHY. Without that the report would quietly present a simpler
%   model as though it were the intended one, which is the failure mode
%   worth spending a paragraph to avoid: lmer does not refuse an
%   unestimable interaction so much as return something that looks fine.
%
%   Plain markdown rather than a chunk: there is nothing to compute.
    lines = {};
    if ~isempty(plan.fallbackReason)
        lines = { ...
            '' ...
            '::: {.callout-note}' ...
            '## A simpler model than the data seemed to offer' ...
            '' ...
            plan.fallbackReason ...
            ':::'};
        return;
    end
    if numel(plan.withinFactors) < 2
        return;   % no session: the sections speak for themselves
    end
    % Only a design with all three factors HAS a three-way interaction to
    % omit; saying so for a two-factor model would describe a decision that
    % was never available.
    if isempty(plan.betweenFactors)
        omissionNote = '';
    else
        omissionNote = ['The three-way interaction is deliberately omitted: `^2` fits every ' ...
            'main effect and every two-way interaction and nothing beyond. '];
    end

    lines = { ...
        '' ...
        '::: {.callout-note}' ...
        '## Design' ...
        '' ...
        ['Session is treated as a within-subjects factor. Fixed effects: `' plan.fixed ...
         '`; random effects: `' plan.random '`.'] ...
        '' ...
        [omissionNote 'Post-hoc contrasts are kept to at most one family, and only where ' ...
         'the term they follow is significant; `emmeans` is loaded and the fitted model is ' ...
         'in scope if you want to add more.'] ...
        ':::'};
end

function chunk = groupsSummaryChunk(hasGroups)
%GROUPSSUMMARYCHUNK  A short, visible chunk (unlike the invisible setup
%   chunk groupFilterLines' own logic lives in) reporting which subjects
%   were excluded for having no group, and the resulting group sizes --
%   printed once, near the top of the report, rather than leaving the
%   reader to infer it from the per-channel counts scattered through every
%   section below. {} (no chunk at all) when HASGROUPS is false.
    if ~hasGroups
        chunk = {};
        return;
    end
    chunk = { ...
        '' ...
        '```{r}' ...
        '#| label: groups-summary' ...
        '#| results: asis' ...
        'if (length(ungrouped_subjects) > 0) {' ...
        '  cat(sprintf("\n\n*Note: %d subject(s) have no group assigned and are excluded from every test below: %s.*\n\n",' ...
        '              length(ungrouped_subjects), paste(ungrouped_subjects, collapse = ", ")))' ...
        '}' ...
        'grp_sizes <- dat %>% distinct(dataset, group) %>% count(group, name = "n_subjects")' ...
        'cat(sprintf("\nBetween-subjects groups: %s.\n\n",' ...
        '            paste(sprintf("%s (*n* = %d)", grp_sizes$group, grp_sizes$n_subjects), collapse = ", ")))' ...
        '```'};
end


function text = closingText()
    lines = { ...
        '## Summary Across All Tests' ...
        '' ...
        '```{r}' ...
        '#| label: summary-all-tests' ...
        '#| results: asis' ...
        '#| fig-height: 7' ...
        'if (nrow(omnibus) > 0) {' ...
        '  # THE CORRECTION APPLIES TO ONE FAMILY, NOT TO EVERY ROW IN THE' ...
        '  # DOCUMENT. Benjamini-Hochberg assumes a family of distinct tests.' ...
        '  # The rows here are not all distinct: a two-condition design yields' ...
        '  # an omnibus on the conditions, a one-sample test of the difference' ...
        '  # bin that re-expresses the same contrast, and a single-trial model' ...
        '  # that re-analyses the same data. Correcting across those three does' ...
        '  # not control anything -- it inflates the family with rows carrying' ...
        '  # no independent information, and makes the correction look more' ...
        '  # severe than it is while protecting against nothing.' ...
        '  #' ...
        '  # So the planned condition comparisons are the PRIMARY family and are' ...
        '  # corrected together; derived and re-analysed quantities are reported' ...
        '  # as SECONDARY, with their uncorrected p and no adjusted value at' ...
        '  # all. That is what a pre-registration would say, and it keeps the' ...
        '  # adjusted numbers meaning what they claim to mean.' ...
        '  omnibus2 <- omnibus %>% filter(!is.na(p)) %>%' ...
        '    mutate(role = ifelse(is.na(role) | role == "", "primary", role))' ...
        '  prim <- omnibus2 %>% filter(role == "primary") %>%' ...
        '          mutate(p_bh = p.adjust(p, method = "BH"))' ...
        '  seco <- omnibus2 %>% filter(role != "primary") %>% mutate(p_bh = NA_real_)' ...
        '  omnibus2 <- bind_rows(prim, seco)' ...
        '' ...
        '  cat(sprintf("\nThe primary family is %d planned condition comparison(s). Of these, %d were\n",' ...
        '              nrow(prim), sum(prim$p < .05, na.rm = TRUE)))' ...
        '  cat(sprintf("significant at *p* < .05 uncorrected and %d remained significant after\n",' ...
        '              sum(prim$p_bh < .05, na.rm = TRUE)))' ...
        '  cat("Benjamini-Hochberg (BH/FDR) correction within that family.\n\n")' ...
        '  if (nrow(seco) > 0) {' ...
        '    cat(sprintf("A further %d row(s) are secondary: difference-bin tests and single-trial\n", nrow(seco)))' ...
        '    cat("re-analyses of those same contrasts. They are shown with uncorrected *p* and no\n")' ...
        '    cat("adjusted value, because they are further looks at the primary hypotheses rather\n")' ...
        '    cat("than additional ones, and folding them into the correction would control nothing.\n\n")' ...
        '  }' ...
        '  # The glued tag is dropped from the display, not from the tibble: the' ...
        '  # forest plot below still labels its points with it.' ...
        '  cat(as_raw_html(apa_gt(omnibus2 %>%' ...
        '        arrange(role != "primary", p) %>%' ...
        '        select(-any_of(c("group", "estimate", "conf.low", "conf.high"))) %>%' ...
        '        mutate(contrast = ifelse(is.na(contrast), "--", contrast)),' ...
        '                         "Summary of All Tests (primary family BH-corrected)")))' ...
        '' ...
        '  # A forest plot alongside the table: every test''s own point effect-size' ...
        '  # estimate, with its CI where the test provides one. The LMM-based' ...
        '  # designs (lmmSection) convert their own F-test into a' ...
        '  # partial eta-squared WITH a CI (effectsize::F_to_eta2, via the' ...
        '  # noncentral F -- Steiger, 2004) specifically so this plot has a real' ...
        '  # interval to draw rather than a lone dot; a handful of other omnibus' ...
        '  # designs still have no CI-bearing effect size logged at all (e.g. a' ...
        '  # 3+-group Welch ANOVA''s own omnibus row), so those points show with no' ...
        '  # whisker and na.rm=TRUE silences the resulting "removed N rows" warning.' ...
        '  # Faceted by effect-size TYPE, not shown on one shared axis -- Cohen''s d' ...
        '  # and eta-squared are different scales with different meanings of "0", so' ...
        '  # plotting them on the same x-axis would visually imply they are' ...
        '  # comparable when they are not.' ...
        '  if (any(!is.na(omnibus2$estimate))) {' ...
        '    omnibus_fp <- omnibus2 %>%' ...
        '      mutate(' ...
        '        effect_type = case_when(' ...
        '          design %in% c("paired_t", "one_sample_vs_0", "indep_t") ~ "Cohen''s d / dz",' ...
        '          test %in% c("welch_t_test") ~ "Cohen''s d / dz",' ...
        ... % Matched by PREFIX, not by an explicit list: lmm_session was added
        ... % as a design and this list was not updated with it, so a session
        ... % report's partial eta-squared was labelled "effect size" and
        ... % faceted away from the other LMM effects it belongs beside.
        '          str_detect(design, "^lmm_") ~ "Partial eta-sq. (LMM)",' ...
        '          TRUE ~ "effect size"' ...
        '        ),' ...
        '        label_short = str_trunc(group, 40)' ...
        '      )' ...
        '    fp <- ggplot(omnibus_fp, aes(x = estimate, y = reorder(label_short, estimate), xmin = conf.low, xmax = conf.high)) +' ...
        '      geom_vline(xintercept = 0, linetype = "dashed", colour = "grey60") +' ...
        '      geom_pointrange(colour = "#4a7fc9", size = 0.3, na.rm = TRUE) +' ...
        '      facet_wrap(~ effect_type, scales = "free", ncol = 1) +' ...
        '      labs(x = "Effect size (point estimate, 95% CI where available)", y = NULL) +' ...
        '      theme_pubr(base_size = 9) +' ...
        '      theme(axis.text.y = element_text(size = 7),' ...
        '            strip.background = element_rect(fill = "#4a7fc9", colour = NA),' ...
        '            strip.text = element_text(colour = "white", face = "bold"))' ...
        '    print(fp)' ...
        '  }' ...
        '} else {' ...
        '  cat("\nNo tests were run.\n\n")' ...
        '}' ...
        '```' ...
        };
    text = strjoin(lines, newline);
end
