function qmdText = generateQuartoReport(entries, csvFileName)
%GENERATEQUARTOREPORT  A design-aware Quarto (.qmd) report for an exported
%   measurements CSV: rendering it (self-contained HTML) produces a short,
%   APA-styled results report -- narrative prose with inline-computed
%   statistics, APA-formatted tables (gt), and embedded plots -- rather
%   than a plain R console script. Replaces the earlier generateRScript.m,
%   which this supersedes: same design-aware bin classification and
%   rstatix computations underneath (see the +ReportSections package's own
%   section-builder functions), only the OUTPUT layer changed, from
%   cat()/print() console text to Quarto markdown + APA prose.
%
%   This file stays the orchestrator: deciding what design each window/
%   frequency actually has (classifyBins, distinctGroups) and assembling
%   the final document (preambleText + one section per design +
%   closingText). The section builders themselves -- one Quarto/R text
%   template per statistical design, plus the token-substitution/escaping
%   helpers they share (rLit, mdLit, fillToken, ...) -- live one-per-file
%   in +ReportSections, alongside this file (src/IO/), so this file does
%   not also have to be the place every rstatix call and every R code
%   template lives.
%
%   Design (see +ReportSections' own section-builder functions for the
%   exact rstatix calls, unchanged from generateRScript.m's own choices):
%     - 1 ordinary bin: descriptive statistics only -- no comparison is
%       possible.
%     - 2 ordinary bins: a paired t-test + Cohen's dz, with a Wilcoxon
%       signed-rank robustness check and a Shapiro-Wilk normality note.
%     - 3+ ordinary bins: a linear mixed model (subject random intercept
%       and slope for bin) + Holm-corrected model-based pairwise contrasts
%       (emmeans), with a Friedman test robustness check -- an LMM, not a
%       repeated-measures ANOVA, specifically so a subject missing one bin
%       still contributes their other bins instead of being dropped from
%       the whole channel (see anovaSection's own header comment).
%     - Each COMBINATION (difference) bin, separately: a one-sample
%       t-test (and Wilcoxon) against zero -- never folded into the
%       omnibus test above, since a combination bin's scores are a linear
%       combination of the OTHER bins', not an independent condition, so
%       including it there would be statistically invalid.
%   Every block's own key p-value also feeds one final cross-group
%   summary table, BH/FDR-corrected across every channel x window x
%   measure group the export produced, not just within one group's own
%   pairwise tests.
%
%   Unlike an APA manuscript's usual terse, no-explanation results prose,
%   generateRScript.m's own console version also carried short "what does
%   this test mean" explainer text throughout, aimed at a reader learning
%   the statistics alongside the results -- deliberately dropped here:
%   an APA-styled report reads as results prose (a repeated-measures
%   ANOVA revealed a significant effect of bin, F(...) = ..., p = ...),
%   not a statistics tutorial.
%
%   ENTRIES/CSVFILENAME: see generateRScript.m's own header comment for
%   both (unchanged) -- ENTRIES(1).EEG carries the bin/design structure
%   (EEG.bindesc) plus either EEG.measurements (an ERP export -- see
%   measureRowTypes) or EEG.spectralMeasures (a Spectral export -- see
%   spectralBlocks), auto-detected from whichever field is present so
%   both onExportMeasurements and onExportSpectral can call this the same
%   way. CSVFILENAME is the bare file name the report's own read_csv()
%   call references, relative to where the report itself is written.
%
%   Requires the R packages tidyverse, rstatix, ggpubr and gt (auto-
%   installed by the report's own setup chunk on first render) plus a
%   working Quarto installation (https://quarto.org) to actually render
%   the .qmd this function returns into HTML.
%
%   See also EXPORTMEASUREMENTSCSV, EXPORTSPECTRALCSV, MEASUREROWTYPES,
%   MEASUREROWVALUE.
    if isempty(entries)
        throw(MException('Alakazam:generateQuartoReport', ...
            'I''m afraid generateQuartoReport needs at least one Measure result to build a report from.'));
    end
    EEG = entries(1).EEG;
    hasErp      = isfield(EEG, 'measurements') && ~isempty(EEG.measurements);
    hasSpectral = isfield(EEG, 'spectralMeasures') && ~isempty(EEG.spectralMeasures);
    if ~hasErp && ~hasSpectral
        throw(MException('Alakazam:generateQuartoReport', ...
            ['I''m afraid generateQuartoReport needs a dataset with at least one Measure window ' ...
             '(EEG.measurements) or Spectral Measure (EEG.spectralMeasures).']));
    end
    if hasErp
        reportTitle = 'ERP';
        groupColumn = 'window';
        blocks = erpBlocks(EEG);
    else
        reportTitle = 'Spectral';
        groupColumn = 'frequency_label';
        blocks = spectralBlocks(EEG);
    end

    [ordinaryLabels, comboBins] = classifyBins(EEG);

    % Between-subjects grouping (see WorkSpace.editSubjects/groupFor): a
    % MATLAB-side decision, not rediscovered per section in R, mirroring
    % how ordinaryLabels/comboBins above are also decided once here rather
    % than per chunk. >= 2 DISTINCT non-blank group labels across the
    % export's own subject entries is what actually activates the
    % between/mixed path below -- a workspace where nobody has been
    % assigned a group (or everybody shares one label) renders exactly as
    % it always has, no opt-in flag needed.
    hasGroups = numel(distinctGroups(entries)) >= 2;

    sections = {};
    for bl = 1:numel(blocks)
        blockLabel = blocks(bl).label;
        types = blocks(bl).measureTypes;
        for ti = 1:numel(types)
            measureType = types{ti};

            if numel(ordinaryLabels) == 1
                if hasGroups
                    sections{end + 1} = ReportSections.betweenSection(blockLabel, measureType, ordinaryLabels{1}); %#ok<AGROW>
                else
                    sections{end + 1} = ReportSections.descriptiveSection(blockLabel, measureType, ordinaryLabels{1}); %#ok<AGROW>
                end
            elseif numel(ordinaryLabels) == 2
                if hasGroups
                    sections{end + 1} = ReportSections.mixedSection(blockLabel, measureType, ordinaryLabels); %#ok<AGROW>
                else
                    sections{end + 1} = ReportSections.pairedSection(blockLabel, measureType, ordinaryLabels{1}, ordinaryLabels{2}); %#ok<AGROW>
                end
            elseif numel(ordinaryLabels) >= 3
                if hasGroups
                    sections{end + 1} = ReportSections.mixedSection(blockLabel, measureType, ordinaryLabels); %#ok<AGROW>
                else
                    sections{end + 1} = ReportSections.anovaSection(blockLabel, measureType, ordinaryLabels); %#ok<AGROW>
                end
            end
            for cb = 1:numel(comboBins)
                if hasGroups
                    % includeVsZero: skip for latency/circular types, same
                    % reason as the no-groups path (isDescriptiveOnlyType).
                    % includeBetweenGroups: skip ONLY for circular types --
                    % unlike the "vs zero" test, an ordinary linear
                    % between-groups comparison (a latency IS on a linear
                    % scale) is perfectly valid for a latency combo bin,
                    % just not for a circular one (see isCircularType).
                    sections{end + 1} = ReportSections.comboSectionGrouped(blockLabel, measureType, ...
                        comboBins(cb).label, comboBins(cb).recipeText, ...
                        ~ReportSections.isDescriptiveOnlyType(measureType), ~ReportSections.isCircularType(measureType)); %#ok<AGROW>
                else
                    sections{end + 1} = ReportSections.comboSection(blockLabel, measureType, ...
                        comboBins(cb).label, comboBins(cb).recipeText); %#ok<AGROW>
                end
            end
        end
    end

    parts = [{preambleText(csvFileName, reportTitle, groupColumn, hasGroups)}, sections, {closingText()}];
    qmdText = char(strjoin(parts, [newline newline]));
end

function labels = distinctGroups(entries)
%DISTINCTGROUPS  Every distinct, non-blank .group value across ENTRIES'
%   own 'subject' rows (a grand_average entry's .group is always '', see
%   collectEntriesWithField, so it never contributes a spurious group of
%   its own here).
    isSubject = strcmp({entries.datasetType}, 'subject');
    subjectGroups = {entries(isSubject).group};
    labels = unique(subjectGroups(~cellfun(@isempty, subjectGroups)));
end

function blocks = erpBlocks(EEG)
%ERPBLOCKS  One block per Measure window, .label/.measureTypes (from
%   measureRowTypes) -- the ERP counterpart of spectralBlocks.
    blocks = struct('label', {}, 'measureTypes', {});
    for w = 1:numel(EEG.measurements)
        win = EEG.measurements{w};
        blocks(end + 1) = struct('label', char(string(win.label)), ...
            'measureTypes', {measureRowTypes(win)}); %#ok<AGROW>
    end
end

function blocks = spectralBlocks(EEG)
%SPECTRALBLOCKS  One block per named frequency in EEG.spectralMeasures,
%   .label/.measureTypes -- the Spectral counterpart of erpBlocks. Every
%   named frequency always carries power/amplitude/snr/itc/phase (see
%   SpectralMeasure.m); coherence/phaselag are additional, only present
%   when that frequency was measured against a reference channel --
%   exactly mirroring exportSpectralCSV.m's own writeEntry, so this can
%   never claim a measure_type the CSV does not actually have a column
%   value for.
    blocks = struct('label', {}, 'measureTypes', {});
    for w = 1:numel(EEG.spectralMeasures)
        m = EEG.spectralMeasures{w};
        types = {'power', 'amplitude', 'snr', 'itc', 'phase'};
        if ~isempty(strtrim(char(string(m.refChannel))))
            types = [types, {'coherence', 'phaselag'}]; %#ok<AGROW>
        end
        blocks(end + 1) = struct('label', char(string(m.label)), 'measureTypes', {types}); %#ok<AGROW>
    end
end

% ======================================================================= %
%  Bin classification -- identical to generateRScript.m's own (the whole
%  point of doing this in MATLAB, not R): EEG.bindesc(b).combo is not
%  recoverable from the flat CSV at all.
% ======================================================================= %
function [ordinaryLabels, comboBins] = classifyBins(EEG)
%CLASSIFYBINS  ORDINARYLABELS (cellstr, real conditions) and COMBOBINS (a
%   struct array, .label/.recipeText, one per DefineBins/Average
%   combination bin) from EEG.bindesc. A dataset with no bindesc at all
%   (an unbinned Average) is treated as one implicit ordinary bin, "1" --
%   csvBinLabel's own fallback for exactly this case, so this matches
%   whatever bin value actually ended up in the CSV.
    comboBins = struct('label', {}, 'recipeText', {});
    if ~isfield(EEG, 'bindesc') || isempty(EEG.bindesc)
        ordinaryLabels = {'1'};
        return;
    end
    bindesc = EEG.bindesc;
    isCombo = false(1, numel(bindesc));
    if isfield(bindesc, 'combo')
        isCombo = ~cellfun(@isempty, {bindesc.combo});
    end
    ordinaryLabels = {bindesc(~isCombo).label};
    for b = find(isCombo)
        comboBins(end + 1) = struct('label', char(string(bindesc(b).label)), ...
            'recipeText', comboRecipeText(bindesc, bindesc(b))); %#ok<AGROW>
    end
end

function txt = comboRecipeText(bindesc, entry)
%COMBORECIPETEXT  A combination bin's own recipe as readable text, e.g.
%   "Rare - Frequent" or "0.5*Left + 0.5*Right" -- entry.combo's own .bin
%   values are referenced bins' .index (Average.m's own convention), not
%   array positions, so they are mapped back to a label via bindesc's own
%   .index field.
    indices = [bindesc.index];
    parts = strings(1, numel(entry.combo));
    for t = 1:numel(entry.combo)
        refLabel = bindesc(indices == entry.combo(t).bin).label;
        coeff = entry.combo(t).coeff;
        if t == 1
            if coeff < 0; sgn = "-"; else; sgn = ""; end
        else
            if coeff < 0; sgn = " - "; else; sgn = " + "; end
        end
        if abs(coeff) == 1
            magTxt = "";
        else
            magTxt = string(sprintf('%.3g*', abs(coeff)));
        end
        parts(t) = sgn + magTxt + string(refLabel);
    end
    txt = char(strjoin(parts, ""));
end

function text = preambleText(csvFileName, reportTitle, groupColumn, hasGroups)
%PREAMBLETEXT  The YAML header + setup chunk shared by every report kind.
%   REPORTTITLE ("ERP" or "Spectral") names the report in its own title
%   and intro comment. GROUPCOLUMN is the CSV column that plays "window"'s
%   role for this report kind (literally "window" for an ERP export,
%   "frequency_label" for a Spectral one -- see exportMeasurementsCSV.m/
%   exportSpectralCSV.m's own column lists). Every +ReportSections
%   section-builder function (descriptiveSection, pairedSection, ...)
%   hardcodes `window ==` in its own R filter -- rather than threading GROUPCOLUMN
%   through every one of them, the read chunk here renames GROUPCOLUMN to
%   "window" ONCE, right after read_csv, so the rest of the generated R
%   code (and every section-builder function that emits it) does not need
%   to know or care which report kind it is building for.
%
%   HASGROUPS (see generateQuartoReport's own distinctGroups) does the
%   same thing for the CSV's "group" column: when true, every subject
%   with no group assigned is dropped from `dat` HERE, once, with a
%   printed diagnostic -- so betweenSection/mixedSection can both just
%   assume every remaining row already has a usable group, the same way
%   every section already assumes dataset_type == "subject" was already
%   filtered for it.
    readLines = {'dat <- read_csv(csv_file, show_col_types = FALSE) %>%'};
    if ~strcmp(groupColumn, 'window')
        readLines{end + 1} = sprintf('  rename(window = %s) %%>%%', groupColumn);
    end
    readLines = [readLines, { ...
        '  filter(dataset_type == "subject") %>%' ...
        '  mutate(dataset = factor(dataset), bin = factor(bin))'}];

    lines = [{ ...
        '---' ...
        ['title: "Alakazam ' reportTitle ' Statistical Report"'] ...
        'format:' ...
        '  html:' ...
        '    self-contained: true' ...
        '    toc: true' ...
        '    theme: cosmo' ...
        '    include-in-header:' ...
        '      text: |' ...
        '        <meta name="color-scheme" content="light">' ...
        '        <style>' ...
        '          :root { color-scheme: light !important; }' ...
        '          html, body { background-color: #ffffff !important; }' ...
        '          #TOC, .sidebar, .toc-actions { background-color: #ffffff !important; }' ...
        '        </style>' ...
        'execute:' ...
        '  echo: false' ...
        '  warning: false' ...
        '  message: false' ...
        '---' ...
        '' ...
        '<!--' ...
        ['Alakazam -- statistical report for exported ' reportTitle ' measurements.'] ...
        'Auto-generated, DESIGN-AWARE: unlike a generic report, this one was built' ...
        'specifically for this export''s own bins/windows -- each section below runs' ...
        'the test appropriate to what THAT window/measure actually has (a paired' ...
        't-test for two conditions, a repeated-measures ANOVA for three or more, a' ...
        'one-sample test against zero for a difference/combination bin), rather than' ...
        'one generic loop re-discovering the design at runtime. Edit freely: this is' ...
        'a sensible starting point, not the last word on your design or your prose.' ...
        'Render with: quarto render <this file>.qmd' ...
        '-->' ...
        '' ...
        '```{r}' ...
        '#| label: setup' ...
        '#| include: false' ...
        'pkgs <- c("tidyverse", "rstatix", "ggpubr", "gt", "BayesFactor",' ...
        '          "lme4", "lmerTest", "emmeans", "performance", "effectsize")' ...
        'missing <- pkgs[!pkgs %in% rownames(installed.packages())]' ...
        'if (length(missing)) install.packages(missing, repos = "https://cloud.r-project.org")' ...
        'invisible(lapply(pkgs, library, character.only = TRUE))' ...
        '' ...
        'csv_file <- "__CSVFILE_R__"'}, ...
        readLines, ...
        { ...
        '' ...
        'if (n_distinct(dat$dataset) < 2) {' ...
        '  stop("Need at least two subjects (dataset_type == subject) for statistics.")' ...
        '}' ...
        ''}, ...
        groupFilterLines(hasGroups), ...
        { ...
        '' ...
        '# One row per test run below (design/group/p, plus its own effect size' ...
        '# estimate/CI where the test provides one), so the closing section can' ...
        '# report a BH/FDR-adjusted summary ACROSS every group tested (not just' ...
        '# within one group''s own pairwise comparisons) and a forest plot of every' ...
        '# effect size alongside it. estimate/conf.low/conf.high are NA for a test' ...
        '# that does not report a CI-bearing effect size (e.g. an omnibus ANOVA''s' ...
        '# own generalized eta-squared, which rstatix does not attach a CI to).' ...
        'omnibus <- tibble(group = character(), design = character(), test = character(), p = double(),' ...
        '                  estimate = double(), conf.low = double(), conf.high = double())' ...
        '' ...
        '# ---- APA-style formatting helpers ----' ...
        '# apa_p/apa_num both drop the leading zero APA convention omits for any' ...
        '# statistic that cannot exceed 1 in magnitude (p, r, eta-squared, ...) --' ...
        '# and, since the regex only matches a value that STARTS with "0.", leave a' ...
        '# statistic that CAN exceed 1 (t, F, M, SD, ...) untouched, so one helper' ...
        '# serves both without the caller having to say which kind of number it is.' ...
        '# Vectorised (ifelse, not if): called on a single test statistic in most' ...
        '# sections, but on a whole column at once (e.g. sig_pw$p.adj, one row per' ...
        '# significant pair) when narrating the ANOVA''s pairwise comparisons -- a' ...
        '# scalar if() on a length > 1 vector is a hard error as of R >= 4.2/4.3.' ...
        'apa_p <- function(p) {' ...
        '  ifelse(is.na(p), "= NA",' ...
        '    ifelse(p < .001, "< .001",' ...
        '      paste("=", sub("^0\\.", ".", sprintf("%.3f", p)))))' ...
        '}' ...
        'apa_num <- function(x, digits = 2) {' ...
        '  ifelse(is.na(x), "NA",' ...
        '    sub("^(-?)0\\.", "\\1.", sprintf(paste0("%.", digits, "f"), x)))' ...
        '}' ...
        '# A three-line APA table (rule above the header, rule below it, rule at the' ...
        '# foot; no vertical rules) via gt, printed with as_raw_html() so it can be' ...
        '# emitted from inside a per-channel for loop in a results:"asis" chunk --' ...
        '# gt''s own auto-print only works for a table that is a chunk''s sole,' ...
        '# top-level, unassigned result, which a table built inside a loop never is.' ...
        '# Numeric columns that happen to be whole numbers everywhere (n, df, ...)' ...
        '# are formatted with 0 decimals, not 3 -- APA never shows a sample size or' ...
        '# degrees of freedom as e.g. "10.000".' ...
        'apa_gt <- function(df, title = NULL) {' ...
        '  is_whole <- function(x) is.numeric(x) && all(x == round(x), na.rm = TRUE)' ...
        '  int_cols <- names(df)[sapply(df, is_whole)]' ...
        '  dec_cols <- setdiff(names(df)[sapply(df, is.numeric)], int_cols)' ...
        '  tbl <- gt(df)' ...
        '  if (!is.null(title)) tbl <- tab_header(tbl, title = title)' ...
        '  if (length(dec_cols) > 0) tbl <- tbl %>% fmt_number(columns = all_of(dec_cols), decimals = 3)' ...
        '  if (length(int_cols) > 0) tbl <- tbl %>% fmt_number(columns = all_of(int_cols), decimals = 0)' ...
        '  tbl %>%' ...
        '    tab_options(' ...
        '      table.border.top.style = "solid", table.border.top.width = px(1.5), table.border.top.color = "black",' ...
        '      table.border.bottom.style = "solid", table.border.bottom.width = px(1.5), table.border.bottom.color = "black",' ...
        '      column_labels.border.bottom.style = "solid", column_labels.border.bottom.width = px(1), column_labels.border.bottom.color = "black",' ...
        '      table_body.hlines.style = "none", table.border.left.style = "none", table.border.right.style = "none",' ...
        '      column_labels.font.weight = "bold", table.font.size = px(13), heading.align = "left"' ...
        '    )' ...
        '}' ...
        '# Classifies a Bayes factor (BF10, alternative over null) by conventional' ...
        '# strength-of-evidence bands (Lee & Wagenmakers, 2013, after Jeffreys, 1961)' ...
        '# and formats it -- used everywhere a Bayesian t-test runs alongside the' ...
        '# frequentist one as a robustness check, the same slot Wilcoxon/Mann-' ...
        '# Whitney/Friedman already occupy: BF10 > 1 favours the alternative' ...
        '# (H1 over H0), < 1 favours the null, so a small BF10 is itself informative' ...
        '# (evidence FOR "no effect", not just "not enough evidence for an effect")' ...
        '# in a way a non-significant p-value alone cannot say.' ...
        'apa_bf <- function(bf) {' ...
        '  if (is.na(bf)) return("NA")' ...
        '  bf10 <- if (bf < 1) 1 / bf else bf' ...
        '  band <- cut(bf10, breaks = c(0, 1, 3, 10, 30, 100, Inf),' ...
        '              labels = c("anecdotal", "anecdotal", "moderate", "strong", "very strong", "extreme"),' ...
        '              right = FALSE, include.lowest = TRUE)' ...
        '  favours <- if (bf >= 1) "H1" else "H0"' ...
        '  sprintf("%s (%s evidence for %s)", apa_num(bf, 2), as.character(band), favours)' ...
        '}' ...
        '# The violin distribution layer every per-channel plot below uses. FILL,' ...
        '# when given, is a literal colour for a single-distribution plot; omitted' ...
        '# (NULL) so the violin instead inherits the plot''s own colour/fill' ...
        '# aesthetic (e.g. aes(colour = group, fill = group)) for a multi-group plot.' ...
        'violin_layers <- function(fill = NULL) {' ...
        '  if (is.null(fill)) {' ...
        '    list(geom_violin(alpha = 0.15, trim = FALSE, linewidth = 0.4))' ...
        '  } else {' ...
        '    list(geom_violin(fill = fill, alpha = 0.15, colour = fill, trim = FALSE, linewidth = 0.4))' ...
        '  }' ...
        '}' ...
        '```' ...
        }, ...
        groupsSummaryChunk(hasGroups)];
    text = strrep(strjoin(lines, newline), '__CSVFILE_R__', ReportSections.rLit(csvFileName));
end

function lines = groupFilterLines(hasGroups)
%GROUPFILTERLINES  R lines (still inside the invisible setup chunk) that
%   drop every subject with no group assigned from `dat`, once, when
%   HASGROUPS -- see preambleText's own comment. {} (a no-op splice) when
%   HASGROUPS is false, so a report with no between-subjects grouping
%   generates byte-identical R to before this feature existed.
    if ~hasGroups
        lines = {};
        return;
    end
    lines = { ...
        '' ...
        '# Between-subjects group (see WorkSpace.editSubjects): every subject with' ...
        '# no group assigned is unusable for the group-based tests every section' ...
        '# below now runs, so they are set aside here, once, rather than each' ...
        '# section re-deriving the same exclusion from scratch.' ...
        'ungrouped_subjects <- dat %>% filter(is.na(group) | group == "") %>% distinct(dataset) %>% pull(dataset)' ...
        'dat <- dat %>% filter(!is.na(group), group != "") %>% mutate(group = factor(group))' ...
        'if (n_distinct(dat$group) < 2) {' ...
        '  stop("Need at least two groups with a usable subject for between-subjects/mixed statistics.")' ...
        '}'};
end

function chunk = groupsSummaryChunk(hasGroups)
%GROUPSSUMMARYCHUNK  A short, visible chunk (unlike the invisible setup
%   chunk groupFilterLines' own logic lives in) reporting which subjects
%   were excluded for having no group, and the resulting group sizes --
%   printed once, near the top of the report, rather than leaving the
%   reader to infer it from the per-channel counts scattered through every
%   section below. {} (no chunk at all) when HASGROUPS is false.
    if ~hasGroups
        chunk = {};
        return;
    end
    chunk = { ...
        '' ...
        '```{r}' ...
        '#| label: groups-summary' ...
        '#| results: asis' ...
        'if (length(ungrouped_subjects) > 0) {' ...
        '  cat(sprintf("\n\n*Note: %d subject(s) have no group assigned and are excluded from every test below: %s.*\n\n",' ...
        '              length(ungrouped_subjects), paste(ungrouped_subjects, collapse = ", ")))' ...
        '}' ...
        'grp_sizes <- dat %>% distinct(dataset, group) %>% count(group, name = "n_subjects")' ...
        'cat(sprintf("\nBetween-subjects groups: %s.\n\n",' ...
        '            paste(sprintf("%s (*n* = %d)", grp_sizes$group, grp_sizes$n_subjects), collapse = ", ")))' ...
        '```'};
end


function text = closingText()
    lines = { ...
        '## Summary Across All Tests' ...
        '' ...
        '```{r}' ...
        '#| label: summary-all-tests' ...
        '#| results: asis' ...
        '#| fig-height: 7' ...
        'if (nrow(omnibus) > 0) {' ...
        '  omnibus2 <- omnibus %>% filter(!is.na(p)) %>% mutate(p_bh = p.adjust(p, method = "BH"))' ...
        '  cat(sprintf("\nAcross %d test(s), %d were significant at *p* < .05 uncorrected, and %d remained\n",' ...
        '              nrow(omnibus2), sum(omnibus2$p < .05, na.rm = TRUE), sum(omnibus2$p_bh < .05, na.rm = TRUE)))' ...
        '  cat("significant after Benjamini-Hochberg (BH/FDR) correction across all of them.\n\n")' ...
        '  cat(as_raw_html(apa_gt(omnibus2 %>% select(-any_of(c("estimate", "conf.low", "conf.high"))),' ...
        '                         "Summary of All Tests (BH-Corrected)")))' ...
        '' ...
        '  # A forest plot alongside the table: every test''s own point effect-size' ...
        '  # estimate, with its CI where the test provides one. The LMM-based' ...
        '  # designs (anovaSection/mixedSection) convert their own F-test into a' ...
        '  # partial eta-squared WITH a CI (effectsize::F_to_eta2, via the' ...
        '  # noncentral F -- Steiger, 2004) specifically so this plot has a real' ...
        '  # interval to draw rather than a lone dot; a handful of other omnibus' ...
        '  # designs still have no CI-bearing effect size logged at all (e.g. a' ...
        '  # 3+-group Welch ANOVA''s own omnibus row), so those points show with no' ...
        '  # whisker and na.rm=TRUE silences the resulting "removed N rows" warning.' ...
        '  # Faceted by effect-size TYPE, not shown on one shared axis -- Cohen''s d' ...
        '  # and eta-squared are different scales with different meanings of "0", so' ...
        '  # plotting them on the same x-axis would visually imply they are' ...
        '  # comparable when they are not.' ...
        '  if (any(!is.na(omnibus2$estimate))) {' ...
        '    omnibus_fp <- omnibus2 %>%' ...
        '      mutate(' ...
        '        effect_type = case_when(' ...
        '          design %in% c("paired_t", "one_sample_vs_0", "indep_t") ~ "Cohen''s d / dz",' ...
        '          test %in% c("welch_t_test") ~ "Cohen''s d / dz",' ...
        '          design %in% c("lmm_within", "lmm_mixed") ~ "Partial eta-sq. (LMM)",' ...
        '          TRUE ~ "effect size"' ...
        '        ),' ...
        '        label_short = str_trunc(group, 40)' ...
        '      )' ...
        '    fp <- ggplot(omnibus_fp, aes(x = estimate, y = reorder(label_short, estimate), xmin = conf.low, xmax = conf.high)) +' ...
        '      geom_vline(xintercept = 0, linetype = "dashed", colour = "grey60") +' ...
        '      geom_pointrange(colour = "#4a7fc9", size = 0.3, na.rm = TRUE) +' ...
        '      facet_wrap(~ effect_type, scales = "free", ncol = 1) +' ...
        '      labs(x = "Effect size (point estimate, 95% CI where available)", y = NULL) +' ...
        '      theme_pubr(base_size = 9) +' ...
        '      theme(axis.text.y = element_text(size = 7),' ...
        '            strip.background = element_rect(fill = "#4a7fc9", colour = NA),' ...
        '            strip.text = element_text(colour = "white", face = "bold"))' ...
        '    print(fp)' ...
        '  }' ...
        '} else {' ...
        '  cat("\nNo tests were run.\n\n")' ...
        '}' ...
        '```' ...
        };
    text = strjoin(lines, newline);
end
