function qmdText = generateSourceClusterStatsReport(summary, assets)
%GENERATESOURCECLUSTERSTATSREPORT  A Quarto report for a source-space
%   cluster permutation test.
%
%   QMDTEXT = generateSourceClusterStatsReport(SUMMARY, ASSETS) assembles
%   the document from SourceClusterStats' own return value and the figures
%   generateSourceClusterAssets rendered from it.
%
%   PURE MARKDOWN, NO R CHUNK, unlike the scalp cluster report. Every number
%   here -- the p-values, the cluster extents, the anatomical labels -- was
%   computed in MATLAB by FieldTrip's permutation, and every figure was
%   rendered in MATLAB from the cortical mesh. There is no per-subject table
%   for R to run a test over, so a code chunk would have nothing to compute.
%   This also keeps the report renderable without R being able to reach
%   FieldTrip, which it cannot.
%
%   THE DOCUMENT LEADS WITH WHAT THE TEST DOES NOT SHOW. Cluster inference
%   is among the most over-read results in the literature: a significant
%   cluster establishes that an effect exists somewhere in a space-time
%   region, and specifically does NOT license a claim about where it starts,
%   stops, or which gyrus it occupies. Stating that after the tables would
%   be stating it after it has already been misread, so it comes first.
%
%   See also SOURCECLUSTERSTATS, GENERATESOURCECLUSTERASSETS,
%   GENERATECLUSTERSTATSREPORT, TRANSTOOLS.DESCRIBECLUSTER.
    lines = [ReportDoc.yamlHeader('Alakazam Source Cluster Statistics'), { ...
        '' ...
        '<!--' ...
        'Alakazam -- source-space cluster permutation report.' ...
        'Auto-generated. Every figure and number was computed in MATLAB; this' ...
        'document is markdown only and needs no R packages to render.' ...
        'Render with: quarto render <this file>.qmd' ...
        '-->' ...
        ''}, ...
        methodLines(summary), ...
        limitationLines(), ...
        resultLines(summary, assets)];

    qmdText = char(strjoin(lines, newline));
end

% ======================================================================= %
function lines = methodLines(summary)
%METHODLINES  What was actually run, in the words a methods section needs.
%   Read off SUMMARY.opts rather than restated from the dialog's defaults,
%   so the document describes the analysis that ran and not the one that was
%   requested -- numrandomization in particular can be raised to exhaustive
%   by resolveNumRandomization without the analyst asking.
    opts = summary.opts;
    lines = { ...
        '## What was tested' ...
        '' ...
        sprintf('%s, across %d subjects, on cortical source estimates.', ...
            contrastSentence(summary.contrast), summary.nSubjects) ...
        '' ...
        '| Setting | Value |' ...
        '| --- | --- |' ...
        sprintf('| Inverse method | %s |', methodName(opts.Method)) ...
        sprintf('| Orientation | %s |', orientationName(opts.Orientation)) ...
        sprintf('| Source space | template cortical sheet, %d vertices |', ...
            numel(summary.vertexLabels)) ...
        sprintf('| Time window | %s |', windowText(summary.times)) ...
        sprintf('| Sampling for the test | %.0f Hz |', samplingHz(summary.times)) ...
        sprintf('| Multiple-comparison correction | %s |', correctionName(opts.correctm)) ...
        sprintf('| Permutations | %d |', opts.numrandomization) ...
        sprintf('| Alpha | %g, %s |', opts.alpha, tailText(opts.tail)) ...
        ''};
end

function lines = limitationLines()
%LIMITATIONLINES  Placed before the results, deliberately -- see this
%   file's own header.
    lines = { ...
        '## How to read this' ...
        '' ...
        '> **A significant cluster means an effect exists, not where it is.**' ...
        '> Cluster-based permutation controls the family-wise error rate over the' ...
        '> whole vertex-by-time volume at once. It licenses the statement "there is a' ...
        '> difference between these conditions". It does NOT license "the difference' ...
        '> is in this region, between these two latencies": a cluster''s boundaries' ...
        '> are where a statistic crossed a threshold, not where the effect began and' ...
        '> ended.' ...
        '>' ...
        '> **The head model is a template.** Template anatomy, template electrode' ...
        '> positions, and a few dozen channels explaining tens of thousands of' ...
        '> vertices. The anatomical labels below name where the model places the' ...
        '> activity, which carries far more uncertainty than any p-value here' ...
        '> expresses. The peak coordinates are given alongside the region names so' ...
        '> that precision can be judged rather than assumed.' ...
        '>' ...
        '> **Neighbouring vertices are not independent.** The inverse is spatially' ...
        '> smooth, so an apparently focal cluster is partly the method''s own' ...
        '> point-spread. This is exactly why the correction is cluster-based rather' ...
        '> than per-vertex, and it is also why cluster extent should not be read as a' ...
        '> measurement of the effect''s size.' ...
        ''};
end

function lines = resultLines(summary, assets)
    lines = {'## Clusters' ''};

    if isempty(summary.clusters)
        lines = [lines, { ...
            'The permutation found no candidate clusters at all: no vertex-by-time' ...
            'point reached the threshold for cluster formation. There is no effect' ...
            'here at this sensitivity, which is a result, not a failure to run.' ''}];
        return;
    end

    significant = summary.clusters([summary.clusters.significant]);
    if isempty(significant)
        lines = [lines, { ...
            sprintf(['The permutation formed %d candidate cluster(s), none of which ' ...
                     'survived correction (smallest p = %.3f). Candidate clusters are ' ...
                     'formed routinely from noise, so this is a null result rather than ' ...
                     'a near-miss, and the clusters below are listed only for ' ...
                     'completeness.'], numel(summary.clusters), min([summary.clusters.pValue])) ...
            ''}];
    end

    lines = [lines, { ...
        '| # | Direction | p | Vertices | Time range | Location |' ...
        '| --- | --- | --- | --- | --- | --- |'}];
    for k = 1:numel(assets)
        a = assets(k);
        lines{end + 1} = sprintf('| %d | %s | %s | %d | %.0f to %.0f ms | %s |', ...
            a.Index, a.Sign, pValueText(a.PValue), a.NVertices, ...
            a.TimeRangeMs(1), a.TimeRangeMs(2), ...
            ReportSections.mdLit(a.Description.Text)); %#ok<AGROW>
    end
    lines{end + 1} = '';

    for k = 1:numel(assets)
        a = assets(k);
        lines = [lines, { ...
            sprintf('### Cluster %d (%s, %s)', a.Index, a.Sign, pValueText(a.PValue)) ...
            '' ...
            ReportSections.mdLit(a.Description.Text) ...
            '' ...
            }, truncationLines(a), { ...
            '::: {.panel-tabset}' ...
            '' ...
            '#### Where' ...
            '' ...
            sprintf('![Cluster %d on the cortical surface](<%s>)', a.Index, a.MapPath) ...
            '' ...
            'Each hemisphere is shown from the side and from the midline, so that the' ...
            'whole cortical sheet is visible: a single three-quarter view hides the' ...
            'medial wall entirely, and a cluster that is absent would look the same as' ...
            'one that is merely facing away. All four panels share one scale.' ...
            '' ...
            'Coloured by the cluster''s own statistic, averaged over its time range,' ...
            'red for positive and blue for negative. Vertices outside the cluster are' ...
            'not shaded: nothing below threshold is drawn, so the picture shows what' ...
            'was found rather than what was tested.' ...
            '' ...
            '#### When' ...
            '' ...
            sprintf('![Cluster %d over time](<%s>)', a.Index, a.TimeCoursePath) ...
            '' ...
            'The statistic averaged across the cluster''s vertices, over the whole' ...
            'tested window. The shaded band is the cluster''s extent -- where the' ...
            'statistic crossed threshold, which is not the same as where the effect' ...
            'started and stopped.' ...
            '' ...
            'Time is latency within the epoch, in milliseconds relative to the' ...
            'time-locking event, the same axis an ERP waveform is drawn on. It spans' ...
            'the tested window rather than the whole epoch, so if it looks narrower' ...
            'than the recording, that is the **Time window** setting reported above' ...
            'and not a property of the data.' ...
            '' ...
            ':::' ...
            ''}]; %#ok<AGROW>

        if ~isempty(a.Description.Regions)
            lines = [lines, regionTableLines(a.Description)]; %#ok<AGROW>
        end
    end
end

function lines = regionTableLines(description)
%REGIONTABLELINES  Where the cluster's vertices fall, by share.
%   A distribution rather than a single label, because a cluster crossing a
%   regional boundary is the normal case and naming only its peak would
%   hide that.
    lines = {'Vertices by region:' '' '| Region | Share of cluster |' '| --- | --- |'};
    show = min(5, numel(description.Regions));
    for r = 1:show
        lines{end + 1} = sprintf('| %s | %.0f%% |', ...
            ReportSections.mdLit(description.Regions{r}), 100 * description.RegionShare(r)); %#ok<AGROW>
    end
    lines{end + 1} = '';
end

function lines = truncationLines(asset)
%TRUNCATIONLINES  Say so when a cluster runs into the edge of the analysis
%   window, because its reported time range is then a property of the
%   window rather than of the effect.
    if ~asset.TouchesWindowEdge
        lines = {};
        return;
    end
    lines = { ...
        ['> This cluster reaches the edge of the tested time window, so its time ' ...
         'range is limited by where the analysis looked rather than by where the ' ...
         'effect ended. Widen the window to see its true extent.'] ...
        ''};
end

% ---- small formatting helpers ------------------------------------------- %
function s = contrastSentence(contrast)
    switch contrast.mode
        case 'vsZero'
            s = sprintf('Bin "%s" tested against zero', contrast.bin);
        case 'paired'
            s = sprintf('Bin "%s" compared with bin "%s" within each subject', ...
                contrast.binA, contrast.binB);
        case 'independent'
            s = sprintf('Bin "%s" compared between groups', contrast.bin);
        otherwise
            s = 'An unrecognised contrast';
    end
end

function s = methodName(method)
%METHODNAME  The displayed name plus its expansion. The name itself comes
%   from TransTools.SourceMethodName so this table, the dialog that
%   configured the run and the on-screen summary cannot disagree about
%   which method ran.
    [name, gloss] = TransTools.SourceMethodName(method);
    if isempty(gloss)
        s = name;
    else
        s = sprintf('%s (%s)', name, gloss);
    end
end

function s = orientationName(orientation)
    if strcmpi(orientation, 'normal')
        s = 'signed, projected onto the cortical normal';
    else
        s = 'magnitude (unsigned)';
    end
end

function s = correctionName(correctm)
    switch lower(char(string(correctm)))
        case 'tfce'
            s = 'threshold-free cluster enhancement (Smith & Nichols, 2009)';
        case 'cluster'
            s = 'cluster-based permutation (Maris & Oostenveld, 2007)';
        otherwise
            s = char(string(correctm));
    end
end

function s = windowText(times)
    s = sprintf('%.0f to %.0f ms', times(1), times(end));
end

function hz = samplingHz(times)
    if numel(times) < 2
        hz = NaN;
        return;
    end
    hz = 1000 / median(diff(times));
end

function s = tailText(tail)
    if tail == 0
        s = 'two-sided';
    elseif tail > 0
        s = 'one-sided (positive)';
    else
        s = 'one-sided (negative)';
    end
end

function s = pValueText(p)
%PVALUETEXT  A permutation p-value cannot be smaller than 1/nPermutations,
%   so it is reported at its resolution rather than as a spuriously precise
%   decimal or as a bare "0".
    if p <= 0
        s = 'p < 0.001';
    elseif p < 0.001
        s = 'p < 0.001';
    else
        s = sprintf('p = %.3f', p);
    end
end
