function qmdText = generateDataQualityReport(entries, summaryCsvName, trialCsvName, smeCsvName)
%GENERATEDATAQUALITYREPORT  A Quarto (.qmd) report on per-subject ERP data
%   quality: rendering it (self-contained HTML) produces a per-subject
%   overview table, the condition-wise rejection figure that is the whole
%   point of the exercise, per-trial noise distributions, a subject x
%   channel noise map, and a short "worth a look" list naming the subjects
%   and channels that stand out.
%
%   Adapted from the data-quality assessment section of Mathot &
%   Vilotijevic (2023), "Methods in cognitive pupillometry: Design,
%   preprocessing, and statistical analysis" (Behav Res Methods 55,
%   3055-3077) -- see dataQualityMetrics.m's own header for the
%   pupillometry-to-ERP mapping each metric comes from, and for the two
%   places the translation deliberately departs from the original.
%
%   Like generateClusterStatsReport.m (and unlike generateQuartoReport.m,
%   whose R code runs the actual statistical tests), every number here was
%   already computed in MATLAB by dataQualityMetrics; this report's own R
%   code narrates, tabulates and plots a precomputed result. The one
%   exception is the omnibus test for whether rejection rate differs
%   BETWEEN bins, which is a genuine inferential question about the export
%   as a whole rather than about any one subject, so it belongs with the
%   other cross-subject statistics in R.
%
%   ENTRIES is the same struct array exportDataQualityCSVs was handed (only
%   its length and grouping are used here, to decide which sections can
%   run at all); SUMMARYCSVNAME/TRIALCSVNAME are bare filenames, resolved
%   relative to the .qmd's own folder.
%
%   Requires the R packages tidyverse and gt (auto-installed by the
%   report's own setup chunk on first render, same as the other two report
%   generators) plus a working Quarto installation.
%
%   See also DATAQUALITYMETRICS, EXPORTDATAQUALITYCSVS,
%   ALAKAZAM.ONEXPORTDATAQUALITY.
    if isempty(entries)
        throw(MException('Alakazam:generateDataQualityReport', ...
            ['I''m afraid a data-quality report needs at least one Averaged dataset ' ...
             'with segmented data behind it.']));
    end
    hasGroups = numel(distinctGroups(entries)) >= 2;
    if nargin < 4 || isempty(smeCsvName)
        smeCsvName = '';
    end

    lines = [ ...
        preambleLines(summaryCsvName, trialCsvName, smeCsvName), ...
        introLines(numel(entries)), ...
        overviewLines(), ...
        rejectionByBinLines(), ...
        baselineNoiseLines(), ...
        noiseOverSessionLines(), ...
        channelNoiseLines(), ...
        smeLines(smeCsvName), ...
        groupComparisonLines(hasGroups), ...
        attentionLines()];
    qmdText = strjoin(lines, newline);
end

% ======================================================================= %
function labels = distinctGroups(entries)
    groups = {entries.group};
    labels = unique(groups(~cellfun(@isempty, groups)));
end

% ======================================================================= %
%  Preamble
% ======================================================================= %
function lines = preambleLines(summaryCsvName, trialCsvName, smeCsvName)
    lines = [ReportDoc.yamlHeader('Alakazam Data Quality Report'), { ...
        '' ...
        '<!--' ...
        'Alakazam -- per-subject ERP data-quality report. Every per-subject number was' ...
        'computed in MATLAB (see dataQualityMetrics.m, whose own header records where' ...
        'the metric set was adapted from); this report narrates and plots them. It' ...
        'excludes nothing on your behalf -- see the closing section. Edit freely.' ...
        'Render with: quarto render <this file>.qmd' ...
        '-->' ...
        '' ...
        '```{r}' ...
        '#| label: setup' ...
        '#| include: false' ...
        }, ReportDoc.packageBootstrap({'tidyverse', 'gt'}), { ...
        '' ...
        sprintf('qual <- read_csv("%s", show_col_types = FALSE)', rLit(summaryCsvName)) ...
        sprintf('trl  <- read_csv("%s", show_col_types = FALSE)', rLit(trialCsvName)) ...
        smeReadLine(smeCsvName) ...
        '' ...
        '# One row per subject: every subject_* column is constant within a dataset' ...
        '# (dataQualityMetrics computes them once per subject and exportDataQualityCSVs' ...
        '# repeats them onto every bin x channel row), so first() is exact here, not an' ...
        '# arbitrary pick among differing values.' ...
        'subj <- qual %>%' ...
        '  group_by(dataset, group, session) %>%' ...
        '  summarise(' ...
        '    n_trials = first(subject_n_trials),' ...
        '    n_channels = first(subject_n_channels),' ...
        '    pct_rejected = first(subject_pct_trials_rejected),' ...
        '    pct_flagged = first(subject_pct_channel_epochs_flagged),' ...
        '    pct_interpolated = first(subject_pct_channel_epochs_interpolated),' ...
        '    pct_outlier = first(subject_pct_baseline_outlier_trials),' ...
        '    pct_truncated = first(subject_pct_trials_truncated),' ...
        '    max_truncated_pct = first(subject_max_truncated_pct),' ...
        '    rejection_ran = first(subject_rejection_ran),' ...
        '    n_discarded = first(subject_n_trials_rejected),' ...
        '    n_kept = first(subject_n_trials_kept),' ...
        '    n_truncated = first(subject_n_trials_truncated),' ...
        '    median_baseline_sd = median(baseline_sd_uv, na.rm = TRUE),' ...
        '    median_sme = median(sme_uv, na.rm = TRUE),' ...
        '    .groups = "drop"' ...
        '  ) %>%' ...
        '  arrange(desc(pct_rejected))' ...
        '' ...
        'alz_blue <- "#4a7fc9"' ...
        'alz_red  <- "#d0454a"' ...
        '' ...
        }, ReportDoc.apaHelpers(), { ...
        '```' ...
        ''}];
end

function line = smeReadLine(smeCsvName)
%SMEREADLINE  Read the per-window SME table, or stand in an empty one of
%   the same shape when this export had no Measure results to score. The
%   section below then needs only ONE emptiness check (nrow == 0), rather
%   than separate "file absent" and "file empty" branches that would both
%   have to be kept in step with it.
    if isempty(smeCsvName)
        line = ['wsme <- tibble(dataset = character(), group = character(), window = character(), ' ...
            'bin = character(), channel = character(), measure = character(), method = character(), ' ...
            'sme_uv = double(), score = double())'];
    else
        line = sprintf('wsme <- read_csv("%s", show_col_types = FALSE)', rLit(smeCsvName));
    end
end

% ======================================================================= %
%  Intro
% ======================================================================= %
function lines = introLines(nEntries)
    lines = { ...
        '## What This Report Is' ...
        '' ...
        sprintf(['Data quality for each of the %d subject(s) whose Average currently sits in this ' ...
            'workspace, computed from the segmented data each average was actually built from.'], nEntries) ...
        '' ...
        ['The number that matters here is not how much data you lost, but **whether you lost it ' ...
         'evenly across conditions**. A high but even rejection rate costs statistical power; an ' ...
         'uneven one biases the contrast itself, because the surviving trials in one condition are ' ...
         'no longer a fair sample of that condition.'] ...
        '' ...
        'What each metric is:' ...
        '' ...
        '| Metric | What it tells you |' ...
        '|---|---|' ...
        ['| % trials rejected | How much of the recording survived artefact rejection. See the note ' ...
         'directly below: with no artefact step in the chain, an empty trial means an epoch that ' ...
         'could not be cut, not one anything rejected |'] ...
        ['| % trials truncated | Trials whose epoch ran off the start or end of the recording. They ' ...
         'still enter the average, with less data at the ends than their neighbours |'] ...
        ['| % trials rejected **per bin** | Whether that loss is even across conditions. This is ' ...
         'the one that can invalidate a result rather than just weaken it |'] ...
        ['| % channel-epochs flagged | Loss confined to single channels rather than whole trials, ' ...
         'usually one bad electrode. Note this is a share of *all* channel-epochs: one electrode ' ...
         'dead in every trial of a 64-channel montage is only 1.6% here, so read it with the ' ...
         'per-channel map below rather than on its own |'] ...
        ['| % channel-epochs interpolated | Channel-epochs that were *reconstructed* from ' ...
         'neighbouring electrodes rather than discarded. Not loss, but not measurement either: ' ...
         'these samples are an estimate, and a spatially widespread artefact (a blink spans the ' ...
         'frontal electrodes at once) can be reproduced rather than removed by the reconstruction |'] ...
        ['| Pre-stimulus SD (uV) | Per-trial noise. Measured as *variability* over the pre-stimulus ' ...
         'window, not its mean, which baseline correction sets to zero by construction |'] ...
        ['| % baseline outlier trials | Trials whose pre-stimulus noise is extreme *for that ' ...
         'subject*, at \|z\| > 2 against their own distribution |'] ...
        ['| SME (uV) | Standardized measurement error (Luck et al., 2021), the ERP field''s own ' ...
         'single-subject quality statistic |'] ...
        '' ...
        ['Nothing below has been excluded from your data. Exclusion criteria are best set in advance ' ...
         'and reported openly, so this report tells you what is there and leaves the decision with ' ...
         'you.'] ...
        '' ...
        '```{r}' ...
        '#| label: empty-trial-provenance' ...
        '#| results: asis' ...
        '# A trial counts as "rejected" when every channel of it is NaN, and there are' ...
        '# TWO ways to get that: an artefact step removed it, or DefineBins could not' ...
        '# cut the epoch at all (an anchor event past the end of the recording). The' ...
        '# two are identical in the data, so rather than assert a cause, this says' ...
        '# which one applies from whether any artefact step is actually in the chain.' ...
        'any_lost <- any(subj$pct_rejected > 0, na.rm = TRUE)' ...
        'ran <- subj$rejection_ran' ...
        'if (any_lost && all(ran == 0, na.rm = TRUE) && !all(is.na(ran))) {' ...
        '  cat(paste0("\n::: {.callout-important}\n## These trials were not rejected by anything\n\n",' ...
        '             "No ArtefactDetect or ManualReject step appears in these datasets, so nothing ",' ...
        '             "removed the empty trials counted below. They are epochs **DefineBins could not ",' ...
        '             "cut**: the anchor event sat past the end of the recording, or had no usable ",' ...
        '             "latency, so the epoch was never filled with data. Check the event codes near ",' ...
        '             "the end of your recordings, and the epoch window against how long they run ",' ...
        '             "on for after the last event.\n:::\n\n"))' ...
        '} else if (any_lost && any(ran == 0, na.rm = TRUE)) {' ...
        '  mixed <- subj$dataset[!is.na(ran) & ran == 0]' ...
        '  cat(sprintf(paste0("\n*No artefact-rejection step is present for %s, so any empty trials ",' ...
        '                     "there are epochs DefineBins could not cut rather than rejections.*\n\n"),' ...
        '              paste(mixed, collapse = ", ")))' ...
        '}' ...
        '```' ...
        ''};
end

% ======================================================================= %
%  Per-subject overview
% ======================================================================= %
function lines = overviewLines()
    lines = { ...
        '## Per-Subject Overview' ...
        '' ...
        '```{r}' ...
        '#| label: subject-overview' ...
        '#| results: asis' ...
        'cat(as_raw_html(apa_gt(' ...
        '  subj %>% select(dataset, group, n_channels, n_trials, n_discarded, n_kept,' ...
        '                  pct_rejected, n_truncated, pct_flagged, pct_interpolated,' ...
        '                  pct_outlier, median_baseline_sd, median_sme),' ...
        '  "Data Quality by Subject (worst rejection rate first)")))' ...
        '```' ...
        '' ...
        '```{r}' ...
        '#| label: subject-overview-plot' ...
        '#| fig-height: 5' ...
        '# Ordered by rejection rate rather than alphabetically: the reason to look at' ...
        '# this plot at all is to find the tail, and an alphabetical axis hides it.' ...
        'sp <- subj %>%' ...
        '  mutate(dataset = fct_reorder(dataset, pct_rejected)) %>%' ...
        '  ggplot(aes(x = pct_rejected, y = dataset)) +' ...
        '  geom_col(fill = alz_blue, width = 0.7) +' ...
        '  geom_vline(xintercept = median(subj$pct_rejected, na.rm = TRUE),' ...
        '             linetype = "dashed", colour = "grey40") +' ...
        '  labs(x = "Trials rejected (%)", y = NULL,' ...
        '       subtitle = "Dashed line: median across subjects") +' ...
        '  theme_minimal(base_size = 11)' ...
        'print(sp)' ...
        '```' ...
        ''};
end

% ======================================================================= %
%  Rejection by bin -- the central figure
% ======================================================================= %
function lines = rejectionByBinLines()
    lines = { ...
        '## Rejection Rate by Condition' ...
        '' ...
        ['One line per subject, one point per bin. Flat lines indicate even loss across ' ...
         'conditions. A line sloping consistently in the same direction as the others indicates ' ...
         'that rejection is removing more trials from one condition than another, in which case ' ...
         'the surviving averages are not comparable in the way the analysis assumes.'] ...
        '' ...
        '```{r}' ...
        '#| label: rejection-by-bin' ...
        '#| fig-height: 5' ...
        '# Channel-invariant: whole-epoch rejection removes every channel at once, so any' ...
        '# one channel''s row already carries the per-bin trial counts. distinct() rather' ...
        '# than a mean over channels, so the value is exact rather than an average of' ...
        '# identical numbers.' ...
        'by_bin <- qual %>%' ...
        '  distinct(dataset, group, bin, n_trials, n_trials_rejected, pct_trials_rejected)' ...
        '' ...
        'if (n_distinct(by_bin$bin) < 2) {' ...
        '  cat("\n\nOnly one bin is present, so there is no between-condition comparison to make here.\n\n")' ...
        '} else {' ...
        '  bp <- ggplot(by_bin, aes(x = bin, y = pct_trials_rejected, group = dataset)) +' ...
        '    geom_line(colour = "grey65", alpha = 0.7) +' ...
        '    geom_point(colour = alz_blue, size = 1.6) +' ...
        '    stat_summary(aes(group = 1), fun = mean, geom = "line",' ...
        '                 colour = alz_red, linewidth = 1.2) +' ...
        '    stat_summary(aes(group = 1), fun = mean, geom = "point",' ...
        '                 colour = alz_red, size = 3) +' ...
        '    labs(x = NULL, y = "Trials rejected (%)",' ...
        '         subtitle = "Grey: individual subjects. Red: mean across subjects") +' ...
        '    theme_minimal(base_size = 11)' ...
        '  print(bp)' ...
        '}' ...
        '```' ...
        '' ...
        '```{r}' ...
        '#| label: rejection-by-bin-test' ...
        '#| results: asis' ...
        '# The one genuinely inferential test in this report (see' ...
        '# generateDataQualityReport.m''s own header): is the per-bin rejection rate' ...
        '# different across bins? Friedman rather than a repeated-measures ANOVA --' ...
        '# rejection percentages are bounded, typically skewed towards zero, and often' ...
        '# have a floor of exactly 0 for most subjects, none of which suits a normal-theory' ...
        '# test. Needs a complete subject x bin table, so subjects missing a bin are' ...
        '# dropped here (and counted in the sentence below) rather than silently.' ...
        'if (n_distinct(by_bin$bin) >= 2 && n_distinct(by_bin$dataset) >= 2) {' ...
        '  wide <- by_bin %>% select(dataset, bin, pct_trials_rejected) %>%' ...
        '    pivot_wider(names_from = bin, values_from = pct_trials_rejected)' ...
        '  complete_rows <- wide %>% drop_na()' ...
        '  n_dropped <- nrow(wide) - nrow(complete_rows)' ...
        '  if (nrow(complete_rows) >= 2) {' ...
        '    mat <- as.matrix(complete_rows %>% select(-dataset))' ...
        '    if (all(apply(mat, 1, function(r) length(unique(r))) == 1)) {' ...
        '      cat("\n\nEvery subject has an identical rejection rate in every bin, so there is nothing to test.\n\n")' ...
        '    } else {' ...
        '      ft <- friedman.test(mat)' ...
        '      # One backslash reaches the output, not two: this string is written by' ...
        '      # MATLAB into R SOURCE, so R''s own parser consumes one level before cat' ...
        '      # ever runs. "\\\\chi" here would emit \\chi, which is a LaTeX line break,' ...
        '      # and MathJax renders the rest as the literal letters c-h-i.' ...
        '      cat(sprintf(paste0("\nA Friedman test across %d subject(s) with a complete set of bins ",' ...
        '                         "found %s evidence that rejection rate differs between conditions, ",' ...
        '                         "$\\chi^2$(%d) = %s, *p* %s.\n\n"),' ...
        '                  nrow(complete_rows),' ...
        '                  ifelse(ft$p.value < .05, "**significant**", "no significant"),' ...
        '                  ft$parameter, apa_num(ft$statistic), apa_p(ft$p.value)))' ...
        '      if (ft$p.value < .05) {' ...
        '        cat(paste0("Treat the condition comparison in your main analysis with care: the trials ",' ...
        '                   "surviving rejection are not an even sample across conditions. Consider ",' ...
        '                   "whether the artefact most responsible (eye movement, muscle, drift) is ",' ...
        '                   "itself tied to what the conditions asked participants to do.\n\n"))' ...
        '      }' ...
        '    }' ...
        '  }' ...
        '  if (n_dropped > 0) {' ...
        '    cat(sprintf("*%d subject(s) were left out of that test for having no trials in at least one bin.*\n\n", n_dropped))' ...
        '  }' ...
        '}' ...
        '```' ...
        ''};
end

% ======================================================================= %
%  Per-trial baseline noise
% ======================================================================= %
function lines = baselineNoiseLines()
    lines = { ...
        '## Per-Trial Noise Distribution' ...
        '' ...
        ['Each trial''s pre-stimulus standard deviation, meaned across channels. Good data gives a ' ...
         'roughly unimodal, right-skewed distribution. A second bump well to the right is a block ' ...
         'of trials recorded under different conditions (an electrode drying out, a participant ' ...
         'becoming restless), not just noise around one mean.'] ...
        '' ...
        '```{r}' ...
        '#| label: baseline-hist' ...
        '#| fig-height: 4' ...
        'kept <- trl %>% filter(rejected == 0, !is.na(baseline_sd_uv))' ...
        'if (nrow(kept) == 0) {' ...
        '  cat("\n\nNo surviving trials to describe.\n\n")' ...
        '} else {' ...
        '  hp <- ggplot(kept, aes(x = baseline_sd_uv)) +' ...
        '    geom_histogram(bins = 50, fill = alz_blue, colour = NA) +' ...
        '    labs(x = "Pre-stimulus SD (uV)", y = "Trials",' ...
        '         subtitle = "Every surviving trial, all subjects pooled") +' ...
        '    theme_minimal(base_size = 11)' ...
        '  print(hp)' ...
        '}' ...
        '```' ...
        '' ...
        ['Pooling subjects, as above, mixes together people who simply recorded at different ' ...
         'overall noise levels. The z-scores below are computed **within each subject**, which is ' ...
         'what makes the \|z\| > 2 cutoff meaningful here: it asks whether a trial is unusual *for ' ...
         'that person*, not whether that person is noisy overall.'] ...
        '' ...
        '```{r}' ...
        '#| label: baseline-z' ...
        '#| fig-height: 5' ...
        'zp <- ggplot(kept, aes(x = baseline_z, y = fct_reorder(dataset, baseline_z, .fun = median))) +' ...
        '  geom_vline(xintercept = c(-2, 2), linetype = "dashed", colour = alz_red) +' ...
        '  geom_jitter(height = 0.2, alpha = 0.25, size = 0.5, colour = alz_blue) +' ...
        '  labs(x = "Pre-stimulus SD (z, within subject)", y = NULL,' ...
        '       subtitle = "Dashed lines: the |z| > 2 flagging cutoff") +' ...
        '  theme_minimal(base_size = 11)' ...
        'print(zp)' ...
        '```' ...
        ''};
end

% ======================================================================= %
%  Noise across the session
% ======================================================================= %
function lines = noiseOverSessionLines()
    lines = { ...
        '## Noise Across the Session' ...
        '' ...
        ['A check for a recording that degrades as it runs (a participant settling, slumping, or an ' ...
         'electrode drying out): pre-stimulus noise against trial number. A flat cloud is fine. A ' ...
         'rising trend means later trials are noisier than earlier ones, which matters if condition ' ...
         'order was not counterbalanced.'] ...
        '' ...
        ['**Each panel has its own y-axis.** That is deliberate -- the question here is whether a ' ...
         'subject drifts over their own session, and a shared axis would flatten every quiet ' ...
         'subject into a line at the bottom of the panel, hiding exactly the trend worth finding. ' ...
         'The cost is that panels cannot be compared to each other by eye, so the dashed line marks ' ...
         'the median across all subjects: it sits at the same value in every panel, and where it ' ...
         'falls tells you whether a steep-looking slope is a large drift or a small one magnified ' ...
         'by a narrow axis. For comparing overall noise levels between subjects, use the channel ' ...
         'map below or the overview table, both of which are on one scale.'] ...
        '' ...
        '```{r}' ...
        '#| label: noise-over-session' ...
        '#| fig-height: 6' ...
        'if (nrow(kept) == 0) {' ...
        '  cat("\n\nNo surviving trials to plot.\n\n")' ...
        '} else {' ...
        '  n_sub <- n_distinct(kept$dataset)' ...
        '  cohort_median <- median(kept$baseline_sd_uv, na.rm = TRUE)' ...
        '  op <- ggplot(kept, aes(x = trial, y = baseline_sd_uv)) +' ...
        '    geom_point(alpha = 0.3, size = 0.5, colour = alz_blue) +' ...
        '    geom_hline(yintercept = cohort_median, linetype = "dashed", colour = "grey40") +' ...
        '    geom_smooth(method = "lm", se = FALSE, colour = alz_red, linewidth = 0.7, formula = y ~ x) +' ...
        '    facet_wrap(~ dataset, scales = "free_y", ncol = min(4, n_sub)) +' ...
        '    labs(x = "Trial number", y = "Pre-stimulus SD (uV)",' ...
        '         subtitle = "Free y-axis per subject. Dashed line: median across all subjects (same value in every panel)") +' ...
        '    theme_minimal(base_size = 9) +' ...
        '    theme(strip.background = element_rect(fill = alz_blue, colour = NA),' ...
        '          strip.text = element_text(colour = "white", face = "bold", size = 7),' ...
        '          plot.subtitle = element_text(size = 7, colour = "grey30"))' ...
        '  print(op)' ...
        '}' ...
        '```' ...
        ''};
end

% ======================================================================= %
%  Per-channel noise
% ======================================================================= %
function lines = channelNoiseLines()
    lines = { ...
        '## Noise by Channel' ...
        '' ...
        ['Which electrodes, on which subjects. A whole row standing out is a noisy recording; a ' ...
         'single bright cell is one bad electrode on one subject, which is the case interpolation ' ...
         'is actually for.'] ...
        '' ...
        ['Colour is noise **among the samples that survived**, so the worst channels are the ones ' ...
         'colour cannot show: a channel rejected in every trial has nothing left to take a median ' ...
         'of and would otherwise sit here as an unremarkable grey cell, and an interpolated one ' ...
         'shows the noise of its neighbours rather than its own. Both are marked instead of left ' ...
         'to the colour scale.'] ...
        '' ...
        '```{r}' ...
        '#| label: channel-noise-map' ...
        '#| fig-height: 7' ...
        '# Weighted by n_trials rather than a plain mean over bins: bins routinely differ in' ...
        '# trial count, and an unweighted mean would let a 12-trial bin count as heavily as a' ...
        '# 200-trial one when deciding whether a channel is mostly gone.' ...
        'chan <- qual %>%' ...
        '  group_by(dataset, channel) %>%' ...
        '  summarise(baseline_sd_uv = median(baseline_sd_uv, na.rm = TRUE),' ...
        '            pct_flagged = weighted.mean(pct_flagged, n_trials, na.rm = TRUE),' ...
        '            pct_interpolated = weighted.mean(pct_interpolated, n_trials, na.rm = TRUE),' ...
        '            .groups = "drop")' ...
        'if (all(is.na(chan$baseline_sd_uv)) && all(chan$pct_flagged == 0, na.rm = TRUE)) {' ...
        '  cat("\n\nNo per-channel noise estimates are available.\n\n")' ...
        '} else {' ...
        '  gone <- chan %>% filter(!is.na(pct_flagged), pct_flagged > 20)' ...
        '  interp <- chan %>% filter(!is.na(pct_interpolated), pct_interpolated > 20)' ...
        '  cp <- ggplot(chan, aes(x = channel, y = dataset)) +' ...
        '    geom_tile(aes(fill = baseline_sd_uv)) +' ...
        '    scale_fill_viridis_c(option = "magma", direction = -1, name = "SD (uV)", na.value = "grey90") +' ...
        '    geom_point(data = gone, shape = 4, size = 1.3, stroke = 0.6, colour = "white") +' ...
        '    geom_point(data = interp, shape = 1, size = 1.6, stroke = 0.6, colour = "black") +' ...
        '    labs(x = NULL, y = NULL,' ...
        '         subtitle = paste("x  flagged in >20% of trials (grey = nothing left to measure)",' ...
        '                          "o  interpolated in >20% of trials", sep = "    ")) +' ...
        '    theme_minimal(base_size = 9) +' ...
        '    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1, size = 6),' ...
        '          plot.subtitle = element_text(size = 7, colour = "grey30"))' ...
        '  print(cp)' ...
        '}' ...
        '```' ...
        ''};
end

% ======================================================================= %
%  SME
% ======================================================================= %
function lines = smeLines(~)
    lines = [{ ...
        '## Standardized Measurement Error' ...
        '' ...
        ['SME (Luck et al., 2021) is the ERP field''s own answer to the question this whole report ' ...
         'asks. Unlike a rejection rate, it combines how noisy the single trials were **and** how ' ...
         'many of them survived into one number in the units of the measurement itself: the ' ...
         'standard error you would expect if you re-ran the same subject in the same condition. ' ...
         'Lower is better, and it is directly comparable across subjects in a way a rejection ' ...
         'percentage is not.'] ...
        '' ...
        '### Whole-epoch SME' ...
        '' ...
        ['A single figure per subject, over the whole epoch. Useful as a first sort, but see the ' ...
         'next part: SME is only strictly interpretable for the score you actually report, and this ' ...
         'one averages together time ranges a subject may have been clean in and ranges they were ' ...
         'not.'] ...
        '' ...
        '```{r}' ...
        '#| label: sme-plot' ...
        '#| fig-height: 5' ...
        'sme <- qual %>% filter(!is.na(sme_uv))' ...
        'if (nrow(sme) == 0) {' ...
        '  cat(paste0("\n\nNo SME values are available. These come from Average.m''s own aSME field, ",' ...
        '             "so a dataset averaged before that field existed will need re-averaging to ",' ...
        '             "report one.\n\n"))' ...
        '} else {' ...
        '  smp <- ggplot(sme, aes(x = sme_uv, y = fct_reorder(dataset, sme_uv, .fun = median))) +' ...
        '    geom_boxplot(outlier.size = 0.5, fill = alz_blue, alpha = 0.25, colour = alz_blue) +' ...
        '    labs(x = "SME (uV)", y = NULL, subtitle = "Across every channel and bin, per subject") +' ...
        '    theme_minimal(base_size = 11)' ...
        '  print(smp)' ...
        '}' ...
        '```' ...
        ''}, windowSmeLines()];
end

function lines = windowSmeLines()
%WINDOWSMELINES  Per-Measure-window SME: the grain Luck et al. actually
%   argue for, and the one that can be quoted in a methods section.
    lines = { ...
        '### SME per measurement window' ...
        '' ...
        ['This is the number to report. SME describes the error on **a specific score**, so it is ' ...
         'computed here for each Measure window on the score that window actually produces, from ' ...
         'the single trials behind each subject''s average.'] ...
        '' ...
        ['Two estimators are used, chosen automatically per score type. Mean amplitude has a closed ' ...
         'form, because the mean amplitude of the average is exactly the average of the per-trial ' ...
         'mean amplitudes, so its standard error is simply SD/sqrt(*n*) (**analytic**). Every other ' ...
         'score is a non-linear function of the waveform: the peak of the average is not the average ' ...
         'of the peaks, so no such identity exists and there is no closed form. Those are ' ...
         '**bootstrapped** instead, by repeatedly resampling trials with replacement, re-averaging, ' ...
         're-scoring, and taking the spread of the result.'] ...
        '' ...
        '```{r}' ...
        '#| label: window-sme-table' ...
        '#| results: asis' ...
        'if (nrow(wsme) == 0) {' ...
        '  cat(paste0("\n\nNo Measure windows were found for these subjects, so there is no ",' ...
        '             "per-window SME to report. Run Measure on a subject''s Average to get one.\n\n"))' ...
        '} else {' ...
        '  wtab <- wsme %>%' ...
        '    group_by(window, measure, method, bin) %>%' ...
        '    summarise(subjects = n_distinct(dataset), channels = n_distinct(channel),' ...
        '              median_sme = median(sme_uv, na.rm = TRUE),' ...
        '              worst_sme = max(sme_uv, na.rm = TRUE), .groups = "drop") %>%' ...
        '    arrange(window, measure, bin)' ...
        '  cat(as_raw_html(apa_gt(wtab, "SME by Measurement Window")))' ...
        '}' ...
        '```' ...
        '' ...
        '```{r}' ...
        '#| label: window-sme-plot' ...
        '#| fig-height: 6' ...
        '# Faceted by window x measure with a free x scale, never pooled onto one axis:' ...
        '# an amplitude SME is in uV and a latency SME is in ms, so a shared axis would' ...
        '# invite a comparison between two quantities that have nothing to do with' ...
        '# each other. Points, not boxes: with one value per channel the underlying' ...
        '# spread is worth seeing directly.' ...
        'if (nrow(wsme) > 0) {' ...
        '  wp <- wsme %>%' ...
        '    mutate(panel = paste0(window, " / ", measure)) %>%' ...
        '    ggplot(aes(x = sme_uv, y = fct_reorder(dataset, sme_uv, .fun = median), colour = bin)) +' ...
        '    geom_point(alpha = 0.6, size = 1.2) +' ...
        '    facet_wrap(~ panel, scales = "free_x") +' ...
        '    labs(x = "SME (uV for amplitudes and areas, ms for latencies)", y = NULL, colour = "Bin") +' ...
        '    theme_minimal(base_size = 9) +' ...
        '    theme(strip.background = element_rect(fill = alz_blue, colour = NA),' ...
        '          strip.text = element_text(colour = "white", face = "bold", size = 8))' ...
        '  print(wp)' ...
        '}' ...
        '```' ...
        '' ...
        '```{r}' ...
        '#| label: window-sme-note' ...
        '#| results: asis' ...
        '# Worth stating explicitly rather than leaving to be inferred from the table:' ...
        '# a reader who sees "bootstrap" against a latency needs to know it is the' ...
        '# correct choice there, not a fallback taken because something failed.' ...
        'if (nrow(wsme) > 0) {' ...
        '  used <- wsme %>% distinct(measure, method) %>% arrange(method, measure)' ...
        '  cat(sprintf("\n%s\n\n", paste(sprintf("*%s* used the **%s** estimator.", used$measure, used$method),' ...
        '                                collapse = " ")))' ...
        '  n_boot_rows <- sum(wsme$method == "bootstrap")' ...
        '  if (n_boot_rows > 0) {' ...
        '    cat(paste0("Bootstrapped values carry their own sampling error: they will shift slightly ",' ...
        '               "if this report is regenerated, which is expected and is not a sign of ",' ...
        '               "instability in the data.\n\n"))' ...
        '  }' ...
        '}' ...
        '```' ...
        ''};
end

% ======================================================================= %
%  Between-groups check
% ======================================================================= %
function lines = groupComparisonLines(hasGroups)
%GROUPCOMPARISONLINES  A between-subjects counterpart to the by-bin figure,
%   emitted only when the workspace actually has two or more groups (see
%   WorkSpace.editSubjects). Uneven quality BETWEEN groups is the same
%   threat to validity as uneven quality between bins, one level up: a
%   patient group that blinks more than a control group produces a group
%   difference in the ERP that is not a group difference in the brain.
    if ~hasGroups
        lines = {};
        return;
    end
    lines = { ...
        '## Quality by Between-Subjects Group' ...
        '' ...
        ['The same concern as the by-condition figure, one level up. If one group''s data is ' ...
         'systematically noisier or more heavily rejected than another''s, any group difference ' ...
         'you find in the ERP has a competing explanation that has nothing to do with the brain.'] ...
        '' ...
        '```{r}' ...
        '#| label: quality-by-group' ...
        '#| fig-height: 4' ...
        '#| results: asis' ...
        'gsub_dat <- subj %>% filter(!is.na(group), group != "")' ...
        'if (n_distinct(gsub_dat$group) >= 2) {' ...
        '  gp <- gsub_dat %>%' ...
        '    pivot_longer(c(pct_rejected, median_baseline_sd), names_to = "metric", values_to = "value") %>%' ...
        '    mutate(metric = recode(metric, pct_rejected = "Trials rejected (%)",' ...
        '                           median_baseline_sd = "Median pre-stimulus SD (uV)")) %>%' ...
        '    ggplot(aes(x = group, y = value, colour = group)) +' ...
        '    geom_boxplot(outlier.shape = NA, alpha = 0.2) +' ...
        '    geom_jitter(width = 0.15, size = 1.5, alpha = 0.7) +' ...
        '    facet_wrap(~ metric, scales = "free_y") +' ...
        '    labs(x = NULL, y = NULL) +' ...
        '    theme_minimal(base_size = 10) + theme(legend.position = "none")' ...
        '  print(gp)' ...
        '' ...
        '  # Two groups: Wilcoxon rank-sum, for the same distributional reasons the' ...
        '  # by-bin test uses Friedman. Three or more: Kruskal-Wallis, its extension.' ...
        '  grps <- unique(gsub_dat$group)' ...
        '  if (length(grps) == 2) {' ...
        '    wt <- suppressWarnings(wilcox.test(pct_rejected ~ group, data = gsub_dat))' ...
        '    cat(sprintf("\n\nRejection rate did %sdiffer significantly between groups (Wilcoxon rank-sum, *W* = %s, *p* %s).\n\n",' ...
        '                ifelse(wt$p.value < .05, "", "not "), apa_num(wt$statistic), apa_p(wt$p.value)))' ...
        '  } else {' ...
        '    kt <- kruskal.test(pct_rejected ~ factor(group), data = gsub_dat)' ...
        '    cat(sprintf("\n\nRejection rate did %sdiffer significantly between groups (Kruskal-Wallis, $\\chi^2$(%d) = %s, *p* %s).\n\n",' ...
        '                ifelse(kt$p.value < .05, "", "not "), kt$parameter, apa_num(kt$statistic), apa_p(kt$p.value)))' ...
        '  }' ...
        '}' ...
        '```' ...
        ''};
end

% ======================================================================= %
%  Closing: what to look at
% ======================================================================= %
function lines = attentionLines()
    lines = { ...
        '## Worth a Look' ...
        '' ...
        ['A shortlist, not a verdict. Nothing here has been excluded, and none of these ' ...
         'thresholds is a standard: they are conventional starting points, chosen to be worth a ' ...
         'second look rather than to be correct. Whether a subject at 35% rejection is usable ' ...
         'depends on how many trials they started with and what is being measured.'] ...
        '' ...
        'The criteria, and the reasoning behind each:' ...
        '' ...
        '| Flagged when | Why this value |' ...
        '|---|---|' ...
        ['| More than **25%** of trials discarded | At a quarter of the data gone, the surviving ' ...
         'trials are no longer a random subset: whatever removed them (drowsiness, movement, ' ...
         'drift) is systematic, and is likely to correlate with condition or with time in the ' ...
         'session. Below roughly this level, loss behaves more like attrition than like bias |'] ...
        ['| Fewer than **20** surviving trials in a bin that began with more than 20 | Noise in an ' ...
         'average falls as 1/sqrt(*n*), so returns diminish quickly, but below about 20 trials the ' ...
         'average is still visibly unstable for a typical ERP component and the SME grows sharply. ' ...
         'Luck et al. (2021) argue the SME column is the better guide here, since it accounts for ' ...
         'how noisy the individual trials actually were; this count is the cruder proxy that needs ' ...
         'no measurement window to have been defined yet. The second half of the condition matters: ' ...
         'a bin designed with 15 trials has not lost anything, and flagging it would report the ' ...
         'design rather than the data |'] ...
        ['| A channel flagged in more than **20%** of trials | A channel that fails this often is ' ...
         'usually a bad electrode rather than an occasional artefact, and one persistently bad ' ...
         'channel is a case for interpolation rather than for discarding trials |'] ...
        ['| A channel interpolated in more than **20%** of trials | The same threshold applied to ' ...
         'repair rather than loss. Interpolated samples pass every other check in this report as ' ...
         'ordinary data, so this is the only place a mostly-reconstructed channel appears |'] ...
        ['| A subject more than **3 MAD** noisier than the sample median | Median absolute ' ...
         'deviation rather than standard deviation, because with a handful of subjects the very ' ...
         'outliers being looked for would inflate an SD enough to hide inside it. 3 MAD is the ' ...
         'usual robust-statistics analogue of a 3-sigma rule |'] ...
        ['| Any trial truncated at a recording boundary | Not a threshold: any occurrence is ' ...
         'worth knowing about, because such a trial still enters the average with less data at ' ...
         'the ends than its neighbours, and nothing else in the report would reveal it |'] ...
        '' ...
        ['These are applied per subject, and the report flags rather than acts. Exclusion criteria ' ...
         'are best fixed in advance and reported openly, which a threshold discovered after ' ...
         'looking at the data is not.'] ...
        '' ...
        '```{r}' ...
        '#| label: attention-list' ...
        '#| results: asis' ...
        '# Median absolute deviation, not SD, for the "unusually noisy" rule: with a' ...
        '# handful of subjects the very outliers being looked for would inflate an SD' ...
        '# enough to hide themselves inside it.' ...
        'notes <- character()' ...
        '' ...
        'high_rej <- subj %>% filter(pct_rejected > 25)' ...
        'if (nrow(high_rej) > 0) {' ...
        '  notes <- c(notes, sprintf("- **More than 25%% of trials rejected**: %s.",' ...
        '    paste(sprintf("%s (%s%%)", high_rej$dataset, apa_num(high_rej$pct_rejected, 1)), collapse = ", ")))' ...
        '}' ...
        '' ...
        'mad_sd <- mad(subj$median_baseline_sd, na.rm = TRUE)' ...
        'med_sd <- median(subj$median_baseline_sd, na.rm = TRUE)' ...
        'if (!is.na(mad_sd) && mad_sd > 0) {' ...
        '  noisy <- subj %>% filter(median_baseline_sd > med_sd + 3 * mad_sd)' ...
        '  if (nrow(noisy) > 0) {' ...
        '    notes <- c(notes, sprintf("- **Unusually noisy relative to the rest of the sample** (> 3 MAD above the median): %s.",' ...
        '      paste(sprintf("%s (%s uV)", noisy$dataset, apa_num(noisy$median_baseline_sd)), collapse = ", ")))' ...
        '  }' ...
        '}' ...
        '' ...
        '# n_trials > 20 as well as kept < 20: a bin that never had 20 trials to' ...
        '# begin with cannot end up with 20, and saying so every time describes' ...
        '# the design rather than the data quality. The flag is for trials LOST,' ...
        '# so it only applies where there were enough to lose.' ...
        'low_n <- qual %>% distinct(dataset, bin, n_trials, n_trials_rejected) %>%' ...
        '  mutate(kept = n_trials - n_trials_rejected) %>%' ...
        '  filter(kept < 20, n_trials > 20)' ...
        'if (nrow(low_n) > 0) {' ...
        '  notes <- c(notes, sprintf("- **Fewer than 20 surviving trials in a bin that started with more**: %s.",' ...
        '    paste(sprintf("%s / %s (%d of %d left)", low_n$dataset, low_n$bin, low_n$kept, low_n$n_trials), collapse = ", ")))' ...
        '}' ...
        '' ...
        'truncated <- subj %>% filter(pct_truncated > 0)' ...
        'if (nrow(truncated) > 0) {' ...
        '  notes <- c(notes, sprintf(paste0("- **Trials truncated at a recording boundary** (they still ",' ...
        '    "enter the average, with less data at the ends): %s. Nothing rejected these; the epoch ",' ...
        '    "simply ran off the start or end of the file."),' ...
        '    paste(sprintf("%s (%s%% of trials, worst one missing %s%% of its epoch)", truncated$dataset,' ...
        '                  apa_num(truncated$pct_truncated, 1), apa_num(truncated$max_truncated_pct, 1)),' ...
        '          collapse = ", ")))' ...
        '}' ...
        '' ...
        'bad_chan <- qual %>% filter(pct_flagged > 20) %>% distinct(dataset, channel)' ...
        'if (nrow(bad_chan) > 0) {' ...
        '  notes <- c(notes, sprintf("- **Channel flagged in more than 20%% of trials** (a candidate for interpolation): %s.",' ...
        '    paste(sprintf("%s / %s", bad_chan$dataset, bad_chan$channel), collapse = ", ")))' ...
        '}' ...
        '' ...
        '# The mirror of the line above: a channel that is mostly RECONSTRUCTED rather than' ...
        '# mostly missing. It needs saying separately because nothing else in the report can' ...
        '# reveal it -- interpolated samples are real numbers, so they pass every noise and' ...
        '# rejection check as ordinary data.' ...
        'interp_chan <- qual %>% filter(pct_interpolated > 20) %>% distinct(dataset, channel)' ...
        'if (nrow(interp_chan) > 0) {' ...
        '  notes <- c(notes, sprintf(paste0("- **Channel interpolated in more than 20%% of trials**: %s. ",' ...
        '                                   "More than a fifth of this channel is an estimate from its ",' ...
        '                                   "neighbours rather than a measurement. That is a legitimate ",' ...
        '                                   "repair for one bad electrode, but it should be reported, and ",' ...
        '                                   "it is worth checking the artefact was not shared with the ",' ...
        '                                   "neighbours it was reconstructed from."),' ...
        '    paste(sprintf("%s / %s", interp_chan$dataset, interp_chan$channel), collapse = ", ")))' ...
        '}' ...
        '' ...
        'if (length(notes) == 0) {' ...
        '  cat("\nNothing crossed any of the conventional thresholds checked here.\n\n")' ...
        '} else {' ...
        '  cat(paste(notes, collapse = "\n"), "\n\n")' ...
        '}' ...
        '```' ...
        '' ...
        '## References' ...
        '' ...
        ['Luck, S. J., Stewart, A. X., Simmons, A. M., & Kappenman, E. S. (2021). Standardized ' ...
         'measurement error: A universal metric of data quality for averaged event-related ' ...
         'potentials. *Psychophysiology*, 58(6), e13793.'] ...
        ''};
end

% ======================================================================= %
function s = rLit(matlabText)
    s = strrep(char(matlabText), '\', '\\');
    s = strrep(s, '"', '\"');
end
