function qmdText = generateClusterStatsReport(summary, statCsvName, waveformCsvName, outlineCsvName)
%GENERATECLUSTERSTATSREPORT  A Quarto (.qmd) report for one ClusterStats()
%   result: rendering it (self-contained HTML) produces narrative prose
%   explaining the test that ran, a summary table of every cluster found,
%   an overview heatmap of the test statistic across the whole channel x
%   time grid, and, for the strongest few clusters, a topographic plot
%   (where) and a time-course plot (when) each.
%
%   Unlike generateQuartoReport.m (whose R code runs the actual
%   statistical tests, since rstatix/lme4/etc. can do that from a flat
%   CSV), the cluster-permutation test itself has ALREADY run in MATLAB
%   by the time this is called -- FieldTrip is a MATLAB toolbox, R has no
%   equivalent -- so this report's own R code only narrates and PLOTS a
%   precomputed result; SUMMARY (see ClusterStats.m) supplies every number
%   it narrates, and STATCSVNAME/WAVEFORMCSVNAME/OUTLINECSVNAME (bare
%   filenames, resolved relative to the .qmd's own folder -- see
%   exportClusterStatsCSVs.m) supply what it plots.
%
%   Requires the R packages tidyverse and gt (auto-installed by the
%   report's own setup chunk on first render, same as
%   generateQuartoReport.m) plus a working Quarto installation to actually
%   render the .qmd this function returns into HTML.
%
%   See also EXPORTCLUSTERSTATSCSVS, CLUSTERSTATS, ALAKAZAM.ONCLUSTERSTATS.
    lines = [ ...
        preambleLines(summary, statCsvName, waveformCsvName, outlineCsvName), ...
        introLines(summary), ...
        summaryTableLines(), ...
        heatmapLines(), ...
        clusterDetailLines(summary)];
    qmdText = strjoin(lines, newline);
end

% ======================================================================= %
%  Preamble
% ======================================================================= %
function lines = preambleLines(summary, statCsvName, waveformCsvName, outlineCsvName)
    lines = { ...
        '---' ...
        'title: "Alakazam Cluster Statistics Report"' ...
        'format:' ...
        '  html:' ...
        '    self-contained: true' ...
        '    toc: true' ...
        '    theme: cosmo' ...
        '    include-in-header:' ...
        '      text: |' ...
        '        <meta name="color-scheme" content="light">' ...
        '        <style>' ...
        '          :root { color-scheme: light !important; }' ...
        '          html, body { background-color: #ffffff !important; }' ...
        '          #TOC, .sidebar, .toc-actions { background-color: #ffffff !important; }' ...
        '        </style>' ...
        'execute:' ...
        '  echo: false' ...
        '  warning: false' ...
        '  message: false' ...
        '---' ...
        '' ...
        '<!--' ...
        'Alakazam -- cluster-based permutation statistics report (Maris &' ...
        'Oostenveld, 2007), via FieldTrip''s ft_timelockstatistics. Unlike the' ...
        'ERP/Spectral Measure reports, the test itself already ran in MATLAB (see' ...
        'ClusterStats.m); this report narrates and plots that precomputed result,' ...
        'it does not run any statistics of its own. Edit freely: this is a' ...
        'sensible starting point, not the last word on your own plots or prose.' ...
        'Render with: quarto render <this file>.qmd' ...
        '-->' ...
        '' ...
        '```{r}' ...
        '#| label: setup' ...
        '#| include: false' ...
        'pkgs <- c("tidyverse", "gt")' ...
        'missing <- pkgs[!pkgs %in% rownames(installed.packages())]' ...
        'if (length(missing)) install.packages(missing, repos = "https://cloud.r-project.org")' ...
        'invisible(lapply(pkgs, library, character.only = TRUE))' ...
        '' ...
        sprintf('stat_df     <- read_csv("%s", show_col_types = FALSE)', rLit(statCsvName)) ...
        sprintf('waveform_df <- read_csv("%s", show_col_types = FALSE)', rLit(waveformCsvName)) ...
        sprintf('outline_df  <- read_csv("%s", show_col_types = FALSE)', rLit(outlineCsvName)) ...
        '' ...
        '# ---- APA-style formatting helpers (see generateQuartoReport.m''s own' ...
        '# copy of these -- duplicated rather than shared, no common R-helper' ...
        '# source file exists yet for either report generator to pull from) ----' ...
        'apa_p <- function(p) {' ...
        '  ifelse(is.na(p), "= NA",' ...
        '    ifelse(p < .001, "< .001",' ...
        '      paste("=", sub("^0\\.", ".", sprintf("%.3f", p)))))' ...
        '}' ...
        'apa_num <- function(x, digits = 2) {' ...
        '  ifelse(is.na(x), "NA",' ...
        '    sub("^(-?)0\\.", "\\1.", sprintf(paste0("%.", digits, "f"), x)))' ...
        '}' ...
        'apa_gt <- function(df, title = NULL) {' ...
        '  is_whole <- function(x) is.numeric(x) && all(x == round(x), na.rm = TRUE)' ...
        '  int_cols <- names(df)[sapply(df, is_whole)]' ...
        '  dec_cols <- setdiff(names(df)[sapply(df, is.numeric)], int_cols)' ...
        '  tbl <- gt(df)' ...
        '  if (!is.null(title)) tbl <- tab_header(tbl, title = title)' ...
        '  if (length(dec_cols) > 0) tbl <- tbl %>% fmt_number(columns = all_of(dec_cols), decimals = 3)' ...
        '  if (length(int_cols) > 0) tbl <- tbl %>% fmt_number(columns = all_of(int_cols), decimals = 0)' ...
        '  tbl %>%' ...
        '    tab_options(' ...
        '      table.border.top.style = "solid", table.border.top.width = px(1.5), table.border.top.color = "black",' ...
        '      table.border.bottom.style = "solid", table.border.bottom.width = px(1.5), table.border.bottom.color = "black",' ...
        '      column_labels.border.bottom.style = "solid", column_labels.border.bottom.width = px(1), column_labels.border.bottom.color = "black",' ...
        '      table_body.hlines.style = "none", table.border.left.style = "none", table.border.right.style = "none",' ...
        '      column_labels.font.weight = "bold", table.font.size = px(13), heading.align = "left"' ...
        '    )' ...
        '}' ...
        '```' ...
        ''};
end

% ======================================================================= %
%  Intro narrative
% ======================================================================= %
function lines = introLines(summary)
    nSig = sum([summary.clusters.significant]);
    lines = { ...
        '## Cluster Statistics' ...
        '' ...
        sprintf('%s', mdLit(contrastSentence(summary.contrast))) ...
        '' ...
        sprintf(['Tested across %d subject(s), %s permutation(s), %s correction ' ...
            '(cluster-forming *p* < %s, cluster-level %s = %s).'], ...
            summary.nSubjects, permutationLabel(summary.opts.numrandomization), upper(summary.opts.correctm), ...
            numToStr(summary.opts.clusteralpha), alphaLabel(summary.opts.correctm), numToStr(summary.opts.alpha)) ...
        '' ...
        sprintf(['%d cluster(s) were found (positive and negative together); %d were significant ' ...
            'at %s.'], numel(summary.clusters), nSig, alphaClause(summary.opts.alpha)) ...
        '' ...
        ['This is a whole-scalp, whole-epoch test: unlike a pre-chosen channel/window ' ...
         'analysis, it does not assume in advance where or when an effect should appear. ' ...
         'A **cluster** is a contiguous group of (channel, time) points that all crossed the ' ...
         'cluster-forming threshold in the same direction; its own p-value comes from comparing ' ...
         'its summed test statistic against a null distribution built by repeatedly shuffling ' ...
         'condition/group labels and re-running the same clustering procedure -- so it already ' ...
         'accounts for having tested every channel and time point at once, rather than needing a ' ...
         'separate per-comparison correction.'] ...
        ''};
end

function s = contrastSentence(contrast)
    switch contrast.mode
        case 'vsZero'
            s = sprintf('Bin "%s" was tested against zero, within subjects.', contrast.bin);
        case 'paired'
            s = sprintf('Bin "%s" was tested against bin "%s", within subjects (paired).', ...
                contrast.binA, contrast.binB);
        case 'independent'
            s = sprintf('Bin "%s" was tested between two groups (independent samples).', contrast.bin);
    end
end

function s = alphaLabel(correctm)
    if strcmpi(correctm, 'tfce')
        s = '$\\alpha$';
    else
        s = 'cluster $\\alpha$';
    end
end

function s = alphaClause(alpha)
    s = sprintf('*p* < %s', numToStr(alpha));
end

function s = numToStr(x)
    s = regexprep(sprintf('%.4g', x), '^0\.', '.');
end

function s = permutationLabel(numrandomization)
%PERMUTATIONLABEL  NUMRANDOMIZATION for narration -- a plain count, or
%   "all (exhaustive)" when ClusterStats.resolveNumRandomization upgraded
%   it to FieldTrip's own 'all' (an exhaustive 2^N sign-flip enumeration,
%   not a number of randomizations to pass through %d, which would
%   otherwise print each character of "all" as its own code point).
    if ischar(numrandomization) || isstring(numrandomization)
        s = 'all (exhaustive)';
    else
        s = sprintf('%d', numrandomization);
    end
end

% ======================================================================= %
%  Summary table
% ======================================================================= %
function lines = summaryTableLines()
    lines = { ...
        '```{r}' ...
        '#| label: cluster-summary-table' ...
        '#| results: asis' ...
        'summary_tbl <- stat_df %>%' ...
        '  filter(cluster_rank != "NA") %>%' ...
        '  mutate(cluster_rank = as.integer(cluster_rank)) %>%' ...
        '  group_by(cluster_rank, sign) %>%' ...
        '  summarise(' ...
        '    p = first(cluster_p), significant = first(significant),' ...
        '    channels = n_distinct(channel), time_from_ms = min(time_ms), time_to_ms = max(time_ms),' ...
        '    .groups = "drop"' ...
        '  ) %>%' ...
        '  arrange(p)' ...
        'if (nrow(summary_tbl) > 0) {' ...
        '  cat(as_raw_html(apa_gt(summary_tbl, "Clusters Found")))' ...
        '} else {' ...
        '  cat("\n\nNo clusters were found at all (not even a non-significant one) -- every point fell ' ...
             'below the cluster-forming threshold.\n\n")' ...
        '}' ...
        '```' ...
        ''};
end

% ======================================================================= %
%  Overview heatmap
% ======================================================================= %
function lines = heatmapLines()
    lines = { ...
        '## Overview: Test Statistic Across Every Channel and Time Point' ...
        '' ...
        ['The full grid the cluster test ran over. Tile colour is the raw test statistic ' ...
         '(before clustering); a black outline marks a point belonging to a cluster reported above.'] ...
        '' ...
        '```{r}' ...
        '#| label: overview-heatmap' ...
        '#| fig-height: 6' ...
        'chan_order <- stat_df %>% distinct(channel) %>% pull(channel)' ...
        'hp <- ggplot(stat_df, aes(x = time_ms, y = factor(channel, levels = rev(chan_order)), fill = statistic)) +' ...
        '  geom_tile() +' ...
        '  geom_tile(data = filter(stat_df, cluster_rank != "NA"), colour = "black", linewidth = 0.3, fill = NA) +' ...
        '  scale_fill_gradient2(low = "#c0392b", mid = "white", high = "#2980b9", midpoint = 0, name = "statistic") +' ...
        '  labs(x = "Time (ms)", y = NULL) +' ...
        '  theme_minimal(base_size = 11)' ...
        'print(hp)' ...
        '```' ...
        ''};
end

% ======================================================================= %
%  Per-cluster detail (strongest few, already p-sorted -- see this file's
%  own header on why not every spurious tiny cluster gets a full section)
% ======================================================================= %
function lines = clusterDetailLines(summary)
    lines = {'## Where and When: the Strongest Clusters' ''};
    nShow = min(5, numel(summary.clusters));
    if nShow == 0
        lines = [lines, {'No clusters to show.' ''}];
        return;
    end
    for r = 1:nShow
        c = summary.clusters(r);
        lines = [lines, oneClusterLines(r, c)]; %#ok<AGROW>
    end
end

function lines = oneClusterLines(rank, c)
    sigWord = 'not significant';
    if c.significant
        sigWord = 'significant';
    end
    chLit = rLit(strjoin(c.channels, ', '));
    lines = { ...
        sprintf('### Cluster %d (%s, %s)', rank, c.sign, sigWord) ...
        '' ...
        sprintf(['A %s cluster spanning %s, %.0f to %.0f ms (*p* %s, %d point(s)).'], ...
            c.sign, mdLit(strjoin(c.channels, ', ')), c.timeRangeMs(1), c.timeRangeMs(2), ...
            pStr(c.pValue), c.nPoints) ...
        '' ...
        '::: {layout-ncol=2}' ...
        '' ...
        sprintf('```{r}') ...
        sprintf('#| label: topo-%d', rank) ...
        sprintf('#| fig-width: 4') ...
        sprintf('#| fig-height: 4') ...
        sprintf('t_lo <- %g; t_hi <- %g', c.timeRangeMs(1), c.timeRangeMs(2)) ...
        sprintf('pts <- stat_df %%>%% filter(time_ms >= t_lo, time_ms <= t_hi) %%>%%') ...
        sprintf('  group_by(channel, x, y) %%>%% summarise(statistic = mean(statistic), .groups = "drop")') ...
        sprintf('in_cluster <- stat_df %%>%% filter(channel %%in%% c(%s), time_ms >= t_lo, time_ms <= t_hi) %%>%%', ...
            strjoin(cellfun(@(ch) ['"' rLit(ch) '"'], c.channels, 'UniformOutput', false), ', ')) ...
        sprintf('  distinct(channel)') ...
        sprintf('tp <- ggplot() +') ...
        sprintf('  geom_path(data = outline_df, aes(x = x, y = y, group = outline_id), colour = "grey60") +') ...
        sprintf('  geom_point(data = pts, aes(x = x, y = y, colour = statistic), size = 5) +') ...
        sprintf(['  geom_point(data = pts %%>%% filter(channel %%in%% in_cluster$channel), ' ...
            'aes(x = x, y = y), shape = 1, size = 7, colour = "black", stroke = 1) +']) ...
        sprintf(['  geom_text(data = pts, aes(x = x, y = y, label = channel), ' ...
            'size = 2.2, vjust = -1.1, colour = "grey20") +']) ...
        sprintf('  scale_colour_gradient2(low = "#c0392b", mid = "white", high = "#2980b9", midpoint = 0) +') ...
        sprintf('  coord_fixed() + theme_void() + labs(title = "Where (mean over cluster window)")') ...
        sprintf('print(tp)') ...
        '```' ...
        '' ...
        sprintf('```{r}') ...
        sprintf('#| label: timecourse-%d', rank) ...
        sprintf('#| fig-width: 5') ...
        sprintf('#| fig-height: 4') ...
        sprintf('wf <- waveform_df %%>%% filter(channel %%in%% c(%s))', ...
            strjoin(cellfun(@(ch) ['"' rLit(ch) '"'], c.channels, 'UniformOutput', false), ', ')) ...
        sprintf('tc <- ggplot(wf, aes(x = time_ms, y = value, colour = condition, fill = condition)) +') ...
        sprintf('  annotate("rect", xmin = t_lo, xmax = t_hi, ymin = -Inf, ymax = Inf, alpha = 0.12, fill = "grey40") +') ...
        sprintf('  stat_summary(fun = mean, geom = "line", linewidth = 0.8) +') ...
        sprintf('  stat_summary(fun.data = mean_se, geom = "ribbon", alpha = 0.15, colour = NA) +') ...
        sprintf('  geom_hline(yintercept = 0, linetype = "dashed", colour = "grey60") +') ...
        sprintf('  labs(x = "Time (ms)", y = "Amplitude", title = "When (shaded = cluster window)") +') ...
        sprintf('  theme_minimal(base_size = 11)') ...
        sprintf('print(tc)') ...
        '```' ...
        '' ...
        ':::' ...
        ''};
end

function s = pStr(p)
    if p < .001
        s = '< .001';
    else
        s = ['= ' regexprep(sprintf('%.3f', p), '^0\.', '.')];
    end
end

% ======================================================================= %
%  String-escaping helpers (see generateQuartoReport.m's own copies of
%  these -- duplicated rather than shared, both local-only there too)
% ======================================================================= %
function s = rLit(matlabText)
    s = strrep(char(matlabText), '\', '\\');
    s = strrep(s, '"', '\"');
end

function s = mdLit(matlabText)
    s = char(matlabText);
    special = {'\', '*', '_', '#', '[', ']', '`', '<', '>'};
    for i = 1:numel(special)
        s = strrep(s, special{i}, ['\' special{i}]);
    end
end
