function qmdText = generateSourceClusterStatsReport(summary, assets, extras)
%GENERATESOURCECLUSTERSTATSREPORT  A Quarto report for a source-space
%   cluster permutation test.
%
%   QMDTEXT = generateSourceClusterStatsReport(SUMMARY, ASSETS) assembles
%   the document from SourceClusterStats' own return value and the figures
%   generateSourceClusterAssets rendered from it.
%
%   PURE MARKDOWN, NO R CHUNK, unlike the scalp cluster report. The
%   difference is not about who runs the test: the permutation runs in
%   MATLAB for both, since FieldTrip is a MATLAB toolbox. It is about the
%   figures. The scalp report exports long-format CSVs and has R plot a
%   heatmap, topographies and waveforms from them; this report's figures are
%   cortical surfaces, which cannot be drawn from a flat CSV without
%   shipping the mesh with it, so they are rendered in MATLAB and the
%   document is plain markdown. It therefore also renders on a machine with
%   no R at all.
%
%   THE DOCUMENT LEADS WITH WHAT THE TEST DOES NOT SHOW. Cluster inference
%   is among the most over-read results in the literature: a significant
%   cluster establishes that an effect exists somewhere in a space-time
%   region, and specifically does NOT license a claim about where it starts,
%   stops, or which gyrus it occupies. Stating that after the tables would
%   be stating it after it has already been misread, so it comes first.
%
%   See also SOURCECLUSTERSTATS, GENERATESOURCECLUSTERASSETS,
%   GENERATECLUSTERSTATSREPORT, TRANSTOOLS.DESCRIBECLUSTER.
    if nargin < 3 || isempty(extras)
        extras = struct('UnthresholdedMapPath', '');
    end

    lines = [ReportDoc.yamlHeader('Alakazam Source Cluster Statistics'), { ...
        '' ...
        '<!--' ...
        'Alakazam -- source-space cluster permutation report.' ...
        'Auto-generated. Every figure and number was computed in MATLAB; this' ...
        'document is markdown only and needs no R packages to render.' ...
        'Render with: quarto render <this file>.qmd' ...
        '-->' ...
        ''}, ...
        methodLines(summary), ...
        forwardModelLines(summary), ...
        limitationLines(), ...
        resultLines(summary, assets), ...
        subjectLines(summary), ...
        appendixLines(extras), ...
        provenanceLines(summary)];

    qmdText = char(strjoin(lines, newline));
end

% ======================================================================= %
function lines = methodLines(summary)
%METHODLINES  What was actually run, in the words a methods section needs.
%   Read off SUMMARY.opts rather than restated from the dialog's defaults,
%   so the document describes the analysis that ran and not the one that was
%   requested -- numrandomization in particular can be raised to exhaustive
%   by resolveNumRandomization without the analyst asking.
    opts = summary.opts;
    lines = { ...
        '## What was tested' ...
        '' ...
        sprintf('%s, across %d subjects, on cortical source estimates.', ...
            contrastSentence(summary.contrast), summary.nSubjects) ...
        '' ...
        '| Setting | Value |' ...
        '| --- | --- |' ...
        sprintf('| Inverse method | %s |', methodName(opts.Method)) ...
        sprintf('| Orientation | %s |', orientationName(opts.Orientation)) ...
        sprintf('| Source space | template cortical sheet, %d vertices |', ...
            numel(summary.vertexLabels)) ...
        sprintf('| Time window | %s |', windowText(summary.times)) ...
        sprintf('| Sampling for the test | %.0f Hz |', samplingHz(summary.times)) ...
        sprintf('| Regularisation | %s |', regularisationText(summary)) ...
        sprintf('| Noise covariance | %s |', provenanceField(summary, 'noiseCovariance', 'not recorded')) ...
        sprintf('| Multiple-comparison correction | %s |', correctionName(opts.correctm)) ...
        correctionParameterRow(summary) ...
        sprintf('| Permutations | %s |', permutationText(opts.numrandomization)) ...
        sprintf('| Smallest attainable p | %s |', smallestPText(opts.numrandomization)) ...
        sprintf('| Alpha | %g, %s |', opts.alpha, tailText(opts.tail)) ...
        '' ...
        ['Only the contrast above was tested. If several contrasts were run on ' ...
         'these data, nothing here corrects across them: the correction below is ' ...
         'family-wise over the vertex-by-time volume of this one test.'] ...
        ''};
end

function row = correctionParameterRow(summary)
%CORRECTIONPARAMETERROW  The correction's OWN free parameters.
%   TFCE's E and H are choices, and a cluster-forming alpha applies only to
%   the classic method. Printing clusteralpha under TFCE, as an earlier
%   version did, states that a threshold was used when none was.
    opts = summary.opts;
    if strcmpi(opts.correctm, 'tfce')
        tfce = provenanceField(summary, 'tfce', struct('variant', 'exact', 'E', 0.5, 'H', 2));
        row = sprintf(['| TFCE parameters | %s variant, E = %g, H = %g ' ...
            '(no cluster-forming threshold is used) |'], tfce.variant, tfce.E, tfce.H);
    else
        row = sprintf('| Cluster-forming threshold | p < %g, minimum %d neighbours |', ...
            opts.clusteralpha, TransTools.FieldOr(opts, 'minnbchan', 0));
    end
end

function lines = forwardModelLines(summary)
%FORWARDMODELLINES  How the scalp data was mapped onto the cortex.
%   Its own table because these are a separate set of reporting items from
%   the statistics, and because every entry in it is a template rather than
%   a measurement of these participants. Stating that plainly is the point.
    if ~isfield(summary, 'provenance')
        lines = {};
        return;
    end
    % EVERY FIELD READ THROUGH A FALLBACK, none directly. A summary can
    % reach here from an older cached run, or with provenance only partly
    % filled, and a report generator is the wrong place to discover that:
    % the analysis has already finished by the time this runs, so an
    % "Unrecognized field name" here throws away work that succeeded. The
    % same assumption -- that a struct holds what its name suggests -- has
    % already cost one crash on a bin whose trial count was text.
    p = summary.provenance;
    lines = { ...
        '## The forward model' ...
        '' ...
        '| Component | Value |' ...
        '| --- | --- |' ...
        sprintf('| Head model | %s |', provenanceField(summary, 'headModel', 'not recorded')) ...
        sprintf('| Electrode positions | %s |', provenanceField(summary, 'electrodes', 'not recorded')) ...
        sprintf('| Coregistration | %s |', provenanceField(summary, 'coregistration', 'not recorded')) ...
        sprintf('| Source space | %s, %s vertices |', ...
            provenanceField(summary, 'sourceTemplate', 'not recorded'), ...
            countText(provenanceField(summary, 'nVertices', NaN))) ...
        sprintf('| Vertex adjacency | %s |', provenanceField(summary, 'adjacency', 'not recorded')) ...
        sprintf('| Channels used | %s |', channelsText(summary)) ...
        sprintf('| Reference | %s |', provenanceField(summary, 'reference', 'not recorded')) ...
        sprintf('| Variance explained by the fitted sources | %s |', varianceExplainedText(p)) ...
        '' ...
        ['Channels whose labels the 10-5 template does not recognise are dropped ' ...
         'rather than placed by guesswork, so the channel count may be lower than ' ...
         'the recording''s own. Where subjects differ, the analysis uses only what ' ...
         'they share: how many spatial patterns a forward model can distinguish is ' ...
         'bounded by that number, so a single reduced montage limits the whole ' ...
         'group, and excluding that subject may buy more than including them does.'] ...
        '' ...
        ['A HIGH VARIANCE EXPLAINED IS EXPECTED AND IS NOT EVIDENCE THAT THE ' ...
         'MODEL IS RIGHT. There are far more vertices than electrodes, so the ' ...
         'inverse can reproduce almost any scalp data almost exactly; near-total ' ...
         'fit is a property of the problem, not a validation of the solution. It ' ...
         'is worth reporting only in the negative: a subject whose fit is poor ' ...
         'indicates something wrong with that subject''s channels or reference, ' ...
         'and it was a fit of 25% where 96% was available that revealed a ' ...
         'reference mismatch during this feature''s development.'] ...
        ''};
end

function lines = subjectLines(summary)
%SUBJECTLINES  Who was in it, with the two per-subject numbers that bear on
%   a source estimate: how many trials were averaged, and how much of that
%   subject's scalp data the fitted sources actually account for.
    if ~isfield(summary, 'provenance') || isempty(summary.provenance.subjects)
        lines = {};
        return;
    end
    rows = summary.provenance.subjects;
    lines = {'## Subjects' '' ...
        '| Subject | Trials in contrast | Unexplained variance |' '| --- | --- | --- |'};
    for i = 1:numel(rows)
        lines{end + 1} = sprintf('| %s | %s | %s |', ...
            ReportSections.mdLit(rows(i).id), trialsCell(rows(i)), ...
            percentText(rows(i).residualVariance)); %#ok<AGROW>
    end
    lines = [lines, {'' ...
        ['Unexplained variance is the fraction of a subject''s scalp data the ' ...
         'fitted sources do not reproduce. It checks the forward model, not the ' ...
         'effect: a value near 100% means the model failed for that subject and ' ...
         'their source estimate should not be trusted. It is not defined for ' ...
         'sLORETA, whose filter output is a standardised statistic rather than a ' ...
         'current, and appears as "n/a" there.'] ''}];
end

function lines = appendixLines(extras)
%APPENDIXLINES  The unthresholded statistic, once, at the end.
%   At the end deliberately: it is a check on the analysis rather than a
%   result, and placing it beside the cluster figures would invite reading
%   it as one.
    if ~isfield(extras, 'UnthresholdedMapPath') || isempty(extras.UnthresholdedMapPath)
        lines = {};
        return;
    end
    lines = { ...
        '## Appendix: the unthresholded statistic' ...
        '' ...
        sprintf('![The test statistic across the whole cortex](<%s>)', extras.UnthresholdedMapPath) ...
        '' ...
        ['The test statistic everywhere, averaged over the tested window, with ' ...
         'nothing masked and no threshold applied. **None of this is a result:** ' ...
         'the test makes no claim about any vertex here except through the ' ...
         'clusters above. It is included because a masked map alone hides how ' ...
         'close the rest of the cortex came, and because a reader is entitled to ' ...
         'see the statistic the correction was applied to.'] ...
        ''};
end

function lines = provenanceLines(summary)
%PROVENANCELINES  What produced this document.
%   Last, because nobody reads it until they need it, and then they need it
%   exactly. Required by COBIDAS MEEG (Pernet et al., 2020): an inverse
%   solution or a permutation scheme can change between releases, and a
%   result without a version is not reproducible.
    if ~isfield(summary, 'provenance')
        lines = {};
        return;
    end
    v = provenanceField(summary, 'software', struct());
    lines = { ...
        '## Software' ...
        '' ...
        '| Component | Version |' ...
        '| --- | --- |' ...
        sprintf('| MATLAB | %s |', ReportSections.mdLit(softwareField(v, 'matlab'))) ...
        sprintf('| FieldTrip | %s |', ReportSections.mdLit(softwareField(v, 'fieldtrip'))) ...
        sprintf('| Alakazam | %s |', ReportSections.mdLit(softwareField(v, 'alakazam'))) ...
        '' ...
        ['Permutations are drawn with a seed taken fresh for each run, so ' ...
         'repeating this analysis gives slightly different p-values. That ' ...
         'variation is the Monte Carlo error of the test, and it shrinks as the ' ...
         'permutation count rises.'] ...
        ''};
end

% ---- provenance formatting helpers -------------------------------------- %
function value = provenanceField(summary, field, fallback)
    value = fallback;
    if isfield(summary, 'provenance') && isfield(summary.provenance, field)
        value = summary.provenance.(field);
    end
end

function s = regularisationText(summary)
%REGULARISATIONTEXT  Both the dimensionless knob and the absolute lambda it
%   produced. The knob is what the analyst set; the absolute value is what
%   the inverse actually used, and only the latter reproduces the result.
    reg = provenanceField(summary, 'regParam', TransTools.FieldOr(summary.opts, 'RegParam', NaN));
    lambda = provenanceField(summary, 'lambda', NaN);
    if isfinite(lambda)
        s = sprintf('RegParam %g, giving lambda = %.4g', reg, lambda);
    else
        s = sprintf('RegParam %g', reg);
    end
end

function s = channelsText(summary)
%CHANNELSTEXT  The shared montage, and what it cost.
%   A vertex-wise test must use the channels every subject has, so one
%   subject with a reduced montage sets the count for everyone. Reporting
%   only the shared number reads as though nothing was given up.
    shared = provenanceField(summary, 'nChannels', NaN);
    counts = provenanceField(summary, 'subjectChannels', []);
    if isempty(counts) || ~isnumeric(counts)
        s = sprintf('%s, shared by every subject', countText(shared));
        return;
    end
    if min(counts) == max(counts)
        s = sprintf('%s, and every subject carries exactly these', countText(shared));
        return;
    end
    limiting = provenanceField(summary, 'limitingSubject', '');
    s = sprintf(['%s, the set shared by all %d subjects. They carry %d to %d ' ...
        'channels each (median %d)'], countText(shared), numel(counts), ...
        min(counts), max(counts), round(median(counts)));
    if ~isempty(limiting)
        s = sprintf('%s; %s has the fewest and therefore sets this montage', ...
            s, ReportSections.mdLit(limiting));
    end
end

function s = varianceExplainedText(p)
    if ~isfield(p, 'residualVariance') || all(isnan(p.residualVariance))
        s = 'not defined for this inverse (see Subjects)';
        return;
    end
    rv = p.residualVariance(~isnan(p.residualVariance));
    s = sprintf('%.1f%% to %.1f%% across subjects and bins', ...
        100 * (1 - max(rv)), 100 * (1 - min(rv)));
end

function s = softwareField(v, name)
    if isstruct(v) && isfield(v, name) && ~isempty(v.(name))
        s = char(string(v.(name)));
    else
        s = 'unknown';
    end
end

function s = trialsCell(row)
%TRIALSCELL  A trial count, or the bins' own description when there is no
%   single number to give (a difference bin records '39-161', not a count).
    if isfield(row, 'trialsText') && ~isempty(row.trialsText)
        s = ReportSections.mdLit(row.trialsText);
        return;
    end
    if ~isfield(row, 'trials')
        s = 'not recorded';
        return;
    end
    s = countText(row.trials);
end

function s = countText(n)
    if ~isnumeric(n) || ~isscalar(n) || isnan(n)
        s = 'not recorded';
    else
        s = sprintf('%d', round(n));
    end
end

function s = percentText(x)
    if ~isnumeric(x) || ~isscalar(x) || isnan(x)
        s = 'n/a';
    else
        s = sprintf('%.0f%%', 100 * x);
    end
end

function s = permutationText(n)
    if ischar(n) || isstring(n)
        s = 'all (exhaustive)';
    else
        s = sprintf('%d', n);
    end
end

function s = smallestPText(n)
%SMALLESTPTEXT  A Monte Carlo p-value cannot fall below 1/(N+1). Stated so
%   that "p < 0.001" is read as the resolution of the test rather than as a
%   vanishingly small probability.
    if ischar(n) || isstring(n)
        s = 'exact (every permutation enumerated)';
    else
        s = sprintf('%.4g (= 1/(%d+1), the resolution of a Monte Carlo test)', ...
            1 / (double(n) + 1), n);
    end
end

function lines = limitationLines()
%LIMITATIONLINES  Placed before the results, deliberately -- see this
%   file's own header.
    lines = { ...
        '## How to read this' ...
        '' ...
        '> **A significant cluster means an effect exists, not where it is.**' ...
        '> Cluster-based permutation controls the family-wise error rate over the' ...
        '> whole vertex-by-time volume at once. It licenses the statement "there is a' ...
        '> difference between these conditions". It does NOT license "the difference' ...
        '> is in this region, between these two latencies": a cluster''s boundaries' ...
        '> are where a statistic crossed a threshold, not where the effect began and' ...
        '> ended.' ...
        '>' ...
        '> **The head model is a template.** Template anatomy, template electrode' ...
        '> positions, and a few dozen channels explaining tens of thousands of' ...
        '> vertices. The anatomical labels below name where the model places the' ...
        '> activity, which carries far more uncertainty than any p-value here' ...
        '> expresses. The peak coordinates are given alongside the region names so' ...
        '> that precision can be judged rather than assumed.' ...
        '>' ...
        '> **Neighbouring vertices are not independent.** The inverse is spatially' ...
        '> smooth, so an apparently focal cluster is partly the method''s own' ...
        '> point-spread. This is exactly why the correction is cluster-based rather' ...
        '> than per-vertex, and it is also why cluster extent should not be read as a' ...
        '> measurement of the effect''s size.' ...
        ''};
end

function lines = resultLines(summary, assets)
    lines = {'## Clusters' ''};

    if isempty(summary.clusters)
        lines = [lines, { ...
            'The permutation found no candidate clusters at all: no vertex-by-time' ...
            'point reached the threshold for cluster formation. There is no effect' ...
            'here at this sensitivity, which is a result, not a failure to run.' ''}];
        return;
    end

    significant = summary.clusters([summary.clusters.significant]);
    if isempty(significant)
        lines = [lines, { ...
            sprintf(['The permutation formed %d candidate cluster(s), none of which ' ...
                     'survived correction (smallest p = %.3f). Candidate clusters are ' ...
                     'formed routinely from noise, so this is a null result rather than ' ...
                     'a near-miss, and the clusters below are listed only for ' ...
                     'completeness.'], numel(summary.clusters), min([summary.clusters.pValue])) ...
            ''}];
    end

    lines = [lines, { ...
        '| # | Direction | p | Vertices | Time range | Location |' ...
        '| --- | --- | --- | --- | --- | --- |'}];
    for k = 1:numel(assets)
        a = assets(k);
        lines{end + 1} = sprintf('| %d | %s | %s | %d | %.0f to %.0f ms | %s |', ...
            a.Index, a.Sign, pValueText(a.PValue), a.NVertices, ...
            a.TimeRangeMs(1), a.TimeRangeMs(2), ...
            ReportSections.mdLit(a.Description.Text)); %#ok<AGROW>
    end
    lines{end + 1} = '';

    for k = 1:numel(assets)
        a = assets(k);
        lines = [lines, { ...
            sprintf('### Cluster %d (%s, %s)', a.Index, a.Sign, pValueText(a.PValue)) ...
            '' ...
            ReportSections.mdLit(a.Description.Text) ...
            '' ...
            }, truncationLines(a), { ...
            '::: {.panel-tabset}' ...
            '' ...
            '#### Where' ...
            '' ...
            sprintf('![Cluster %d on the cortical surface](<%s>)', a.Index, a.MapPath) ...
            '' ...
            'Each hemisphere is shown from the side and from the midline, so that the' ...
            'whole cortical sheet is visible: a single three-quarter view hides the' ...
            'medial wall entirely, and a cluster that is absent would look the same as' ...
            'one that is merely facing away. All four panels share one scale.' ...
            '' ...
            'Coloured by the cluster''s own statistic, averaged over its time range,' ...
            'red for positive and blue for negative. Vertices outside the cluster are' ...
            'not shaded: nothing below threshold is drawn, so the picture shows what' ...
            'was found rather than what was tested.' ...
            '' ...
            '#### When' ...
            '' ...
            sprintf('![Cluster %d over time](<%s>)', a.Index, a.TimeCoursePath) ...
            '' ...
            'The statistic averaged across the cluster''s vertices, over the whole' ...
            'tested window. The shaded band is the cluster''s extent -- where the' ...
            'statistic crossed threshold, which is not the same as where the effect' ...
            'started and stopped.' ...
            '' ...
            'Time is latency within the epoch, in milliseconds relative to the' ...
            'time-locking event, the same axis an ERP waveform is drawn on. It spans' ...
            'the tested window rather than the whole epoch, so if it looks narrower' ...
            'than the recording, that is the **Time window** setting reported above' ...
            'and not a property of the data.' ...
            '' ...
            ':::' ...
            ''}]; %#ok<AGROW>

        if ~isempty(a.Description.Regions)
            lines = [lines, regionTableLines(a.Description)]; %#ok<AGROW>
        end
    end
end

function lines = regionTableLines(description)
%REGIONTABLELINES  Where the cluster's vertices fall, by share.
%   A distribution rather than a single label, because a cluster crossing a
%   regional boundary is the normal case and naming only its peak would
%   hide that.
    lines = {'Vertices by region:' '' '| Region | Share of cluster |' '| --- | --- |'};
    show = min(5, numel(description.Regions));
    for r = 1:show
        lines{end + 1} = sprintf('| %s | %.0f%% |', ...
            ReportSections.mdLit(description.Regions{r}), 100 * description.RegionShare(r)); %#ok<AGROW>
    end
    lines{end + 1} = '';
end

function lines = truncationLines(asset)
%TRUNCATIONLINES  Say so when a cluster runs into the edge of the analysis
%   window, because its reported time range is then a property of the
%   window rather than of the effect.
    if ~asset.TouchesWindowEdge
        lines = {};
        return;
    end
    lines = { ...
        ['> This cluster reaches the edge of the tested time window, so its time ' ...
         'range is limited by where the analysis looked rather than by where the ' ...
         'effect ended. Widen the window to see its true extent.'] ...
        ''};
end

% ---- small formatting helpers ------------------------------------------- %
function s = contrastSentence(contrast)
    switch contrast.mode
        case 'vsZero'
            s = sprintf('Bin "%s" tested against zero', contrast.bin);
        case 'paired'
            s = sprintf('Bin "%s" compared with bin "%s" within each subject', ...
                contrast.binA, contrast.binB);
        case 'independent'
            s = sprintf('Bin "%s" compared between groups', contrast.bin);
        otherwise
            s = 'An unrecognised contrast';
    end
end

function s = methodName(method)
%METHODNAME  The displayed name plus its expansion. The name itself comes
%   from TransTools.SourceMethodName so this table, the dialog that
%   configured the run and the on-screen summary cannot disagree about
%   which method ran.
    [name, gloss] = TransTools.SourceMethodName(method);
    if isempty(gloss)
        s = name;
    else
        s = sprintf('%s (%s)', name, gloss);
    end
end

function s = orientationName(orientation)
    if strcmpi(orientation, 'normal')
        s = 'signed, projected onto the cortical normal';
    else
        s = 'magnitude (unsigned)';
    end
end

function s = correctionName(correctm)
    switch lower(char(string(correctm)))
        case 'tfce'
            s = 'threshold-free cluster enhancement (Smith & Nichols, 2009)';
        case 'cluster'
            s = 'cluster-based permutation (Maris & Oostenveld, 2007)';
        otherwise
            s = char(string(correctm));
    end
end

function s = windowText(times)
    s = sprintf('%.0f to %.0f ms', times(1), times(end));
end

function hz = samplingHz(times)
    if numel(times) < 2
        hz = NaN;
        return;
    end
    hz = 1000 / median(diff(times));
end

function s = tailText(tail)
    if tail == 0
        s = 'two-sided';
    elseif tail > 0
        s = 'one-sided (positive)';
    else
        s = 'one-sided (negative)';
    end
end

function s = pValueText(p)
%PVALUETEXT  A permutation p-value cannot be smaller than 1/nPermutations,
%   so it is reported at its resolution rather than as a spuriously precise
%   decimal or as a bare "0".
    if p <= 0
        s = 'p < 0.001';
    elseif p < 0.001
        s = 'p < 0.001';
    else
        s = sprintf('p = %.3f', p);
    end
end
